import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u09-l02',
  learn: [
    {
      title: 'Colours',
      text: 'Colours are adjectives, so they take the same endings as stor: **-t** for ett-words and **-a** in the plural.\n\nThe spelling rules from the last lesson apply: [[röd]] → [[rött]] (long vowel + d), [[vit]] → [[vitt]] (long vowel + t), [[blå]] → [[blått]] (vowel at the end), and [[svart]] stays svart (it already ends in consonant + t).',
      table: {
        headers: ['en-word', 'ett-word', 'plural', 'English'],
        rows: [
          ['röd', 'rött', 'röda', 'red'],
          ['blå', 'blått', 'blå, blåa', 'blue'],
          ['gul', 'gult', 'gula', 'yellow'],
          ['grön', 'grönt', 'gröna', 'green'],
          ['vit', 'vitt', 'vita', 'white'],
          ['svart', 'svart', 'svarta', 'black'],
          ['grå', 'grått', 'grå, gråa', 'grey'],
          ['brun', 'brunt', 'bruna', 'brown'],
          ['rosa', 'rosa', 'rosa', 'pink'],
          ['orange', 'orange', 'orange', 'orange'],
          ['lila', 'lila', 'lila', 'purple'],
        ],
        svColumns: [0, 1, 2],
      },
      examples: [
        { sv: 'Vilken färg har bilen?', en: 'What colour is the car?' },
        { sv: 'Den är röd.', en: 'It’s red.' },
      ],
      tip: '[[rosa]], [[orange]] and [[lila]] never change: [[en rosa tröja]], [[ett rosa hus]], [[rosa skor]]. For blå and grå, both plurals are fine: [[blå skor]] or [[blåa skor]].',
    },
    {
      title: 'The red car: "the" twice',
      text: 'To say **the** red car, Swedish marks "the" twice: a little word in front (**den** for en-words, **det** for ett-words, **de** for plurals) **and** the ending on the noun.\n\nIn this pattern the adjective always ends in **-a**, whatever the noun.',
      table: {
        headers: ['a …', 'the …', 'English'],
        rows: [
          ['en röd bil', 'den röda bilen', 'the red car'],
          ['ett rött hus', 'det röda huset', 'the red house'],
          ['röda bilar', 'de röda bilarna', 'the red cars'],
          ['en ny cykel', 'den nya cykeln', 'the new bike'],
          ['ett stort rum', 'det stora rummet', 'the big room'],
        ],
        svColumns: [0, 1],
      },
      tip: 'de is said "dom". liten has a special form here: [[den lilla katten]], [[det lilla huset]], but in the plural [[de små katterna]].',
    },
    {
      title: 'After min, mitt, mina',
      text: 'After words like **min**, **din**, **hans** and **vår**, the adjective also ends in **-a**. But the noun gets **no** ending, because "my" already tells you which one.',
      examples: [
        { sv: 'min nya bil', en: 'my new car' },
        { sv: 'mitt nya hus', en: 'my new house' },
        { sv: 'mina nya skor', en: 'my new shoes' },
        { sv: 'hans lilla hund', en: 'his little dog' },
        { sv: 'vår gamla katt', en: 'our old cat' },
      ],
      tip: 'Compare: [[den nya bilen]] (the new car) and [[min nya bil]] (my new car).',
    },
  ],
  vocab: [
    {
      id: 'rod',
      sv: 'röd',
      en: 'red',
      pos: 'adjective',
      note: 'Long vowel + d becomes -tt: ett rött hus.',
      forms: { neuter: 'rött', plural: 'röda' },
    },
    {
      id: 'bla',
      sv: 'blå',
      en: 'blue',
      pos: 'adjective',
      note: 'ett blått hus. In the plural, blå and blåa are both correct: blå skor / blåa skor. The same after den/det/de: den blå bilen / den blåa bilen.',
      forms: { neuter: 'blått', plural: 'blå' },
    },
    {
      id: 'gul',
      sv: 'gul',
      en: 'yellow',
      pos: 'adjective',
      forms: { neuter: 'gult', plural: 'gula' },
    },
    {
      id: 'gron',
      sv: 'grön',
      en: 'green',
      pos: 'adjective',
      forms: { neuter: 'grönt', plural: 'gröna' },
    },
    {
      id: 'vit',
      sv: 'vit',
      en: 'white',
      pos: 'adjective',
      note: 'ett vitt hus: the t doubles because the vowel is short in vitt.',
      forms: { neuter: 'vitt', plural: 'vita' },
    },
    {
      id: 'svart',
      sv: 'svart',
      en: 'black',
      pos: 'adjective',
      note: 'Ends in consonant + t, so no extra t: ett svart hus.',
      forms: { neuter: 'svart', plural: 'svarta' },
    },
    {
      id: 'gra',
      sv: 'grå',
      en: 'grey',
      pos: 'adjective',
      note: 'ett grått hus. In the plural, grå and gråa are both correct, and the same after den/det/de: den grå katten / den gråa katten.',
      forms: { neuter: 'grått', plural: 'grå' },
      enAlt: ['gray'],
    },
    {
      id: 'brun',
      sv: 'brun',
      en: 'brown',
      pos: 'adjective',
      forms: { neuter: 'brunt', plural: 'bruna' },
    },
    {
      id: 'rosa',
      sv: 'rosa',
      en: 'pink',
      pos: 'adjective',
      note: 'Never changes: en rosa tröja, ett rosa hus, rosa skor.',
    },
    {
      id: 'orange',
      sv: 'orange',
      en: 'orange',
      pos: 'adjective',
      pron: 'oh-RANSH',
      note: 'Never changes: en orange tröja, ett orange hus, orange skor.',
    },
    {
      id: 'lila',
      sv: 'lila',
      en: 'purple',
      pos: 'adjective',
      note: 'Never changes: en lila tröja, ett lila hus, lila skor.',
      enAlt: ['lilac', 'violet'],
    },
    {
      id: 'farg',
      sv: 'färg',
      en: 'colour',
      pos: 'noun',
      gender: 'en',
      pron: 'fairy, said as one syllable (rg sounds like "ry")',
      note: 'Vilken färg har …? = What colour is …?',
      forms: { definite: 'färgen', plural: 'färger', pluralDefinite: 'färgerna' },
      enAlt: ['color', 'paint'],
    },
  ],
  dialogue: {
    title: 'I klädaffären',
    setting: 'Lina is shopping for clothes. Jonas works in the shop.',
    lines: [
      { speaker: 'Jonas', sv: 'Hej! Kan jag hjälpa dig?', en: 'Hi! Can I help you?' },
      {
        speaker: 'Lina',
        sv: 'Ja, tack. Jag letar efter en ny jacka.',
        en: 'Yes, please. I’m looking for a new jacket.',
      },
      { speaker: 'Jonas', sv: 'Vilken färg vill du ha?', en: 'What colour would you like?' },
      { speaker: 'Lina', sv: 'Svart eller grå, kanske.', en: 'Black or grey, maybe.' },
      {
        speaker: 'Jonas',
        sv: 'Den här svarta jackan är fin. Och den är på rea!',
        en: 'This black jacket is nice. And it’s on sale!',
      },
      {
        speaker: 'Lina',
        sv: 'Vad bra! Och de röda skorna där, vad kostar de?',
        en: 'Great! And the red shoes over there, how much are they?',
      },
      { speaker: 'Jonas', sv: 'De kostar 400 kronor.', en: 'They’re 400 kronor.' },
      {
        speaker: 'Lina',
        sv: 'Perfekt! Då tar jag den svarta jackan och de röda skorna.',
        en: 'Perfect! Then I’ll take the black jacket and the red shoes.',
      },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Den ___ bilen är min.',
      en: 'The red car is mine.',
      choices: ['röd', 'rött', 'röda'],
      answer: 'röda',
      explanation:
        'With den in front and -en on the noun ("the" twice), the adjective always ends in -a: den röda bilen.',
      vocab: ['rod', 'bil'],
    },
    {
      type: 'gap',
      text: '___ vita huset är vårt.',
      en: 'The white house is ours.',
      choices: ['Den', 'Det', 'De'],
      answer: 'Det',
      explanation:
        'hus is an ett-word, so the little "the" word in front is det: det vita huset. Den is for en-words, de for plurals.',
      vocab: ['vit', 'hus'],
    },
    {
      type: 'gap',
      text: 'Jag gillar den ___ katten.',
      en: 'I like the little cat.',
      choices: ['liten', 'litet', 'lilla'],
      answer: 'lilla',
      explanation:
        'liten has a special form after den, det and min: lilla. So "the little cat" is den lilla katten.',
      vocab: ['liten', 'katt'],
    },
    {
      type: 'gap',
      text: 'Det här är min ___ cykel.',
      en: 'This is my new bike.',
      choices: ['ny', 'nytt', 'nya'],
      answer: 'nya',
      explanation:
        'After min, mitt, mina (my) the adjective ends in -a: min nya cykel. The noun has no ending.',
      vocab: ['ny', 'cykel', 'min'],
    },
    {
      type: 'type',
      prompt: 'the green car',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'den gröna bilen',
      reject: [
        'den grön bilen',
        'den grönt bilen',
        'den gröna bil',
        'det gröna bilen',
        'gröna bilen',
      ],
      strict: true,
      hint: 'Mark "the" twice',
      explanation:
        'bil is an en-word: den in front, -a on the adjective and -en on the noun: den gröna bilen.',
      vocab: ['gron', 'bil'],
    },
    {
      type: 'type',
      prompt: 'blue shoes',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'blå skor',
      accept: ['blåa skor'],
      reject: ['blått skor', 'blåt skor', 'blå sko', 'blåa skorna'],
      strict: true,
      explanation:
        'In the plural, blå can stay blå or take -a: blå skor and blåa skor are both correct.',
      vocab: ['bla', 'sko'],
    },
    {
      type: 'build',
      prompt: 'The black dog is mine.',
      answer: 'Den svarta hunden är min.',
      distractors: ['svart', 'hund', 'det'],
      explanation:
        '"The black dog": den in front, svarta with -a, and hunden with the "the" ending.',
      vocab: ['svart', 'hund', 'min'],
    },
    {
      type: 'listen',
      audio: 'Vilken färg har din cykel?',
      choices: ['What colour is your bike?', 'Where is your bike?', 'Is your bike new?'],
      answer: 'What colour is your bike?',
      explanation: 'Vilken färg har …? is how Swedes ask "What colour is …?"',
      vocab: ['farg', 'cykel', 'vilken'],
    },
    {
      type: 'dictation',
      audio: 'Vi har ett rött hus och en vit bil.',
      en: 'We have a red house and a white car.',
      vocab: ['rod', 'vit', 'hus', 'bil'],
    },
    {
      type: 'speak',
      text: 'Jag tar den rosa tröjan och de svarta skorna.',
      en: 'I’ll take the pink sweater and the black shoes.',
      vocab: ['rosa', 'svart', 'troja', 'sko'],
    },
  ],
})
