import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u09-l03',
  learn: [
    {
      title: 'Group 1: -a becomes -or',
      text: 'Swedish has five ways of making a plural. The easiest one first: en-words that end in **-a** swap the -a for **-or**.\n\n[[en flicka]] → [[två flickor]]\n\nTo say "the" in the plural, add **-na**: [[flickorna]] (the girls).',
      table: {
        headers: ['one', 'two or more', 'the … (plural)', 'English'],
        rows: [
          ['en flicka', 'flickor', 'flickorna', 'girls'],
          ['en blomma', 'blommor', 'blommorna', 'flowers'],
          ['en gurka', 'gurkor', 'gurkorna', 'cucumbers'],
          ['en skola', 'skolor', 'skolorna', 'schools'],
          ['en lampa', 'lampor', 'lamporna', 'lamps'],
        ],
        svColumns: [0, 1, 2],
      },
    },
    {
      title: 'Group 2: -ar',
      text: 'Lots of other en-words, especially short everyday ones, add **-ar**: [[en bil]] → [[två bilar]].\n\nIf the word ends in an unstressed **-e**, the e drops first: [[pojke]] → [[pojkar]], [[kudde]] → [[kuddar]]. "The" is **-na** again: [[bilarna]].',
      table: {
        headers: ['one', 'two or more', 'the … (plural)', 'English'],
        rows: [
          ['en bil', 'bilar', 'bilarna', 'cars'],
          ['en arm', 'armar', 'armarna', 'arms'],
          ['en sten', 'stenar', 'stenarna', 'stones'],
          ['en tidning', 'tidningar', 'tidningarna', 'newspapers'],
          ['en pojke', 'pojkar', 'pojkarna', 'boys'],
          ['en kudde', 'kuddar', 'kuddarna', 'cushions'],
        ],
        svColumns: [0, 1, 2],
      },
      tip: 'Words ending in -ing always take -ar: [[en tidning]] → [[tidningar]].',
    },
    {
      title: 'Words ending in -el, -er and -on',
      text: 'In group 2, an unstressed **-el**, **-er** or **-on** at the end loses its vowel before -ar: [[fågel]] → [[fåglar]], [[vinter]] → [[vintrar]], [[morgon]] → [[morgnar]].',
      table: {
        headers: ['one', 'two or more', 'the … (plural)', 'English'],
        rows: [
          ['en fågel', 'fåglar', 'fåglarna', 'birds'],
          ['en nyckel', 'nycklar', 'nycklarna', 'keys'],
          ['en cykel', 'cyklar', 'cyklarna', 'bikes'],
          ['en vinter', 'vintrar', 'vintrarna', 'winters'],
          ['en morgon', 'morgnar', 'morgnarna', 'mornings'],
        ],
        svColumns: [0, 1, 2],
      },
      tip: 'Rule of thumb: an en-word ending in -a takes -or. For other short en-words, -ar is a good first guess, but not a guarantee: the next lesson brings -er.',
    },
  ],
  vocab: [
    {
      id: 'blomma',
      sv: 'blomma',
      en: 'flower',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'blomman', plural: 'blommor', pluralDefinite: 'blommorna' },
    },
    {
      id: 'gurka',
      sv: 'gurka',
      en: 'cucumber',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'gurkan', plural: 'gurkor', pluralDefinite: 'gurkorna' },
    },
    {
      id: 'skola',
      sv: 'skola',
      en: 'school',
      pos: 'noun',
      gender: 'en',
      note: 'i skolan = at school',
      forms: { definite: 'skolan', plural: 'skolor', pluralDefinite: 'skolorna' },
    },
    {
      id: 'tidning',
      sv: 'tidning',
      en: 'newspaper',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'tidningen', plural: 'tidningar', pluralDefinite: 'tidningarna' },
      enAlt: ['magazine', 'paper'],
    },
    {
      id: 'fagel',
      sv: 'fågel',
      en: 'bird',
      pos: 'noun',
      gender: 'en',
      note: 'The e drops in the plural: fåglar.',
      forms: { definite: 'fågeln', plural: 'fåglar', pluralDefinite: 'fåglarna' },
    },
    {
      id: 'arm',
      sv: 'arm',
      en: 'arm',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'armen', plural: 'armar', pluralDefinite: 'armarna' },
    },
    {
      id: 'sten',
      sv: 'sten',
      en: 'stone / rock',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'stenen', plural: 'stenar', pluralDefinite: 'stenarna' },
      enAlt: ['stone', 'rock'],
    },
    {
      id: 'kudde',
      sv: 'kudde',
      en: 'pillow / cushion',
      pos: 'noun',
      gender: 'en',
      note: 'The final -e drops in the plural: kuddar.',
      forms: { definite: 'kudden', plural: 'kuddar', pluralDefinite: 'kuddarna' },
      enAlt: ['pillow', 'cushion'],
    },
  ],
  dialogue: {
    title: 'På torget',
    setting: 'Mia is at a market stall. Johan sells vegetables and flowers.',
    lines: [
      { speaker: 'Mia', sv: 'Hej! Två gurkor, tack.', en: 'Hi! Two cucumbers, please.' },
      { speaker: 'Johan', sv: 'Varsågod. Något mer?', en: 'Here you go. Anything else?' },
      {
        speaker: 'Mia',
        sv: 'Ja, de gula blommorna, vad kostar de?',
        en: 'Yes, the yellow flowers, how much are they?',
      },
      { speaker: 'Johan', sv: 'Trettio kronor styck.', en: 'Thirty kronor each.' },
      { speaker: 'Mia', sv: 'Då tar jag fem.', en: 'Then I’ll take five.' },
      {
        speaker: 'Johan',
        sv: 'Fem gula blommor, varsågod! Vill du ha en påse?',
        en: 'Five yellow flowers, here you go! Would you like a bag?',
      },
      {
        speaker: 'Mia',
        sv: 'Nej tack, jag har två armar!',
        en: 'No thanks, I’ve got two arms!',
      },
      { speaker: 'Johan', sv: 'Haha! Ha en fin dag!', en: 'Ha ha! Have a nice day!' },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Mia köper fem ___.',
      en: 'Mia is buying five flowers.',
      choices: ['blommor', 'blommar', 'blommer'],
      answer: 'blommor',
      explanation: 'blomma is an en-word ending in -a: group 1, so -a becomes -or: blommor.',
      vocab: ['blomma'],
    },
    {
      type: 'gap',
      text: 'Var är ___?',
      en: 'Where are the newspapers?',
      choices: ['tidningarna', 'tidningorna', 'tidningerna'],
      answer: 'tidningarna',
      explanation:
        'tidning ends in -ing, so it takes -ar (group 2): tidningar. "The" in the plural adds -na: tidningarna.',
      vocab: ['tidning'],
    },
    {
      type: 'gap',
      text: 'Vi har många ___ i soffan.',
      en: 'We have lots of cushions on the sofa.',
      choices: ['kuddar', 'kuddor', 'kudder'],
      answer: 'kuddar',
      explanation: 'kudde ends in -e: the e drops and it takes -ar (group 2): kuddar.',
      vocab: ['kudde', 'soffa'],
    },
    {
      type: 'type',
      prompt: 'two cucumbers',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'två gurkor',
      reject: ['två gurkar', 'två gurka', 'två gurkorna', 'två gurker'],
      strict: true,
      hint: 'en gurka',
      explanation: 'gurka is an en-word ending in -a: group 1, so the plural is gurkor.',
      vocab: ['gurka'],
    },
    {
      type: 'type',
      prompt: 'the schools',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'skolorna',
      reject: ['skolor', 'skolarna', 'skolerna', 'skolan'],
      strict: true,
      hint: 'en skola',
      explanation: 'skola → skolor (group 1). "The" in the plural adds -na: skolorna.',
      vocab: ['skola'],
    },
    {
      type: 'type',
      prompt: 'birds',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'fåglar',
      reject: ['fågelar', 'fåglor', 'fågeler', 'fågels', 'fågler'],
      strict: true,
      hint: 'en fågel',
      explanation:
        'fågel takes -ar (group 2), and the unstressed e in -el drops: fågel → fåglar, just like nyckel → nycklar.',
      vocab: ['fagel'],
    },
    {
      type: 'build',
      prompt: 'The boys have big stones.',
      answer: 'Pojkarna har stora stenar.',
      distractors: ['stenor', 'stort', 'pojkar'],
      explanation:
        'pojke → pojkar → pojkarna (the e drops, group 2). sten → stenar. And the adjective takes -a in the plural: stora.',
      vocab: ['pojke', 'sten', 'stor'],
    },
    {
      type: 'listen',
      audio: 'Flickorna läser tidningar.',
      choices: [
        'The girls are reading newspapers.',
        'The girl is reading a newspaper.',
        'The boys are reading newspapers.',
      ],
      answer: 'The girls are reading newspapers.',
      explanation: 'flickorna (-orna) is "the girls", plural. tidningar is plural too: newspapers.',
      vocab: ['flicka', 'tidning'],
    },
    {
      type: 'dictation',
      audio: 'Vi köper två gurkor och fem blommor.',
      en: 'We’re buying two cucumbers and five flowers.',
      accept: ['Vi köper 2 gurkor och 5 blommor.'],
      vocab: ['gurka', 'blomma'],
    },
    {
      type: 'speak',
      text: 'Var är cyklarna?',
      en: 'Where are the bikes?',
      vocab: ['cykel'],
    },
  ],
})
