import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u09-l05',
  learn: [
    {
      title: 'Group 4: ett-words add -n',
      text: 'ett-words that end in a **vowel** just add **-n**: [[ett äpple]] → [[två äpplen]].\n\nFor "the" in the plural, add **-a**: [[äpplena]] (the apples).',
      table: {
        headers: ['one', 'two or more', 'the … (plural)', 'English'],
        rows: [
          ['ett äpple', 'äpplen', 'äpplena', 'apples'],
          ['ett hjärta', 'hjärtan', 'hjärtana', 'hearts'],
          ['ett ställe', 'ställen', 'ställena', 'places'],
        ],
        svColumns: [0, 1, 2],
      },
    },
    {
      title: 'Group 5: no ending at all',
      text: 'ett-words that end in a **consonant** don’t change in the plural: [[ett hus]], [[två hus]]. The "the" form shows the difference: [[huset]] (the house), [[husen]] (the houses).\n\nen-words ending in **-are** (often jobs) don’t change either: [[en lärare]], [[två lärare]].',
      table: {
        headers: ['one', 'two or more', 'the … (plural)', 'English'],
        rows: [
          ['ett barn', 'barn', 'barnen', 'children'],
          ['ett djur', 'djur', 'djuren', 'animals'],
          ['ett träd', 'träd', 'träden', 'trees'],
          ['ett ord', 'ord', 'orden', 'words'],
          ['ett språk', 'språk', 'språken', 'languages'],
          ['ett ben', 'ben', 'benen', 'legs'],
          ['en lärare', 'lärare', 'lärarna', 'teachers'],
          ['en läkare', 'läkare', 'läkarna', 'doctors'],
        ],
        svColumns: [0, 1, 2],
      },
      tip: 'Careful with -are words: the e drops before -na, so "the doctors" is [[läkarna]], not "läkarena".',
    },
    {
      title: 'All five groups, and a few rebels',
      text: 'Here are all five plural groups together. A handful of everyday words are irregular and just have to be learnt: [[en man]] → [[två män]], [[en mus]] → [[två möss]], [[ett öga]] → [[två ögon]].',
      table: {
        headers: ['Group', 'Ending', 'Which words', 'Example'],
        rows: [
          ['1', '-or', 'en-words ending in -a', 'en flicka, två flickor'],
          ['2', '-ar', 'many en-words (-e, -el, -ing …)', 'en bil, två bilar'],
          ['3', '-er', 'loanwords, stress at the end, some with ä/ö', 'en sak, två saker'],
          ['4', '-n', 'ett-words ending in a vowel', 'ett äpple, två äpplen'],
          ['5', '(none)', 'ett-words ending in a consonant, en-words in -are', 'ett hus, två hus'],
        ],
        svColumns: [3],
      },
      tip: 'An ett-word never takes -or or -ar. So once you know a word is an ett-word, the plural is almost always -n (vowel at the end) or nothing (consonant at the end).',
    },
  ],
  vocab: [
    {
      id: 'hjarta',
      sv: 'hjärta',
      en: 'heart',
      pos: 'noun',
      gender: 'ett',
      pron: 'YAIR-ta (the h is silent)',
      forms: { definite: 'hjärtat', plural: 'hjärtan', pluralDefinite: 'hjärtana' },
    },
    {
      id: 'stalle',
      sv: 'ställe',
      en: 'place / spot',
      pos: 'noun',
      gender: 'ett',
      note: 'Ett bra ställe = a good place (to eat, to live …).',
      forms: { definite: 'stället', plural: 'ställen', pluralDefinite: 'ställena' },
      enAlt: ['place', 'spot'],
    },
    {
      id: 'djur',
      sv: 'djur',
      en: 'animal',
      pos: 'noun',
      gender: 'ett',
      pron: 'yoor (the d is silent)',
      forms: { definite: 'djuret', plural: 'djur', pluralDefinite: 'djuren' },
    },
    {
      id: 'trad',
      sv: 'träd',
      en: 'tree',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'trädet', plural: 'träd', pluralDefinite: 'träden' },
    },
    {
      id: 'ord',
      sv: 'ord',
      en: 'word',
      pos: 'noun',
      gender: 'ett',
      pron: 'oord',
      forms: { definite: 'ordet', plural: 'ord', pluralDefinite: 'orden' },
    },
    {
      id: 'sprak',
      sv: 'språk',
      en: 'language',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'språket', plural: 'språk', pluralDefinite: 'språken' },
    },
    {
      id: 'lakare',
      sv: 'läkare',
      en: 'doctor',
      pos: 'noun',
      gender: 'en',
      note: 'Same form in the plural: två läkare. The doctors = läkarna.',
      forms: { definite: 'läkaren', plural: 'läkare', pluralDefinite: 'läkarna' },
    },
    {
      id: 'mus',
      sv: 'mus',
      en: 'mouse',
      pos: 'noun',
      gender: 'en',
      note: 'Irregular plural: en mus, två möss.',
      forms: { definite: 'musen', plural: 'möss', pluralDefinite: 'mössen' },
    },
    {
      id: 'ben',
      sv: 'ben',
      en: 'leg / bone',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'benet', plural: 'ben', pluralDefinite: 'benen' },
      enAlt: ['leg', 'bone'],
    },
  ],
  dialogue: {
    title: 'I parken',
    setting: 'Leo and his dad are out for a walk in the park.',
    lines: [
      { speaker: 'Leo', sv: 'Pappa, titta! Där är en mus!', en: 'Dad, look! There’s a mouse!' },
      { speaker: 'Pappa', sv: 'Nej, där är tre möss!', en: 'No, there are three mice!' },
      { speaker: 'Leo', sv: 'Vilka söta djur!', en: 'What cute animals!' },
      {
        speaker: 'Pappa',
        sv: 'Ja. Och titta på fåglarna i träden.',
        en: 'Yes. And look at the birds in the trees.',
      },
      {
        speaker: 'Leo',
        sv: 'Hur många ben har en fågel?',
        en: 'How many legs does a bird have?',
      },
      { speaker: 'Pappa', sv: 'Två. Och en mus har fyra.', en: 'Two. And a mouse has four.' },
      {
        speaker: 'Leo',
        sv: 'Och jag har två ben och två armar!',
        en: 'And I have two legs and two arms!',
      },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Jag köper fem ___.',
      en: 'I’m buying five apples.',
      choices: ['äpplen', 'äpplar', 'äpple'],
      answer: 'äpplen',
      explanation: 'äpple is an ett-word ending in a vowel: group 4, so it just adds -n: äpplen.',
      vocab: ['apple'],
    },
    {
      type: 'gap',
      text: 'Hon pratar tre ___.',
      en: 'She speaks three languages.',
      choices: ['språk', 'språken', 'språker'],
      answer: 'språk',
      explanation:
        'språk is an ett-word ending in a consonant: group 5, no ending. (språken means "the languages".)',
      vocab: ['sprak'],
    },
    {
      type: 'gap',
      text: 'Barnen leker under ___.',
      en: 'The children are playing under the trees.',
      choices: ['träden', 'trädena', 'träder'],
      answer: 'träden',
      explanation:
        'träd is group 5: the plural is träd, and "the trees" adds -en, just like barnen (the children).',
      vocab: ['trad', 'barn'],
    },
    {
      type: 'type',
      prompt: 'the doctors',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'läkarna',
      reject: ['läkarena', 'läkare', 'läkaren', 'läkarerna', 'läkarne'],
      strict: true,
      hint: 'en läkare, två läkare',
      explanation:
        'läkare ends in -are, so the plural is the same: läkare. For "the", the e drops before -na: läkarna.',
      vocab: ['lakare'],
    },
    {
      type: 'type',
      prompt: 'mice',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'möss',
      reject: ['muser', 'musar', 'mus', 'mössen', 'mös'],
      strict: true,
      hint: 'irregular, like mouse → mice',
      explanation: 'mus is irregular, just like English mouse → mice: en mus, två möss.',
      vocab: ['mus'],
    },
    {
      type: 'type',
      prompt: 'hearts',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'hjärtan',
      reject: ['hjärtor', 'hjärtar', 'hjärtat', 'hjärta', 'hjärtana'],
      strict: true,
      hint: 'ett hjärta',
      explanation:
        'hjärta is an ett-word ending in a vowel: group 4, so it adds -n. (An ett-word never takes -or.)',
      vocab: ['hjarta'],
    },
    {
      type: 'build',
      prompt: 'How many Swedish words do you know?',
      answer: 'Hur många svenska ord kan du?',
      distractors: ['orden', 'svenskt', 'ordar'],
      explanation:
        'ord is group 5: one word, two words, both ord. svenska takes the plural -a because ord is plural here.',
      vocab: ['ord'],
    },
    {
      type: 'listen',
      audio: 'Katten har fyra ben.',
      choices: ['The cat has four legs.', 'The cat has four eyes.', 'The cats have four legs.'],
      answer: 'The cat has four legs.',
      explanation: 'ben (leg) is group 5, so it doesn’t change in the plural: fyra ben.',
      vocab: ['ben', 'katt'],
    },
    {
      type: 'dictation',
      audio: 'Vi har två barn och tre djur.',
      en: 'We have two children and three animals.',
      accept: ['Vi har 2 barn och 3 djur.'],
      vocab: ['barn', 'djur'],
    },
    {
      type: 'speak',
      text: 'Jag har två ögon och två ben.',
      en: 'I have two eyes and two legs.',
      vocab: ['ben'],
    },
  ],
})
