import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u09-l04',
  learn: [
    {
      title: 'Group 3: -er',
      text: 'The third group adds **-er**. It’s used by many en-words, especially **loanwords** and words stressed on the **last** syllable, like [[restaurang]], [[person]] and [[telefon]].\n\n"The" in the plural adds **-na** again: [[saker]] → [[sakerna]].',
      table: {
        headers: ['one', 'two or more', 'the … (plural)', 'English'],
        rows: [
          ['en sak', 'saker', 'sakerna', 'things'],
          ['en månad', 'månader', 'månaderna', 'months'],
          ['en person', 'personer', 'personerna', 'people'],
          ['en restaurang', 'restauranger', 'restaurangerna', 'restaurants'],
          ['en telefon', 'telefoner', 'telefonerna', 'phones'],
          ['en idé', 'idéer', 'idéerna', 'ideas'],
        ],
        svColumns: [0, 1, 2],
      },
      tip: 'Words ending in a stressed -é simply add -er, so two e’s in a row is correct: [[idé]] → [[idéer]]. Some short words ending in another vowel just add **-r**: [[en sko]] → [[skor]].',
    },
    {
      title: 'Vowel changes: stad → städer',
      text: 'A few short, very old words in group 3 also change their vowel, a bit like English man → men or foot → feet. **a** becomes **ä** and **o** becomes **ö**.',
      table: {
        headers: ['one', 'two or more', 'the … (plural)', 'English'],
        rows: [
          ['en stad', 'städer', 'städerna', 'cities'],
          ['en hand', 'händer', 'händerna', 'hands'],
          ['en natt', 'nätter', 'nätterna', 'nights'],
          ['ett land', 'länder', 'länderna', 'countries'],
          ['en fot', 'fötter', 'fötterna', 'feet'],
          ['en bok', 'böcker', 'böckerna', 'books'],
        ],
        svColumns: [0, 1, 2],
      },
      tip: 'In fötter and böcker the vowel becomes short, so the consonant after it doubles (k is doubled as ck). Notice ett land: a few ett-words join group 3 too.',
    },
    {
      title: 'So far: three groups',
      text: 'Here are the three groups you know. Almost all the words in them are en-words.',
      table: {
        headers: ['Group', 'Ending', 'Typical words', 'Example'],
        rows: [
          ['1', '-or', 'en-words ending in -a', 'en flicka, två flickor'],
          ['2', '-ar', 'many short en-words; words ending in -e, -el, -ing', 'en bil, två bilar'],
          ['3', '-er', 'loanwords, stress at the end, some with ä/ö', 'en sak, två saker'],
        ],
        svColumns: [3],
      },
      tip: 'When you learn a new noun, learn the plural with it: en sak, saker. The vocabulary list always shows it.',
    },
  ],
  vocab: [
    {
      id: 'sak',
      sv: 'sak',
      en: 'thing',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'saken', plural: 'saker', pluralDefinite: 'sakerna' },
    },
    {
      id: 'manad',
      sv: 'månad',
      en: 'month',
      pos: 'noun',
      gender: 'en',
      pron: 'MOH-nahd',
      forms: { definite: 'månaden', plural: 'månader', pluralDefinite: 'månaderna' },
    },
    {
      id: 'ide',
      sv: 'idé',
      en: 'idea',
      pos: 'noun',
      gender: 'en',
      pron: 'ee-DAY',
      forms: { definite: 'idén', plural: 'idéer', pluralDefinite: 'idéerna' },
      alt: ['ide'],
    },
    {
      id: 'person',
      sv: 'person',
      en: 'person',
      pos: 'noun',
      gender: 'en',
      pron: 'pair-SHOON (rs sounds like "sh")',
      note: 'Used for counting people: fem personer = five people.',
      forms: { definite: 'personen', plural: 'personer', pluralDefinite: 'personerna' },
    },
    {
      id: 'restaurang',
      sv: 'restaurang',
      en: 'restaurant',
      pos: 'noun',
      gender: 'en',
      pron: 'res-toh-RANG',
      forms: {
        definite: 'restaurangen',
        plural: 'restauranger',
        pluralDefinite: 'restaurangerna',
      },
    },
    {
      id: 'stad',
      sv: 'stad',
      en: 'city / town',
      pos: 'noun',
      gender: 'en',
      note: 'Vowel change in the plural: städer.',
      forms: { definite: 'staden', plural: 'städer', pluralDefinite: 'städerna' },
      enAlt: ['city', 'town'],
    },
    {
      id: 'hand',
      sv: 'hand',
      en: 'hand',
      pos: 'noun',
      gender: 'en',
      note: 'Vowel change in the plural: händer.',
      forms: { definite: 'handen', plural: 'händer', pluralDefinite: 'händerna' },
    },
    {
      id: 'fot',
      sv: 'fot',
      en: 'foot',
      pos: 'noun',
      gender: 'en',
      note: 'Vowel change in the plural: fötter.',
      forms: { definite: 'foten', plural: 'fötter', pluralDefinite: 'fötterna' },
    },
    {
      id: 'natt',
      sv: 'natt',
      en: 'night',
      pos: 'noun',
      gender: 'en',
      note: 'Vowel change in the plural: nätter. i natt = tonight / last night.',
      forms: { definite: 'natten', plural: 'nätter', pluralDefinite: 'nätterna' },
    },
    {
      id: 'land',
      sv: 'land',
      en: 'country',
      pos: 'noun',
      gender: 'ett',
      note: 'An ett-word with an -er plural and a vowel change: länder.',
      forms: { definite: 'landet', plural: 'länder', pluralDefinite: 'länderna' },
      enAlt: ['land'],
    },
  ],
  dialogue: {
    title: 'Sommarplaner',
    setting: 'Emma and Omar are chatting over coffee about the summer.',
    lines: [
      { speaker: 'Emma', sv: 'Vad gör du i sommar?', en: 'What are you doing this summer?' },
      {
        speaker: 'Omar',
        sv: 'Jag reser runt i Europa i två månader!',
        en: 'I’m travelling around Europe for two months!',
      },
      { speaker: 'Emma', sv: 'Två månader! Vilka länder?', en: 'Two months! Which countries?' },
      {
        speaker: 'Omar',
        sv: 'Italien, Spanien och Frankrike. Tre nätter i varje stad.',
        en: 'Italy, Spain and France. Three nights in each city.',
      },
      {
        speaker: 'Emma',
        sv: 'Vad kul! Ta inte med för många saker.',
        en: 'How fun! Don’t take too many things.',
      },
      {
        speaker: 'Omar',
        sv: 'Nej, bara en liten väska. Och massor av idéer!',
        en: 'No, just a small bag. And loads of ideas!',
      },
      {
        speaker: 'Emma',
        sv: 'Skicka tips på bra restauranger!',
        en: 'Send me tips for good restaurants!',
      },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Stockholm och Göteborg är stora ___.',
      en: 'Stockholm and Gothenburg are big cities.',
      choices: ['städer', 'stader', 'stadar'],
      answer: 'städer',
      explanation: 'stad belongs to group 3 and changes its vowel: a → ä. So the plural is städer.',
      vocab: ['stad', 'stor'],
    },
    {
      type: 'gap',
      text: 'Mina ___ är kalla.',
      en: 'My hands are cold.',
      choices: ['händer', 'hander', 'handar'],
      answer: 'händer',
      explanation: 'hand is group 3 with a vowel change, a → ä: händer.',
      vocab: ['hand'],
    },
    {
      type: 'gap',
      text: 'Sverige och Norge är två ___.',
      en: 'Sweden and Norway are two countries.',
      choices: ['länder', 'lander', 'land'],
      answer: 'länder',
      explanation:
        'land is an ett-word, but it doesn’t stay the same in the plural: it takes -er and changes a → ä: länder.',
      vocab: ['land'],
    },
    {
      type: 'type',
      prompt: 'restaurants',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'restauranger',
      reject: ['restaurangar', 'restaurangor', 'restaurangs', 'restaurangerna'],
      strict: true,
      hint: 'en restaurang (stressed on the last syllable)',
      explanation:
        'restaurang is a loanword stressed on the last syllable, so it takes -er (group 3): restauranger.',
      vocab: ['restaurang'],
    },
    {
      type: 'type',
      prompt: 'feet',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'fötter',
      reject: ['föter', 'foter', 'fotar', 'fötar', 'fotter', 'fötterna'],
      strict: true,
      hint: 'en fot: o becomes ö',
      explanation:
        'fot is group 3 with a vowel change: o → ö. The vowel is short, so the t doubles: fötter.',
      vocab: ['fot'],
    },
    {
      type: 'type',
      prompt: 'the ideas',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'idéerna',
      accept: ['ideerna'],
      reject: ['idéer', 'idéarna', 'idérna', 'idéorna', 'idén'],
      strict: true,
      hint: 'en idé',
      explanation: 'idé ends in a stressed vowel, so it adds -er: idéer. "The" adds -na: idéerna.',
      vocab: ['ide'],
    },
    {
      type: 'build',
      prompt: 'Five people live in the house.',
      answer: 'Fem personer bor i huset.',
      accept: ['I huset bor fem personer.'],
      distractors: ['personar', 'hus', 'personen'],
      explanation:
        'person is stressed on the last syllable, so it takes -er: personer. Use it when you count people.',
      vocab: ['person', 'hus'],
    },
    {
      type: 'listen',
      audio: 'Hon reser i tre månader.',
      choices: [
        'She’s travelling for three months.',
        'She’s travelling for three weeks.',
        'She’s travelling for three nights.',
      ],
      answer: 'She’s travelling for three months.',
      explanation: 'månader is the plural of månad (month). Weeks would be veckor, nights nätter.',
      vocab: ['manad'],
    },
    {
      type: 'dictation',
      audio: 'Staden har många bra restauranger.',
      en: 'The city has lots of good restaurants.',
      vocab: ['stad', 'restaurang'],
    },
    {
      type: 'speak',
      text: 'Jag har två händer och två fötter.',
      en: 'I have two hands and two feet.',
      vocab: ['hand', 'fot'],
    },
  ],
})
