import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u09-l01',
  learn: [
    {
      title: 'Adjectives match the noun',
      text: 'In English, "big" is always "big". In Swedish, an adjective changes its ending to match the noun it describes:\n\n**en**-words: no ending: [[en stor bil]]\n**ett**-words: add **-t**: [[ett stort hus]]\nplural (two or more): add **-a**: [[stora bilar]]',
      table: {
        headers: ['en-word', 'ett-word', 'plural', 'English'],
        rows: [
          ['en stor bil', 'ett stort hus', 'stora bilar', 'big'],
          ['en fin tröja', 'ett fint rum', 'fina tröjor', 'nice'],
          ['en ful lampa', 'ett fult bord', 'fula lampor', 'ugly'],
          ['en tung väska', 'ett tungt glas', 'tunga väskor', 'heavy'],
          ['en smutsig kopp', 'ett smutsigt glas', 'smutsiga koppar', 'dirty'],
        ],
        svColumns: [0, 1, 2],
      },
      tip: 'In the plural it doesn’t matter if the noun is an en-word or an ett-word: [[stora bilar]], [[stora hus]].',
    },
    {
      title: 'After är, too',
      text: 'The adjective still matches the noun when it comes after **är**. Look back at the noun: is it an en-word, an ett-word or a plural?',
      examples: [
        { sv: 'Bilen är stor.', en: 'The car is big.' },
        { sv: 'Huset är stort.', en: 'The house is big.' },
        { sv: 'Bilarna är stora.', en: 'The cars are big.' },
        { sv: 'Rummet är rent.', en: 'The room is clean.' },
        { sv: 'Väskorna är tunga.', en: 'The bags are heavy.' },
      ],
    },
    {
      title: 'A few adjectives bend the rules',
      text: 'Some adjectives follow small spelling rules, and one is a real rebel:',
      table: {
        headers: ['Rule', 'en-word', 'ett-word', 'plural'],
        rows: [
          ['ends in -tt or consonant + t: no extra t', 'lätt', 'lätt', 'lätta'],
          ['long vowel + d or t → -tt', 'god', 'gott', 'goda'],
          ['ends in a vowel → -tt', 'ny', 'nytt', 'nya'],
          ['irregular', 'liten', 'litet', 'små'],
          ['never changes', 'bra', 'bra', 'bra'],
        ],
        svColumns: [1, 2, 3],
      },
      tip: 'Learn liten by heart: [[en liten katt]], [[ett litet hus]], [[små barn]]. And two favourites never change at all: [[ett bra rum]], [[bra böcker]], [[Det är kul!]]',
    },
  ],
  vocab: [
    {
      id: 'stor',
      sv: 'stor',
      en: 'big / large',
      pos: 'adjective',
      forms: { neuter: 'stort', plural: 'stora', comparative: 'större', superlative: 'störst' },
      enAlt: ['big', 'large'],
    },
    {
      id: 'liten',
      sv: 'liten',
      en: 'small / little',
      pos: 'adjective',
      note: 'Irregular: en liten bil, ett litet hus, små bilar. "The little …" is lilla: den lilla bilen.',
      forms: { neuter: 'litet', plural: 'små', comparative: 'mindre', superlative: 'minst' },
      enAlt: ['small', 'little'],
    },
    {
      id: 'ny',
      sv: 'ny',
      en: 'new',
      pos: 'adjective',
      note: 'Ends in a vowel, so the ett-form doubles the t: ett nytt hus.',
      forms: { neuter: 'nytt', plural: 'nya', comparative: 'nyare', superlative: 'nyast' },
    },
    {
      id: 'dalig',
      sv: 'dålig',
      en: 'bad',
      pos: 'adjective',
      note: 'Jag mår dåligt = I feel bad / unwell.',
      forms: { neuter: 'dåligt', plural: 'dåliga', comparative: 'sämre', superlative: 'sämst' },
      enAlt: ['poor'],
    },
    {
      id: 'fin',
      sv: 'fin',
      en: 'nice / fine',
      pos: 'adjective',
      note: 'Swedes use fin all the time for things that look nice: Vad fint! = How nice!',
      forms: { neuter: 'fint', plural: 'fina', comparative: 'finare', superlative: 'finast' },
      enAlt: ['nice', 'fine', 'pretty'],
    },
    {
      id: 'ful',
      sv: 'ful',
      en: 'ugly',
      pos: 'adjective',
      forms: { neuter: 'fult', plural: 'fula', comparative: 'fulare', superlative: 'fulast' },
    },
    {
      id: 'latt',
      sv: 'lätt',
      en: 'easy / light',
      pos: 'adjective',
      note: 'Already ends in -tt, so the ett-form is the same: en lätt väska (a light bag), ett lätt jobb (an easy job).',
      forms: { neuter: 'lätt', plural: 'lätta', comparative: 'lättare', superlative: 'lättast' },
      enAlt: ['easy', 'light'],
    },
    {
      id: 'svar-difficult',
      sv: 'svår',
      en: 'difficult / hard',
      pos: 'adjective',
      forms: { neuter: 'svårt', plural: 'svåra', comparative: 'svårare', superlative: 'svårast' },
      enAlt: ['difficult', 'hard'],
    },
    {
      id: 'ren',
      sv: 'ren',
      en: 'clean',
      pos: 'adjective',
      forms: { neuter: 'rent', plural: 'rena', comparative: 'renare', superlative: 'renast' },
    },
    {
      id: 'smutsig',
      sv: 'smutsig',
      en: 'dirty',
      pos: 'adjective',
      forms: { neuter: 'smutsigt', plural: 'smutsiga' },
    },
    {
      id: 'tung',
      sv: 'tung',
      en: 'heavy',
      pos: 'adjective',
      forms: { neuter: 'tungt', plural: 'tunga', comparative: 'tyngre', superlative: 'tyngst' },
    },
  ],
  dialogue: {
    title: 'På loppis',
    setting: 'Sara and Ali are at a flea market, looking for things for their flat.',
    lines: [
      { speaker: 'Ali', sv: 'Titta, en fin cykel!', en: 'Look, a nice bike!' },
      {
        speaker: 'Sara',
        sv: 'Ja, men den är ganska ful. Och smutsig!',
        en: 'Yes, but it’s pretty ugly. And dirty!',
      },
      {
        speaker: 'Ali',
        sv: 'Den är inte ny, men den är billig.',
        en: 'It isn’t new, but it’s cheap.',
      },
      {
        speaker: 'Sara',
        sv: 'Okej. Och titta här, ett litet bord!',
        en: 'Okay. And look here, a little table!',
      },
      { speaker: 'Ali', sv: 'Vad fint! Är det tungt?', en: 'How nice! Is it heavy?' },
      { speaker: 'Sara', sv: 'Nej, det är lätt. Och rent!', en: 'No, it’s light. And clean!' },
      {
        speaker: 'Ali',
        sv: 'Bra, då köper vi bordet och cykeln!',
        en: 'Great, then we’ll buy the table and the bike!',
      },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Vi har ett ___ hus.',
      en: 'We have a big house.',
      choices: ['stor', 'stort', 'stora'],
      answer: 'stort',
      explanation: 'hus is an ett-word, so the adjective adds -t: ett stort hus.',
      vocab: ['stor', 'hus'],
    },
    {
      type: 'gap',
      text: 'Rummet är ___.',
      en: 'The room is clean.',
      choices: ['ren', 'rent', 'rena'],
      answer: 'rent',
      explanation:
        'rum is an ett-word (ett rum, rummet), so the adjective adds -t, even after är: Rummet är rent.',
      vocab: ['ren', 'rum'],
    },
    {
      type: 'gap',
      text: 'Skorna är ___.',
      en: 'The shoes are ugly.',
      choices: ['ful', 'fult', 'fula'],
      answer: 'fula',
      explanation: 'skorna (the shoes) is plural, so the adjective adds -a: fula.',
      vocab: ['ful', 'sko'],
    },
    {
      type: 'type',
      prompt: 'a new house',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'ett nytt hus',
      reject: ['ett nyt hus', 'ett ny hus', 'ett nya hus', 'en ny hus'],
      strict: true,
      hint: 'ny ends in a vowel',
      explanation:
        'hus is an ett-word, and ny ends in a vowel, so the ett-form doubles the t: nytt.',
      vocab: ['ny', 'hus'],
    },
    {
      type: 'type',
      prompt: 'small cars',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'små bilar',
      reject: ['liten bilar', 'litet bilar', 'litna bilar', 'lilla bilar', 'små bil'],
      strict: true,
      hint: 'liten is irregular in the plural',
      explanation: 'liten is irregular: en liten bil, ett litet hus, but små bilar.',
      vocab: ['liten', 'bil'],
    },
    {
      type: 'type',
      prompt: 'The house is dirty.',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'Huset är smutsigt.',
      reject: ['Huset är smutsig.', 'Huset är smutsiga.'],
      strict: true,
      explanation:
        'hus is an ett-word (huset = the house), so the adjective adds -t after är too: smutsigt.',
      vocab: ['smutsig', 'hus'],
    },
    {
      type: 'build',
      prompt: 'We have a big house and a small car.',
      answer: 'Vi har ett stort hus och en liten bil.',
      distractors: ['stor', 'litet', 'stora'],
      explanation:
        'ett hus takes the -t form (stort); en bil takes the basic form (liten). The adjective comes before the noun, as in English.',
      vocab: ['stor', 'liten', 'hus', 'bil'],
    },
    {
      type: 'listen',
      audio: 'Väskan är tung.',
      choices: ['The bag is heavy.', 'The bag is light.', 'The bag is new.'],
      answer: 'The bag is heavy.',
      explanation: 'tung means heavy. "Light" would be lätt, and "new" would be ny.',
      vocab: ['tung', 'vaska'],
    },
    {
      type: 'dictation',
      audio: 'Bilen är ny, men den är smutsig.',
      en: 'The car is new, but it’s dirty.',
      vocab: ['ny', 'smutsig', 'bil'],
    },
    {
      type: 'speak',
      text: 'Det är ett fint rum.',
      en: 'It’s a nice room.',
      vocab: ['fin', 'rum'],
    },
  ],
})
