import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u10-l04',
  learn: [
    {
      title: 'Plans: ska + verb',
      text: 'You met **ska** in Unit 5. Its most common job is talking about **plans**: things you have decided to do. Just put the infinitive after it, with no "att": [[Vi ska resa.]] (We’re going to travel.)\n\n**tänker** + infinitive works the same way and means "intend to / am planning to": [[Jag tänker plugga mer.]]',
      examples: [
        { sv: 'Vad ska du göra i helgen?', en: 'What are you doing at the weekend?' },
        { sv: 'Vi ska hyra en sommarstuga.', en: 'We’re going to rent a summer cottage.' },
        { sv: 'Vi ska vara där i två veckor.', en: 'We’ll be there for two weeks.' },
        { sv: 'Jag tänker boka en resa.', en: 'I’m planning to book a trip.' },
        { sv: 'Vi planerar att resa till Norge.', en: 'We’re planning to travel to Norway.' },
      ],
      tip: 'ska and tänker take the verb directly, but planerar needs att: [[Vi planerar att resa.]]\n\n[[i sommar]] means *this coming* summer; [[i somras]] means *last* summer, just like i lördags.',
    },
    {
      title: 'Present tense + a time word',
      text: 'Like English "I’m working tomorrow", Swedish often uses the plain present tense for the future, as long as a time word makes it clear: [[Imorgon jobbar jag hemma.]] [[På fredag reser vi.]]\n\nTo say **in** a week, in two days and so on, use **om**:',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['om en vecka', 'in a week'],
          ['om två dagar', 'in two days'],
          ['om en timme', 'in an hour'],
          ['om tio minuter', 'in ten minutes'],
          ['senare', 'later'],
          ['i framtiden', 'in the future'],
        ],
        svColumns: [0],
      },
      tip: 'Careful: [[i en vecka]] means *for* a week. "Vi reser om en vecka" = we leave in a week. "Vi reser i en vecka" = we travel for a week.',
    },
  ],
  culture: {
    title: 'Sommarstugan',
    text: 'Many Swedes own, rent or borrow a **sommarstuga**, a summer cottage in the countryside, often by a lake or the sea. The classic one is a red wooden house with white corners. With five weeks of paid holiday a year, lots of families spend a few weeks there in July: swimming, reading, picking berries and doing as little as possible.',
    examples: [
      { sv: 'Vi ska vara i sommarstugan i juli.', en: 'We’ll be at the summer cottage in July.' },
    ],
  },
  vocab: [
    {
      id: 'planera',
      sv: 'planera',
      en: 'to plan',
      pos: 'verb',
      forms: { present: 'planerar', past: 'planerade', supine: 'planerat', imperative: 'planera' },
      note: 'Followed by att + verb: "Vi planerar att resa."',
      enAlt: ['plan'],
    },
    {
      id: 'framtid',
      sv: 'framtid',
      en: 'future',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'framtiden', plural: 'framtider', pluralDefinite: 'framtiderna' },
      note: '"i framtiden" = in the future.',
      enAlt: ['the future'],
    },
    {
      id: 'senare',
      sv: 'senare',
      en: 'later',
      pos: 'adverb',
      note: '"Vi ses senare!" = See you later!',
    },
    {
      id: 'om-in',
      sv: 'om',
      en: 'in (+ time ahead)',
      pos: 'preposition',
      note: '"om en vecka" = in a week (from now). om also means "if" and "about", which you will meet later.',
      enAlt: ['in'],
    },
    {
      id: 'resa-trip',
      sv: 'resa',
      en: 'trip / journey',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'resan', plural: 'resor', pluralDefinite: 'resorna' },
      note: 'The noun "en resa" looks like the verb "resa" (to travel).',
      enAlt: ['trip', 'journey'],
    },
    {
      id: 'hyra',
      sv: 'hyra',
      en: 'to rent',
      pos: 'verb',
      forms: { present: 'hyr', past: 'hyrde', supine: 'hyrt', imperative: 'hyr' },
      enAlt: ['rent', 'to hire'],
    },
    {
      id: 'boka',
      sv: 'boka',
      en: 'to book',
      pos: 'verb',
      forms: { present: 'bokar', past: 'bokade', supine: 'bokat', imperative: 'boka' },
      enAlt: ['book'],
    },
    {
      id: 'sommarstuga',
      sv: 'sommarstuga',
      en: 'summer cottage',
      pos: 'noun',
      gender: 'en',
      forms: {
        definite: 'sommarstugan',
        plural: 'sommarstugor',
        pluralDefinite: 'sommarstugorna',
      },
      enAlt: ['summer house', 'cottage'],
    },
    {
      id: 'packa',
      sv: 'packa',
      en: 'to pack',
      pos: 'verb',
      forms: { present: 'packar', past: 'packade', supine: 'packat', imperative: 'packa' },
      enAlt: ['pack'],
    },
    {
      id: 'langta',
      sv: 'längta',
      en: 'to long / to look forward',
      pos: 'verb',
      forms: { present: 'längtar', past: 'längtade', supine: 'längtat', imperative: 'längta' },
      note: '"Jag längtar till sommaren" = I can’t wait for summer. "Jag längtar efter dig" = I miss you / I long for you.',
      enAlt: ['to long', 'to look forward', 'long'],
    },
  ],
  dialogue: {
    title: 'Summer plans',
    setting: 'Anna and Leo are having fika at work in May.',
    lines: [
      { speaker: 'Anna', sv: 'Vad ska ni göra i sommar?', en: 'What are you doing this summer?' },
      {
        speaker: 'Leo',
        sv: 'Vi ska hyra en sommarstuga i Dalarna.',
        en: 'We’re going to rent a summer cottage in Dalarna.',
      },
      {
        speaker: 'Anna',
        sv: 'Vad mysigt! Hur länge ska ni vara där?',
        en: 'How lovely! How long will you be there?',
      },
      {
        speaker: 'Leo',
        sv: 'I två veckor. Vi har redan bokat den.',
        en: 'For two weeks. We’ve already booked it.',
      },
      { speaker: 'Anna', sv: 'När reser ni?', en: 'When are you leaving?' },
      {
        speaker: 'Leo',
        sv: 'Om en månad. Jag längtar verkligen!',
        en: 'In a month. I really can’t wait!',
      },
      {
        speaker: 'Anna',
        sv: 'Och vad tänker du göra där?',
        en: 'And what are you planning to do there?',
      },
      {
        speaker: 'Leo',
        sv: 'Ingenting! Läsa, simma och sova.',
        en: 'Nothing! Read, swim and sleep.',
      },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Vi ___ hyra en sommarstuga i sommar.',
      en: 'We’re going to rent a summer cottage this summer.',
      choices: ['ska', 'har', 'är'],
      answer: 'ska',
      explanation: 'For a plan, use ska + the infinitive: ska hyra.',
      vocab: ['hyra', 'sommarstuga', 'sommar'],
    },
    {
      type: 'gap',
      text: 'Filmen börjar ___ tio minuter.',
      en: 'The film starts in ten minutes.',
      choices: ['om', 'i', 'på'],
      answer: 'om',
      explanation:
        'om + a time = "in" (from now): om tio minuter. "i tio minuter" would mean "for ten minutes".',
      vocab: ['om-in', 'minut'],
    },
    {
      type: 'gap',
      text: 'Jag ___ boka en resa till Spanien.',
      en: 'I’m planning to book a trip to Spain.',
      choices: ['tänker', 'tänka', 'tänkt'],
      answer: 'tänker',
      explanation:
        'tänker + infinitive = "intend to / am planning to". After jag the verb must be in the present (tänker), then comes boka, with no att.',
      vocab: ['boka', 'resa-trip'],
    },
    {
      type: 'type',
      prompt: 'the trip',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'resan',
      reject: ['resa', 'en resa', 'resen', 'reset', 'resor'],
      strict: true,
      hint: 'en resa',
      explanation: 'en resa ends in a vowel, so "the trip" just adds -n: resan.',
      vocab: ['resa-trip'],
    },
    {
      type: 'type',
      prompt: 'in two days',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'om två dagar',
      reject: ['i två dagar', 'på två dagar', 'om två dag'],
      strict: true,
      explanation:
        'Use om for "in" + a time ahead: om två dagar. "i två dagar" means "for two days".',
      vocab: ['om-in', 'tva'],
    },
    {
      type: 'build',
      prompt: 'We’re going to rent a summer cottage.',
      answer: 'Vi ska hyra en sommarstuga.',
      distractors: ['att', 'hyr'],
      explanation: 'ska is followed directly by the infinitive (hyra), with no att.',
      vocab: ['hyra', 'sommarstuga'],
    },
    {
      type: 'listen',
      audio: 'Jag längtar till sommaren.',
      choices: [
        'I can’t wait for the summer.',
        'I’m waiting for the summer.',
        'I’m planning the summer.',
      ],
      answer: 'I can’t wait for the summer.',
      explanation:
        'längta till means looking forward to something, longing for it. "To wait" is vänta.',
      vocab: ['langta', 'sommar'],
    },
    {
      type: 'dictation',
      audio: 'Vi har bokat en sommarstuga i två veckor.',
      en: 'We’ve booked a summer cottage for two weeks.',
      explanation: 'har bokat is the perfect of boka, and "i två veckor" means "for two weeks".',
      vocab: ['boka', 'sommarstuga', 'vecka'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Anna', sv: 'När reser ni?', en: 'When are you leaving?' }],
      question: 'You’re leaving in a month. What do you say?',
      choices: ['Om en månad.', 'I en månad.', 'För en månad sedan.'],
      answer: 'Om en månad.',
      explanation:
        'om en månad = in a month. "I en månad" means "for a month", and "för en månad sedan" means "a month ago".',
      vocab: ['om-in'],
    },
    {
      type: 'speak',
      text: 'Vad ska du göra i helgen?',
      en: 'What are you doing at the weekend?',
      vocab: ['gora', 'helg'],
    },
  ],
})
