import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u10-l03',
  learn: [
    {
      title: 'har + supine',
      text: 'To say "I have done" something, Swedish uses **har** + the *supine*, the last column in your verb tables. [[Jag har ätit.]] (I have eaten.) Like the other tenses, it is the same for every person.\n\nThe supine is easy to guess for most verbs:\n-ar verbs end in **-at**: [[jobbat]], [[provat]].\n-er verbs end in **-t**: [[läst]], [[besökt]].\nStrong verbs end in **-it**: [[ätit]], [[druckit]], [[skrivit]].',
      table: {
        headers: ['Infinitive', 'Present', 'Past', 'Supine'],
        rows: [
          ['prova', 'provar', 'provade', 'provat'],
          ['plugga', 'pluggar', 'pluggade', 'pluggat'],
          ['besöka', 'besöker', 'besökte', 'besökt'],
          ['uppleva', 'upplever', 'upplevde', 'upplevt'],
          ['lära sig', 'lär sig', 'lärde sig', 'lärt sig'],
          ['äta', 'äter', 'åt', 'ätit'],
          ['vara', 'är', 'var', 'varit'],
          ['se', 'ser', 'såg', 'sett'],
          ['gå', 'går', 'gick', 'gått'],
          ['få', 'får', 'fick', 'fått'],
        ],
        svColumns: [0, 1, 2, 3],
      },
      tip: 'The short and irregular verbs are the odd ones out: sett, gått, fått, gjort, haft, sagt. Learn them as words.',
    },
    {
      title: 'Past or perfect?',
      text: 'Swedish uses the two tenses much like English does.\n\n**Past** (åt, var) for a finished time: yesterday, last year, in May. [[Igår åt jag fisk.]]\n**Perfect** (har ätit, har varit) for experiences, or when no time is given. [[Jag har ätit surströmming.]]',
      examples: [
        { sv: 'Har du någonsin varit i Norge?', en: 'Have you ever been to Norway?' },
        { sv: 'Ja, jag var där förra året.', en: 'Yes, I was there last year.' },
        { sv: 'Jag har bott i Sverige i två år.', en: 'I’ve lived in Sweden for two years.' },
        { sv: 'Vi har upplevt mycket här.', en: 'We’ve experienced a lot here.' },
      ],
      tip: 'Just like in English, a question with "när" (when) takes the past: [[När var du i Norge?]] Not "När har du varit …".',
    },
    {
      title: 'ever, never, already, just, yet',
      text: 'Most of these little words go **after har**, just where inte goes: [[Jag har inte ätit.]] The exception is än (yet), which goes at the end.',
      examples: [
        { sv: 'Har du någonsin varit utomlands?', en: 'Have you ever been abroad?' },
        { sv: 'Jag har aldrig sett en älg.', en: 'I’ve never seen a moose.' },
        { sv: 'Jag har redan ätit.', en: 'I’ve already eaten.' },
        { sv: 'Hon har just kommit.', en: 'She has just arrived.' },
        { sv: 'Jag har inte ätit än.', en: 'I haven’t eaten yet.' },
        { sv: 'Jag har lärt mig mycket.', en: 'I’ve learned a lot.' },
      ],
      tip: '**än** (yet) goes at the end of the sentence. Use it in negatives and questions: [[inte än]] = not yet, [[Har du ätit än?]] = Have you eaten yet?',
    },
  ],
  vocab: [
    {
      id: 'nagonsin',
      sv: 'någonsin',
      en: 'ever',
      pos: 'adverb',
      pron: 'NOH-gon-sin (often just "NOHN-sin")',
      note: '"Har du någonsin …?" = Have you ever …?',
    },
    {
      id: 'just',
      sv: 'just',
      en: 'just (a moment ago)',
      pos: 'adverb',
      pron: 'yoost',
      note: '"Hon har just kommit" = She has just arrived.',
      enAlt: ['just'],
    },
    {
      id: 'an-yet',
      sv: 'än',
      en: 'yet',
      pos: 'adverb',
      pron: 'en',
      note: '"Inte än" = not yet. It goes at the end: "Jag har inte ätit än."',
      enAlt: ['still'],
    },
    {
      id: 'besoka',
      sv: 'besöka',
      en: 'to visit',
      pos: 'verb',
      forms: { present: 'besöker', past: 'besökte', supine: 'besökt', imperative: 'besök' },
      enAlt: ['visit'],
    },
    {
      id: 'prova',
      sv: 'prova',
      en: 'to try (out)',
      pos: 'verb',
      forms: { present: 'provar', past: 'provade', supine: 'provat', imperative: 'prova' },
      note: 'Try food, clothes or something new: "Prova kanelbullen!" For "try hard", use försöka.',
      enAlt: ['to try', 'try', 'to try on'],
    },
    {
      id: 'lara-sig',
      sv: 'lära sig',
      en: 'to learn',
      pos: 'verb',
      forms: {
        present: 'lär sig',
        past: 'lärde sig',
        supine: 'lärt sig',
        imperative: 'lär dig',
      },
      note: 'A reflexive verb: jag lär mig, du lär dig, hon lär sig, vi lär oss.',
      enAlt: ['learn'],
    },
    {
      id: 'utomlands',
      sv: 'utomlands',
      en: 'abroad',
      pos: 'adverb',
      pron: 'OO-tom-lands',
    },
    {
      id: 'plugga',
      sv: 'plugga',
      en: 'to study',
      pos: 'verb',
      forms: { present: 'pluggar', past: 'pluggade', supine: 'pluggat', imperative: 'plugga' },
      note: 'Everyday word for studying, revising or learning for school.',
      enAlt: ['study', 'to revise'],
    },
    {
      id: 'uppleva',
      sv: 'uppleva',
      en: 'to experience',
      pos: 'verb',
      forms: { present: 'upplever', past: 'upplevde', supine: 'upplevt', imperative: 'upplev' },
      enAlt: ['experience'],
    },
  ],
  dialogue: {
    title: 'Have you ever…?',
    setting: 'Johan chats with his new colleague Sam over lunch.',
    lines: [
      {
        speaker: 'Johan',
        sv: 'Hur länge har du bott i Sverige, Sam?',
        en: 'How long have you lived in Sweden, Sam?',
      },
      { speaker: 'Sam', sv: 'Jag har bott här i ett år.', en: 'I’ve lived here for a year.' },
      { speaker: 'Johan', sv: 'Har du varit i Norge?', en: 'Have you been to Norway?' },
      {
        speaker: 'Sam',
        sv: 'Nej, inte än. Men jag har besökt Danmark. Vi var i Köpenhamn i maj.',
        en: 'No, not yet. But I’ve visited Denmark. We were in Copenhagen in May.',
      },
      {
        speaker: 'Johan',
        sv: 'Har du någonsin provat surströmming?',
        en: 'Have you ever tried fermented herring?',
      },
      { speaker: 'Sam', sv: 'Nej, aldrig! Har du?', en: 'No, never! Have you?' },
      { speaker: 'Johan', sv: 'Ja, en gång. Aldrig mer!', en: 'Yes, once. Never again!' },
    ],
  },
  culture: {
    title: 'Surströmming',
    text: 'Surströmming is fermented Baltic herring, famous for its very strong smell. It is eaten in late summer, often outdoors, typically wrapped in thin flatbread (tunnbröd) with potatoes and onion. Many Swedes have never tried it, so [[Har du provat surströmming?]] is a classic conversation starter.',
  },
  exercises: [
    {
      type: 'gap',
      text: 'Jag har ___ i Spanien.',
      en: 'I’ve been to Spain.',
      choices: ['varit', 'var', 'vara'],
      answer: 'varit',
      explanation:
        'After har you need the supine: har varit. var is the past and vara the infinitive.',
    },
    {
      type: 'gap',
      text: 'Igår ___ jag fisk.',
      en: 'Yesterday I ate fish.',
      choices: ['åt', 'har ätit', 'äter'],
      answer: 'åt',
      explanation:
        'igår is a finished time, so use the past: åt. Just like in English, you can’t say "Yesterday I have eaten".',
      vocab: ['igar'],
    },
    {
      type: 'gap',
      text: 'Jag har inte ätit ___.',
      en: 'I haven’t eaten yet.',
      choices: ['än', 'redan', 'just'],
      answer: 'än',
      explanation:
        'inte … än = not yet. redan means "already" and just means "just", and neither works with inte here.',
      vocab: ['an-yet'],
    },
    {
      type: 'type',
      prompt: 'Jag har aldrig (prova) surströmming.',
      promptLang: 'sv',
      question: 'Write the supine (the form after har)',
      answer: 'provat',
      reject: ['provade', 'prova', 'provar', 'provit', 'provt'],
      strict: true,
      hint: 'An -ar verb',
      explanation: 'prova is an -ar verb, so the supine ends in -at: har provat.',
      vocab: ['prova'],
    },
    {
      type: 'type',
      prompt: 'Har du (se) den nya filmen?',
      promptLang: 'sv',
      question: 'Write the supine (the form after har)',
      answer: 'sett',
      reject: ['såg', 'se', 'ser', 'set', 'seet', 'sedd'],
      strict: true,
      hint: 'A short verb, spelled with two t',
      explanation: 'se is one of the short irregular verbs: ser, såg, sett. Remember the double t.',
    },
    {
      type: 'build',
      prompt: 'I have never been abroad.',
      answer: 'Jag har aldrig varit utomlands.',
      distractors: ['var', 'vara'],
      explanation: 'har + supine (varit). aldrig goes after har, in the same place as inte.',
      vocab: ['utomlands'],
    },
    {
      type: 'listen',
      audio: 'Hon har just kommit.',
      choices: ['She has just arrived.', 'She arrived yesterday.', 'She is just coming.'],
      answer: 'She has just arrived.',
      explanation: 'har … kommit is the perfect (has arrived), and just means "just".',
      vocab: ['just', 'komma'],
    },
    {
      type: 'dictation',
      audio: 'Jag har pluggat svenska i två år.',
      en: 'I’ve been studying Swedish for two years.',
      explanation:
        'Swedish uses har + supine for something that started in the past and is still going on.',
      vocab: ['plugga', 'svenska', 'ar-year'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Johan', sv: 'Har du ätit lunch?', en: 'Have you had lunch?' }],
      question: 'You haven’t eaten yet. What do you say?',
      choices: ['Nej, inte än.', 'Nej, inte redan.', 'Nej, jag åt inte än.'],
      answer: 'Nej, inte än.',
      explanation:
        '"Inte än" is the natural short answer for "not yet". Swedes don’t say "inte redan", and än goes with the perfect: "Jag har inte ätit än".',
      vocab: ['an-yet'],
    },
    {
      type: 'speak',
      text: 'Har du någonsin besökt Danmark?',
      en: 'Have you ever visited Denmark?',
      vocab: ['nagonsin', 'besoka'],
    },
  ],
})
