import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u10-l02',
  learn: [
    {
      title: '-er verbs: -de or -te',
      text: 'Most verbs whose present tense ends in **-er** take **-de** or **-te** in the past. Take away -er to find the stem, then listen to its last sound:\n\nA soft, *voiced* sound (g, l, m, n, r, v …) → **-de**: [[ringer]] → [[ringde]].\nA hard, *voiceless* **k, p, s** or **t** → **-te**: [[läser]] → [[läste]].',
      table: {
        headers: ['Infinitive', 'Present', 'Past', 'Supine'],
        rows: [
          ['ringa', 'ringer', 'ringde', 'ringt'],
          ['höra', 'hör', 'hörde', 'hört'],
          ['stänga', 'stänger', 'stängde', 'stängt'],
          ['behöva', 'behöver', 'behövde', 'behövt'],
          ['glömma', 'glömmer', 'glömde', 'glömt'],
          ['läsa', 'läser', 'läste', 'läst'],
          ['köpa', 'köper', 'köpte', 'köpt'],
          ['tycka', 'tycker', 'tyckte', 'tyckt'],
          ['hjälpa', 'hjälper', 'hjälpte', 'hjälpt'],
          ['försöka', 'försöker', 'försökte', 'försökt'],
        ],
        svColumns: [0, 1, 2, 3],
      },
      tip: 'A stem that already ends in d just adds -e: [[använder]] → [[använde]], [[händer]] → [[hände]]. And a double m loses one m before the ending: glömmer → glömde, glömt.',
    },
    {
      title: 'Strong verbs change their vowel',
      text: 'Many of the most common verbs are *strong*: the vowel usually changes and the past has **no ending** at all, like English sing → sang. A few others (hade, gjorde, sa, visste) are simply irregular. You already know all these verbs, so now learn their past forms: they come up all the time.',
      table: {
        headers: ['Infinitive', 'Present', 'Past', 'Supine'],
        rows: [
          ['vara', 'är', 'var', 'varit'],
          ['ha', 'har', 'hade', 'haft'],
          ['gå', 'går', 'gick', 'gått'],
          ['komma', 'kommer', 'kom', 'kommit'],
          ['se', 'ser', 'såg', 'sett'],
          ['äta', 'äter', 'åt', 'ätit'],
          ['dricka', 'dricker', 'drack', 'druckit'],
          ['sova', 'sover', 'sov', 'sovit'],
          ['ta', 'tar', 'tog', 'tagit'],
          ['få', 'får', 'fick', 'fått'],
          ['skriva', 'skriver', 'skrev', 'skrivit'],
          ['göra', 'gör', 'gjorde', 'gjort'],
          ['säga', 'säger', 'sa (sade)', 'sagt'],
          ['veta', 'vet', 'visste', 'vetat'],
        ],
        svColumns: [0, 1, 2, 3],
      },
      tip: 'sa is how everyone says it; sade is a more formal written form. Both are correct, and both are pronounced "sah".',
    },
    {
      title: 'New verbs and a handy pattern',
      text: 'Many strong verbs follow the pattern **i → a → u**: [[dricka]], [[drack]], [[druckit]]. Once you know one, the others feel familiar.',
      table: {
        headers: ['Infinitive', 'Present', 'Past', 'Supine'],
        rows: [
          ['springa', 'springer', 'sprang', 'sprungit'],
          ['vinna', 'vinner', 'vann', 'vunnit'],
          ['sitta', 'sitter', 'satt', 'suttit'],
          ['flyga', 'flyger', 'flög', 'flugit'],
          ['bli', 'blir', 'blev', 'blivit'],
          ['ge', 'ger', 'gav', 'gett'],
          ['förlora', 'förlorar', 'förlorade', 'förlorat'],
          ['hända', 'händer', 'hände', 'hänt'],
        ],
        svColumns: [0, 1, 2, 3],
      },
      examples: [
        { sv: 'Vad hände?', en: 'What happened?' },
        { sv: 'Vi vann!', en: 'We won!' },
        { sv: 'Hon blev glad.', en: 'She was pleased.' },
        { sv: 'Jag gav henne en bok.', en: 'I gave her a book.' },
      ],
      tip: 'förlora is a plain -ar verb (förlorade), the opposite of vinna. bli often translates as "get" or "become": [[Jag blev trött.]] (I got tired.)',
    },
  ],
  vocab: [
    {
      id: 'springa',
      sv: 'springa',
      en: 'to run',
      pos: 'verb',
      forms: { present: 'springer', past: 'sprang', supine: 'sprungit', imperative: 'spring' },
      enAlt: ['run'],
    },
    {
      id: 'sitta',
      sv: 'sitta',
      en: 'to sit / to be sitting',
      pos: 'verb',
      forms: { present: 'sitter', past: 'satt', supine: 'suttit', imperative: 'sitt' },
      enAlt: ['to sit', 'sit'],
    },
    {
      id: 'flyga',
      sv: 'flyga',
      en: 'to fly',
      pos: 'verb',
      forms: { present: 'flyger', past: 'flög', supine: 'flugit', imperative: 'flyg' },
      enAlt: ['fly'],
    },
    {
      id: 'glomma',
      sv: 'glömma',
      en: 'to forget',
      pos: 'verb',
      forms: { present: 'glömmer', past: 'glömde', supine: 'glömt', imperative: 'glöm' },
      enAlt: ['forget'],
    },
    {
      id: 'vinna',
      sv: 'vinna',
      en: 'to win',
      pos: 'verb',
      forms: { present: 'vinner', past: 'vann', supine: 'vunnit', imperative: 'vinn' },
      enAlt: ['win'],
    },
    {
      id: 'forlora',
      sv: 'förlora',
      en: 'to lose',
      pos: 'verb',
      forms: {
        present: 'förlorar',
        past: 'förlorade',
        supine: 'förlorat',
        imperative: 'förlora',
      },
      note: 'Lose a game or a match. Losing your keys is "tappa bort".',
      enAlt: ['lose'],
    },
    {
      id: 'handa',
      sv: 'hända',
      en: 'to happen',
      pos: 'verb',
      forms: { present: 'händer', past: 'hände', supine: 'hänt' },
      note: '"Vad hände?" = What happened?',
      enAlt: ['happen'],
    },
    {
      id: 'forsoka',
      sv: 'försöka',
      en: 'to try',
      pos: 'verb',
      forms: { present: 'försöker', past: 'försökte', supine: 'försökt', imperative: 'försök' },
      enAlt: ['try'],
    },
    {
      id: 'bli',
      sv: 'bli',
      en: 'to become / to get',
      pos: 'verb',
      forms: { present: 'blir', past: 'blev', supine: 'blivit', imperative: 'bli' },
      enAlt: ['to become', 'to get', 'become'],
    },
    {
      id: 'ge',
      sv: 'ge',
      en: 'to give',
      pos: 'verb',
      forms: { present: 'ger', past: 'gav', supine: 'gett', imperative: 'ge' },
      pron: 'yeh',
      note: 'The supine "givit" is also correct, but "gett" is what most people say.',
      enAlt: ['give'],
    },
  ],
  dialogue: {
    title: 'The match',
    setting: 'Emma meets Jonas the day after his football match.',
    lines: [
      { speaker: 'Emma', sv: 'Hej Jonas! Vann ni igår?', en: 'Hi Jonas! Did you win yesterday?' },
      { speaker: 'Jonas', sv: 'Nej, tyvärr. Vi förlorade.', en: 'No, unfortunately. We lost.' },
      { speaker: 'Emma', sv: 'Åh nej! Vad hände?', en: 'Oh no! What happened?' },
      {
        speaker: 'Jonas',
        sv: 'Vi försökte, men de var bättre. Och jag glömde mina skor!',
        en: 'We tried, but they were better. And I forgot my shoes!',
      },
      {
        speaker: 'Emma',
        sv: 'Dina skor? Vad gjorde du då?',
        en: 'Your shoes? What did you do then?',
      },
      {
        speaker: 'Jonas',
        sv: 'Erik gav mig sina gamla skor. De var för stora, så jag satt på bänken.',
        en: 'Erik gave me his old shoes. They were too big, so I sat on the bench.',
      },
      { speaker: 'Emma', sv: 'Haha! Nästa vecka vinner ni.', en: 'Haha! Next week you’ll win.' },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Igår ___ jag till Anna.',
      en: 'Yesterday I phoned Anna.',
      choices: ['ringde', 'ringte', 'ringer'],
      answer: 'ringde',
      explanation:
        'The stem ring- ends in a voiced sound (ng), so the past takes -de: ringde. "ringte" is a common mistake, even among Swedes!',
    },
    {
      type: 'gap',
      text: 'I morse ___ jag tidningen.',
      en: 'This morning I read the paper.',
      choices: ['läste', 'läsde', 'läser'],
      answer: 'läste',
      explanation: 'The stem läs- ends in s, a voiceless sound, so the past takes -te: läste.',
      vocab: ['i-morse'],
    },
    {
      type: 'gap',
      text: 'I lördags ___ vi på restaurang.',
      en: 'Last Saturday we ate at a restaurant.',
      choices: ['åt', 'ätte', 'äter'],
      answer: 'åt',
      explanation: 'äta is a strong verb: the vowel changes and there is no ending. äter → åt.',
    },
    {
      type: 'type',
      prompt: 'Vad (hända)?',
      promptLang: 'sv',
      question: 'Write the verb in the past tense',
      answer: 'hände',
      reject: ['händer', 'hända', 'händde', 'hänt', 'händte'],
      strict: true,
      hint: 'The stem ends in d',
      explanation:
        'The stem händ- already ends in d, so it just adds -e: hände. "Vad hände?" = What happened?',
      vocab: ['handa'],
    },
    {
      type: 'type',
      prompt: 'Hon (flyga) till Norge i förrgår.',
      promptLang: 'sv',
      question: 'Write the verb in the past tense',
      answer: 'flög',
      reject: ['flyger', 'flyga', 'flygde', 'flugit', 'flyg', 'flog'],
      strict: true,
      hint: 'A strong verb: the vowel changes to ö',
      explanation: 'flyga is strong: flyger → flög (no ending), and the supine is flugit.',
      vocab: ['flyga', 'i-forrgar'],
    },
    {
      type: 'build',
      prompt: 'Yesterday we won, but last week we lost.',
      answer: 'Igår vann vi, men förra veckan förlorade vi.',
      accept: [
        'Vi vann igår, men förra veckan förlorade vi.',
        'Igår vann vi, men vi förlorade förra veckan.',
        'Vi vann igår, men vi förlorade förra veckan.',
      ],
      distractors: ['vinner', 'förlorar'],
      explanation:
        'vinna is strong (vann), förlora is an -ar verb (förlorade). After igår and förra veckan the verb comes before vi (V2).',
      vocab: ['vinna', 'forlora', 'igar', 'vecka'],
    },
    {
      type: 'listen',
      audio: 'Jag glömde nyckeln.',
      choices: ['I forgot the key.', 'I forget the key.', 'I found the key.'],
      answer: 'I forgot the key.',
      explanation: 'glömde is the past of glömma (to forget). "I found" would be hittade.',
      vocab: ['glomma', 'nyckel'],
    },
    {
      type: 'dictation',
      audio: 'Vi satt i köket och drack kaffe.',
      en: 'We sat in the kitchen and drank coffee.',
      explanation: 'Two strong verbs: sitter → satt and dricker → drack.',
      vocab: ['sitta', 'kok', 'kaffe'],
    },
    {
      type: 'dialogueReply',
      lines: [
        {
          speaker: 'Emma',
          sv: 'Vad gav du Erik på hans födelsedag?',
          en: 'What did you give Erik for his birthday?',
        },
      ],
      question: 'You gave him a book. What do you say?',
      choices: ['Jag gav Erik en bok.', 'Jag ger Erik en bok.', 'Jag gedde Erik en bok.'],
      answer: 'Jag gav Erik en bok.',
      explanation: 'ge is strong: ger → gav. There is no form "gedde".',
      vocab: ['ge', 'bok'],
    },
    {
      type: 'speak',
      text: 'Jag försökte, men det gick inte.',
      en: 'I tried, but it didn’t work.',
      vocab: ['forsoka'],
    },
  ],
})
