import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u10-l01',
  learn: [
    {
      title: 'Yesterday: -ar becomes -ade',
      text: 'Good news: the biggest group of Swedish verbs, the ones whose present tense ends in **-ar**, all make the past tense the same way. Just swap **-ar** for **-ade**.\n\n[[Jag jobbar]] (I work) → [[Jag jobbade]] (I worked).\n\nThe last column is the *supine*. You don’t need it yet: it comes back in lesson 3, in "I have worked".',
      table: {
        headers: ['Infinitive', 'Present', 'Past', 'Supine'],
        rows: [
          ['jobba', 'jobbar', 'jobbade', 'jobbat'],
          ['prata', 'pratar', 'pratade', 'pratat'],
          ['städa', 'städar', 'städade', 'städat'],
          ['träffa', 'träffar', 'träffade', 'träffat'],
          ['flytta', 'flyttar', 'flyttade', 'flyttat'],
          ['öppna', 'öppnar', 'öppnade', 'öppnat'],
        ],
        svColumns: [0, 1, 2, 3],
      },
      tip: 'Say it out loud: jobb-a-de. The ending is a full syllable, so -ade verbs are easy to hear.',
    },
    {
      title: 'One form for everyone',
      text: 'Just like the present tense, the past tense never changes with the person. [[jag jobbade]], [[du jobbade]], [[hon jobbade]], [[vi jobbade]], [[de jobbade]]. No "was/were"-style headaches.\n\n**inte** still goes straight after the verb: [[Jag jobbade inte igår.]]',
      examples: [
        { sv: 'Vi pratade länge.', en: 'We talked for a long time.' },
        { sv: 'Hon städade köket.', en: 'She cleaned the kitchen.' },
        { sv: 'De flyttade till Sverige.', en: 'They moved to Sweden.' },
        { sv: 'Jag jobbade inte igår.', en: 'I didn’t work yesterday.' },
      ],
      tip: 'English needs "did" for questions and "not": "Did you work?", "I didn’t work". Swedish just uses the past form: [[Jobbade du?]] [[Jag jobbade inte.]]',
    },
    {
      title: 'When did it happen?',
      text: 'These time words point to the past. If one of them comes first, the verb still comes second (V2): [[Igår jobbade jag.]] Not "Igår jag jobbade".',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['igår', 'yesterday'],
          ['i förrgår', 'the day before yesterday'],
          ['i morse', 'this morning (earlier today)'],
          ['förra veckan', 'last week'],
          ['förra året', 'last year'],
          ['i lördags', 'last Saturday'],
          ['sist', 'last time / most recently'],
        ],
        svColumns: [0],
      },
      examples: [
        { sv: 'I morse lagade jag frukost.', en: 'This morning I made breakfast.' },
        { sv: 'Förra veckan träffade vi Anna.', en: 'Last week we met Anna.' },
        { sv: 'När pratade ni sist?', en: 'When did you last talk?' },
      ],
      tip: 'Watch the days: [[i lördags]] means *last* Saturday, but [[på lördag]] means *this coming* Saturday. Same trick with every day: i måndags, i tisdags …',
    },
  ],
  vocab: [
    {
      id: 'i-morse',
      sv: 'i morse',
      en: 'this morning (in the past)',
      pos: 'phrase',
      pron: 'ee MOSH-eh (rs sounds like "sh")',
      note: 'Only about earlier today. For a morning still to come, say "imorgon bitti" (early tomorrow).',
      enAlt: ['this morning'],
    },
    {
      id: 'i-forrgar',
      sv: 'i förrgår',
      en: 'the day before yesterday',
      pos: 'phrase',
      pron: 'ee FURR-gore',
    },
    {
      id: 'plotsligt',
      sv: 'plötsligt',
      en: 'suddenly',
      pos: 'adverb',
      pron: 'PLUHTS-lit (the g is silent)',
    },
    {
      id: 'tyvarr',
      sv: 'tyvärr',
      en: 'unfortunately',
      pos: 'adverb',
      pron: 'tee-VAIR',
      enAlt: ['sadly', 'I’m afraid'],
    },
    {
      id: 'sist',
      sv: 'sist',
      en: 'last / last time',
      pos: 'adverb',
      note: '"När träffade du henne sist?" = When did you last see her? Also "at the end": "Han kom sist." (He came last.)',
      enAlt: ['last', 'last time'],
    },
    {
      id: 'stanna',
      sv: 'stanna',
      en: 'to stay / to stop',
      pos: 'verb',
      forms: { present: 'stannar', past: 'stannade', supine: 'stannat', imperative: 'stanna' },
      note: '"Bilen stannade" = the car stopped. "Vi stannade en vecka" = we stayed for a week.',
      enAlt: ['to stay', 'to stop', 'stay', 'stop'],
    },
    {
      id: 'flytta',
      sv: 'flytta',
      en: 'to move (house)',
      pos: 'verb',
      forms: { present: 'flyttar', past: 'flyttade', supine: 'flyttat', imperative: 'flytta' },
      enAlt: ['to move', 'move'],
    },
    {
      id: 'traffa',
      sv: 'träffa',
      en: 'to meet',
      pos: 'verb',
      forms: { present: 'träffar', past: 'träffade', supine: 'träffat', imperative: 'träffa' },
      enAlt: ['meet', 'to see (a person)'],
    },
    {
      id: 'handla',
      sv: 'handla',
      en: 'to shop (for groceries)',
      pos: 'verb',
      forms: { present: 'handlar', past: 'handlade', supine: 'handlat', imperative: 'handla' },
      note: '"Jag handlade mat" = I bought groceries / did the food shopping.',
      enAlt: ['to shop', 'shop', 'to do the shopping'],
    },
    {
      id: 'visa',
      sv: 'visa',
      en: 'to show',
      pos: 'verb',
      forms: { present: 'visar', past: 'visade', supine: 'visat', imperative: 'visa' },
      enAlt: ['show'],
    },
    {
      id: 'oppna',
      sv: 'öppna',
      en: 'to open',
      pos: 'verb',
      forms: { present: 'öppnar', past: 'öppnade', supine: 'öppnat', imperative: 'öppna' },
      enAlt: ['open'],
    },
  ],
  dialogue: {
    title: 'Monday morning',
    setting: 'Sara and Ali meet at work on Monday morning.',
    lines: [
      {
        speaker: 'Sara',
        sv: 'Hej Ali! Vad gjorde du i helgen?',
        en: 'Hi Ali! What did you do at the weekend?',
      },
      {
        speaker: 'Ali',
        sv: 'Vi flyttade! Vi har en ny lägenhet nu.',
        en: 'We moved! We have a new flat now.',
      },
      { speaker: 'Sara', sv: 'Vad roligt! Var ligger den?', en: 'How nice! Where is it?' },
      {
        speaker: 'Ali',
        sv: 'Bredvid kyrkan. Och du, vad gjorde du?',
        en: 'Next to the church. And you, what did you do?',
      },
      {
        speaker: 'Sara',
        sv: 'Inte så mycket. Jag städade och handlade. I söndags träffade jag min syster.',
        en: 'Not much. I cleaned and did the shopping. On Sunday I met my sister.',
      },
      {
        speaker: 'Ali',
        sv: 'Du ser trött ut. Är allt okej?',
        en: 'You look tired. Is everything OK?',
      },
      {
        speaker: 'Sara',
        sv: 'Ja, men jag jobbade sent igår. Och i morse vaknade jag klockan fem!',
        en: 'Yes, but I worked late yesterday. And this morning I woke up at five!',
      },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Igår ___ jag i tio timmar.',
      en: 'Yesterday I worked for ten hours.',
      choices: ['jobbade', 'jobbar', 'jobba'],
      answer: 'jobbade',
      explanation:
        'igår points to the past, so jobbar becomes jobbade. Notice the word order: the verb comes second, right after igår.',
      vocab: ['igar'],
    },
    {
      type: 'gap',
      text: 'I förrgår ___ vi till en ny lägenhet.',
      en: 'The day before yesterday we moved to a new flat.',
      choices: ['flyttade', 'flyttar', 'flytta'],
      answer: 'flyttade',
      explanation: 'i förrgår is in the past, so -ar becomes -ade: flyttar → flyttade.',
      vocab: ['i-forrgar', 'flytta'],
    },
    {
      type: 'gap',
      text: 'När ___ du Anna sist?',
      en: 'When did you last meet Anna?',
      choices: ['träffade', 'träffar', 'träffa'],
      answer: 'träffade',
      explanation:
        'sist (last time) is about the past, so you need the past form. There is no "did" in Swedish: the verb itself shows the tense.',
      vocab: ['sist', 'traffa'],
    },
    {
      type: 'type',
      prompt: 'Jag (öppna) fönstret i morse.',
      promptLang: 'sv',
      question: 'Write the verb in the past tense',
      answer: 'öppnade',
      reject: ['öppnar', 'öppna', 'öppnat', 'öpnade', 'öppnde'],
      strict: true,
      hint: 'öppnar → …',
      explanation: 'i morse means "earlier this morning", so use the past: öppnar → öppnade.',
      vocab: ['oppna', 'i-morse'],
    },
    {
      type: 'type',
      prompt: 'Hon (visa) mig huset igår.',
      promptLang: 'sv',
      question: 'Write the verb in the past tense',
      answer: 'visade',
      reject: ['visar', 'visa', 'visat', 'visde', 'viste'],
      strict: true,
      hint: 'visar → …',
      explanation: 'visa is an -ar verb (visar), so the past is visade.',
      vocab: ['visa', 'igar'],
    },
    {
      type: 'build',
      prompt: 'This morning I opened the window.',
      answer: 'I morse öppnade jag fönstret.',
      accept: ['Jag öppnade fönstret i morse.'],
      distractors: ['öppnar', 'fönster'],
      explanation:
        'When the sentence starts with i morse, the verb comes next and jag after it: I morse öppnade jag …',
      vocab: ['i-morse', 'oppna', 'fonster'],
    },
    {
      type: 'listen',
      audio: 'Plötsligt stannade bilen.',
      choices: [
        'Suddenly the car stopped.',
        'Unfortunately the car stopped.',
        'Suddenly the car stops.',
      ],
      answer: 'Suddenly the car stopped.',
      explanation:
        'plötsligt means "suddenly" (tyvärr is "unfortunately"), and stannade is the past tense of stanna, to stop.',
      vocab: ['plotsligt', 'stanna', 'bil'],
    },
    {
      type: 'dictation',
      audio: 'Tyvärr jobbade jag i helgen.',
      en: 'Unfortunately I worked at the weekend.',
      explanation: 'tyvärr comes first, so the verb jobbade comes second, before jag.',
      vocab: ['tyvarr', 'helg'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Sara', sv: 'Vad gjorde du igår?', en: 'What did you do yesterday?' }],
      question: 'You played football. What do you say?',
      choices: ['Jag spelade fotboll.', 'Jag spelar fotboll.', 'Jag spela fotboll.'],
      answer: 'Jag spelade fotboll.',
      explanation:
        'Sara asks about yesterday, so answer in the past: spelar → spelade. "Jag spelar fotboll" means "I play football".',
      vocab: ['fotboll', 'igar'],
    },
    {
      type: 'speak',
      text: 'Igår städade jag och handlade mat.',
      en: 'Yesterday I cleaned and did the food shopping.',
      vocab: ['handla', 'igar'],
    },
  ],
})
