import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u10-l05',
  learn: [
    {
      title: 'Predictions: kommer att',
      text: 'To say what you think **will happen**, use **kommer att** + infinitive. [[Det kommer att bli bra.]] (It will be fine.)\n\nkommer is the same verb as in "Jag kommer från …", but here it simply means "will". It is the same for every person: jag kommer att, du kommer att, de kommer att.',
      examples: [
        { sv: 'Du kommer att klara provet.', en: 'You’ll pass the test.' },
        { sv: 'Hon kommer att bli glad.', en: 'She’ll be happy.' },
        { sv: 'Det kommer att ta tid.', en: 'It will take time.' },
        { sv: 'Det kommer inte att gå.', en: 'It won’t work.' },
      ],
      tip: 'In everyday speech many Swedes drop the att: "Det kommer bli bra". In formal writing, keep it.',
    },
    {
      title: 'ska or kommer att?',
      text: 'Both talk about the future, but ask yourself: **has someone decided this?**\n\nA plan or decision → **ska**: [[Jag ska plugga ikväll.]]\nA prediction, something nobody decides → **kommer att**: [[Du kommer att klara det.]]\n\nSuggestions are always ska: [[Ska vi fika?]] (Shall we have a coffee?)',
      table: {
        headers: ['Plan: ska', 'Prediction: kommer att'],
        rows: [
          ['Jag ska plugga mycket.', 'Det kommer att gå bra.'],
          ['Vi ska flytta i juni.', 'Barnen kommer att bli trötta.'],
          ['Hon ska bli läkare.', 'Hon kommer att bli en bra läkare.'],
        ],
        svColumns: [0, 1],
      },
      tip: '"Hon ska bli läkare" means she has decided to become a doctor. "Hon kommer att bli en bra läkare" is your guess about the future.',
    },
    {
      title: 'blir, and how sure are you?',
      text: 'Swedes also use the present tense **blir** for the future, especially with det: [[Det blir kul!]] (It’ll be fun!)\n\nAdd a word to show how sure you are. Like inte, it goes right after the verb: [[Det blir säkert bra.]] [[Hon kommer troligen att vinna.]]',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['säkert', 'surely / I’m sure'],
          ['troligen', 'probably'],
          ['förhoppningsvis', 'hopefully'],
        ],
        svColumns: [0],
      },
      examples: [
        { sv: 'Det kommer förhoppningsvis att gå bra.', en: 'Hopefully it will go well.' },
        { sv: 'Han lyckas säkert.', en: 'I’m sure he’ll succeed.' },
      ],
    },
  ],
  vocab: [
    {
      id: 'troligen',
      sv: 'troligen',
      en: 'probably',
      pos: 'adverb',
      pron: 'TROO-li-gen',
      enAlt: ['likely'],
    },
    {
      id: 'sakert',
      sv: 'säkert',
      en: 'surely / I’m sure',
      pos: 'adverb',
      note: '"Det blir säkert bra" = I’m sure it’ll be fine. The adjective säker means "sure" or "safe".',
      enAlt: ['surely', 'certainly', 'probably'],
    },
    {
      id: 'forhoppningsvis',
      sv: 'förhoppningsvis',
      en: 'hopefully',
      pos: 'adverb',
      pron: 'fur-HOPP-nings-vees',
    },
    {
      id: 'lyckas',
      sv: 'lyckas',
      en: 'to succeed / to manage',
      pos: 'verb',
      forms: { present: 'lyckas', past: 'lyckades', supine: 'lyckats' },
      note: 'Always ends in -s: jag lyckas, jag lyckades, jag har lyckats.',
      enAlt: ['to succeed', 'to manage', 'succeed'],
    },
    {
      id: 'klara',
      sv: 'klara',
      en: 'to manage / to pass (a test)',
      pos: 'verb',
      forms: { present: 'klarar', past: 'klarade', supine: 'klarat', imperative: 'klara' },
      note: '"Jag klarade provet" = I passed the test. "Jag klarar det" = I can manage it.',
      enAlt: ['to manage', 'to pass', 'manage', 'pass'],
    },
    {
      id: 'prov',
      sv: 'prov',
      en: 'test / exam',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'provet', plural: 'prov', pluralDefinite: 'proven' },
      enAlt: ['test', 'exam'],
    },
    {
      id: 'drom',
      sv: 'dröm',
      en: 'dream',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'drömmen', plural: 'drömmar', pluralDefinite: 'drömmarna' },
      note: 'The m doubles before an ending: drömmen, drömmar.',
    },
  ],
  dialogue: {
    title: 'The night before the test',
    setting: 'Mira is nervous about her test tomorrow. Her friend Erik calls her.',
    lines: [
      {
        speaker: 'Mira',
        sv: 'Imorgon har jag ett stort prov. Jag är så stressad!',
        en: 'I have a big test tomorrow. I’m so stressed!',
      },
      {
        speaker: 'Erik',
        sv: 'Ta det lugnt! Du har pluggat jättemycket. Du kommer att klara det.',
        en: 'Take it easy! You’ve studied loads. You’ll pass.',
      },
      {
        speaker: 'Mira',
        sv: 'Tror du? Men tänk om jag inte lyckas?',
        en: 'Do you think so? But what if I don’t make it?',
      },
      {
        speaker: 'Erik',
        sv: 'Det kommer du att göra! Och efter provet ska vi fika.',
        en: 'You will! And after the test we’re going for a coffee.',
      },
      {
        speaker: 'Mira',
        sv: 'Ja, gärna! Det blir säkert kul.',
        en: 'Yes, please! I’m sure it’ll be fun.',
      },
      {
        speaker: 'Erik',
        sv: 'Vad är din stora dröm, förresten?',
        en: 'What’s your big dream, by the way?',
      },
      {
        speaker: 'Mira',
        sv: 'Att bli läkare. Förhoppningsvis!',
        en: 'To become a doctor. Hopefully!',
      },
      {
        speaker: 'Erik',
        sv: 'Du kommer att bli en jättebra läkare.',
        en: 'You’re going to be a great doctor.',
      },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Jag tror att det ___ att bli bra.',
      en: 'I think it will be fine.',
      choices: ['kommer', 'ska', 'blir'],
      answer: 'kommer',
      explanation:
        'Only kommer is followed by att + infinitive: kommer att bli. It’s a prediction.',
    },
    {
      type: 'gap',
      text: '___ vi fika klockan tre?',
      en: 'Shall we have a coffee at three?',
      choices: ['Ska', 'Kommer att', 'Blir'],
      answer: 'Ska',
      explanation: 'Suggestions and plans use ska: "Ska vi …?" = Shall we …?',
      vocab: ['klocka'],
    },
    {
      type: 'gap',
      text: 'Det blir ___ bra!',
      en: 'I’m sure it’ll be fine!',
      choices: ['säkert', 'säker', 'sist'],
      answer: 'säkert',
      explanation:
        'säkert (with -t) is the adverb "surely / I’m sure". säker is the adjective "sure", as in "Jag är säker".',
      vocab: ['sakert'],
    },
    {
      type: 'type',
      prompt: 'Jag försökte, men jag (lyckas) inte.',
      promptLang: 'sv',
      question: 'Write the verb in the past tense',
      answer: 'lyckades',
      reject: ['lyckas', 'lyckade', 'lyckats', 'lycka'],
      strict: true,
      hint: 'The -s stays at the end',
      explanation: 'lyckas keeps its -s in every form: lyckas, lyckades, har lyckats.',
      vocab: ['lyckas'],
    },
    {
      type: 'type',
      prompt: 'dreams',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'drömmar',
      reject: ['drömar', 'drömmer', 'drömmarna', 'drömmen', 'drömmor'],
      strict: true,
      hint: 'en dröm',
      explanation: 'dröm takes -ar in the plural, and the m doubles: drömmar.',
      vocab: ['drom'],
    },
    {
      type: 'build',
      prompt: 'You will pass the test.',
      answer: 'Du kommer att klara provet.',
      distractors: ['klarade', 'prov'],
      explanation: 'A prediction: kommer att + infinitive (klara). "the test" is provet.',
      vocab: ['klara', 'prov'],
    },
    {
      type: 'listen',
      audio: 'Det kommer förhoppningsvis att gå bra.',
      choices: [
        'Hopefully it will go well.',
        'It probably went well.',
        'Unfortunately it won’t go well.',
      ],
      answer: 'Hopefully it will go well.',
      explanation: 'förhoppningsvis = hopefully, and kommer att gå is the future.',
      vocab: ['forhoppningsvis'],
    },
    {
      type: 'dictation',
      audio: 'Hon kommer troligen att vinna.',
      en: 'She will probably win.',
      explanation: 'troligen goes right after kommer, just where inte would go.',
      vocab: ['troligen', 'vinna'],
    },
    {
      type: 'dialogueReply',
      lines: [
        {
          speaker: 'Mira',
          sv: 'Imorgon har jag ett prov. Jag är så stressad!',
          en: 'I have a test tomorrow. I’m so stressed!',
        },
      ],
      question: 'Encourage her.',
      choices: ['Du kommer att klara det!', 'Du klarade det!', 'Du ska att klara det!'],
      answer: 'Du kommer att klara det!',
      explanation:
        'You’re predicting the future, so use kommer att. The test is tomorrow, so klarade (past) doesn’t fit, and ska never takes att.',
      vocab: ['klara', 'prov'],
    },
    {
      type: 'speak',
      text: 'Det blir säkert kul!',
      en: 'I’m sure it’ll be fun!',
      vocab: ['sakert', 'kul'],
    },
  ],
})
