import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u11-l04',
  learn: [
    {
      title: 'It rains: weather starts with det',
      text: 'Swedes love to talk about the weather, so this is perfect small talk. Like English "it", Swedish uses **det**: [[Det regnar.]] [[Det snöar.]] [[Det blåser.]]\n\nWith är, the adjective gets the ett-ending **-t**, because det counts as an ett-word: [[Det är kallt.]] [[Det är molnigt.]]',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['Det regnar.', 'It’s raining.'],
          ['Det snöar.', 'It’s snowing.'],
          ['Det blåser.', 'It’s windy.'],
          ['Det är sol.', 'It’s sunny.'],
          ['Det är molnigt.', 'It’s cloudy.'],
          ['Det är kallt.', 'It’s cold.'],
          ['Det är varmt.', 'It’s warm.'],
        ],
        svColumns: [0],
      },
      tip: 'A classic opener at the bus stop: "Vilket väder!" (What weather!). It works for good and bad weather alike.',
    },
    {
      title: 'Degrees and tomorrow’s weather',
      text: 'Sweden uses Celsius. Say [[Det är fem grader.]] Below zero is **minus**, above zero is **plus**: [[Det är minus tio grader.]] [[Det är plus tjugo.]]\n\nTo ask about tomorrow: [[Vad blir det för väder imorgon?]] (What will the weather be like tomorrow?)',
      examples: [
        { sv: 'Hur många grader är det?', en: 'How many degrees is it?' },
        { sv: 'Det kommer att regna.', en: 'It’s going to rain.' },
        { sv: 'Det blir sol imorgon.', en: 'It’ll be sunny tomorrow.' },
        { sv: 'Igår snöade det hela dagen.', en: 'Yesterday it snowed all day.' },
      ],
      tip: 'Notice the word order in the last example: Igår snöade det. The verb comes second, so det moves after it.',
    },
    {
      title: 'No bad weather',
      text: 'Most Swedes grow up with this saying: [[Det finns inget dåligt väder, bara dåliga kläder.]] "There’s no bad weather, only bad clothes." So put on a jacket, grab a [[paraply]] (umbrella) and go out anyway!\n\nIf you forget, you get **blöt** (wet). Watch the endings: [[Jag är blöt.]] [[Paraplyet är blött.]] [[Skorna är blöta.]]',
      tip: 'Hear the difference: blöt has a long ö, blött a short one.',
    },
  ],
  vocab: [
    {
      id: 'vader',
      sv: 'väder',
      en: 'weather',
      pos: 'noun',
      gender: 'ett',
      pron: 'VAI-der',
      forms: { definite: 'vädret' },
    },
    {
      id: 'sol',
      sv: 'sol',
      en: 'sun / sunshine',
      pos: 'noun',
      gender: 'en',
      note: 'Det är sol = It’s sunny. Solen skiner = The sun is shining.',
      forms: { definite: 'solen' },
      enAlt: ['sun', 'sunshine'],
    },
    {
      id: 'regn',
      sv: 'regn',
      en: 'rain',
      pos: 'noun',
      gender: 'ett',
      pron: 'rengn (gn sounds like "ngn")',
      forms: { definite: 'regnet' },
    },
    {
      id: 'regna',
      sv: 'regna',
      en: 'to rain',
      pos: 'verb',
      forms: { present: 'regnar', past: 'regnade', supine: 'regnat' },
    },
    {
      id: 'sno',
      sv: 'snö',
      en: 'snow',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'snön' },
    },
    {
      id: 'snoa',
      sv: 'snöa',
      en: 'to snow',
      pos: 'verb',
      forms: { present: 'snöar', past: 'snöade', supine: 'snöat' },
    },
    {
      id: 'blasa',
      sv: 'blåsa',
      en: 'to blow / be windy',
      pos: 'verb',
      note: 'Det blåser = It’s windy.',
      forms: { present: 'blåser', past: 'blåste', supine: 'blåst', imperative: 'blås' },
      enAlt: ['to blow', 'to be windy'],
    },
    {
      id: 'molnig',
      sv: 'molnig',
      en: 'cloudy',
      pos: 'adjective',
      forms: { neuter: 'molnigt', plural: 'molniga' },
    },
    {
      id: 'grad',
      sv: 'grad',
      en: 'degree',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'graden', plural: 'grader', pluralDefinite: 'graderna' },
    },
    {
      id: 'paraply',
      sv: 'paraply',
      en: 'umbrella',
      pos: 'noun',
      gender: 'ett',
      pron: 'pa-ra-PLY (y as in ny)',
      forms: { definite: 'paraplyet', plural: 'paraplyer', pluralDefinite: 'paraplyerna' },
    },
    {
      id: 'blot',
      sv: 'blöt',
      en: 'wet',
      pos: 'adjective',
      pron: 'blurt (long ö)',
      forms: { neuter: 'blött', plural: 'blöta' },
    },
  ],
  dialogue: {
    title: 'Small talk at the bus stop',
    setting: 'Maria and her neighbour Ahmed are waiting for the bus in November.',
    lines: [
      {
        speaker: 'Maria',
        sv: 'Vilket väder! Det regnar igen.',
        en: 'What weather! It’s raining again.',
      },
      {
        speaker: 'Ahmed',
        sv: 'Ja, och det blåser också. Jag är helt blöt!',
        en: 'Yes, and it’s windy too. I’m completely wet!',
      },
      { speaker: 'Maria', sv: 'Har du inget paraply?', en: 'Don’t you have an umbrella?' },
      { speaker: 'Ahmed', sv: 'Nej, jag glömde det hemma.', en: 'No, I forgot it at home.' },
      {
        speaker: 'Maria',
        sv: 'Vad blir det för väder imorgon?',
        en: 'What will the weather be like tomorrow?',
      },
      {
        speaker: 'Ahmed',
        sv: 'Det kommer att snöa. Minus fem grader!',
        en: 'It’s going to snow. Minus five degrees!',
      },
      {
        speaker: 'Maria',
        sv: 'Typiskt. Men det finns inget dåligt väder …',
        en: 'Typical. But there’s no bad weather …',
      },
      { speaker: 'Ahmed', sv: '… bara dåliga kläder. Jag vet!', en: '… only bad clothes. I know!' },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Det är ___ idag.',
      en: 'It’s cloudy today.',
      choices: ['molnigt', 'molnig', 'molniga'],
      answer: 'molnigt',
      explanation:
        'In weather sentences, det counts as an ett-word, so the adjective takes -t: det är molnigt, det är kallt.',
      vocab: ['molnig', 'idag'],
    },
    {
      type: 'gap',
      text: 'Mina skor är ___.',
      en: 'My shoes are wet.',
      choices: ['blöta', 'blöt', 'blött'],
      answer: 'blöta',
      explanation:
        'skor is plural, so the adjective takes -a: skorna är blöta, mina skor är blöta.',
      vocab: ['blot', 'sko', 'min'],
    },
    {
      type: 'build',
      prompt: 'It is minus ten degrees.',
      answer: 'Det är minus tio grader.',
      distractors: ['grad', 'plus'],
      explanation: 'More than one degree is grader. Below zero is minus.',
      vocab: ['grad', 'tio'],
    },
    {
      type: 'dialogueReply',
      lines: [
        {
          speaker: 'Maria',
          sv: 'Vad blir det för väder imorgon?',
          en: 'What will the weather be like tomorrow?',
        },
      ],
      question: 'The forecast says snow. What do you answer?',
      choices: ['Det kommer att snöa.', 'Det snöade.', 'Det har snöat.'],
      answer: 'Det kommer att snöa.',
      explanation:
        'Tomorrow is the future, so use kommer att + infinitive. Det snöade and det har snöat are about the past.',
      vocab: ['snoa', 'vader', 'imorgon'],
    },
    {
      type: 'dialogueReply',
      lines: [
        {
          speaker: 'Maria',
          sv: 'Det regnar. Har du ett paraply?',
          en: 'It’s raining. Do you have an umbrella?',
        },
      ],
      question: 'You don’t. What do you say?',
      choices: [
        'Nej, tyvärr. Jag har inget paraply.',
        'Nej, tyvärr. Jag har ingen paraply.',
        'Nej, tyvärr. Jag har inget paraplyet.',
      ],
      answer: 'Nej, tyvärr. Jag har inget paraply.',
      explanation:
        'paraply is an ett-word, so "no umbrella" is inget paraply. After inget the noun has no ending.',
      vocab: ['paraply', 'regna'],
    },
    {
      type: 'listen',
      audio: 'Det blåser och det är kallt.',
      choices: ['It’s windy and cold.', 'It’s snowing and cold.', 'It’s sunny and warm.'],
      answer: 'It’s windy and cold.',
      explanation: 'Det blåser = it’s windy. Det är kallt = it’s cold.',
      vocab: ['blasa'],
    },
    {
      type: 'type',
      prompt: 'It’s snowing.',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'Det snöar.',
      hint: 'Weather sentences start with det',
      explanation: 'Like English "it", Swedish uses det, and snöa → snöar in the present.',
      vocab: ['snoa'],
    },
    {
      type: 'dictation',
      audio: 'Det är tjugo grader och sol.',
      en: 'It’s twenty degrees and sunny.',
      vocab: ['grad', 'sol', 'tjugo'],
    },
    {
      type: 'mcq',
      prompt: 'Det finns inget dåligt väder, bara dåliga kläder.',
      promptLang: 'sv',
      question: 'What does this Swedish saying mean?',
      choices: [
        'There’s no bad weather, only bad clothes.',
        'The weather is always bad in Sweden.',
        'Bad weather is fine if you stay at home.',
      ],
      answer: 'There’s no bad weather, only bad clothes.',
      explanation: 'The idea: dress for the weather and go out anyway. kläder means clothes.',
      vocab: ['vader'],
    },
    {
      type: 'speak',
      text: 'Vilket fint väder idag!',
      en: 'What lovely weather today!',
      vocab: ['vader', 'vilken', 'idag'],
    },
  ],
})
