import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u11-l05',
  learn: [
    {
      title: 'Everyone’s right',
      text: '[[Allemansrätten]] literally means "everyone’s right". It is the right of public access to Swedish nature: you may walk, cycle, ski and swim almost everywhere in the countryside, even on land that someone else owns.\n\nThe golden rule is short: [[inte störa, inte förstöra]], "don’t disturb, don’t destroy". Respect people, animals and nature, and the forest is yours to enjoy.',
      examples: [
        { sv: 'Vi går i skogen.', en: 'We’re walking in the forest.' },
        { sv: 'De simmar i sjön.', en: 'They’re swimming in the lake.' },
        { sv: 'Hon åker skidor på fjället.', en: 'She’s skiing in the mountains.' },
      ],
      tip: 'fjället, "the fell", is the bare, open mountain land in the north and west of Sweden. Swedes say på fjället (on the mountain).',
    },
    {
      title: 'Man får … and man får inte …',
      text: 'Rules in Swedish often use **man**, meaning "one" or "you" in general (not "a man"!). The verb is the same as for everyone: [[man får]], [[man kan]], [[man måste]].\n\n**får** here means "may / is allowed to", and **får inte** means "may not".',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['Man får plocka bär och svamp.', 'You may pick berries and mushrooms.'],
          ['Man får tälta en natt eller två.', 'You may camp for a night or two.'],
          ['Man får inte tälta för nära ett hus.', 'You may not camp too close to a house.'],
          ['Man får inte lämna skräp i naturen.', 'You may not leave litter in nature.'],
          [
            'Man får inte göra upp eld när det är eldningsförbud.',
            'You may not make a fire when there’s a fire ban.',
          ],
        ],
        svColumns: [0],
      },
      tip: 'Asking permission works the same way: "Får man tälta här?" (Is it OK to camp here?) or "Får jag …?" (May I …?).',
    },
  ],
  culture: {
    title: 'Allemansrätten: the details',
    text: 'Allemansrätten is a **customary right**, not one single law. The Swedish Environmental Protection Agency (Naturvårdsverket) explains what it allows, and since 1994 it has been mentioned in the Swedish constitution.\n\n**You may:** walk, cycle, ride, ski and swim on most land and water; camp (tälta) for a night or two in one place, well away from homes and not on farmland; pick berries, mushrooms and wild flowers, except protected (fridlysta) species.\n\n**You may not:** go into people’s gardens or too close to houses (Swedes call the privacy around a home **hemfriden**); walk across fields with growing crops; leave litter (skräp), so take it home with you; light a fire when there is a fire ban (eldningsförbud). Even without a ban, make fires small and safe, and never directly on bare rock, which can crack.\n\nNational parks and nature reserves can have stricter local rules, and fishing mostly needs a licence. From 1 March to 20 August, keep your dog on a leash wherever there may be wild animals.',
    tip: 'Sweden is roughly two thirds forest, so in late summer people head out with a bucket to pick blåbär (blueberries) and lingon (lingonberries). Picking is free for everyone!',
  },
  vocab: [
    {
      id: 'natur',
      sv: 'natur',
      en: 'nature / countryside',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'naturen' },
      enAlt: ['nature', 'countryside'],
    },
    {
      id: 'skog',
      sv: 'skog',
      en: 'forest / woods',
      pos: 'noun',
      gender: 'en',
      pron: 'skoog',
      forms: { definite: 'skogen', plural: 'skogar', pluralDefinite: 'skogarna' },
      enAlt: ['forest', 'woods', 'wood'],
    },
    {
      id: 'talt',
      sv: 'tält',
      en: 'tent',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'tältet', plural: 'tält', pluralDefinite: 'tälten' },
    },
    {
      id: 'talta',
      sv: 'tälta',
      en: 'to camp (in a tent)',
      pos: 'verb',
      forms: { present: 'tältar', past: 'tältade', supine: 'tältat', imperative: 'tälta' },
      enAlt: ['to camp'],
    },
    {
      id: 'plocka',
      sv: 'plocka',
      en: 'to pick',
      pos: 'verb',
      forms: { present: 'plockar', past: 'plockade', supine: 'plockat', imperative: 'plocka' },
      enAlt: ['to gather', 'to collect'],
    },
    {
      id: 'svamp',
      sv: 'svamp',
      en: 'mushroom',
      pos: 'noun',
      gender: 'en',
      note: 'Often used without an ending for mushrooms in general: plocka svamp = go mushroom picking.',
      forms: { definite: 'svampen', plural: 'svampar', pluralDefinite: 'svamparna' },
      enAlt: ['mushrooms', 'fungus'],
    },
    {
      id: 'bar-berry',
      sv: 'bär',
      en: 'berry',
      pos: 'noun',
      gender: 'ett',
      pron: 'bair',
      forms: { definite: 'bäret', plural: 'bär', pluralDefinite: 'bären' },
      enAlt: ['berries'],
    },
    {
      id: 'fjall',
      sv: 'fjäll',
      en: 'mountain (in the north)',
      pos: 'noun',
      gender: 'ett',
      pron: 'fyell',
      note: 'The open, treeless mountains of northern and western Sweden. på fjället = in the mountains.',
      forms: { definite: 'fjället', plural: 'fjäll', pluralDefinite: 'fjällen' },
      enAlt: ['mountain', 'fell', 'mountains'],
    },
    {
      id: 'skrap',
      sv: 'skräp',
      en: 'litter / rubbish',
      pos: 'noun',
      gender: 'ett',
      pron: 'skrairp',
      forms: { definite: 'skräpet' },
      enAlt: ['litter', 'rubbish', 'trash', 'junk'],
    },
    {
      id: 'eld',
      sv: 'eld',
      en: 'fire',
      pos: 'noun',
      gender: 'en',
      note: 'göra upp eld = make a fire. A fire ban is eldningsförbud.',
      forms: { definite: 'elden', plural: 'eldar', pluralDefinite: 'eldarna' },
      enAlt: ['campfire'],
    },
  ],
  dialogue: {
    title: 'A hike in the forest',
    setting: 'Sara and Leo are hiking near Sara’s summer cottage in August.',
    lines: [
      {
        speaker: 'Leo',
        sv: 'Vad fin skogen är! Får man tälta här?',
        en: 'What a lovely forest! Is it OK to camp here?',
      },
      {
        speaker: 'Sara',
        sv: 'Ja, en natt är okej. Men inte för nära huset där borta.',
        en: 'Yes, one night is fine. But not too close to the house over there.',
      },
      {
        speaker: 'Leo',
        sv: 'Titta, blåbär! Får man plocka dem?',
        en: 'Look, blueberries! Can we pick them?',
      },
      {
        speaker: 'Sara',
        sv: 'Ja, bär och svamp får alla plocka. Det är allemansrätten.',
        en: 'Yes, everyone can pick berries and mushrooms. That’s allemansrätten.',
      },
      {
        speaker: 'Leo',
        sv: 'Kan vi göra upp eld och grilla?',
        en: 'Can we make a fire and have a barbecue?',
      },
      {
        speaker: 'Sara',
        sv: 'Inte idag. Det är eldningsförbud, för det är så torrt.',
        en: 'Not today. There’s a fire ban, because it’s so dry.',
      },
      {
        speaker: 'Leo',
        sv: 'Okej. Då äter vi smörgåsar i stället.',
        en: 'OK. Then we’ll eat sandwiches instead.',
      },
      {
        speaker: 'Sara',
        sv: 'Och skräpet tar vi med hem!',
        en: 'And we take the litter home with us!',
      },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: 'inte störa, inte förstöra',
      promptLang: 'sv',
      question: 'What is the golden rule of allemansrätten?',
      choices: [
        'Don’t disturb, don’t destroy.',
        'Don’t stop, don’t stay.',
        'Don’t camp, don’t pick.',
      ],
      answer: 'Don’t disturb, don’t destroy.',
      explanation:
        'You may enjoy nature almost everywhere, as long as you don’t disturb people or animals and don’t destroy anything.',
    },
    {
      type: 'gap',
      text: 'Man ___ plocka bär och svamp.',
      en: 'You may pick berries and mushrooms.',
      choices: ['får', 'måste', 'ska'],
      answer: 'får',
      explanation:
        'får means "may / is allowed to". Picking berries and mushrooms is allowed for everyone, but nobody has to.',
      vocab: ['plocka', 'bar-berry', 'svamp'],
    },
    {
      type: 'gap',
      text: 'Man får inte göra upp ___ när det är eldningsförbud.',
      en: 'You may not make a fire when there’s a fire ban.',
      choices: ['eld', 'elden', 'eldet'],
      answer: 'eld',
      explanation:
        'göra upp eld (make a fire) is a fixed phrase with no ending on eld. eld is an en-word, so eldet does not exist.',
      vocab: ['eld'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Leo', sv: 'Får man tälta här?', en: 'Is it OK to camp here?' }],
      question: 'You’re deep in the forest, far from any houses. What does Sara answer?',
      choices: [
        'Ja, en natt eller två är okej.',
        'Nej, man får aldrig tälta i Sverige.',
        'Ja, men bara bredvid ett hus.',
      ],
      answer: 'Ja, en natt eller två är okej.',
      explanation:
        'Under allemansrätten you may camp for a night or two, away from houses. Next to a house is exactly where you may not camp.',
      vocab: ['talta'],
    },
    {
      type: 'dialogueReply',
      lines: [
        { speaker: 'Sara', sv: 'Vad gör vi med skräpet?', en: 'What do we do with the litter?' },
      ],
      question: 'What’s the right answer?',
      choices: ['Vi tar med det hem.', 'Vi lägger det under ett träd.', 'Vi gör upp eld i skogen.'],
      answer: 'Vi tar med det hem.',
      explanation: 'Never leave skräp in nature: take it home with you.',
      vocab: ['skrap'],
    },
    {
      type: 'build',
      prompt: 'You may pick mushrooms in the forest.',
      answer: 'Man får plocka svamp i skogen.',
      accept: ['I skogen får man plocka svamp.'],
      distractors: ['plockar', 'skog'],
      explanation:
        'After får the next verb stays in the infinitive: får plocka. "The forest" is skogen.',
      vocab: ['plocka', 'svamp', 'skog'],
    },
    {
      type: 'listen',
      audio: 'Vi tältar en natt på fjället.',
      choices: [
        'We’re camping for a night in the mountains.',
        'We’re camping for a night in the forest.',
        'We’re walking for a week in the mountains.',
      ],
      answer: 'We’re camping for a night in the mountains.',
      explanation: 'tältar = are camping, på fjället = in the mountains.',
      vocab: ['talta', 'fjall'],
    },
    {
      type: 'type',
      prompt: 'the tent',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'tältet',
      reject: ['tält', 'tälten', 'tälteen'],
      strict: true,
      hint: 'ett tält',
      explanation: 'tält is an ett-word, so "the tent" is tältet. tälten means "the tents".',
      vocab: ['talt'],
    },
    {
      type: 'dictation',
      audio: 'Vi plockade bär i skogen.',
      en: 'We picked berries in the forest.',
      vocab: ['plocka', 'bar-berry', 'skog'],
    },
    {
      type: 'speak',
      text: 'Får man tälta här?',
      en: 'Is it OK to camp here?',
      vocab: ['talta'],
    },
  ],
})
