import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u11-l02',
  learn: [
    {
      title: 'Åka or gå?',
      text: 'English "go" has two Swedish partners:\n\n**gå** = go on foot, walk: [[Jag går till jobbet.]]\n**åka** = go by any vehicle (bus, train, car, boat): [[Jag åker buss till jobbet.]]\n\nWith åka you usually say the vehicle with no en or ett: [[åka buss]], [[åka tåg]], [[åka tunnelbana]]. You can also use **ta** (take) with the definite form: [[ta bussen]], [[ta tåget]], [[ta flyget]].',
      examples: [
        { sv: 'Jag går till skolan.', en: 'I walk to school.' },
        { sv: 'Jag åker buss till skolan.', en: 'I take the bus to school.' },
        { sv: 'Vi åker tåg till Göteborg.', en: 'We’re going to Gothenburg by train.' },
        { sv: 'De tar flyget till Kiruna.', en: 'They’re flying to Kiruna.' },
      ],
      tip: 'One twist: buses and trains themselves "go" with gå, meaning they run or leave: "Bussen går klockan tre." (The bus leaves at three.)',
    },
    {
      title: 'Buses, trains and trams',
      text: 'Sweden is great for public transport (kollektivtrafik). Stockholm has the [[tunnelbana]] (underground), often called [[T-banan]]: look for the blue T sign. Göteborg, Norrköping and a few other cities have [[spårvagnar]] (trams).',
      table: {
        headers: ['a …', 'the …', 'more than one', 'English'],
        rows: [
          ['en buss', 'bussen', 'bussar', 'bus'],
          ['ett tåg', 'tåget', 'tåg', 'train'],
          ['en tunnelbana', 'tunnelbanan', 'tunnelbanor', 'underground / metro'],
          ['en spårvagn', 'spårvagnen', 'spårvagnar', 'tram'],
          ['ett flyg', 'flyget', 'flyg', 'flight / plane'],
          ['en hållplats', 'hållplatsen', 'hållplatser', 'stop (bus, tram)'],
        ],
        svColumns: [0, 1, 2],
      },
    },
    {
      title: 'At the station',
      text: 'Trains **avgår** (depart) from a **spår** (track, platform), and sometimes they are **försenade** (delayed). Watch the ending: [[Bussen är försenad]], but [[Tåget är försenat]], because tåg is an ett-word.\n\nTo change trains or buses, use **byta**: [[Byt till tunnelbanan vid T-Centralen.]]',
      examples: [
        { sv: 'Tåget avgår från spår 3.', en: 'The train departs from platform 3.' },
        { sv: 'Tåget är försenat.', en: 'The train is delayed.' },
        { sv: 'Bussarna är försenade.', en: 'The buses are delayed.' },
        { sv: 'Vi måste byta till bussen i Lund.', en: 'We have to change to the bus in Lund.' },
        { sv: 'Hur ofta går bussen?', en: 'How often does the bus run?' },
      ],
      tip: 'avgå is formal, the word on signs and announcements. In everyday speech Swedes just say "Tåget går klockan tio."',
    },
  ],
  vocab: [
    {
      id: 'aka',
      sv: 'åka',
      en: 'to go (by vehicle) / travel',
      pos: 'verb',
      pron: 'OH-ka',
      note: 'åka buss = go by bus. For walking, use gå.',
      forms: { present: 'åker', past: 'åkte', supine: 'åkt', imperative: 'åk' },
      enAlt: ['to go', 'to travel', 'to ride'],
    },
    {
      id: 'buss',
      sv: 'buss',
      en: 'bus',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'bussen', plural: 'bussar', pluralDefinite: 'bussarna' },
    },
    {
      id: 'tag-train',
      sv: 'tåg',
      en: 'train',
      pos: 'noun',
      gender: 'ett',
      pron: 'tohg (long å)',
      forms: { definite: 'tåget', plural: 'tåg', pluralDefinite: 'tågen' },
    },
    {
      id: 'tunnelbana',
      sv: 'tunnelbana',
      en: 'underground / metro',
      pos: 'noun',
      gender: 'en',
      note: 'In Stockholm often called T-banan.',
      forms: { definite: 'tunnelbanan', plural: 'tunnelbanor', pluralDefinite: 'tunnelbanorna' },
      enAlt: ['underground', 'metro', 'subway', 'tube'],
    },
    {
      id: 'sparvagn',
      sv: 'spårvagn',
      en: 'tram',
      pos: 'noun',
      gender: 'en',
      pron: 'SPOHR-vangn',
      forms: { definite: 'spårvagnen', plural: 'spårvagnar', pluralDefinite: 'spårvagnarna' },
      enAlt: ['streetcar'],
    },
    {
      id: 'flyg',
      sv: 'flyg',
      en: 'flight / plane',
      pos: 'noun',
      gender: 'ett',
      note: 'ta flyget = fly, go by plane.',
      forms: { definite: 'flyget', plural: 'flyg', pluralDefinite: 'flygen' },
      enAlt: ['flight', 'plane', 'flying'],
    },
    {
      id: 'hallplats',
      sv: 'hållplats',
      en: 'stop (bus or tram)',
      pos: 'noun',
      gender: 'en',
      pron: 'HOLL-plats',
      forms: { definite: 'hållplatsen', plural: 'hållplatser', pluralDefinite: 'hållplatserna' },
      enAlt: ['bus stop', 'stop', 'tram stop'],
    },
    {
      id: 'byta',
      sv: 'byta',
      en: 'to change / switch',
      pos: 'verb',
      note: 'byta till tåget = change to the train.',
      forms: { present: 'byter', past: 'bytte', supine: 'bytt', imperative: 'byt' },
      enAlt: ['to change', 'to switch'],
    },
    {
      id: 'forsenad',
      sv: 'försenad',
      en: 'delayed / late',
      pos: 'adjective',
      forms: { neuter: 'försenat', plural: 'försenade' },
      enAlt: ['delayed', 'late'],
    },
    {
      id: 'avga',
      sv: 'avgå',
      en: 'to depart / leave',
      pos: 'verb',
      note: 'Used on signs and in announcements: Tåget avgår från spår 3.',
      forms: { present: 'avgår', past: 'avgick', supine: 'avgått' },
      enAlt: ['to depart', 'to leave'],
    },
  ],
  dialogue: {
    title: 'At the bus stop',
    setting: 'Omar is waiting at a bus stop and asks Lina for help.',
    lines: [
      {
        speaker: 'Omar',
        sv: 'Ursäkta, går den här bussen till stationen?',
        en: 'Excuse me, does this bus go to the station?',
      },
      {
        speaker: 'Lina',
        sv: 'Nej, du måste ta buss fyra. Den går från hållplatsen där borta.',
        en: 'No, you have to take the number 4. It leaves from the stop over there.',
      },
      {
        speaker: 'Omar',
        sv: 'Tack! Åker du också till stationen?',
        en: 'Thanks! Are you going to the station too?',
      },
      {
        speaker: 'Lina',
        sv: 'Ja, jag ska ta tåget till Uppsala.',
        en: 'Yes, I’m taking the train to Uppsala.',
      },
      {
        speaker: 'Omar',
        sv: 'Titta, bussen är försenad. Tio minuter!',
        en: 'Look, the bus is delayed. Ten minutes!',
      },
      {
        speaker: 'Lina',
        sv: 'Typiskt! Ska vi gå i stället? Det tar femton minuter.',
        en: 'Typical! Shall we walk instead? It takes fifteen minutes.',
      },
      { speaker: 'Omar', sv: 'Ja, gärna!', en: 'Yes, let’s!' },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Jag ___ buss till jobbet varje dag.',
      en: 'I take the bus to work every day.',
      choices: ['åker', 'går', 'avgår'],
      answer: 'åker',
      explanation:
        'You travel by bus, so the verb is åka: jag åker buss. Jag går would mean you walk, and avgå is what the bus itself does.',
      vocab: ['aka', 'buss'],
    },
    {
      type: 'gap',
      text: 'Det är nära, så jag ___ till skolan.',
      en: 'It’s close, so I walk to school.',
      choices: ['går', 'åker', 'avgår'],
      answer: 'går',
      explanation: 'Walking is gå. åka always means going by some kind of vehicle.',
      vocab: ['aka', 'nara'],
    },
    {
      type: 'gap',
      text: 'Tåget ___ från spår 3.',
      en: 'The train departs from platform 3.',
      choices: ['avgår', 'byter', 'stannar'],
      answer: 'avgår',
      explanation:
        'avgå means "depart", the word you see on signs. People åker tåg, but the train itself avgår (or just går).',
      vocab: ['avga', 'tag-train'],
    },
    {
      type: 'gap',
      text: 'Tåget är ___.',
      en: 'The train is delayed.',
      choices: ['försenat', 'försenad', 'försenade'],
      answer: 'försenat',
      explanation:
        'tåg is an ett-word, so the adjective takes -t: tåget är försenat. Compare bussen är försenad.',
      vocab: ['forsenad', 'tag-train'],
    },
    {
      type: 'dialogueReply',
      lines: [
        {
          speaker: 'Omar',
          sv: 'Går den här bussen till stationen?',
          en: 'Does this bus go to the station?',
        },
      ],
      question: 'It doesn’t. Omar needs the number 4. What do you say?',
      choices: [
        'Nej, du måste ta buss fyra.',
        'Ja, du måste ta buss fyra.',
        'Nej, du måste åka fyra bussar.',
      ],
      answer: 'Nej, du måste ta buss fyra.',
      explanation:
        'The answer is no, and "the number 4 bus" is buss fyra: the number comes after the word.',
      vocab: ['buss', 'station'],
    },
    {
      type: 'build',
      prompt: 'I take the tram to work.',
      answer: 'Jag åker spårvagn till jobbet.',
      distractors: ['går', 'en'],
      explanation: 'åka + vehicle, with no en or ett: åka spårvagn, åka buss, åka tåg.',
      vocab: ['aka', 'sparvagn'],
    },
    {
      type: 'build',
      prompt: 'We have to change to the train in Uppsala.',
      answer: 'Vi måste byta till tåget i Uppsala.',
      accept: ['I Uppsala måste vi byta till tåget.'],
      distractors: ['byter', 'från'],
      explanation:
        'After måste the verb stays in the infinitive: måste byta. "Change to" is byta till.',
      vocab: ['byta', 'tag-train'],
    },
    {
      type: 'listen',
      audio: 'Flyget till Stockholm är försenat.',
      choices: [
        'The flight to Stockholm is delayed.',
        'The train to Stockholm is delayed.',
        'The flight to Stockholm leaves soon.',
      ],
      answer: 'The flight to Stockholm is delayed.',
      explanation: 'flyget is "the flight". It is an ett-word, so försenad gets -t: försenat.',
      vocab: ['flyg', 'forsenad'],
    },
    {
      type: 'dictation',
      audio: 'Jag åker tunnelbana till jobbet.',
      en: 'I take the underground to work.',
      vocab: ['aka', 'tunnelbana'],
    },
    {
      type: 'speak',
      text: 'Ursäkta, var är hållplatsen?',
      en: 'Excuse me, where is the bus stop?',
      vocab: ['ursakta', 'hallplats'],
    },
  ],
})
