import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u11-l03',
  learn: [
    {
      title: 'One-way or return?',
      text: 'At a ticket counter you need three things: where to, what kind of ticket, and how many people.\n\nA one-way ticket is [[en enkel biljett]] or just [[en enkelbiljett]]. A return ticket is [[tur och retur]] ("trip and return").',
      examples: [
        { sv: 'En biljett till Göteborg, tack.', en: 'A ticket to Gothenburg, please.' },
        { sv: 'Enkel eller tur och retur?', en: 'One-way or return?' },
        { sv: 'Tur och retur, tack.', en: 'Return, please.' },
        { sv: 'Två vuxna och ett barn.', en: 'Two adults and one child.' },
        { sv: 'Är den här platsen ledig?', en: 'Is this seat free?' },
      ],
      tip: 'vuxen (adult) works like an adjective: en vuxen, två vuxna. And enkel also means "simple": Det är enkelt!',
    },
    {
      title: 'Buy it before you board',
      text: 'On most city buses in Sweden you **can’t pay cash**. Buy your ticket in the operator’s **app**, at a ticket machine, or (in many regions) by tapping your bank card or phone at the gate or on the bus (Swedes call this [[blippa]]).\n\nEach region has its own operator, like **SL** in Stockholm and **Västtrafik** in Göteborg. For long-distance trains, the big name is **SJ**.\n\nA local ticket is valid for a set time, for example 75 minutes in Stockholm: [[Biljetten är giltig i 75 minuter.]]',
      examples: [
        { sv: 'Jag köper biljetten i appen.', en: 'I buy the ticket in the app.' },
        { sv: 'Biljetten är giltig i 75 minuter.', en: 'The ticket is valid for 75 minutes.' },
        { sv: 'Alla resenärer måste ha en biljett.', en: 'All passengers must have a ticket.' },
      ],
    },
    {
      title: 'Discounts and endings',
      text: 'Students, young people and pensioners often get a **rabatt** (discount): [[studentrabatt]], [[pensionärsrabatt]].\n\nRemember the adjective endings from earlier: -t for ett-words, -a for plurals.',
      table: {
        headers: ['en-word', 'ett-word', 'plural', 'English'],
        rows: [
          ['Biljetten är giltig.', 'Kortet är giltigt.', 'Biljetterna är giltiga.', 'valid'],
          ['en enkel biljett', 'ett enkelt svar', 'enkla biljetter', 'single / simple'],
          ['en vuxen', 'ett vuxet barn', 'två vuxna', 'adult / grown-up'],
        ],
        svColumns: [0, 1, 2],
      },
    },
  ],
  vocab: [
    {
      id: 'biljett',
      sv: 'biljett',
      en: 'ticket',
      pos: 'noun',
      gender: 'en',
      pron: 'bil-YETT',
      forms: { definite: 'biljetten', plural: 'biljetter', pluralDefinite: 'biljetterna' },
    },
    {
      id: 'enkel',
      sv: 'enkel',
      en: 'single (one-way) / simple',
      pos: 'adjective',
      note: 'en enkel biljett or en enkelbiljett = a one-way ticket.',
      forms: { neuter: 'enkelt', plural: 'enkla' },
      enAlt: ['single', 'one-way', 'simple', 'easy'],
    },
    {
      id: 'tur-och-retur',
      sv: 'tur och retur',
      en: 'return (ticket)',
      pos: 'phrase',
      pron: 'tewr o reh-TEWR',
      enAlt: ['return', 'round trip', 'return ticket'],
    },
    {
      id: 'app',
      sv: 'app',
      en: 'app',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'appen', plural: 'appar', pluralDefinite: 'apparna' },
    },
    {
      id: 'plats',
      sv: 'plats',
      en: 'seat / place',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'platsen', plural: 'platser', pluralDefinite: 'platserna' },
      enAlt: ['seat', 'place', 'space'],
    },
    {
      id: 'resenar',
      sv: 'resenär',
      en: 'traveller / passenger',
      pos: 'noun',
      gender: 'en',
      pron: 'reh-seh-NAIR',
      forms: { definite: 'resenären', plural: 'resenärer', pluralDefinite: 'resenärerna' },
      enAlt: ['traveller', 'traveler', 'passenger'],
    },
    {
      id: 'rabatt',
      sv: 'rabatt',
      en: 'discount',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'rabatten', plural: 'rabatter', pluralDefinite: 'rabatterna' },
      enAlt: ['reduction'],
    },
    {
      id: 'vuxen',
      sv: 'vuxen',
      en: 'adult / grown-up',
      pos: 'adjective',
      note: 'Also used as a noun: en vuxen, två vuxna.',
      forms: { neuter: 'vuxet', plural: 'vuxna' },
      enAlt: ['adult', 'grown-up', 'grown up'],
    },
    {
      id: 'giltig',
      sv: 'giltig',
      en: 'valid',
      pos: 'adjective',
      pron: 'YIL-tig (soft g before i)',
      forms: { neuter: 'giltigt', plural: 'giltiga' },
    },
  ],
  dialogue: {
    title: 'No cash, please',
    setting: 'Tom is about to get on a bus in Stockholm. Ella helps him.',
    lines: [
      {
        speaker: 'Tom',
        sv: 'Ursäkta, kan jag betala kontant på bussen?',
        en: 'Excuse me, can I pay cash on the bus?',
      },
      {
        speaker: 'Ella',
        sv: 'Nej, tyvärr. Du köper biljetten i appen eller betalar med kort.',
        en: 'No, sorry. You buy the ticket in the app or pay by card.',
      },
      {
        speaker: 'Tom',
        sv: 'Okej. Vilken biljett behöver jag?',
        en: 'OK. Which ticket do I need?',
      },
      {
        speaker: 'Ella',
        sv: 'En enkelbiljett. Den är giltig i 75 minuter.',
        en: 'A single ticket. It’s valid for 75 minutes.',
      },
      { speaker: 'Tom', sv: 'Finns det studentrabatt?', en: 'Is there a student discount?' },
      {
        speaker: 'Ella',
        sv: 'Ja, om du har ett studentkort.',
        en: 'Yes, if you have a student card.',
      },
      { speaker: 'Tom', sv: 'Ja, det har jag!', en: 'Yes, I do!' },
      { speaker: 'Ella', sv: 'Bra, då blir det billigare.', en: 'Great, then it’s cheaper.' },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'En ___ till Malmö, tack.',
      en: 'A ticket to Malmö, please.',
      choices: ['biljett', 'biljetten', 'biljetter'],
      answer: 'biljett',
      explanation:
        'After en the noun has no ending: en biljett. biljetten already means "the ticket".',
      vocab: ['biljett'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Johan', sv: 'Enkel eller tur och retur?', en: 'One-way or return?' }],
      question: 'You’re at the SJ counter and you want to come back too. What do you say?',
      choices: ['Tur och retur, tack.', 'Enkel, tack.', 'Ingen rabatt, tack.'],
      answer: 'Tur och retur, tack.',
      explanation: 'tur och retur is a return ticket. Enkel would be one-way only.',
      vocab: ['tur-och-retur', 'enkel', 'tack'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Johan', sv: 'Hur många vuxna?', en: 'How many adults?' }],
      question: 'You and a friend are both adults. What do you answer?',
      choices: ['Två vuxna, tack.', 'Två vuxen, tack.', 'Två vuxet, tack.'],
      answer: 'Två vuxna, tack.',
      explanation: 'vuxen works like an adjective, so more than one is vuxna: en vuxen, två vuxna.',
      vocab: ['vuxen', 'tva'],
    },
    {
      type: 'gap',
      text: 'Biljetten är ___ i 75 minuter.',
      en: 'The ticket is valid for 75 minutes.',
      choices: ['giltig', 'giltigt', 'giltiga'],
      answer: 'giltig',
      explanation:
        'biljett is an en-word, so the adjective has no ending: giltig. An ett-word would take -t (kortet är giltigt).',
      vocab: ['giltig', 'biljett'],
    },
    {
      type: 'gap',
      text: 'Alla ___ måste ha en giltig biljett.',
      en: 'All passengers must have a valid ticket.',
      choices: ['resenärer', 'resenär', 'resenären'],
      answer: 'resenärer',
      explanation: 'alla (all) is followed by a plural: resenär → resenärer.',
      vocab: ['resenar', 'alla'],
    },
    {
      type: 'build',
      prompt: 'I buy the ticket in the app.',
      answer: 'Jag köper biljetten i appen.',
      accept: ['I appen köper jag biljetten.'],
      distractors: ['app', 'biljetter'],
      explanation: 'Both nouns are definite here: biljetten (the ticket), appen (the app).',
      vocab: ['kopa', 'biljett', 'app'],
    },
    {
      type: 'listen',
      audio: 'Två vuxna och ett barn, tur och retur.',
      choices: [
        'Two adults and one child, return.',
        'Two adults and one child, one-way.',
        'One adult and two children, return.',
      ],
      answer: 'Two adults and one child, return.',
      explanation: 'två vuxna = two adults, ett barn = one child, tur och retur = return.',
      vocab: ['vuxen', 'barn', 'tur-och-retur'],
    },
    {
      type: 'type',
      prompt: 'a one-way ticket',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'en enkelbiljett',
      accept: ['en enkel biljett', 'enkelbiljett', 'enkel biljett'],
      hint: 'en enkel …',
      explanation: 'en enkel biljett and en enkelbiljett both mean a single, one-way ticket.',
      vocab: ['enkel', 'biljett'],
    },
    {
      type: 'dictation',
      audio: 'Är den här platsen ledig?',
      en: 'Is this seat free?',
      vocab: ['plats', 'den', 'har-here'],
    },
    {
      type: 'speak',
      text: 'En biljett till Uppsala, tur och retur, tack.',
      en: 'A return ticket to Uppsala, please.',
      vocab: ['biljett', 'tur-och-retur'],
    },
  ],
})
