import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u11-l01',
  learn: [
    {
      title: 'Asking the way',
      text: 'Lost? Start with [[Ursäkta]] (excuse me) and ask **Hur kommer jag till …?** (literally "How do I come to …?"). It works for any place: [[Hur kommer jag till stationen?]]\n\nSwedes are often a bit shy with strangers, but they are happy to help once you ask. Places usually **ligger** (lie): [[Det ligger bredvid torget.]]',
      examples: [
        {
          sv: 'Ursäkta, hur kommer jag till stationen?',
          en: 'Excuse me, how do I get to the station?',
        },
        { sv: 'Det ligger bredvid torget.', en: 'It’s next to the square.' },
        { sv: 'Är det långt?', en: 'Is it far?' },
        { sv: 'Nej, det är nära. Fem minuter.', en: 'No, it’s close. Five minutes.' },
        { sv: 'Kan du visa mig på kartan?', en: 'Can you show me on the map?' },
      ],
    },
    {
      title: 'Left, right, straight ahead',
      text: 'Directions use **till** for "to the": [[till vänster]], [[till höger]]. Straight ahead is [[rakt fram]].\n\nIn quick speech you will also hear [[Sväng vänster!]] without till. Both are fine.',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['till vänster', 'to the left'],
          ['till höger', 'to the right'],
          ['rakt fram', 'straight ahead'],
          ['på vänster sida', 'on the left-hand side'],
          ['runt hörnet', 'around the corner'],
          ['vid korsningen', 'at the crossroads'],
          ['över bron', 'over the bridge'],
          ['långt bort', 'far away'],
        ],
        svColumns: [0],
      },
      tip: 'Count the streets with första (first) and andra (second): "Ta andra gatan till höger." (Take the second street on the right.)',
    },
    {
      title: 'Giving directions: the command form',
      text: 'To tell someone what to do, Swedish uses the **imperative**, which is just the bare verb: [[Gå!]] [[Ta!]] [[Sväng!]] [[Fortsätt!]]\n\nThe rule: drop the final **-a** of the infinitive: [[svänga]] → [[sväng]], [[fortsätta]] → [[fortsätt]]. But if the present tense ends in **-ar**, keep the -a: [[titta]] → [[titta]]. Short verbs stay as they are: [[gå]], [[ta]].',
      table: {
        headers: ['Infinitive', 'Present', 'Command', 'English'],
        rows: [
          ['gå', 'går', 'gå!', 'go! / walk!'],
          ['ta', 'tar', 'ta!', 'take!'],
          ['svänga', 'svänger', 'sväng!', 'turn!'],
          ['fortsätta', 'fortsätter', 'fortsätt!', 'keep going!'],
          ['titta', 'tittar', 'titta!', 'look!'],
        ],
        svColumns: [0, 1, 2],
      },
      tip: 'Commands sound friendly in Swedish, especially with a smile. A typical answer: "Gå rakt fram och sväng till vänster vid korsningen."',
    },
  ],
  vocab: [
    {
      id: 'vanster',
      sv: 'vänster',
      en: 'left',
      pos: 'adverb',
      note: 'till vänster = to the left; på vänster sida = on the left-hand side.',
    },
    {
      id: 'hoger',
      sv: 'höger',
      en: 'right (direction)',
      pos: 'adverb',
      note: 'till höger = to the right; på höger sida = on the right-hand side.',
      enAlt: ['right'],
    },
    {
      id: 'rakt-fram',
      sv: 'rakt fram',
      en: 'straight ahead',
      pos: 'phrase',
      enAlt: ['straight on'],
    },
    {
      id: 'horn',
      sv: 'hörn',
      en: 'corner',
      pos: 'noun',
      gender: 'ett',
      note: 'runt hörnet = around the corner. On a street corner Swedes often say på hörnet.',
      forms: { definite: 'hörnet', plural: 'hörn', pluralDefinite: 'hörnen' },
    },
    {
      id: 'korsning',
      sv: 'korsning',
      en: 'crossroads / junction',
      pos: 'noun',
      gender: 'en',
      pron: 'KORSH-ning (rs sounds like "sh")',
      forms: { definite: 'korsningen', plural: 'korsningar', pluralDefinite: 'korsningarna' },
      enAlt: ['crossroads', 'junction', 'intersection'],
    },
    {
      id: 'torg',
      sv: 'torg',
      en: 'square / market square',
      pos: 'noun',
      gender: 'ett',
      pron: 'tor-y (the g sounds like "y")',
      note: 'Many towns have a Stortorget, the main square.',
      forms: { definite: 'torget', plural: 'torg', pluralDefinite: 'torgen' },
      enAlt: ['square', 'market square', 'marketplace'],
    },
    {
      id: 'nara',
      sv: 'nära',
      en: 'near / close',
      pos: 'adverb',
      note: 'Never changes: Det är nära. It also works like "near": nära stationen.',
      enAlt: ['near', 'close'],
    },
    {
      id: 'langt-bort',
      sv: 'långt bort',
      en: 'far away',
      pos: 'phrase',
      note: 'Är det långt? = Is it far?',
      enAlt: ['far'],
    },
    {
      id: 'karta',
      sv: 'karta',
      en: 'map',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'kartan', plural: 'kartor', pluralDefinite: 'kartorna' },
    },
    {
      id: 'svanga',
      sv: 'svänga',
      en: 'to turn',
      pos: 'verb',
      forms: { present: 'svänger', past: 'svängde', supine: 'svängt', imperative: 'sväng' },
    },
    {
      id: 'bro',
      sv: 'bro',
      en: 'bridge',
      pos: 'noun',
      gender: 'en',
      pron: 'broo',
      forms: { definite: 'bron', plural: 'broar', pluralDefinite: 'broarna' },
    },
  ],
  dialogue: {
    title: 'The way to the station',
    setting: 'Sam is new in town and asks Karin on the street.',
    lines: [
      {
        speaker: 'Sam',
        sv: 'Ursäkta, hur kommer jag till stationen?',
        en: 'Excuse me, how do I get to the station?',
      },
      {
        speaker: 'Karin',
        sv: 'Gå rakt fram och sväng till vänster vid korsningen.',
        en: 'Go straight ahead and turn left at the crossroads.',
      },
      {
        speaker: 'Sam',
        sv: 'Vänster vid korsningen. Och sedan?',
        en: 'Left at the crossroads. And then?',
      },
      {
        speaker: 'Karin',
        sv: 'Sedan går du över bron. Stationen ligger bredvid torget.',
        en: 'Then you walk over the bridge. The station is next to the square.',
      },
      { speaker: 'Sam', sv: 'Är det långt?', en: 'Is it far?' },
      {
        speaker: 'Karin',
        sv: 'Nej, det är nära. Fem minuter, kanske.',
        en: 'No, it’s close. Five minutes, maybe.',
      },
      { speaker: 'Sam', sv: 'Tack så mycket!', en: 'Thank you so much!' },
      { speaker: 'Karin', sv: 'Ingen orsak!', en: 'No problem!' },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Gå rakt fram och ___ till höger.',
      en: 'Go straight ahead and turn right.',
      choices: ['sväng', 'svänger', 'svänga'],
      answer: 'sväng',
      explanation:
        'Directions are commands, and the command form is the bare verb: svänga → sväng, just like gå → gå.',
      vocab: ['svanga', 'rakt-fram', 'hoger'],
    },
    {
      type: 'build',
      prompt: 'Turn left at the crossroads.',
      answer: 'Sväng till vänster vid korsningen.',
      distractors: ['höger', 'svänger'],
      explanation:
        'Start with the command sväng, then the direction till vänster, then where: vid korsningen.',
      vocab: ['svanga', 'vanster', 'korsning'],
    },
    {
      type: 'dialogueReply',
      lines: [
        {
          speaker: 'Turist',
          sv: 'Ursäkta, var ligger torget?',
          en: 'Excuse me, where is the square?',
        },
      ],
      question: 'The square is just around the corner. What do you say?',
      choices: ['Det ligger runt hörnet.', 'Det ligger långt bort.', 'Det ligger på bron.'],
      answer: 'Det ligger runt hörnet.',
      explanation: 'runt hörnet means "around the corner". långt bort would mean it is far away.',
      vocab: ['horn', 'torg'],
    },
    {
      type: 'dialogueReply',
      lines: [
        { speaker: 'Sam', sv: 'Är det långt till stationen?', en: 'Is it far to the station?' },
      ],
      question: 'It’s only a five-minute walk. What do you answer?',
      choices: [
        'Nej, det är nära. Fem minuter.',
        'Ja, det är långt bort. Fem timmar.',
        'Ja, sväng till höger.',
      ],
      answer: 'Nej, det är nära. Fem minuter.',
      explanation: 'nära means "close". Five minutes is fem minuter, not fem timmar (five hours).',
      vocab: ['nara', 'langt-bort', 'minut'],
    },
    {
      type: 'gap',
      text: 'Affären ligger runt ___.',
      en: 'The shop is around the corner.',
      choices: ['hörnet', 'hörn', 'korsning'],
      answer: 'hörnet',
      explanation:
        'hörn is an ett-word, so "the corner" is hörnet. runt hörnet is a fixed phrase: around the corner.',
      vocab: ['horn'],
    },
    {
      type: 'listen',
      audio: 'Det ligger bredvid torget.',
      choices: ['It’s next to the square.', 'It’s behind the square.', 'It’s next to the bridge.'],
      answer: 'It’s next to the square.',
      explanation: 'bredvid means "next to", and torget is "the square".',
      vocab: ['torg', 'bredvid'],
    },
    {
      type: 'type',
      prompt: 'the bridge',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'bron',
      reject: ['bro', 'broen', 'broet'],
      strict: true,
      hint: 'en bro ends in a vowel',
      explanation: 'en bro ends in a vowel, so "the bridge" just adds -n: bron.',
      vocab: ['bro'],
    },
    {
      type: 'dictation',
      audio: 'Gå rakt fram och sväng till höger.',
      en: 'Go straight ahead and turn right.',
      vocab: ['rakt-fram', 'svanga', 'hoger'],
    },
    {
      type: 'build',
      prompt: 'Excuse me, how do I get to the station?',
      answer: 'Ursäkta, hur kommer jag till stationen?',
      distractors: ['station', 'vem'],
      explanation:
        'Hur kommer jag till …? is the standard way to ask the way. stationen is "the station".',
      vocab: ['ursakta', 'station'],
    },
    {
      type: 'speak',
      text: 'Ursäkta, hur kommer jag till torget?',
      en: 'Excuse me, how do I get to the square?',
      vocab: ['ursakta', 'torg'],
    },
  ],
})
