import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u03-l01',
  learn: [
    {
      title: 'Zero to ten',
      text: 'You already know [[två]] (two) and [[sju]] (seven). Here are the rest. Tap each number to hear it, then try counting out loud.',
      table: {
        headers: ['', 'Swedish', 'Sounds roughly like'],
        rows: [
          ['0', 'noll', 'nol (short o)'],
          ['1', 'ett', 'et'],
          ['2', 'två', 'tvoh'],
          ['3', 'tre', 'treh'],
          ['4', 'fyra', 'FEE-rah, lips rounded'],
          ['5', 'fem', 'fem'],
          ['6', 'sex', 'sex (yes, really!)'],
          ['7', 'sju', 'hwoo (the sj-sound)'],
          ['8', 'åtta', 'OT-tah'],
          ['9', 'nio', 'NEE-oo'],
          ['10', 'tio', 'TEE-oo'],
        ],
        svColumns: [1],
      },
      tip: 'In everyday speech many Swedes say [[nio]] and [[tio]] more like "NEE-eh" and "TEE-eh". Both are fine.',
    },
    {
      title: 'One: en or ett',
      text: 'When you count, "one" is **ett**: [[ett, två, tre]].\n\nBut in front of a noun, "one" looks just like "a": it is **en** with en-words and **ett** with ett-words. So [[en bil]] can mean "a car" or "one car", and [[ett hus]] can mean "a house" or "one house".',
      examples: [
        { sv: 'en bil', en: 'a car / one car' },
        { sv: 'ett hus', en: 'a house / one house' },
        { sv: 'ett glas vatten', en: 'a glass of water / one glass of water' },
      ],
    },
    {
      title: 'How many?',
      text: 'Ask **[[Hur många?]]** (How many?). The answer can be just a number: [[Tre, tack.]] (Three, please.)\n\nGood news: many ett-words look the same in the plural, so you can already count them: [[två barn]] (two children), [[tre hus]] (three houses), [[fem glas]] (five glasses).',
      examples: [
        { sv: 'Hur många barn?', en: 'How many children?' },
        { sv: 'Två barn.', en: 'Two children.' },
        { sv: 'Två kaffe, tack!', en: 'Two coffees, please!' },
      ],
      tip: 'In a café, Swedes order coffee like this: [[en kaffe]] (a cup of coffee), [[två kaffe]], [[tre kaffe]]. No plural ending needed.',
    },
  ],
  vocab: [
    { id: 'noll', sv: 'noll', en: 'zero', pos: 'numeral', pron: 'nol (short o)' },
    {
      id: 'ett-one',
      sv: 'ett',
      en: 'one',
      pos: 'numeral',
      pron: 'et',
      note: 'With en-words, "one" is en: en bil (one car), ett hus (one house).',
      alt: ['en'],
    },
    { id: 'tre', sv: 'tre', en: 'three', pos: 'numeral', pron: 'treh' },
    {
      id: 'fyra',
      sv: 'fyra',
      en: 'four',
      pos: 'numeral',
      pron: 'FEE-rah, with rounded lips',
      note: 'The y is the Swedish y: say "ee" while rounding your lips.',
    },
    { id: 'fem', sv: 'fem', en: 'five', pos: 'numeral', pron: 'fem' },
    { id: 'sex', sv: 'sex', en: 'six', pos: 'numeral', pron: 'sex' },
    { id: 'atta', sv: 'åtta', en: 'eight', pos: 'numeral', pron: 'OT-tah' },
    {
      id: 'nio',
      sv: 'nio',
      en: 'nine',
      pos: 'numeral',
      pron: 'NEE-oo',
      note: 'Often sounds like "NEE-eh" in everyday speech.',
    },
    {
      id: 'tio',
      sv: 'tio',
      en: 'ten',
      pos: 'numeral',
      pron: 'TEE-oo',
      note: 'Often sounds like "TEE-eh" in everyday speech.',
    },
    {
      id: 'hur-manga',
      sv: 'hur många',
      en: 'how many',
      pos: 'phrase',
      pron: 'hoor MONG-ah',
      note: 'Hur många barn? = How many children?',
    },
  ],
  dialogue: {
    title: 'Coffee for everyone',
    setting: 'Sara orders at a café. Johan works behind the counter.',
    lines: [
      { speaker: 'Johan', sv: 'Hej! Vad vill du ha?', en: 'Hi! What would you like?' },
      { speaker: 'Sara', sv: 'Hej! Tre kaffe, tack.', en: 'Hi! Three coffees, please.' },
      { speaker: 'Johan', sv: 'Tre kaffe. Något mer?', en: 'Three coffees. Anything else?' },
      {
        speaker: 'Sara',
        sv: 'Ja, två glas vatten, tack.',
        en: 'Yes, two glasses of water, please.',
      },
      { speaker: 'Johan', sv: 'Varsågod!', en: 'Here you go!' },
      { speaker: 'Sara', sv: 'Tack så mycket!', en: 'Thank you very much!' },
    ],
  },
  exercises: [
    {
      type: 'listen',
      audio: 'fyra',
      question: 'Which number did you hear?',
      choices: ['4', '5', '3'],
      answer: '4',
      explanation: 'fyra is 4. The y is the rounded Swedish y: "FEE-rah" with pursed lips.',
      vocab: ['fyra'],
    },
    {
      type: 'listen',
      audio: 'åtta',
      question: 'Which number did you hear?',
      choices: ['8', '3', '6'],
      answer: '8',
      explanation: 'åtta is 8. The å sounds like the "o" in "hot" here, because it is short.',
      vocab: ['atta'],
    },
    {
      type: 'mcq',
      prompt: 'tre + fyra',
      promptLang: 'sv',
      question: 'Add them up. Which number is it?',
      choices: ['sju', 'sex', 'åtta'],
      answer: 'sju',
      explanation: 'tre (3) + fyra (4) = sju (7).',
      vocab: ['tre', 'fyra'],
    },
    {
      type: 'gap',
      text: 'Två kaffe och ___ glas vatten, tack.',
      en: 'Two coffees and one glass of water, please.',
      question: 'Which word means "one" here?',
      choices: ['en', 'ett'],
      answer: 'ett',
      explanation: 'glas is an ett-word (ett glas), so "one glass" is ett glas.',
      vocab: ['ett-one', 'glas'],
    },
    {
      type: 'type',
      prompt: '8',
      promptLang: 'en',
      question: 'Write the number as a Swedish word',
      answer: 'åtta',
      strict: true,
      explanation: 'Eight is åtta, with å and double t.',
      vocab: ['atta'],
    },
    {
      type: 'type',
      prompt: '0',
      promptLang: 'en',
      question: 'Write the number as a Swedish word',
      answer: 'noll',
      strict: true,
      explanation: 'Zero is noll, with double l.',
      vocab: ['noll'],
    },
    {
      type: 'build',
      prompt: 'Two coffees, please.',
      answer: 'Två kaffe, tack.',
      distractors: ['tre', 'nej'],
      explanation: 'In a café you just say the number and kaffe: två kaffe, tre kaffe.',
      vocab: ['tva', 'kaffe', 'tack'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Johan', sv: 'Hur många kaffe?', en: 'How many coffees?' }],
      question: 'You want three. What do you say?',
      choices: ['Tre, tack.', 'Tio, tack.', 'Nej, tack.'],
      answer: 'Tre, tack.',
      explanation: 'tre is three. Tio is ten, which is a lot of coffee!',
      vocab: ['hur-manga', 'tre'],
    },
    {
      type: 'dictation',
      audio: 'Ett, två, tre, fyra, fem.',
      en: 'One, two, three, four, five.',
      vocab: ['ett-one', 'tre', 'fyra', 'fem'],
    },
    {
      type: 'speak',
      text: 'Sex, sju, åtta, nio, tio!',
      en: 'Six, seven, eight, nine, ten!',
      vocab: ['sex', 'atta', 'nio', 'tio'],
    },
  ],
})
