import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u03-l03',
  learn: [
    {
      title: 'Counting in tens',
      text: 'The tens end in **-tio**, like English "-ty". In everyday speech that ending sounds like a short "-ti": [[trettio]] sounds like "TRET-ti" and [[fyrtio]] like "FÖR-ti".\n\nSo listen to the ending: **-ton** is a teen, **-tio** is a ten. [[fjorton]] is 14, [[fyrtio]] is 40.',
      table: {
        headers: ['', 'Swedish', 'Sounds roughly like'],
        rows: [
          ['20', 'tjugo', 'SHOO-go'],
          ['30', 'trettio', 'TRET-ti'],
          ['40', 'fyrtio', 'FÖR-ti'],
          ['50', 'femtio', 'FEM-ti'],
          ['60', 'sextio', 'SEX-ti'],
          ['70', 'sjuttio', 'HWUT-ti'],
          ['80', 'åttio', 'OT-ti'],
          ['90', 'nittio', 'NIT-ti'],
          ['100', 'hundra', 'HUN-drah'],
          ['1000', 'tusen', 'TOO-sen'],
        ],
        svColumns: [1],
      },
    },
    {
      title: 'One long word',
      text: 'Bigger numbers are glued together into **one word**, biggest part first: [[tjugoett]] (21), [[trettiofem]] (35), [[hundrafemtio]] (150).\n\nFor 100 and 1000 you can just say [[hundra]] and [[tusen]], or [[etthundra]] and [[ettusen]].',
      table: {
        headers: ['', 'Swedish'],
        rows: [
          ['21', 'tjugoett'],
          ['22', 'tjugotvå'],
          ['35', 'trettiofem'],
          ['47', 'fyrtiosju'],
          ['99', 'nittionio'],
          ['150', 'hundrafemtio'],
          ['2000', 'tvåtusen'],
        ],
        svColumns: [1],
      },
      tip: 'Write numbers as one word, with no spaces or dashes: tjugofem, not "tjugo fem" or "tjugo-fem".',
    },
    {
      title: 'How old are you?',
      text: 'Ask [[Hur gammal är du?]] (How old are you?). Answer with **Jag är** + number + **år**. Adding **gammal** at the end is optional: [[Jag är trettiofyra år.]] or [[Jag är trettiofyra år gammal.]]',
      examples: [
        { sv: 'Hur gammal är du?', en: 'How old are you?' },
        { sv: 'Jag är tjugofem år.', en: "I'm twenty-five (years old)." },
        { sv: 'Hon är sju år gammal.', en: 'She is seven years old.' },
        { sv: 'Han är hundra år!', en: "He's a hundred!" },
      ],
      tip: '[[år]] (year) is the same in the plural: ett år, två år, tjugo år.',
    },
  ],
  vocab: [
    { id: 'trettio', sv: 'trettio', en: 'thirty', pos: 'numeral', pron: 'TRET-ti' },
    {
      id: 'fyrtio',
      sv: 'fyrtio',
      en: 'forty',
      pos: 'numeral',
      pron: 'FÖR-ti',
      note: 'Spelled fyr- but said "för-".',
    },
    { id: 'femtio', sv: 'femtio', en: 'fifty', pos: 'numeral', pron: 'FEM-ti' },
    { id: 'sextio', sv: 'sextio', en: 'sixty', pos: 'numeral', pron: 'SEX-ti' },
    {
      id: 'sjuttio',
      sv: 'sjuttio',
      en: 'seventy',
      pos: 'numeral',
      pron: 'HWUT-ti (the sj-sound)',
    },
    { id: 'attio', sv: 'åttio', en: 'eighty', pos: 'numeral', pron: 'OT-ti' },
    { id: 'nittio', sv: 'nittio', en: 'ninety', pos: 'numeral', pron: 'NIT-ti' },
    {
      id: 'hundra',
      sv: 'hundra',
      en: 'hundred',
      pos: 'numeral',
      pron: 'HUN-drah',
      enAlt: ['a hundred', 'one hundred'],
      alt: ['etthundra'],
    },
    {
      id: 'tusen',
      sv: 'tusen',
      en: 'thousand',
      pos: 'numeral',
      pron: 'TOO-sen',
      note: 'Tusen tack! = Thanks a lot! (literally "a thousand thanks").',
      enAlt: ['a thousand', 'one thousand'],
      alt: ['ettusen'],
    },
    {
      id: 'ar-year',
      sv: 'år',
      en: 'year',
      pos: 'noun',
      gender: 'ett',
      pron: 'ohr (long å)',
      note: 'Same form in the plural: två år.',
      forms: { definite: 'året', plural: 'år', pluralDefinite: 'åren' },
    },
    {
      id: 'gammal',
      sv: 'gammal',
      en: 'old',
      pos: 'adjective',
      pron: 'GAM-mal',
      note: 'Hur gammal är du? = How old are you?',
      forms: { neuter: 'gammalt', plural: 'gamla' },
    },
  ],
  dialogue: {
    title: 'Grandma’s age',
    setting: 'Leo is visiting his grandmother Birgitta.',
    lines: [
      { speaker: 'Leo', sv: 'Mormor, hur gammal är du?', en: 'Grandma, how old are you?' },
      { speaker: 'Birgitta', sv: 'Jag är sjuttiotvå år. Och du?', en: "I'm seventy-two. And you?" },
      {
        speaker: 'Leo',
        sv: 'Jag är sju. Sju och sjuttiotvå!',
        en: "I'm seven. Seven and seventy-two!",
      },
      { speaker: 'Birgitta', sv: 'Ja! Och morfar är åttio.', en: 'Yes! And Grandpa is eighty.' },
      { speaker: 'Leo', sv: 'Åttio? Han är jättegammal!', en: "Eighty? He's super old!" },
      {
        speaker: 'Birgitta',
        sv: 'Nej då, han är inte gammal. Han är bara åttio!',
        en: "No, no, he isn't old. He's only eighty!",
      },
    ],
  },
  exercises: [
    {
      type: 'listen',
      audio: 'fyrtio',
      question: 'Which number did you hear?',
      choices: ['40', '14', '4'],
      answer: '40',
      explanation: 'fyrtio (40) sounds like "FÖR-ti". The teen fjorton (14) ends in -ton.',
      vocab: ['fyrtio'],
    },
    {
      type: 'listen',
      audio: 'sextio',
      question: 'Which number did you hear?',
      choices: ['60', '16', '6'],
      answer: '60',
      explanation: 'sextio (60) ends in a short "-ti". sexton (16) ends in -ton.',
      vocab: ['sextio'],
    },
    {
      type: 'listen',
      audio: 'trettiofem',
      question: 'Which number did you hear?',
      choices: ['35', '53', '30'],
      answer: '35',
      explanation: 'trettio (30) + fem (5): the tens come first, just like in English.',
      vocab: ['trettio', 'fem'],
    },
    {
      type: 'mcq',
      prompt: 'hundrafemtio',
      promptLang: 'sv',
      question: 'Which number is this?',
      choices: ['150', '105', '1050'],
      answer: '150',
      explanation: 'hundra (100) + femtio (50) = 150.',
      vocab: ['hundra', 'femtio'],
    },
    {
      type: 'type',
      prompt: '21',
      promptLang: 'en',
      question: 'Write the number as one Swedish word',
      answer: 'tjugoett',
      strict: true,
      reject: ['tjugo ett'],
      explanation: 'Compound numbers are one word: tjugo + ett = tjugoett.',
      vocab: ['tjugo', 'ett-one'],
    },
    {
      type: 'type',
      prompt: '80',
      promptLang: 'en',
      question: 'Write the number as a Swedish word',
      answer: 'åttio',
      strict: true,
      explanation: 'Eighty is åttio: å and double t, just like åtta (8), plus -io.',
      vocab: ['attio'],
    },
    {
      type: 'gap',
      text: 'Hur ___ är du?',
      en: 'How old are you?',
      choices: ['gammal', 'många', 'bra'],
      answer: 'gammal',
      explanation: 'Hur gammal är du? asks for your age. Hur många? means "how many?".',
      vocab: ['gammal'],
    },
    {
      type: 'build',
      prompt: "I'm twenty-five years old.",
      answer: 'Jag är tjugofem år gammal.',
      distractors: ['tjugo', 'fem'],
      explanation: 'tjugofem is written as one word. Gammal at the end is optional.',
      vocab: ['tjugo', 'fem', 'ar-year', 'gammal'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Nora', sv: 'Hur gammal är du?', en: 'How old are you?' }],
      question: 'Tell Nora your age.',
      choices: ['Jag är trettio år.', 'Jag mår bra, tack.', 'Trettio, tack.'],
      answer: 'Jag är trettio år.',
      explanation:
        'Jag är + number + år. "Jag mår bra" answers "How are you?", and "Trettio, tack" means "Thirty, please".',
      vocab: ['trettio', 'ar-year'],
    },
    {
      type: 'speak',
      text: 'Hur gammal är du? Jag är trettiofyra år.',
      en: "How old are you? I'm thirty-four.",
      vocab: ['gammal', 'trettio', 'fyra', 'ar-year'],
    },
  ],
})
