import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u03-l02',
  learn: [
    {
      title: 'The -ton numbers',
      text: 'Swedish "teens" end in **-ton**, a lot like English "-teen". Most of them are just a small number plus -ton: [[tretton]] (13), [[femton]] (15), [[sexton]] (16).\n\nWatch out for the odd ones: [[elva]] (11) and [[tolv]] (12) are words of their own, like "eleven" and "twelve". And some numbers change a little: fyra becomes **fjor**-ton, åtta becomes **ar**-ton, nio becomes **nit**-ton.',
      table: {
        headers: ['', 'Swedish', 'Built from'],
        rows: [
          ['11', 'elva', 'its own word'],
          ['12', 'tolv', 'its own word'],
          ['13', 'tretton', 'tre + ton'],
          ['14', 'fjorton', 'fyra → fjor + ton'],
          ['15', 'femton', 'fem + ton'],
          ['16', 'sexton', 'sex + ton'],
          ['17', 'sjutton', 'sju + ton'],
          ['18', 'arton', 'åtta → ar + ton'],
          ['19', 'nitton', 'nio → nit + ton'],
          ['20', 'tjugo', 'its own word'],
        ],
        svColumns: [1],
      },
      tip: 'Learn [[arton]] (18) carefully: there is no å in it.',
    },
    {
      title: 'Two sounds you know',
      text: 'Remember the sj-sound and the tj-sound from Unit 1? They both turn up here.\n\n[[sjutton]] (17) starts with the breathy **sj-sound**, just like [[sju]]: think "HWUT-ton".\n[[tjugo]] (20) starts with the softer **tj-sound**, like the "sh" in "sheep": "SHOO-go".',
      examples: [
        { sv: 'sju, sjutton', en: 'seven, seventeen' },
        { sv: 'nitton, tjugo', en: 'nineteen, twenty' },
      ],
      tip: 'The double consonants in [[tretton]], [[sjutton]] and [[nitton]] make the vowel before them short and snappy.',
    },
  ],
  vocab: [
    { id: 'elva', sv: 'elva', en: 'eleven', pos: 'numeral', pron: 'EL-vah' },
    { id: 'tolv', sv: 'tolv', en: 'twelve', pos: 'numeral', pron: 'tolv (short o)' },
    { id: 'tretton', sv: 'tretton', en: 'thirteen', pos: 'numeral', pron: 'TRET-ton' },
    {
      id: 'fjorton',
      sv: 'fjorton',
      en: 'fourteen',
      pos: 'numeral',
      pron: 'FYOOR-ton',
      note: 'Spelled with fj, not fyr. Don’t mix it up with fyra (4).',
    },
    { id: 'femton', sv: 'femton', en: 'fifteen', pos: 'numeral', pron: 'FEM-ton' },
    { id: 'sexton', sv: 'sexton', en: 'sixteen', pos: 'numeral', pron: 'SEX-ton' },
    {
      id: 'sjutton',
      sv: 'sjutton',
      en: 'seventeen',
      pos: 'numeral',
      pron: 'HWUT-ton (the sj-sound)',
    },
    {
      id: 'arton',
      sv: 'arton',
      en: 'eighteen',
      pos: 'numeral',
      pron: 'AR-ton',
      note: 'No å here, even though 8 is åtta.',
    },
    { id: 'nitton', sv: 'nitton', en: 'nineteen', pos: 'numeral', pron: 'NIT-ton' },
  ],
  dialogue: {
    title: 'How many of us are there?',
    setting: 'Karin, a teacher, is counting her class on a school trip. Omar helps.',
    lines: [
      {
        speaker: 'Karin',
        sv: 'Okej, alla! Hur många är vi?',
        en: 'Okay, everyone! How many of us are there?',
      },
      {
        speaker: 'Omar',
        sv: 'Femton, sexton, sjutton … Vi är sjutton.',
        en: 'Fifteen, sixteen, seventeen … There are seventeen of us.',
      },
      {
        speaker: 'Karin',
        sv: 'Sjutton? Och du, Omar?',
        en: 'Seventeen? And what about you, Omar?',
      },
      {
        speaker: 'Omar',
        sv: 'Åh, just det! Vi är arton.',
        en: 'Oh, right! There are eighteen of us.',
      },
      {
        speaker: 'Karin',
        sv: 'Bra! Och vi är två lärare. Så vi är tjugo!',
        en: 'Good! And there are two of us teachers. So we are twenty!',
      },
      { speaker: 'Omar', sv: 'Tjugo! Jättebra!', en: 'Twenty! Great!' },
    ],
  },
  exercises: [
    {
      type: 'listen',
      audio: 'fjorton',
      question: 'Which number did you hear?',
      choices: ['14', '40', '4'],
      answer: '14',
      explanation: 'fjorton (14) ends in -ton. Four is fyra.',
      vocab: ['fjorton'],
    },
    {
      type: 'listen',
      audio: 'sjutton',
      question: 'Which number did you hear?',
      choices: ['17', '7', '70'],
      answer: '17',
      explanation: 'sjutton = sju + ton. The -ton ending tells you it is a "teen".',
      vocab: ['sjutton'],
    },
    {
      type: 'mcq',
      prompt: 'tio + fem',
      promptLang: 'sv',
      question: 'Add them up. Which number is it?',
      choices: ['femton', 'fjorton', 'sexton'],
      answer: 'femton',
      explanation: 'tio (10) + fem (5) = femton (15).',
      vocab: ['femton'],
    },
    {
      type: 'gap',
      text: 'Tio, elva, ___, tretton.',
      en: 'Ten, eleven, twelve, thirteen.',
      choices: ['tolv', 'tjugo', 'två'],
      answer: 'tolv',
      explanation: 'tolv (12) is irregular, like English "twelve".',
      vocab: ['tolv', 'elva', 'tretton'],
    },
    {
      type: 'type',
      prompt: '12',
      promptLang: 'en',
      question: 'Write the number as a Swedish word',
      answer: 'tolv',
      strict: true,
      vocab: ['tolv'],
    },
    {
      type: 'type',
      prompt: '18',
      promptLang: 'en',
      question: 'Write the number as a Swedish word',
      answer: 'arton',
      strict: true,
      reject: ['årton', 'åttaton'],
      explanation: 'Eighteen is arton: no å, even though eight is åtta.',
      vocab: ['arton'],
    },
    {
      type: 'build',
      prompt: 'There are eighteen of us.',
      answer: 'Vi är arton.',
      distractors: ['åtta', 'tjugo'],
      explanation: 'Swedish says "we are eighteen": Vi är arton.',
      vocab: ['arton'],
    },
    {
      type: 'dictation',
      audio: 'Elva, tolv, tretton, fjorton, femton.',
      en: 'Eleven, twelve, thirteen, fourteen, fifteen.',
      vocab: ['elva', 'tolv', 'tretton', 'fjorton', 'femton'],
    },
    {
      type: 'speak',
      text: 'Sexton, sjutton, arton, nitton, tjugo!',
      en: 'Sixteen, seventeen, eighteen, nineteen, twenty!',
      vocab: ['sexton', 'sjutton', 'arton', 'nitton'],
    },
  ],
})
