import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u03-l05',
  learn: [
    {
      title: 'Seven days',
      text: 'The Swedish week starts on Monday. Days are written with a **small letter**: [[måndag]], not "Måndag".\n\nThey all end in **-dag** (day), but in everyday speech the final g is usually silent: [[måndag]] sounds like "MON-dah". Several are named after the old Norse gods, just like in English.',
      table: {
        headers: ['Swedish', 'English', 'Named after'],
        rows: [
          ['måndag', 'Monday', 'the moon (måne)'],
          ['tisdag', 'Tuesday', 'Tyr, god of war'],
          ['onsdag', 'Wednesday', 'Oden (Odin)'],
          ['torsdag', 'Thursday', 'Tor (Thor)'],
          ['fredag', 'Friday', 'Frigg, Odin’s wife'],
          ['lördag', 'Saturday', 'washing day (lögardag)'],
          ['söndag', 'Sunday', 'the sun (sol)'],
        ],
        svColumns: [0],
      },
      tip: 'In [[torsdag]] the rs sounds like "sh": "TOOSH-dah".',
    },
    {
      title: 'På måndag or på måndagar?',
      text: 'Use **på** with days. [[på måndag]] means this coming Monday, one time. Add **-ar** for something that happens every week: [[på måndagar]] (on Mondays).\n\nThe weekend is [[helgen]]: [[i helgen]] means this weekend.',
      examples: [
        { sv: 'Vi ses på fredag!', en: 'See you on Friday!' },
        { sv: 'Jag spelar fotboll på lördagar.', en: 'I play football on Saturdays.' },
        { sv: 'Vad gör du i helgen?', en: 'What are you doing this weekend?' },
      ],
      tip: 'Last Monday is [[i måndags]]. You will meet it again later.',
    },
    {
      title: 'Today, tomorrow, yesterday',
      text: 'Ask [[Vilken dag är det idag?]] (What day is it today?) and answer [[Idag är det fredag.]]\n\nNotice the word order: in a Swedish statement the verb always comes **second**. When you start with idag, the verb **är** comes next, and then **det**. Not "Idag det är"!',
      examples: [
        { sv: 'Idag är det fredag.', en: "Today it's Friday." },
        { sv: 'Imorgon är det lördag.', en: "Tomorrow it's Saturday." },
        { sv: 'Igår var det torsdag.', en: 'Yesterday it was Thursday.' },
        { sv: 'Det är fredag idag.', en: "It's Friday today." },
      ],
      tip: 'You can also write these as two words: [[i dag]], [[i morgon]], [[i går]]. Both spellings are correct.',
    },
  ],
  vocab: [
    {
      id: 'mandag',
      sv: 'måndag',
      en: 'Monday',
      pos: 'noun',
      gender: 'en',
      pron: 'MON-dah (the g is often silent)',
      forms: { definite: 'måndagen', plural: 'måndagar', pluralDefinite: 'måndagarna' },
    },
    {
      id: 'tisdag',
      sv: 'tisdag',
      en: 'Tuesday',
      pos: 'noun',
      gender: 'en',
      pron: 'TEES-dah',
      forms: { definite: 'tisdagen', plural: 'tisdagar', pluralDefinite: 'tisdagarna' },
    },
    {
      id: 'onsdag',
      sv: 'onsdag',
      en: 'Wednesday',
      pos: 'noun',
      gender: 'en',
      pron: 'OONS-dah',
      forms: { definite: 'onsdagen', plural: 'onsdagar', pluralDefinite: 'onsdagarna' },
    },
    {
      id: 'torsdag',
      sv: 'torsdag',
      en: 'Thursday',
      pos: 'noun',
      gender: 'en',
      pron: 'TOOSH-dah (rs = sh)',
      forms: { definite: 'torsdagen', plural: 'torsdagar', pluralDefinite: 'torsdagarna' },
    },
    {
      id: 'fredag',
      sv: 'fredag',
      en: 'Friday',
      pos: 'noun',
      gender: 'en',
      pron: 'FREH-dah',
      forms: { definite: 'fredagen', plural: 'fredagar', pluralDefinite: 'fredagarna' },
    },
    {
      id: 'lordag',
      sv: 'lördag',
      en: 'Saturday',
      pos: 'noun',
      gender: 'en',
      pron: 'LÖ-dah (rd is a soft d)',
      forms: { definite: 'lördagen', plural: 'lördagar', pluralDefinite: 'lördagarna' },
    },
    {
      id: 'sondag',
      sv: 'söndag',
      en: 'Sunday',
      pos: 'noun',
      gender: 'en',
      pron: 'SÖN-dah',
      forms: { definite: 'söndagen', plural: 'söndagar', pluralDefinite: 'söndagarna' },
    },
    {
      id: 'vecka',
      sv: 'vecka',
      en: 'week',
      pos: 'noun',
      gender: 'en',
      pron: 'VECK-ah',
      forms: { definite: 'veckan', plural: 'veckor', pluralDefinite: 'veckorna' },
    },
    {
      id: 'idag',
      sv: 'idag',
      en: 'today',
      pos: 'adverb',
      pron: 'ee-DAHG',
      alt: ['i dag'],
    },
    {
      id: 'imorgon',
      sv: 'imorgon',
      en: 'tomorrow',
      pos: 'adverb',
      pron: 'ee-MOR-on',
      note: 'Often said "imorron".',
      alt: ['i morgon'],
    },
    {
      id: 'igar',
      sv: 'igår',
      en: 'yesterday',
      pos: 'adverb',
      pron: 'ee-GOHR',
      alt: ['i går'],
    },
    {
      id: 'helg',
      sv: 'helg',
      en: 'weekend',
      pos: 'noun',
      gender: 'en',
      pron: 'HEL-y (lg sounds like "ly")',
      note: 'i helgen = this weekend. Trevlig helg! = Have a nice weekend!',
      forms: { definite: 'helgen', plural: 'helger', pluralDefinite: 'helgerna' },
    },
  ],
  dialogue: {
    title: 'Friday, then?',
    setting: 'Maja calls her friend Hassan to plan a fika.',
    lines: [
      {
        speaker: 'Maja',
        sv: 'Hej Hassan! Ska vi fika på torsdag?',
        en: 'Hi Hassan! Shall we meet for a coffee on Thursday?',
      },
      {
        speaker: 'Hassan',
        sv: 'På torsdag? Nej, tyvärr. Men fredag är bra!',
        en: 'On Thursday? Sorry, I can’t. But Friday is good!',
      },
      { speaker: 'Maja', sv: 'Okej, på fredag! Klockan tre?', en: 'Okay, on Friday! At three?' },
      { speaker: 'Hassan', sv: 'Hmm, halv fyra är bättre.', en: 'Hmm, half past three is better.' },
      {
        speaker: 'Maja',
        sv: 'Halv fyra på fredag. Jättebra!',
        en: 'Half past three on Friday. Great!',
      },
      { speaker: 'Hassan', sv: 'Vi ses på fredag!', en: 'See you on Friday!' },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Idag är det måndag. Imorgon är det ___.',
      en: "Today it's Monday. Tomorrow it's Tuesday.",
      choices: ['tisdag', 'söndag', 'onsdag'],
      answer: 'tisdag',
      explanation: 'The day after måndag is tisdag.',
      vocab: ['mandag', 'tisdag', 'imorgon'],
    },
    {
      type: 'mcq',
      prompt: 'Idag är det onsdag.',
      promptLang: 'sv',
      question: 'So which day is it tomorrow?',
      choices: ['torsdag', 'tisdag', 'fredag'],
      answer: 'torsdag',
      explanation: 'onsdag (Wednesday) is followed by torsdag (Thursday).',
      vocab: ['onsdag', 'torsdag', 'idag'],
    },
    {
      type: 'listen',
      audio: 'torsdag',
      question: 'Which day did you hear?',
      choices: ['Thursday', 'Tuesday', 'Saturday'],
      answer: 'Thursday',
      explanation: 'torsdag has the "sh" sound (rs). tisdag (Tuesday) starts with "tees".',
      vocab: ['torsdag'],
    },
    {
      type: 'listen',
      audio: 'Vi ses på söndag!',
      choices: ['See you on Sunday!', 'See you on Saturday!', 'See you today!'],
      answer: 'See you on Sunday!',
      explanation: 'söndag is Sunday. Saturday is lördag.',
      vocab: ['sondag'],
    },
    {
      type: 'mcq',
      prompt: 'på måndagar',
      promptLang: 'sv',
      question: 'What does this mean?',
      choices: ['on Mondays (every week)', 'this Monday', 'last Monday'],
      answer: 'on Mondays (every week)',
      explanation: 'The plural -ar means every week. "This Monday" is på måndag.',
      vocab: ['mandag'],
    },
    {
      type: 'build',
      prompt: "Today it's Friday.",
      answer: 'Idag är det fredag.',
      accept: ['Det är fredag idag.'],
      distractors: ['fredagar'],
      explanation: 'The verb comes second: Idag är det fredag, not "Idag det är fredag".',
      vocab: ['idag', 'fredag'],
    },
    {
      type: 'build',
      prompt: 'See you on Saturday!',
      answer: 'Vi ses på lördag!',
      distractors: ['lördagar', 'i'],
      explanation: 'på lördag = this coming Saturday. På lördagar would mean every Saturday.',
      vocab: ['lordag'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Elin', sv: 'Vilken dag är det idag?', en: 'What day is it today?' }],
      question: 'It is Sunday. What do you answer?',
      choices: ['Idag är det söndag.', 'Idag det är söndag.', 'Igår var det söndag.'],
      answer: 'Idag är det söndag.',
      explanation:
        'Verb second: Idag är det söndag. "Igår var det söndag" means it was Sunday yesterday.',
      vocab: ['idag', 'sondag'],
    },
    {
      type: 'dictation',
      audio: 'Imorgon är det lördag.',
      en: "Tomorrow it's Saturday.",
      accept: ['I morgon är det lördag.'],
      vocab: ['imorgon', 'lordag'],
    },
    {
      type: 'speak',
      text: 'Idag är det fredag, och imorgon är det lördag!',
      en: "Today it's Friday, and tomorrow it's Saturday!",
      vocab: ['idag', 'fredag', 'imorgon', 'lordag'],
    },
  ],
})
