import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u03-l04',
  learn: [
    {
      title: 'Klockan är …',
      text: 'To ask the time, say **[[Vad är klockan?]]** (literally "What is the clock?"). The answer starts with **Klockan är** + the hour: [[Klockan är tre.]] (It\'s three o\'clock.)\n\nFor minutes, use **över** (past) and **i** (to), just like in English. A quarter is **kvart**.',
      table: {
        headers: ['Time', 'Swedish', 'Literally'],
        rows: [
          ['3:00', 'Klockan är tre.', 'the clock is three'],
          ['3:05', 'fem över tre', 'five past three'],
          ['3:10', 'tio över tre', 'ten past three'],
          ['3:15', 'kvart över tre', 'quarter past three'],
          ['3:20', 'tjugo över tre', 'twenty past three'],
          ['3:40', 'tjugo i fyra', 'twenty to four'],
          ['3:45', 'kvart i fyra', 'quarter to four'],
          ['3:50', 'tio i fyra', 'ten to four'],
        ],
        svColumns: [1],
      },
      tip: 'In casual speech you may hear [[Hon är tre]] (literally "she is three"): some Swedes call the clock *hon*. You can always say *klockan*.',
    },
    {
      title: 'Halv tre is 2:30!',
      text: 'This is the classic trap. **Halv** means half, but Swedes count **half way to the next hour**. So [[halv fyra]] is 3:30, not 4:30. Think "half (way to) four".\n\nAround the half hour, Swedes often count from **halv**: [[fem i halv fyra]] is 3:25 and [[fem över halv fyra]] is 3:35.',
      table: {
        headers: ['Time', 'Swedish', 'Literally'],
        rows: [
          ['2:30', 'halv tre', 'half (to) three'],
          ['3:25', 'fem i halv fyra', 'five to half four'],
          ['3:30', 'halv fyra', 'half (to) four'],
          ['3:35', 'fem över halv fyra', 'five past half four'],
          ['7:30', 'halv åtta', 'half (to) eight'],
        ],
        svColumns: [1],
      },
      tip: 'Whenever you hear "halv", take one hour off: halv nio = 8:30.',
    },
    {
      title: 'Early, late, now',
      text: "In everyday speech Swedes mostly use the 12-hour clock, but timetables and signs use the 24-hour clock, often with a dot: **15.30**. In speech that is still [[halv fyra]].\n\nA few handy words: [[nu]] (now), [[Jag är sen!]] (I'm late!), [[Det är tidigt.]] (It's early.)",
      examples: [
        { sv: 'Vad är klockan nu?', en: 'What time is it now?' },
        { sv: 'Åh nej, jag är sen!', en: "Oh no, I'm late!" },
        { sv: 'Bussen kommer om fem minuter.', en: 'The bus is coming in five minutes.' },
        { sv: 'en timme och en kvart', en: 'an hour and a quarter' },
      ],
    },
  ],
  vocab: [
    {
      id: 'klocka',
      sv: 'klocka',
      en: 'clock / watch',
      pos: 'noun',
      gender: 'en',
      pron: 'KLOCK-ah',
      note: 'Klockan är tre = It’s three o’clock. Klockan tre = at three o’clock.',
      forms: { definite: 'klockan', plural: 'klockor', pluralDefinite: 'klockorna' },
      enAlt: ['clock', 'watch'],
    },
    {
      id: 'vad-ar-klockan-u3',
      sv: 'Vad är klockan?',
      en: 'What time is it?',
      pos: 'phrase',
      pron: 'vah air KLOCK-an (the d is usually silent)',
    },
    {
      id: 'halv',
      sv: 'halv',
      en: 'half',
      pos: 'adjective',
      note: 'halv fyra = 3:30 (half way to four).',
      forms: { neuter: 'halvt', plural: 'halva' },
    },
    {
      id: 'kvart',
      sv: 'kvart',
      en: 'quarter of an hour',
      pos: 'noun',
      gender: 'en',
      pron: 'kvart (rt sounds like a soft t)',
      note: 'kvart över tre = 3:15, kvart i fyra = 3:45.',
      forms: { definite: 'kvarten', plural: 'kvartar', pluralDefinite: 'kvartarna' },
      enAlt: ['quarter', 'a quarter of an hour', 'quarter of an hour'],
    },
    {
      id: 'over',
      sv: 'över',
      en: 'past / over',
      pos: 'preposition',
      pron: 'ÖÖ-ver',
      note: 'fem över tre = five past three.',
      enAlt: ['past', 'over'],
    },
    {
      id: 'minut',
      sv: 'minut',
      en: 'minute',
      pos: 'noun',
      gender: 'en',
      pron: 'mi-NOOT',
      forms: { definite: 'minuten', plural: 'minuter', pluralDefinite: 'minuterna' },
    },
    {
      id: 'timme',
      sv: 'timme',
      en: 'hour',
      pos: 'noun',
      gender: 'en',
      pron: 'TIM-meh',
      forms: { definite: 'timmen', plural: 'timmar', pluralDefinite: 'timmarna' },
    },
    { id: 'nu', sv: 'nu', en: 'now', pos: 'adverb', pron: 'noo, lips rounded' },
    {
      id: 'sen',
      sv: 'sen',
      en: 'late',
      pos: 'adjective',
      pron: 'sehn',
      note: 'Jag är sen = I’m late. Det är sent = It’s late. In speech, sen also means "then / later".',
      forms: { neuter: 'sent', plural: 'sena' },
    },
    {
      id: 'tidig',
      sv: 'tidig',
      en: 'early',
      pos: 'adjective',
      pron: 'TEE-dig',
      note: 'Det är tidigt = It’s early.',
      forms: { neuter: 'tidigt', plural: 'tidiga' },
    },
  ],
  dialogue: {
    title: 'At the bus stop',
    setting: 'Ali is waiting for the bus. He asks Linnea for the time.',
    lines: [
      { speaker: 'Ali', sv: 'Ursäkta, vad är klockan?', en: 'Excuse me, what time is it?' },
      { speaker: 'Linnea', sv: 'Klockan är kvart över åtta.', en: "It's quarter past eight." },
      {
        speaker: 'Ali',
        sv: 'Kvart över åtta? Åh nej, jag är sen!',
        en: "Quarter past eight? Oh no, I'm late!",
      },
      {
        speaker: 'Linnea',
        sv: 'Men bussen kommer om fem minuter.',
        en: 'But the bus is coming in five minutes.',
      },
      { speaker: 'Ali', sv: 'Fem minuter? Vad bra. Tack!', en: 'Five minutes? Great. Thanks!' },
      { speaker: 'Linnea', sv: 'Ingen orsak!', en: "You're welcome!" },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: 'halv tre',
      promptLang: 'sv',
      question: 'What time is it?',
      choices: ['2:30', '3:30', '3:00'],
      answer: '2:30',
      explanation: 'Halv tre is half way TO three, so 2:30. Always take one hour off.',
      vocab: ['halv'],
    },
    {
      type: 'mcq',
      prompt: 'kvart i fyra',
      promptLang: 'sv',
      question: 'What time is it?',
      choices: ['3:45', '4:15', '4:45'],
      answer: '3:45',
      explanation: 'i means "to": a quarter to four is 3:45.',
      vocab: ['kvart'],
    },
    {
      type: 'mcq',
      prompt: '5:15',
      promptLang: 'en',
      question: 'How do you say this time in Swedish?',
      choices: ['kvart över fem', 'kvart i fem', 'halv fem'],
      answer: 'kvart över fem',
      explanation: 'över means "past": a quarter past five.',
      vocab: ['kvart', 'over', 'fem'],
    },
    {
      type: 'listen',
      audio: 'Klockan är halv sju.',
      question: 'What time is it?',
      choices: ['6:30', '7:30', '7:00'],
      answer: '6:30',
      explanation: 'Halv sju is half way to seven: 6:30.',
      vocab: ['klocka', 'halv'],
    },
    {
      type: 'gap',
      text: 'Klockan är tjugo ___ tio.',
      en: "It's twenty to ten (9:40).",
      choices: ['i', 'över', 'halv'],
      answer: 'i',
      explanation: 'Before the hour you use i (to): tjugo i tio = 9:40.',
      vocab: ['klocka'],
    },
    {
      type: 'type',
      prompt: '10:30',
      promptLang: 'en',
      question: 'Write the time in Swedish (two words)',
      answer: 'halv elva',
      accept: ['klockan är halv elva'],
      reject: ['halv tio'],
      explanation: '10:30 is half way to eleven: halv elva.',
      vocab: ['halv', 'elva'],
    },
    {
      type: 'build',
      prompt: 'Excuse me, what time is it?',
      answer: 'Ursäkta, vad är klockan?',
      distractors: ['hur', 'nu'],
      explanation: 'Vad är klockan? literally means "What is the clock?"',
      vocab: ['vad-ar-klockan-u3'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Ali', sv: 'Vad är klockan?', en: 'What time is it?' }],
      question: 'Your watch shows 7:30. What do you say?',
      choices: ['Klockan är halv åtta.', 'Klockan är halv sju.', 'Klockan är kvart över sju.'],
      answer: 'Klockan är halv åtta.',
      explanation: '7:30 is half way to eight: halv åtta.',
      vocab: ['halv', 'atta'],
    },
    {
      type: 'dictation',
      audio: 'Klockan är fem i nio.',
      en: "It's five to nine.",
      vocab: ['klocka', 'fem', 'nio'],
    },
    {
      type: 'speak',
      text: 'Vad är klockan? Klockan är kvart över tre.',
      en: "What time is it? It's quarter past three.",
      vocab: ['vad-ar-klockan-u3', 'kvart', 'over'],
    },
  ],
})
