import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u03-l06',
  learn: [
    {
      title: 'Twelve months',
      text: 'The months look a lot like English, but they are written with a **small letter**: [[januari]], not "Januari".\n\nUse **i** for "in": [[i maj]] (in May). To say when your birthday is, use [[Jag fyller år i maj.]] (literally "I fill years in May").',
      table: {
        headers: ['Swedish', 'English', 'Sounds roughly like'],
        rows: [
          ['januari', 'January', 'yah-noo-AH-ri'],
          ['februari', 'February', 'feb-roo-AH-ri'],
          ['mars', 'March', 'marsh'],
          ['april', 'April', 'ah-PRILL'],
          ['maj', 'May', 'my'],
          ['juni', 'June', 'YOO-ni'],
          ['juli', 'July', 'YOO-li'],
          ['augusti', 'August', 'ow-GUS-ti'],
          ['september', 'September', 'sep-TEM-ber'],
          ['oktober', 'October', 'ok-TOO-ber'],
          ['november', 'November', 'no-VEM-ber'],
          ['december', 'December', 'deh-SEM-ber'],
        ],
        svColumns: [0],
      },
      tip: 'Listen carefully to [[juni]] and [[juli]]: only one letter is different!',
    },
    {
      title: 'Dates: den första maj',
      text: 'For dates, Swedish uses **den** + an ordinal number ("first", "second" …) + the month: [[den första maj]] (the first of May). You don\'t need to learn all the ordinals yet, but here are the most useful ones.',
      table: {
        headers: ['', 'Ordinal', 'In a date'],
        rows: [
          ['1st', 'första', 'den första maj'],
          ['2nd', 'andra', 'den andra juni'],
          ['3rd', 'tredje', 'den tredje juli'],
          ['4th', 'fjärde', 'den fjärde april'],
          ['5th', 'femte', 'den femte mars'],
          ['6th', 'sjätte', 'den sjätte juni'],
          ['10th', 'tionde', 'den tionde maj'],
          ['12th', 'tolfte', 'den tolfte april'],
          ['20th', 'tjugonde', 'den tjugonde januari'],
          ['24th', 'tjugofjärde', 'den tjugofjärde december'],
          ['31st', 'trettioförsta', 'den trettioförsta oktober'],
        ],
        svColumns: [1, 2],
      },
    },
    {
      title: 'What is the date today?',
      text: 'Ask [[Vilket datum är det idag?]] and answer [[Idag är det den tredje oktober.]]\n\nIn writing, Swedes put the **day first**: 3/10 means 3 October, not 10 March. Official dates are often written year first: 2026-10-03.',
      examples: [
        { sv: 'Vilket datum är det idag?', en: "What's the date today?" },
        { sv: 'Det är den tredje oktober.', en: "It's the third of October." },
        { sv: 'När fyller du år?', en: 'When is your birthday?' },
        { sv: 'Jag fyller år den sjätte juni.', en: 'My birthday is on the sixth of June.' },
      ],
      tip: 'Sweden’s National Day is [[den sjätte juni]] (6 June).',
    },
  ],
  culture: {
    title: 'Midsommar',
    text: 'After the long, dark winter, **midsommar** is the big summer party. [[Midsommarafton]] (Midsummer Eve) is always a **Friday between 19 and 25 June**, and almost everyone has the day off.\n\nPeople head out to the countryside, pick flowers and make flower wreaths ([[blomsterkrans]]) to wear in their hair. Together they raise a maypole ([[midsommarstång]]) covered in leaves and flowers, and dance around it singing [[Små grodorna]] ("The little frogs"), hopping like frogs. Yes, the grown-ups too!\n\nThe food: pickled herring ([[sill]]), new potatoes ([[färskpotatis]]) with dill, and strawberries ([[jordgubbar]]) with cream. And it hardly gets dark at all: in the far north the sun doesn\'t set, and even in Stockholm the night is just a blue twilight.',
    examples: [
      { sv: 'Glad midsommar!', en: 'Happy Midsummer!' },
      { sv: 'sill och färskpotatis', en: 'herring and new potatoes' },
      { sv: 'jordgubbar och grädde', en: 'strawberries and cream' },
    ],
    tip: 'An old tradition: on midsummer night, pick **seven** ([[sju]]) different kinds of flowers and put them under your pillow. Then you will dream of your future love.',
  },
  vocab: [
    { id: 'januari', sv: 'januari', en: 'January', pos: 'other', pron: 'yah-noo-AH-ri' },
    { id: 'februari', sv: 'februari', en: 'February', pos: 'other', pron: 'feb-roo-AH-ri' },
    { id: 'mars', sv: 'mars', en: 'March', pos: 'other', pron: 'marsh (rs = sh)' },
    { id: 'april', sv: 'april', en: 'April', pos: 'other', pron: 'ah-PRILL' },
    { id: 'maj', sv: 'maj', en: 'May', pos: 'other', pron: 'my' },
    {
      id: 'juni',
      sv: 'juni',
      en: 'June',
      pos: 'other',
      pron: 'YOO-ni',
      note: 'Don’t mix it up with juli (July).',
    },
    {
      id: 'juli',
      sv: 'juli',
      en: 'July',
      pos: 'other',
      pron: 'YOO-li',
      note: 'Don’t mix it up with juni (June).',
    },
    { id: 'augusti', sv: 'augusti', en: 'August', pos: 'other', pron: 'ow-GUS-ti' },
    { id: 'september', sv: 'september', en: 'September', pos: 'other', pron: 'sep-TEM-ber' },
    { id: 'oktober', sv: 'oktober', en: 'October', pos: 'other', pron: 'ok-TOO-ber' },
    { id: 'november', sv: 'november', en: 'November', pos: 'other', pron: 'no-VEM-ber' },
    { id: 'december', sv: 'december', en: 'December', pos: 'other', pron: 'deh-SEM-ber' },
  ],
  dialogue: {
    title: 'A birthday',
    setting: 'Ella and Viktor are having lunch at work.',
    lines: [
      { speaker: 'Ella', sv: 'Vilket datum är det idag?', en: "What's the date today?" },
      { speaker: 'Viktor', sv: 'Det är den tionde maj.', en: "It's the tenth of May." },
      {
        speaker: 'Ella',
        sv: 'Den tionde? Åh nej! Mamma fyller år idag!',
        en: "The tenth? Oh no! It's Mum's birthday today!",
      },
      { speaker: 'Viktor', sv: 'Hur gammal blir hon?', en: 'How old is she turning?' },
      { speaker: 'Ella', sv: 'Hon fyller sextio!', en: "She's turning sixty!" },
      { speaker: 'Viktor', sv: 'Sextio! Grattis till henne!', en: 'Sixty! Happy birthday to her!' },
      {
        speaker: 'Ella',
        sv: 'Tack! Och när fyller du år?',
        en: 'Thanks! And when is your birthday?',
      },
      {
        speaker: 'Viktor',
        sv: 'I december. Den andra december.',
        en: 'In December. The second of December.',
      },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: 'den första maj',
      promptLang: 'sv',
      question: 'Which date is this?',
      choices: ['1 May', '5 May', '1 March'],
      answer: '1 May',
      explanation: 'första means "first", and maj is May. Mars is March.',
      vocab: ['maj'],
    },
    {
      type: 'listen',
      audio: 'den tredje oktober',
      question: 'Which date did you hear?',
      choices: ['3 October', '13 October', '3 August'],
      answer: '3 October',
      explanation: 'tredje means "third". 13th would be trettonde.',
      vocab: ['oktober'],
    },
    {
      type: 'listen',
      audio: 'Jag fyller år i mars.',
      choices: ['My birthday is in March.', 'My birthday is in May.', 'My birthday is on Monday.'],
      answer: 'My birthday is in March.',
      explanation: 'mars (March) ends in an "sh" sound: "marsh". May is maj.',
      vocab: ['mars'],
    },
    {
      type: 'gap',
      text: 'Jag fyller år ___ juli.',
      en: 'My birthday is in July.',
      choices: ['i', 'på', 'den'],
      answer: 'i',
      explanation: 'Use i with months: i juli (in July). På goes with days: på fredag.',
      vocab: ['juli'],
    },
    {
      type: 'build',
      prompt: "Today it's the first of June.",
      answer: 'Idag är det den första juni.',
      distractors: ['ett', 'juli'],
      explanation: 'Dates use ordinals: den första (the first), not "ett".',
      vocab: ['idag', 'juni'],
    },
    {
      type: 'type',
      prompt: '1 May',
      promptLang: 'en',
      question: 'Write the date in Swedish, starting with "den"',
      answer: 'den första maj',
      accept: ['första maj'],
      explanation: 'den + första (first) + maj. Första maj is also a public holiday in Sweden.',
      vocab: ['maj'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Viktor', sv: 'När fyller du år?', en: 'When is your birthday?' }],
      question: 'Your birthday is on 12 April. What do you say?',
      choices: ['Den tolfte april.', 'Klockan tolv.', 'Jag är tolv år.'],
      answer: 'Den tolfte april.',
      explanation: 'Den tolfte april = the twelfth of April. "Jag är tolv år" would tell your age.',
      vocab: ['april'],
    },
    {
      type: 'dictation',
      audio: 'Vilket datum är det idag?',
      en: "What's the date today?",
      accept: ['Vilket datum är det i dag?'],
      vocab: ['idag'],
    },
    {
      type: 'mcq',
      prompt: 'midsommarafton',
      promptLang: 'sv',
      question: 'When is it?',
      choices: ['a Friday in late June', '24 December', '1 May'],
      answer: 'a Friday in late June',
      explanation: 'Midsommarafton is always the Friday between 19 and 25 June.',
      vocab: ['juni'],
    },
    {
      type: 'speak',
      text: 'Jag fyller år den femte augusti.',
      en: 'My birthday is on the fifth of August.',
      vocab: ['augusti'],
    },
  ],
})
