import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u01-l01',
  learn: [
    {
      title: '29 letters',
      text: 'Swedish uses the same 26 letters as English, plus three extra vowels: **å**, **ä** and **ö**.\n\nThey are letters in their own right (not "a with a ring") and they come last in the alphabet: … x, y, z, **å, ä, ö**. Tap any Swedish word to hear it.',
      table: {
        headers: ['Letter', 'Sounds roughly like', 'Example', 'Meaning'],
        rows: [
          ['å', 'the "o" in "more"', 'båt', 'boat'],
          ['ä', 'the "e" in "bed" or "air"', 'äpple', 'apple'],
          ['ö', 'the "u" in "fur", lips rounded', 'ö', 'island'],
        ],
        svColumns: [2],
      },
    },
    {
      title: 'Nine vowels',
      text: 'Swedish has nine vowels: **a, e, i, o, u, y, å, ä, ö**. Two of them surprise English speakers:\n\n**o** often sounds like English "oo": [[bok]] (book) sounds like "boohk".\n**u** and **y** have no English match. For **y**, say "ee" while rounding your lips as if to whistle: [[ny]] (new).',
      tip: "Don't worry about being perfect. Listen, copy, and use the 🐢 button to hear words slowly.",
    },
    {
      title: 'Consonants mostly behave',
      text: 'Most consonants sound as in English. The big exception for now: **j** sounds like English "y". So [[ja]] (yes) sounds like "yah" and [[nej]] (no) like "nay".',
      examples: [
        { sv: 'Hej!', en: 'Hi! / Hello!' },
        { sv: 'Ja, tack!', en: 'Yes, please!' },
        { sv: 'Nej, tack.', en: 'No, thank you.' },
      ],
    },
  ],
  vocab: [
    {
      id: 'hej',
      sv: 'hej',
      en: 'hi / hello',
      pos: 'interjection',
      pron: 'hey',
      enAlt: ['hi', 'hello'],
    },
    { id: 'ja', sv: 'ja', en: 'yes', pos: 'interjection', pron: 'yah' },
    { id: 'nej', sv: 'nej', en: 'no', pos: 'interjection', pron: 'nay' },
    {
      id: 'tack',
      sv: 'tack',
      en: 'thanks / please',
      pos: 'interjection',
      pron: 'tahck (short a)',
      note: '"Ja, tack" means "yes, please".',
      enAlt: ['thanks', 'thank you', 'please'],
    },
    {
      id: 'varsagod',
      sv: 'varsågod',
      en: 'here you go / you’re welcome',
      pos: 'phrase',
      pron: 'VAR-sho-goo',
      note: 'Said when you hand something over or offer something.',
    },
    { id: 'bra', sv: 'bra', en: 'good / fine', pos: 'adjective', pron: 'brah' },
    {
      id: 'ar',
      sv: 'är',
      en: 'am / is / are',
      pos: 'verb',
      pron: 'air',
      note: 'The same form for everyone: jag är, du är, hon är.',
    },
    { id: 'tva', sv: 'två', en: 'two', pos: 'numeral', pron: 'tvoh' },
    {
      id: 'bat',
      sv: 'båt',
      en: 'boat',
      pos: 'noun',
      gender: 'en',
      pron: 'boht (long å, as in "more")',
      forms: { definite: 'båten', plural: 'båtar', pluralDefinite: 'båtarna' },
    },
    {
      id: 'apple',
      sv: 'äpple',
      en: 'apple',
      pos: 'noun',
      gender: 'ett',
      pron: 'EP-leh',
      forms: { definite: 'äpplet', plural: 'äpplen', pluralDefinite: 'äpplena' },
    },
    {
      id: 'o-island',
      sv: 'ö',
      en: 'island',
      pos: 'noun',
      gender: 'en',
      pron: 'uh, with rounded lips',
      forms: { definite: 'ön', plural: 'öar', pluralDefinite: 'öarna' },
    },
  ],
  dialogue: {
    title: 'An apple?',
    setting: 'Anna is having fika. Erik offers her something.',
    lines: [
      { speaker: 'Erik', sv: 'Hej!', en: 'Hi!' },
      { speaker: 'Anna', sv: 'Hej!', en: 'Hi!' },
      { speaker: 'Erik', sv: 'Ett äpple?', en: 'An apple?' },
      { speaker: 'Anna', sv: 'Ja, tack!', en: 'Yes, please!' },
      { speaker: 'Erik', sv: 'Varsågod!', en: 'Here you go!' },
      { speaker: 'Anna', sv: 'Tack!', en: 'Thanks!' },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: '… x, y, z, ?',
      promptLang: 'en',
      question: 'Which letters end the Swedish alphabet?',
      choices: ['å, ä, ö', 'ä, ö, å', 'ö, ä, å'],
      answer: 'å, ä, ö',
      explanation: 'The three extra letters come after z, in the order å, ä, ö.',
    },
    {
      type: 'minimalPair',
      focus: 'Listen for the vowel: å or ä?',
      options: [
        { sv: 'år', en: 'year' },
        { sv: 'är', en: 'am / is / are' },
      ],
      answer: 'är',
      explanation: 'år has the å-sound (as in "more"); är has the ä-sound (as in "air").',
    },
    {
      type: 'minimalPair',
      focus: 'Listen for the vowel: o or ö?',
      options: [
        { sv: 'not', en: 'note (music)' },
        { sv: 'nöt', en: 'nut' },
      ],
      answer: 'nöt',
      explanation:
        'o in not sounds like "oo"; ö in nöt is made with rounded lips, a bit like the "u" in "fur".',
    },
    {
      type: 'listen',
      audio: 'Ja, tack!',
      choices: ['Yes, please!', 'No, thanks.', 'Hi!'],
      answer: 'Yes, please!',
      vocab: ['ja', 'tack'],
    },
    {
      type: 'listen',
      audio: 'Nej, tack.',
      choices: ['No, thank you.', 'Yes, please!', 'Here you go!'],
      answer: 'No, thank you.',
      vocab: ['nej', 'tack'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Erik', sv: 'Ett äpple?', en: 'An apple?' }],
      question: 'You would like the apple. What do you say?',
      choices: ['Ja, tack!', 'Varsågod!', 'En ö.'],
      answer: 'Ja, tack!',
      explanation:
        '"Ja, tack" means "yes, please". Varsågod is what Erik says when he hands it to you.',
    },
    {
      type: 'type',
      prompt: 'thanks',
      promptLang: 'en',
      answer: 'tack',
      vocab: ['tack'],
    },
    {
      type: 'speak',
      text: 'Hej! Ja, tack!',
      en: 'Hi! Yes, please!',
      vocab: ['hej', 'ja', 'tack'],
    },
  ],
})
