import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u01-l02',
  learn: [
    {
      title: 'Long or short?',
      text: 'Every stressed Swedish vowel is either **long** or **short**, and it can change the meaning of a word.\n\nThe rule of thumb is all in the spelling:\n**One consonant (or none) after the vowel → long.** [[tak]], [[glas]], [[bra]]\n**Two consonants after the vowel → short.** [[tack]], [[glass]], [[villa]]',
      table: {
        headers: ['Long vowel', 'Meaning', 'Short vowel', 'Meaning'],
        rows: [
          ['tak', 'roof', 'tack', 'thanks'],
          ['glas', 'glass (to drink from)', 'glass', 'ice cream'],
          ['vila', 'to rest', 'villa', 'house'],
          ['mat', 'food', 'matt', 'matte, weak'],
        ],
        svColumns: [0, 2],
      },
    },
    {
      title: 'Really stretch it',
      text: 'Long vowels in Swedish are *really* long, almost twice as long as short ones. Short vowels are quick and crisp, and the consonant after them gets a little longer instead.\n\nListen to [[glas]] and then [[glass]]. Mix them up and you might get a glass when you wanted an ice cream!',
      tip: 'In Swedish you don’t say "of" in amounts: [[ett glas vatten]] is "a glass of water", word for word "a glass water".',
    },
  ],
  vocab: [
    {
      id: 'tak',
      sv: 'tak',
      en: 'roof / ceiling',
      pos: 'noun',
      gender: 'ett',
      pron: 'tahk (long a)',
      forms: { definite: 'taket', plural: 'tak', pluralDefinite: 'taken' },
    },
    {
      id: 'glas',
      sv: 'glas',
      en: 'glass (to drink from)',
      pos: 'noun',
      gender: 'ett',
      pron: 'glahs (long a)',
      forms: { definite: 'glaset', plural: 'glas', pluralDefinite: 'glasen' },
    },
    {
      id: 'glass',
      sv: 'glass',
      en: 'ice cream',
      pos: 'noun',
      gender: 'en',
      pron: 'glass, with a quick, short a as in "cat"',
      forms: { definite: 'glassen', plural: 'glassar', pluralDefinite: 'glassarna' },
    },
    {
      id: 'mat',
      sv: 'mat',
      en: 'food',
      pos: 'noun',
      gender: 'en',
      pron: 'maht (long a)',
      forms: { definite: 'maten' },
    },
    {
      id: 'hatt',
      sv: 'hatt',
      en: 'hat',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'hatten', plural: 'hattar', pluralDefinite: 'hattarna' },
    },
    {
      id: 'villa',
      sv: 'villa',
      en: 'house (detached)',
      pos: 'noun',
      gender: 'en',
      note: 'A detached family house, not necessarily a fancy one.',
      forms: { definite: 'villan', plural: 'villor', pluralDefinite: 'villorna' },
    },
    {
      id: 'full',
      sv: 'full',
      en: 'full',
      pos: 'adjective',
      forms: { neuter: 'fullt', plural: 'fulla' },
    },
    {
      id: 'vila',
      sv: 'vila',
      en: 'to rest',
      pos: 'verb',
      pron: 'VEE-la (long i)',
      forms: { present: 'vilar', past: 'vilade', supine: 'vilat', imperative: 'vila' },
    },
    {
      id: 'vatten',
      sv: 'vatten',
      en: 'water',
      pos: 'noun',
      gender: 'ett',
      pron: 'VAT-ten (short a)',
      forms: { definite: 'vattnet' },
    },
    {
      id: 'och',
      sv: 'och',
      en: 'and',
      pos: 'conjunction',
      pron: 'ock, often just "o"',
      note: 'In everyday speech och usually sounds like a short "o".',
    },
  ],
  dialogue: {
    title: 'At the kiosk',
    setting: 'Sara buys something at a kiosk on a hot day.',
    lines: [
      { speaker: 'Sara', sv: 'Hej! En glass, tack.', en: 'Hi! An ice cream, please.' },
      { speaker: 'Ali', sv: 'Varsågod!', en: 'Here you go!' },
      {
        speaker: 'Sara',
        sv: 'Tack! Och ett glas vatten, tack.',
        en: 'Thanks! And a glass of water, please.',
      },
      { speaker: 'Ali', sv: 'Ett glas vatten. Varsågod!', en: 'A glass of water. Here you go!' },
      { speaker: 'Sara', sv: 'Tack!', en: 'Thanks!' },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: 'tack, glass, villa',
      promptLang: 'sv',
      question: 'Are the vowels in these words long or short?',
      choices: ['Short', 'Long'],
      answer: 'Short',
      explanation: 'Each vowel is followed by a double consonant (ck, ss, ll), so it is short.',
    },
    {
      type: 'minimalPair',
      focus: 'Long or short a?',
      options: [
        { sv: 'glas', en: 'glass (to drink from)' },
        { sv: 'glass', en: 'ice cream' },
      ],
      answer: 'glass',
      explanation: 'glass has a short a (double s). glas has a long, stretched a.',
      vocab: ['glas', 'glass'],
    },
    {
      type: 'minimalPair',
      focus: 'Long or short a?',
      options: [
        { sv: 'tak', en: 'roof' },
        { sv: 'tack', en: 'thanks' },
      ],
      answer: 'tak',
      explanation: 'tak has one consonant after the a, so the a is long.',
      vocab: ['tak', 'tack'],
    },
    {
      type: 'minimalPair',
      focus: 'Long or short i?',
      options: [
        { sv: 'vila', en: 'to rest' },
        { sv: 'villa', en: 'house' },
      ],
      answer: 'villa',
      explanation: 'villa has a double l, so the i is short and quick.',
      vocab: ['vila', 'villa'],
    },
    {
      type: 'minimalPair',
      focus: 'Long or short a?',
      options: [
        { sv: 'mat', en: 'food' },
        { sv: 'matt', en: 'matte, weak' },
      ],
      answer: 'mat',
      explanation: 'mat (food) has a long a. matt (matte, weak) has a short a.',
      vocab: ['mat'],
    },
    {
      type: 'listen',
      audio: 'Ett glas vatten, tack.',
      choices: ['A glass of water, please.', 'An ice cream, please.', 'Water and food, thanks.'],
      answer: 'A glass of water, please.',
      vocab: ['glas', 'vatten'],
    },
    {
      type: 'gap',
      text: 'Ett ___ vatten, tack.',
      en: 'A glass of water, please.',
      choices: ['glas', 'glass'],
      answer: 'glas',
      explanation: 'glas (long a) is a glass you drink from. glass (short a) is ice cream.',
      vocab: ['glas'],
    },
    {
      type: 'build',
      prompt: 'An ice cream and a glass of water, please.',
      answer: 'En glass och ett glas vatten, tack.',
      distractors: ['mat', 'full'],
      explanation: 'No "of" is needed: ett glas vatten = a glass of water.',
    },
    {
      type: 'dictation',
      audio: 'En glass, tack.',
      en: 'An ice cream, please.',
    },
    {
      type: 'speak',
      text: 'Ett glas vatten, tack.',
      en: 'A glass of water, please.',
    },
  ],
})
