import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u01-l04',
  learn: [
    {
      title: 'Hard and soft k and g',
      text: 'Before the "hard" vowels **a, o, u, å**, the letters k and g sound as in English: [[kaffe]], [[kul]], [[gata]], [[god]].\n\nBefore the "soft" vowels **e, i, y, ä, ö**, they go soft: **k** becomes the tj-sound and **g** becomes a "y" sound: [[köpa]] (SHUH-pa), [[gärna]] (YAIR-na), [[göra]] (YUH-ra).',
      table: {
        headers: ['', 'Hard (before a o u å)', 'Soft (before e i y ä ö)'],
        rows: [
          ['k', 'kaffe', 'köpa'],
          ['g', 'gata', 'gärna'],
        ],
        svColumns: [1, 2],
      },
      tip: 'This only happens at the start of a stressed syllable. In [[pojke]] (boy) the k stays hard.',
    },
    {
      title: 'The rs-sound',
      text: 'When **r** meets **s**, they melt into one "sh" sound: [[först]] (first) sounds like "fösht", and the name Lars sounds like "Lahsh". It happens in the middle of words too: [[varsågod]] sounds like "vashågo".\n\nThe r also melts into t, d and n: your tongue curls back a little and the r disappears. Listen: [[kort]], [[bord]], [[barn]].',
    },
  ],
  vocab: [
    {
      id: 'garna',
      sv: 'gärna',
      en: 'gladly / I’d love to',
      pos: 'adverb',
      pron: 'YAIR-na',
      note: 'Ja, gärna! = Yes, I’d love to! / Yes, please!',
    },
    {
      id: 'gora',
      sv: 'göra',
      en: 'to do / to make',
      pos: 'verb',
      pron: 'YUH-ra',
      forms: { present: 'gör', past: 'gjorde', supine: 'gjort', imperative: 'gör' },
    },
    {
      id: 'gata',
      sv: 'gata',
      en: 'street',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'gatan', plural: 'gator', pluralDefinite: 'gatorna' },
    },
    {
      id: 'god',
      sv: 'god',
      en: 'good, tasty',
      pos: 'adjective',
      pron: 'goohd (long oo)',
      note: 'Mostly used about food and drink: gott kaffe. For "good" in general, use bra.',
      forms: { neuter: 'gott', plural: 'goda' },
    },
    {
      id: 'kaffe',
      sv: 'kaffe',
      en: 'coffee',
      pos: 'noun',
      gender: 'ett',
      note: 'When ordering a cup, people often say "en kaffe".',
      forms: { definite: 'kaffet' },
    },
    {
      id: 'kopa',
      sv: 'köpa',
      en: 'to buy',
      pos: 'verb',
      pron: 'SHUH-pa',
      forms: { present: 'köper', past: 'köpte', supine: 'köpt', imperative: 'köp' },
    },
    {
      id: 'kul',
      sv: 'kul',
      en: 'fun',
      pos: 'adjective',
      note: 'Never changes form. Vad kul! = How nice! / Great!',
    },
    {
      id: 'kort',
      sv: 'kort',
      en: 'card',
      pos: 'noun',
      gender: 'ett',
      note: 'Also an adjective: short.',
      forms: { definite: 'kortet', plural: 'kort', pluralDefinite: 'korten' },
    },
    {
      id: 'bord',
      sv: 'bord',
      en: 'table',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'bordet', plural: 'bord', pluralDefinite: 'borden' },
    },
    {
      id: 'barn',
      sv: 'barn',
      en: 'child',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'barnet', plural: 'barn', pluralDefinite: 'barnen' },
    },
    { id: 'forst', sv: 'först', en: 'first', pos: 'adverb', pron: 'fösht' },
  ],
  dialogue: {
    title: 'Coffee?',
    setting: 'Anna has made coffee for her colleague Erik.',
    lines: [
      { speaker: 'Anna', sv: 'Kaffe?', en: 'Coffee?' },
      { speaker: 'Erik', sv: 'Ja, gärna!', en: 'Yes, I’d love some!' },
      { speaker: 'Anna', sv: 'Varsågod.', en: 'Here you go.' },
      { speaker: 'Erik', sv: 'Tack! Mmm, kaffet är gott!', en: 'Thanks! Mmm, the coffee is good!' },
      { speaker: 'Anna', sv: 'Vad bra!', en: 'Great!' },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: 'gärna',
      promptLang: 'sv',
      question: 'How does the g in gärna sound?',
      choices: ['Like the y in "yes"', 'Like the g in "go"'],
      answer: 'Like the y in "yes"',
      explanation: 'g before ä is soft, so it sounds like a y: YAIR-na.',
      vocab: ['garna'],
    },
    {
      type: 'mcq',
      prompt: 'gata',
      promptLang: 'sv',
      question: 'How does the g in gata sound?',
      choices: ['Like the g in "go"', 'Like the y in "yes"'],
      answer: 'Like the g in "go"',
      explanation: 'g before a is hard, just like in English.',
      vocab: ['gata'],
    },
    {
      type: 'minimalPair',
      focus: 'Hard g or a y-sound?',
      options: [
        { sv: 'gul', en: 'yellow' },
        { sv: 'jul', en: 'Christmas' },
      ],
      answer: 'jul',
      explanation:
        'gul starts with a hard g (g before u). jul starts with a y-sound, because j sounds like y.',
    },
    {
      type: 'minimalPair',
      focus: 'Hard k or soft k?',
      options: [
        { sv: 'ko', en: 'cow' },
        { sv: 'kö', en: 'queue' },
      ],
      answer: 'ko',
      explanation: 'k before o is hard (ko = "koo"). k before ö is soft (kö = "shuh").',
    },
    {
      type: 'mcq',
      prompt: 'först',
      promptLang: 'sv',
      question: 'How do r and s sound together in först?',
      choices: ['Like "sh"', 'Like the "rs" in "horse"', 'Like "z"'],
      answer: 'Like "sh"',
      explanation: 'r + s merge into one "sh" sound: fösht.',
      vocab: ['forst'],
    },
    {
      type: 'listen',
      audio: 'Ja, gärna!',
      choices: ['Yes, I’d love to!', 'No, thank you.', 'Here you go!'],
      answer: 'Yes, I’d love to!',
      vocab: ['ja', 'garna'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Anna', sv: 'Kaffe?', en: 'Coffee?' }],
      question: 'You would love a coffee. What do you say?',
      choices: ['Ja, gärna!', 'Nej, tack.', 'Varsågod!'],
      answer: 'Ja, gärna!',
      explanation: '"Ja, gärna!" is a warm way to accept an offer.',
      vocab: ['garna'],
    },
    {
      type: 'build',
      prompt: 'Coffee first, please!',
      answer: 'Kaffe först, tack!',
      distractors: ['gärna', 'god'],
      vocab: ['kaffe', 'forst'],
    },
    {
      type: 'dictation',
      audio: 'Kaffe, tack.',
      en: 'Coffee, please.',
      vocab: ['kaffe'],
    },
    {
      type: 'speak',
      text: 'Ja, gärna! Kaffet är gott.',
      en: 'Yes, please! The coffee is good.',
      vocab: ['garna', 'kaffe', 'god'],
    },
  ],
})
