import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u01-l05',
  learn: [
    {
      title: 'Stress the first syllable',
      text: 'Most Swedish words are stressed on the **first** syllable: [[flicka]] (FLICK-a), [[pojke]] (POY-keh), [[kaffe]] (KAF-feh).\n\nSome words borrowed from other languages keep their stress later, like [[station]] (sta-HWOON).',
    },
    {
      title: 'Two melodies',
      text: 'Swedish words have one of two melodies, called **accent 1** and **accent 2**.\n\n**Accent 1** sounds like English: the voice falls once. [[bilen]] (the car), [[huset]] (the house), [[boken]] (the book).\n\n**Accent 2** is the famous Swedish "sing-song": the voice falls, then rises again on the next syllable. [[flicka]], [[pojke]], [[bilar]] (cars), [[fotboll]].',
      table: {
        headers: ['Accent 1: one fall', 'Accent 2: sing-song'],
        rows: [
          ['bilen', 'bilar'],
          ['båten', 'båtar'],
          ['huset', 'flicka'],
          ['boken', 'fotboll'],
        ],
        svColumns: [0, 1],
      },
      tip: 'A good rule of thumb: one-syllable words plus -en or -et (bilen, huset) have accent 1. Two-syllable words ending in -a or -e (flicka, pojke), plurals like bilar, and compound words like fotboll have accent 2.',
    },
    {
      title: 'Same letters, different word',
      text: 'A few words are told apart only by their melody. The classic example: **anden** with accent 1 means "the duck", and with accent 2 means "the spirit".\n\nDon\'t worry: the context almost always makes it clear. Just copy the melody of each new word you learn.',
      tip: "The audio in this app comes from your device's voice. It is good at melody in normal words, but it can't show the difference in look-alike pairs like anden.",
    },
  ],
  vocab: [
    {
      id: 'bil',
      sv: 'bil',
      en: 'car',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'bilen', plural: 'bilar', pluralDefinite: 'bilarna' },
    },
    {
      id: 'hus',
      sv: 'hus',
      en: 'house',
      pos: 'noun',
      gender: 'ett',
      pron: 'hoos (Swedish u)',
      forms: { definite: 'huset', plural: 'hus', pluralDefinite: 'husen' },
    },
    {
      id: 'flicka',
      sv: 'flicka',
      en: 'girl',
      pos: 'noun',
      gender: 'en',
      note: 'The neutral word. Tjej is more casual.',
      forms: { definite: 'flickan', plural: 'flickor', pluralDefinite: 'flickorna' },
    },
    {
      id: 'pojke',
      sv: 'pojke',
      en: 'boy',
      pos: 'noun',
      gender: 'en',
      pron: 'POY-keh',
      forms: { definite: 'pojken', plural: 'pojkar', pluralDefinite: 'pojkarna' },
    },
    {
      id: 'sommar',
      sv: 'sommar',
      en: 'summer',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'sommaren', plural: 'somrar', pluralDefinite: 'somrarna' },
    },
    {
      id: 'vinter',
      sv: 'vinter',
      en: 'winter',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'vintern', plural: 'vintrar', pluralDefinite: 'vintrarna' },
    },
    {
      id: 'bok',
      sv: 'bok',
      en: 'book',
      pos: 'noun',
      gender: 'en',
      pron: 'boohk',
      note: 'Irregular plural: böcker.',
      forms: { definite: 'boken', plural: 'böcker', pluralDefinite: 'böckerna' },
    },
    {
      id: 'fotboll',
      sv: 'fotboll',
      en: 'football / soccer',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'fotbollen', plural: 'fotbollar', pluralDefinite: 'fotbollarna' },
    },
  ],
  dialogue: {
    title: 'Summer or winter?',
    setting: 'Leo and Maja are getting to know each other with a quick game of "this or that".',
    lines: [
      { speaker: 'Leo', sv: 'Sommar eller vinter?', en: 'Summer or winter?' },
      { speaker: 'Maja', sv: 'Sommar!', en: 'Summer!' },
      { speaker: 'Leo', sv: 'Och fotboll eller en bok?', en: 'And football or a book?' },
      { speaker: 'Maja', sv: 'Fotboll! Och du?', en: 'Football! And you?' },
      { speaker: 'Leo', sv: 'En bok. Och kaffe!', en: 'A book. And coffee!' },
    ],
  },
  exercises: [
    {
      type: 'minimalPair',
      focus: 'One fall (accent 1) or sing-song (accent 2)?',
      options: [
        { sv: 'bilen', en: 'the car', hint: 'accent 1' },
        { sv: 'bilar', en: 'cars', hint: 'accent 2' },
      ],
      answer: 'bilar',
      explanation: 'bilar has the sing-song accent 2; bilen has the single fall of accent 1.',
      vocab: ['bil'],
    },
    {
      type: 'minimalPair',
      focus: 'One fall (accent 1) or sing-song (accent 2)?',
      options: [
        { sv: 'båten', en: 'the boat', hint: 'accent 1' },
        { sv: 'båtar', en: 'boats', hint: 'accent 2' },
      ],
      answer: 'båten',
      explanation: 'båten (the boat) has accent 1, just like bilen.',
      vocab: ['bat'],
    },
    {
      type: 'mcq',
      prompt: 'flicka',
      promptLang: 'sv',
      question: 'Which melody does flicka have?',
      choices: ['Accent 2: falls, then rises (sing-song)', 'Accent 1: one fall, like English'],
      answer: 'Accent 2: falls, then rises (sing-song)',
      explanation: 'Two-syllable words ending in -a, like flicka, usually have accent 2.',
      vocab: ['flicka'],
    },
    {
      type: 'mcq',
      prompt: 'huset',
      promptLang: 'sv',
      question: 'Which melody does huset have?',
      choices: ['Accent 1: one fall, like English', 'Accent 2: falls, then rises (sing-song)'],
      answer: 'Accent 1: one fall, like English',
      explanation: 'A one-syllable word plus -et (hus → huset) has accent 1.',
      vocab: ['hus'],
    },
    {
      type: 'mcq',
      prompt: 'station',
      promptLang: 'sv',
      question: 'Which syllable is stressed?',
      choices: ['The last one: sta-HWOON', 'The first one: STA-hwoon'],
      answer: 'The last one: sta-HWOON',
      explanation: 'Words ending in -tion keep the stress at the end, as in French.',
      vocab: ['station'],
    },
    {
      type: 'listen',
      audio: 'Sommar eller vinter?',
      choices: ['Summer or winter?', 'Winter and summer.', 'A book or football?'],
      answer: 'Summer or winter?',
      vocab: ['sommar', 'vinter'],
    },
    {
      type: 'gap',
      text: 'En ___ och en pojke.',
      en: 'A girl and a boy.',
      choices: ['flicka', 'bok', 'fotboll'],
      answer: 'flicka',
      vocab: ['flicka', 'pojke'],
    },
    {
      type: 'build',
      prompt: 'A house and a car.',
      answer: 'Ett hus och en bil.',
      distractors: ['bilen', 'huset'],
      vocab: ['hus', 'bil'],
    },
    {
      type: 'dictation',
      audio: 'Pojken och flickan.',
      en: 'The boy and the girl.',
      vocab: ['pojke', 'flicka'],
    },
    {
      type: 'speak',
      text: 'En flicka och en pojke.',
      en: 'A girl and a boy.',
      vocab: ['flicka', 'pojke'],
    },
  ],
})
