import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u01-l03',
  learn: [
    {
      title: 'The sj-sound',
      text: 'Swedish has a sound English doesn\'t: the **sj-sound**. It\'s a breathy "hw" made with rounded lips, a bit like blowing out a candle. Listen to [[sju]] (seven).\n\nIt has several spellings:',
      table: {
        headers: ['Spelling', 'Example', 'Meaning'],
        rows: [
          ['sj', 'sjö', 'lake'],
          ['skj', 'skjorta', 'shirt'],
          ['stj', 'stjärna', 'star'],
          ['sk + e, i, y, ä, ö', 'sked', 'spoon'],
          ['-tion', 'station', 'station'],
        ],
        svColumns: [1],
      },
    },
    {
      title: 'The tj-sound',
      text: 'The **tj-sound** is softer, like the "sh" in "sheep" but with your tongue further forward. Listen to [[tjugo]] (twenty) and [[tjej]] (girl).',
      table: {
        headers: ['Spelling', 'Example', 'Meaning'],
        rows: [
          ['tj', 'tjugo', 'twenty'],
          ['kj', 'kjol', 'skirt'],
          ['k + e, i, y, ä, ö', 'kök', 'kitchen'],
        ],
        svColumns: [1],
      },
      tip: 'Many younger Swedes blur these two sounds. If both come out a bit like "sh", you will still be understood.',
    },
  ],
  vocab: [
    { id: 'sju', sv: 'sju', en: 'seven', pos: 'numeral', pron: 'hwoo' },
    {
      id: 'sjo',
      sv: 'sjö',
      en: 'lake',
      pos: 'noun',
      gender: 'en',
      pron: 'hwuh',
      forms: { definite: 'sjön', plural: 'sjöar', pluralDefinite: 'sjöarna' },
    },
    {
      id: 'skjorta',
      sv: 'skjorta',
      en: 'shirt',
      pos: 'noun',
      gender: 'en',
      pron: 'HWOOR-ta',
      forms: { definite: 'skjortan', plural: 'skjortor', pluralDefinite: 'skjortorna' },
    },
    {
      id: 'stjarna',
      sv: 'stjärna',
      en: 'star',
      pos: 'noun',
      gender: 'en',
      pron: 'HWAIR-na',
      forms: { definite: 'stjärnan', plural: 'stjärnor', pluralDefinite: 'stjärnorna' },
    },
    {
      id: 'sked',
      sv: 'sked',
      en: 'spoon',
      pos: 'noun',
      gender: 'en',
      pron: 'hwayd',
      forms: { definite: 'skeden', plural: 'skedar', pluralDefinite: 'skedarna' },
    },
    {
      id: 'station',
      sv: 'station',
      en: 'station',
      pos: 'noun',
      gender: 'en',
      pron: 'sta-HWOON',
      forms: { definite: 'stationen', plural: 'stationer', pluralDefinite: 'stationerna' },
    },
    { id: 'tjugo', sv: 'tjugo', en: 'twenty', pos: 'numeral', pron: 'SHOO-go' },
    {
      id: 'tjej',
      sv: 'tjej',
      en: 'girl / young woman',
      pos: 'noun',
      gender: 'en',
      pron: 'shay',
      note: 'Casual and very common, also for adult women among friends.',
      forms: { definite: 'tjejen', plural: 'tjejer', pluralDefinite: 'tjejerna' },
    },
    {
      id: 'kjol',
      sv: 'kjol',
      en: 'skirt',
      pos: 'noun',
      gender: 'en',
      pron: 'shool',
      forms: { definite: 'kjolen', plural: 'kjolar', pluralDefinite: 'kjolarna' },
    },
    {
      id: 'kok',
      sv: 'kök',
      en: 'kitchen',
      pos: 'noun',
      gender: 'ett',
      pron: 'shuhk',
      forms: { definite: 'köket', plural: 'kök', pluralDefinite: 'köken' },
    },
    {
      id: 'kyrka',
      sv: 'kyrka',
      en: 'church',
      pos: 'noun',
      gender: 'en',
      pron: 'SHEER-ka',
      note: 'The first k is soft (before y), the second is hard (before a).',
      forms: { definite: 'kyrkan', plural: 'kyrkor', pluralDefinite: 'kyrkorna' },
    },
  ],
  dialogue: {
    title: 'An evening walk',
    setting: 'Lisa and Omar are out walking in the countryside.',
    lines: [
      { speaker: 'Lisa', sv: 'Titta! En sjö!', en: 'Look! A lake!' },
      { speaker: 'Omar', sv: 'Och en kyrka.', en: 'And a church.' },
      { speaker: 'Lisa', sv: 'Titta, en stjärna!', en: 'Look, a star!' },
      { speaker: 'Omar', sv: 'Två stjärnor! Nej, sju!', en: 'Two stars! No, seven!' },
      { speaker: 'Lisa', sv: 'Nej, tjugo!', en: 'No, twenty!' },
    ],
  },
  exercises: [
    {
      type: 'minimalPair',
      focus: 'sj-sound or tj-sound?',
      options: [
        { sv: 'sjö', en: 'lake' },
        { sv: 'kö', en: 'queue' },
      ],
      answer: 'kö',
      explanation:
        'sjö starts with the breathy sj-sound. kö starts with the softer tj-sound (k before ö).',
      vocab: ['sjo'],
    },
    {
      type: 'minimalPair',
      focus: 'sj-sound or tj-sound?',
      options: [
        { sv: 'skära', en: 'to cut' },
        { sv: 'kära', en: 'dear' },
      ],
      answer: 'skära',
      explanation: 'sk before ä gives the sj-sound; k before ä gives the tj-sound.',
    },
    {
      type: 'mcq',
      prompt: 'skjorta',
      promptLang: 'sv',
      question: 'Which sound does skjorta start with?',
      choices: ['The sj-sound', 'The tj-sound', 'A hard k, as in "skate"'],
      answer: 'The sj-sound',
      explanation: 'skj is one of the spellings of the sj-sound.',
      vocab: ['skjorta'],
    },
    {
      type: 'mcq',
      prompt: 'kyrka',
      promptLang: 'sv',
      question: 'What about the first k in kyrka?',
      choices: ['It is soft (the tj-sound)', 'It is hard, as in "kite"'],
      answer: 'It is soft (the tj-sound)',
      explanation: 'k before y is soft. The second k, before a, is hard: SHEER-ka.',
      vocab: ['kyrka'],
    },
    {
      type: 'listen',
      audio: 'sju',
      question: 'Which number do you hear?',
      choices: ['7', '20', '2'],
      answer: '7',
      vocab: ['sju'],
    },
    {
      type: 'listen',
      audio: 'tjugo',
      question: 'Which number do you hear?',
      choices: ['20', '7', '2'],
      answer: '20',
      vocab: ['tjugo'],
    },
    {
      type: 'gap',
      text: '___ stjärnor',
      en: 'seven stars',
      choices: ['Sju', 'Tjugo', 'Två'],
      answer: 'Sju',
      vocab: ['sju', 'stjarna'],
    },
    {
      type: 'build',
      prompt: 'A spoon and a shirt.',
      answer: 'En sked och en skjorta.',
      distractors: ['kjol', 'ett'],
      vocab: ['sked', 'skjorta'],
    },
    {
      type: 'dictation',
      audio: 'Sju stjärnor.',
      en: 'Seven stars.',
      vocab: ['sju', 'stjarna'],
    },
    {
      type: 'speak',
      text: 'Sju sjöar och tjugo stjärnor.',
      en: 'Seven lakes and twenty stars.',
      vocab: ['sju', 'sjo', 'tjugo', 'stjarna'],
    },
  ],
})
