import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u06-l02',
  learn: [
    {
      title: 'The verb is always number 2',
      text: 'This is the most important rule in Swedish word order: in a statement, the verb is **always the second thing**.\n\nUsually the subject comes first: [[Jag dricker te idag.]] But you can start with something else, like a time word. The verb still has to be second, so the subject **moves to after the verb**: [[Idag dricker jag te.]]',
      table: {
        headers: ['Position 1', 'Verb (2)', 'Subject', 'The rest'],
        rows: [
          ['Jag', 'dricker', '–', 'te idag'],
          ['Idag', 'dricker', 'jag', 'te'],
          ['På lördag', 'ska', 'vi', 'fika'],
          ['Sedan', 'äter', 'vi', '–'],
          ['Snart', 'kommer', 'bussen', '–'],
          ['Därför', 'är', 'jag', 'trött'],
        ],
      },
      examples: [
        { sv: 'Idag dricker jag te.', en: 'Today I’m drinking tea.' },
        { sv: 'På lördag ska vi fika.', en: 'On Saturday we’re going for a coffee.' },
        { sv: 'Sedan äter vi.', en: 'Then we eat.' },
        { sv: 'Snart kommer bussen.', en: 'The bus is coming soon.' },
        { sv: 'Därför är jag trött.', en: 'That’s why I’m tired.' },
      ],
      tip: 'Position 1 can be more than one word: på lördag counts as one thing.',
    },
    {
      title: 'The classic mistake',
      text: 'English says "Today **I drink** tea", so it is very tempting to say *Idag jag dricker te*. In Swedish that sounds wrong straight away: the verb would be third!\n\nWhenever you start with something other than the subject, flip the verb and the subject.',
      table: {
        headers: ['✗ Wrong', '✓ Right'],
        rows: [
          ['Idag jag dricker te.', 'Idag dricker jag te.'],
          ['Sedan vi äter.', 'Sedan äter vi.'],
          ['På lördag jag spelar fotboll.', 'På lördag spelar jag fotboll.'],
          ['Därför jag är trött.', 'Därför är jag trött.'],
        ],
        svColumns: [1],
      },
      tip: 'With kan, vill, ska or måste, the little verb takes position 2 and the other verb comes later: [[Imorgon ska jag simma.]]',
    },
    {
      title: 'Next, last, already, still',
      text: 'Some handy time words. Notice [[nästa vecka]] (next week) but [[förra veckan]] (last week): after **förra**, the noun takes its the-ending.\n\n[[redan]] (already) and [[fortfarande]] (still) sit right after the verb, just like alltid and inte.',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['Nästa vecka har jag semester.', 'Next week I’m on holiday.'],
          ['Förra veckan var jag i Sverige.', 'Last week I was in Sweden.'],
          ['Hon är redan här.', 'She’s already here.'],
          ['Jag är fortfarande trött.', 'I’m still tired.'],
          ['Efter maten dricker vi kaffe.', 'After the meal we have coffee.'],
          ['Jag dricker inte kaffe före lunch.', 'I don’t drink coffee before lunch.'],
        ],
        svColumns: [0],
      },
      tip: 'efter maten is position 1 in [[Efter maten dricker vi kaffe]], so the verb dricker comes next.',
    },
  ],
  vocab: [
    {
      id: 'sedan',
      sv: 'sedan',
      en: 'then / after that',
      pos: 'adverb',
      pron: 'SEH-dan (often just "sen")',
      note: 'Very often said and written sen.',
      alt: ['sen'],
      enAlt: ['then', 'after that', 'afterwards'],
    },
    {
      id: 'darfor',
      sv: 'därför',
      en: 'that’s why / so',
      pos: 'adverb',
      note: 'Därför är jag trött. = That’s why I’m tired.',
      enAlt: ["that's why", 'so', 'therefore'],
    },
    {
      id: 'nasta',
      sv: 'nästa',
      en: 'next',
      pos: 'adjective',
      note: 'nästa vecka = next week (no ending on vecka)',
    },
    {
      id: 'forra',
      sv: 'förra',
      en: 'last (the previous)',
      pos: 'adjective',
      note: 'förra veckan = last week (note the -an ending)',
      enAlt: ['last', 'previous'],
    },
    { id: 'snart', sv: 'snart', en: 'soon', pos: 'adverb' },
    { id: 'redan', sv: 'redan', en: 'already', pos: 'adverb', pron: 'REH-dan' },
    {
      id: 'fortfarande',
      sv: 'fortfarande',
      en: 'still',
      pos: 'adverb',
      pron: 'FORT-fah-ran-deh',
      note: 'Jag är fortfarande trött. = I’m still tired.',
    },
    { id: 'efter', sv: 'efter', en: 'after', pos: 'preposition' },
    {
      id: 'fore',
      sv: 'före',
      en: 'before',
      pos: 'preposition',
      note: 'före lunch = before lunch',
    },
  ],
  dialogue: {
    title: 'Saturday plans',
    setting: 'Omar calls his friend Linnea.',
    lines: [
      {
        speaker: 'Omar',
        sv: 'Hej Linnea! Vad gör du på lördag?',
        en: 'Hi Linnea! What are you doing on Saturday?',
      },
      {
        speaker: 'Linnea',
        sv: 'På lördag spelar jag fotboll. Sedan är jag ledig!',
        en: 'On Saturday I’m playing football. After that I’m free!',
      },
      {
        speaker: 'Omar',
        sv: 'Bra! Ska vi fika efter fotbollen?',
        en: 'Great! Shall we go for a coffee after football?',
      },
      {
        speaker: 'Linnea',
        sv: 'Gärna! Men jag är fortfarande trött efter förra veckan.',
        en: 'I’d love to! But I’m still tired after last week.',
      },
      {
        speaker: 'Omar',
        sv: 'Då dricker vi mycket kaffe!',
        en: 'Then we’ll drink lots of coffee!',
      },
      { speaker: 'Linnea', sv: 'Haha, okej. Vi ses snart!', en: 'Haha, okay. See you soon!' },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: 'Today I’m drinking tea.',
      promptLang: 'en',
      question: 'Which sentence is correct?',
      choices: ['Idag dricker jag te.', 'Idag jag dricker te.', 'Idag dricker te jag.'],
      answer: 'Idag dricker jag te.',
      explanation:
        'Idag takes position 1, so the verb dricker must come next, and then the subject jag.',
      vocab: ['idag', 'te'],
    },
    {
      type: 'build',
      prompt: 'Tomorrow we’re playing football.',
      answer: 'Imorgon spelar vi fotboll.',
      accept: ['Vi spelar fotboll imorgon.', 'Fotboll spelar vi imorgon.'],
      distractors: ['spela'],
      explanation: 'Imorgon is position 1, the verb spelar is number 2, then the subject vi.',
      vocab: ['imorgon', 'fotboll'],
    },
    {
      type: 'build',
      prompt: 'Next week I’m free.',
      answer: 'Nästa vecka är jag ledig.',
      accept: ['Jag är ledig nästa vecka.'],
      distractors: ['veckan'],
      explanation:
        'nästa vecka (no ending!) is position 1, so the verb är comes next and then jag.',
      vocab: ['nasta', 'vecka'],
    },
    {
      type: 'build',
      prompt: 'Then we eat ice cream.',
      answer: 'Sedan äter vi glass.',
      accept: ['Vi äter glass sedan.', 'Vi äter sedan glass.', 'Glass äter vi sedan.'],
      distractors: ['jag'],
      explanation: 'Sedan takes position 1, so the verb äter comes before the subject vi.',
      vocab: ['sedan', 'glass'],
    },
    {
      type: 'gap',
      text: 'Efter maten ___ kaffe.',
      en: 'After the meal we drink coffee.',
      choices: ['dricker vi', 'vi dricker', 'vi dricka'],
      answer: 'dricker vi',
      explanation:
        'Efter maten is position 1. The verb must be second, so it is dricker vi, not "vi dricker".',
      vocab: ['efter', 'mat'],
    },
    {
      type: 'gap',
      text: 'Hon är ___ här!',
      en: 'She’s already here!',
      choices: ['redan', 'snart', 'fortfarande'],
      answer: 'redan',
      explanation: 'redan = already. snart = soon, fortfarande = still.',
      vocab: ['redan'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Omar', sv: 'Vad gör du imorgon?', en: 'What are you doing tomorrow?' }],
      question: 'You are working tomorrow. Start your answer with imorgon.',
      choices: ['Imorgon jobbar jag.', 'Imorgon jag jobbar.', 'Jag imorgon jobbar.'],
      answer: 'Imorgon jobbar jag.',
      explanation: 'Imorgon is position 1, so the verb jobbar comes second and jag after it.',
      vocab: ['imorgon'],
    },
    {
      type: 'listen',
      audio: 'Jag är fortfarande trött efter förra veckan.',
      choices: [
        'I’m still tired after last week.',
        'I’m already tired before next week.',
        'I’m still tired after the weekend.',
      ],
      answer: 'I’m still tired after last week.',
      explanation: 'fortfarande = still, efter = after, förra veckan = last week.',
      vocab: ['fortfarande', 'efter', 'forra'],
    },
    {
      type: 'dictation',
      audio: 'Snart är det lördag.',
      en: 'It’ll be Saturday soon.',
      explanation: 'Snart is position 1, so the verb är comes next, then det.',
      vocab: ['snart', 'lordag'],
    },
    {
      type: 'speak',
      text: 'Jag jobbar mycket. Därför är jag trött.',
      en: 'I work a lot. That’s why I’m tired.',
      vocab: ['darfor', 'trott'],
    },
  ],
})
