import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u06-l05',
  learn: [
    {
      title: 'In a normal sentence: right after the verb',
      text: 'You already know this one: [[inte]] goes **right after the verb**. If the subject comes after the verb, inte comes right after the subject. With kan, vill, ska and måste, inte follows the little verb.',
      table: {
        headers: ['Position 1', 'Verb', 'Subject', 'inte', 'The rest'],
        rows: [
          ['Jag', 'dricker', '–', 'inte', 'kaffe'],
          ['Idag', 'dricker', 'jag', 'inte', 'kaffe'],
          ['Jag', 'kan', '–', 'inte', 'komma'],
          ['Imorgon', 'jobbar', 'hon', 'inte', '–'],
        ],
      },
      examples: [
        { sv: 'Jag dricker inte kaffe.', en: 'I don’t drink coffee.' },
        { sv: 'Idag dricker jag inte kaffe.', en: 'Today I’m not drinking coffee.' },
        { sv: 'Jag kan inte komma.', en: 'I can’t come.' },
        { sv: 'Imorgon jobbar hon inte.', en: 'She isn’t working tomorrow.' },
      ],
      tip: 'When the subject comes after the verb, inte comes after the subject: verb, subject, inte. Idag dricker jag inte …',
    },
    {
      title: 'After att and eftersom: inte BEFORE the verb',
      text: 'Words like [[att]] (that), [[eftersom]] (because) and **om** (if) start a **side clause**. Inside a side clause, inte jumps in **front of** the verb (the first verb, if there are two: [[att hon inte kan komma]]).\n\nSwedish teachers remember it as **BIFF**: *i **B**isats står **I**nte **F**öre **F**inita verbet* (in a side clause, inte comes before the verb). Words like alltid and aldrig do the same.',
      table: {
        headers: ['Normal sentence', 'Side clause'],
        rows: [
          ['Hon kommer inte.', 'Jag tror att hon inte kommer.'],
          ['Jag jobbar inte idag.', 'Jag är glad eftersom jag inte jobbar idag.'],
          ['Han är inte trött.', 'Han säger att han inte är trött.'],
          ['Hon dricker aldrig kaffe.', 'Jag vet att hon aldrig dricker kaffe.'],
        ],
        svColumns: [0, 1],
      },
      tip: 'Swedes very often put inte in the main part instead: [[Jag tror inte att hon kommer.]] (I don’t think she’s coming.) Both are correct.',
    },
    {
      title: 'Me neither, nobody and somebody',
      text: '**inte heller** means "not either": [[Jag dricker inte kaffe.]] – [[Inte jag heller!]] (Me neither!)\n\n**ingen** means "no / none" and **någon** means "some / any". Both change like this:',
      table: {
        headers: ['', 'en-word', 'ett-word', 'plural'],
        rows: [
          ['no / none', 'ingen', 'inget', 'inga'],
          ['some / any', 'någon', 'något', 'några'],
        ],
        svColumns: [1, 2, 3],
      },
      examples: [
        { sv: 'Jag har ingen bil.', en: 'I don’t have a car.' },
        { sv: 'Vi har inget kaffe.', en: 'We don’t have any coffee.' },
        { sv: 'Har du några barn?', en: 'Do you have any children?' },
        { sv: 'Hon kommer nog.', en: 'She’ll probably come.' },
        { sv: 'Jag är inte alls trött.', en: 'I’m not tired at all.' },
        { sv: 'Jag hoppas att du kommer!', en: 'I hope you’re coming!' },
      ],
      tip: 'In speech, någon, något and några usually sound like "nån", "nåt" and "nåra".',
    },
  ],
  vocab: [
    {
      id: 'att',
      sv: 'att',
      en: 'that',
      pos: 'conjunction',
      note: 'Jag tror att … = I think that … Swedish usually keeps att where English drops "that".',
    },
    {
      id: 'saga',
      sv: 'säga',
      en: 'to say',
      pos: 'verb',
      pron: 'SAY-ah (often "säja")',
      note: 'The past is sa, also written sade.',
      forms: { present: 'säger', past: 'sa', supine: 'sagt', imperative: 'säg' },
      enAlt: ['say'],
    },
    {
      id: 'tanka',
      sv: 'tänka',
      en: 'to think',
      pos: 'verb',
      note: 'Vad tänker du på? = What are you thinking about? For opinions, use tycka or tro.',
      forms: { present: 'tänker', past: 'tänkte', supine: 'tänkt', imperative: 'tänk' },
      enAlt: ['think'],
    },
    {
      id: 'hoppas',
      sv: 'hoppas',
      en: 'to hope',
      pos: 'verb',
      note: 'Always ends in -s: jag hoppas, vi hoppas.',
      forms: { present: 'hoppas', past: 'hoppades', supine: 'hoppats' },
      enAlt: ['hope'],
    },
    { id: 'nog', sv: 'nog', en: 'probably', pos: 'adverb', pron: 'noog' },
    {
      id: 'heller',
      sv: 'heller',
      en: 'either (in "not either")',
      pos: 'adverb',
      note: 'inte heller = not either. Inte jag heller! = Me neither!',
      enAlt: ['either'],
    },
    {
      id: 'ingen',
      sv: 'ingen',
      en: 'no / none / nobody',
      pos: 'pronoun',
      note: 'ingen bil, inget kaffe, inga barn',
      forms: { neuter: 'inget', plural: 'inga' },
      enAlt: ['no', 'none', 'nobody', 'no one'],
    },
    {
      id: 'nagon',
      sv: 'någon',
      en: 'some / any / someone',
      pos: 'pronoun',
      pron: 'NOH-gon (often "nån")',
      note: 'någon bil, något kaffe, några barn',
      forms: { neuter: 'något', plural: 'några' },
      enAlt: ['some', 'any', 'someone', 'anyone', 'somebody', 'anybody'],
    },
    {
      id: 'alls',
      sv: 'alls',
      en: 'at all',
      pos: 'adverb',
      note: 'inte alls = not at all',
    },
  ],
  dialogue: {
    title: 'Is Sofia coming?',
    setting: 'Nora and Viktor are getting ready for Ali’s birthday party.',
    lines: [
      { speaker: 'Nora', sv: 'Kommer Sofia på festen?', en: 'Is Sofia coming to the party?' },
      {
        speaker: 'Viktor',
        sv: 'Nej, hon säger att hon inte kan komma.',
        en: 'No, she says she can’t come.',
      },
      { speaker: 'Nora', sv: 'Varför inte?', en: 'Why not?' },
      {
        speaker: 'Viktor',
        sv: 'Hon mår inte så bra. Hon jobbar nog för mycket.',
        en: 'She’s not feeling great. She probably works too much.',
      },
      {
        speaker: 'Nora',
        sv: 'Synd! Jag hoppas att hon kommer nästa gång.',
        en: 'Too bad! I hope she comes next time.',
      },
      { speaker: 'Viktor', sv: 'Har du någon present?', en: 'Do you have a present?' },
      {
        speaker: 'Nora',
        sv: 'Nej, inte än. Jag tänker köpa en bok.',
        en: 'No, not yet. I’m thinking of buying a book.',
      },
      {
        speaker: 'Viktor',
        sv: 'Bra! Jag har ingen present heller.',
        en: 'Good! I don’t have a present either.',
      },
    ],
  },
  exercises: [
    {
      type: 'build',
      prompt: 'I can’t come today.',
      answer: 'Jag kan inte komma idag.',
      accept: ['Idag kan jag inte komma.'],
      explanation: 'inte goes right after the little verb kan: Jag kan inte komma.',
      vocab: ['inte', 'komma', 'idag'],
    },
    {
      type: 'build',
      prompt: 'She says that she isn’t tired.',
      answer: 'Hon säger att hon inte är trött.',
      explanation:
        'After att you are in a side clause, so inte comes BEFORE the verb: att hon inte är trött (BIFF).',
      vocab: ['saga', 'att', 'inte'],
    },
    {
      type: 'build',
      prompt: 'I’m happy because I’m not working today.',
      answer: 'Jag är glad eftersom jag inte jobbar idag.',
      accept: [
        'Eftersom jag inte jobbar idag är jag glad.',
        'Jag är glad idag eftersom jag inte jobbar.',
        'Idag är jag glad eftersom jag inte jobbar.',
      ],
      explanation:
        'eftersom starts a side clause, so inte goes before the verb: eftersom jag inte jobbar.',
      vocab: ['eftersom', 'inte', 'glad'],
    },
    {
      type: 'mcq',
      prompt: 'I hope you’re not tired.',
      promptLang: 'en',
      question: 'Which sentence is correct?',
      choices: [
        'Jag hoppas att du inte är trött.',
        'Jag hoppas att du är inte trött.',
        'Jag inte hoppas att du är trött.',
      ],
      answer: 'Jag hoppas att du inte är trött.',
      explanation:
        'In the att-part, inte comes before the verb: att du inte är. In the main part, inte would come after the verb, never before it.',
      vocab: ['hoppas', 'att', 'inte'],
    },
    {
      type: 'gap',
      text: 'Jag dricker inte kaffe. – Inte jag ___!',
      en: 'I don’t drink coffee. – Me neither!',
      choices: ['heller', 'också', 'alls'],
      answer: 'heller',
      explanation: 'After a "not" sentence, agree with inte … heller. Jag också means "me too".',
      vocab: ['heller'],
    },
    {
      type: 'gap',
      text: 'Jag har ___ te.',
      en: 'I don’t have any tea.',
      choices: ['inget', 'ingen', 'inga'],
      answer: 'inget',
      explanation: 'te is an ett-word, so it is inget te. (ingen mjölk, inga barn.)',
      vocab: ['ingen', 'te'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Emil', sv: 'Jag gillar inte fotboll.', en: 'I don’t like football.' }],
      question: 'You don’t like football either. What do you say?',
      choices: ['Inte jag heller!', 'Jag också!', 'Jo, jag heller!'],
      answer: 'Inte jag heller!',
      explanation:
        'To agree with a "not" sentence, say Inte jag heller. Jag också only agrees with a positive sentence.',
      vocab: ['heller', 'gilla', 'fotboll'],
    },
    {
      type: 'listen',
      audio: 'Hon kommer nog inte idag.',
      choices: [
        'She probably isn’t coming today.',
        'She’s definitely coming today.',
        'She isn’t coming at all today.',
      ],
      answer: 'She probably isn’t coming today.',
      explanation: 'nog = probably. "Not at all" would be inte alls.',
      vocab: ['nog', 'inte'],
    },
    {
      type: 'dictation',
      audio: 'Jag är inte alls trött.',
      en: 'I’m not tired at all.',
      vocab: ['alls', 'inte', 'trott'],
    },
    {
      type: 'speak',
      text: 'Han säger att han inte kan komma.',
      en: 'He says he can’t come.',
      vocab: ['saga', 'att', 'komma'],
    },
  ],
})
