import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u06-l04',
  learn: [
    {
      title: 'Question word, then the verb',
      text: 'You already know [[Vad heter du?]], [[Var bor du?]] and [[Hur mår du?]]. All question-word questions work the same way: the **question word** takes position 1, the **verb** comes second, then the subject. It is the V2 rule again!',
      table: {
        headers: ['Question word', 'English', 'Example', 'Meaning'],
        rows: [
          ['vem', 'who', 'Vem är det?', 'Who is it?'],
          ['när', 'when', 'När kommer du?', 'When are you coming?'],
          ['varför', 'why', 'Varför är du trött?', 'Why are you tired?'],
          ['var', 'where (at)', 'Var bor du?', 'Where do you live?'],
          ['vart', 'where (to)', 'Vart ska du?', 'Where are you going?'],
          [
            'hur mycket',
            'how much',
            'Hur mycket kaffe dricker du?',
            'How much coffee do you drink?',
          ],
          ['hur länge', 'how long', 'Hur länge sover du?', 'How long do you sleep?'],
        ],
        svColumns: [0, 2],
      },
      tip: 'Never put the subject before the verb here: Var bor du?, not "Var du bor?" If the question word is itself the subject, the verb simply follows it: [[Vem har fest på lördag?]]',
    },
    {
      title: 'Var or vart?',
      text: '[[var]] asks where something **is**. [[vart]] asks where someone is **going**: it is about movement.\n\nA quick test: if you could say "where **to**" in English, use vart.',
      examples: [
        { sv: 'Var är du?', en: 'Where are you?' },
        { sv: 'Vart ska du?', en: 'Where are you going?' },
        { sv: 'Var är festen?', en: 'Where is the party?' },
        { sv: 'Vart går ni på lördag?', en: 'Where are you going on Saturday?' },
      ],
      tip: 'In casual speech you will hear some Swedes say var for both. Vart for direction is still the standard.',
    },
    {
      title: 'Why? Because…',
      text: '[[eftersom]] means "because" or "since". It starts a **side clause**, and inside it the order is simply subject + verb, with no flipping:\n\n[[Jag är trött eftersom jag jobbar mycket.]]\n\nYou can also start with the eftersom-part. Then that whole part is position 1, so the main verb comes right after it: [[Eftersom jag jobbar mycket är jag trött.]]',
      examples: [
        {
          sv: 'Jag köper en present eftersom Sara har födelsedag.',
          en: 'I’m buying a present because it’s Sara’s birthday.',
        },
        { sv: 'När är din födelsedag?', en: 'When is your birthday?' },
        { sv: 'Vem har fest på lördag?', en: 'Who is having a party on Saturday?' },
      ],
      tip: 'For a quick spoken answer to Varför?, Swedes usually start with [[för att]]: Varför är du glad? – För att det är fredag!',
    },
  ],
  vocab: [
    { id: 'vem', sv: 'vem', en: 'who', pos: 'pronoun' },
    {
      id: 'vart',
      sv: 'vart',
      en: 'where (to)',
      pos: 'adverb',
      note: 'For movement: Vart ska du? Compare var = where (at).',
      enAlt: ['where to', 'where'],
    },
    { id: 'nar', sv: 'när', en: 'when', pos: 'adverb' },
    { id: 'varfor', sv: 'varför', en: 'why', pos: 'adverb', pron: 'var-FÖR' },
    {
      id: 'hur-mycket',
      sv: 'hur mycket',
      en: 'how much',
      pos: 'phrase',
      note: 'For things you can’t count: hur mycket kaffe. For things you count: hur många.',
    },
    { id: 'hur-lange', sv: 'hur länge', en: 'how long (time)', pos: 'phrase', enAlt: ['how long'] },
    {
      id: 'eftersom',
      sv: 'eftersom',
      en: 'because / since',
      pos: 'conjunction',
      pron: 'EF-ter-som',
      enAlt: ['because', 'since', 'as'],
    },
    {
      id: 'fest',
      sv: 'fest',
      en: 'party',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'festen', plural: 'fester', pluralDefinite: 'festerna' },
    },
    {
      id: 'fodelsedag',
      sv: 'födelsedag',
      en: 'birthday',
      pos: 'noun',
      gender: 'en',
      pron: 'FÖ-del-se-dahg',
      note: 'Hon har födelsedag idag. = It’s her birthday today.',
      forms: { definite: 'födelsedagen', plural: 'födelsedagar', pluralDefinite: 'födelsedagarna' },
    },
    {
      id: 'present',
      sv: 'present',
      en: 'present / gift',
      pos: 'noun',
      gender: 'en',
      pron: 'pre-SENT',
      forms: { definite: 'presenten', plural: 'presenter', pluralDefinite: 'presenterna' },
      enAlt: ['present', 'gift'],
    },
  ],
  dialogue: {
    title: 'Where are you going?',
    setting: 'Karim meets his neighbour Elsa outside their building.',
    lines: [
      { speaker: 'Karim', sv: 'Hej Elsa! Vart ska du?', en: 'Hi Elsa! Where are you going?' },
      {
        speaker: 'Elsa',
        sv: 'Till en fest! Min kollega har födelsedag idag.',
        en: 'To a party! It’s my colleague’s birthday today.',
      },
      { speaker: 'Karim', sv: 'Kul! Var är festen?', en: 'Fun! Where is the party?' },
      { speaker: 'Elsa', sv: 'Hemma hos Nora.', en: 'At Nora’s place.' },
      { speaker: 'Karim', sv: 'När börjar den?', en: 'When does it start?' },
      {
        speaker: 'Elsa',
        sv: 'Klockan sju. Och här är presenten: en bok!',
        en: 'At seven. And here’s the present: a book!',
      },
      { speaker: 'Karim', sv: 'Hur länge ska du vara där?', en: 'How long will you be there?' },
      {
        speaker: 'Elsa',
        sv: 'Inte länge, eftersom jag jobbar imorgon.',
        en: 'Not long, since I’m working tomorrow.',
      },
    ],
  },
  exercises: [
    {
      type: 'build',
      prompt: 'When are you coming?',
      answer: 'När kommer du?',
      distractors: ['gör'],
      explanation: 'Question word first, then the verb, then the subject: När kommer du?',
      vocab: ['nar'],
    },
    {
      type: 'build',
      prompt: 'Why are you tired?',
      answer: 'Varför är du trött?',
      distractors: ['eftersom'],
      explanation: 'Varför is position 1, the verb är is second, then du.',
      vocab: ['varfor', 'trott'],
    },
    {
      type: 'build',
      prompt: 'Where are you going?',
      answer: 'Vart ska du?',
      distractors: ['var'],
      explanation:
        'Going somewhere is movement, so use vart (where to). Var is for where something is.',
      vocab: ['vart'],
    },
    {
      type: 'build',
      prompt: 'I’m tired because I work a lot.',
      answer: 'Jag är trött eftersom jag jobbar mycket.',
      accept: ['Eftersom jag jobbar mycket är jag trött.'],
      explanation:
        'After eftersom the order is plain subject + verb: eftersom jag jobbar. No flipping inside the side clause.',
      vocab: ['eftersom', 'trott'],
    },
    {
      type: 'gap',
      text: '___ bor du?',
      en: 'Where do you live?',
      choices: ['Var', 'Vart', 'Vem'],
      answer: 'Var',
      explanation: 'Living somewhere is not movement, so it is var. Vart is for "where to".',
      vocab: ['var-where', 'vart'],
    },
    {
      type: 'mcq',
      prompt: 'When does the party start?',
      promptLang: 'en',
      question: 'Which sentence is correct?',
      choices: ['När börjar festen?', 'När festen börjar?', 'Börjar när festen?'],
      answer: 'När börjar festen?',
      explanation: 'Question word, then verb, then subject: När börjar festen?',
      vocab: ['nar', 'fest'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Karim', sv: 'Varför är du så glad?', en: 'Why are you so happy?' }],
      question: 'It’s your birthday today. What do you answer?',
      choices: [
        'Jag är glad eftersom jag har födelsedag idag.',
        'Jag är glad eftersom har jag födelsedag idag.',
        'Jag glad är eftersom jag har födelsedag idag.',
      ],
      answer: 'Jag är glad eftersom jag har födelsedag idag.',
      explanation:
        'Main part: Jag är glad (verb second). After eftersom, plain subject + verb: jag har.',
      vocab: ['eftersom', 'fodelsedag', 'glad'],
    },
    {
      type: 'listen',
      audio: 'Hur mycket kaffe dricker du?',
      choices: [
        'How much coffee do you drink?',
        'How long do you drink coffee?',
        'Why do you drink coffee?',
      ],
      answer: 'How much coffee do you drink?',
      explanation: 'hur mycket = how much. hur länge = how long, varför = why.',
      vocab: ['hur-mycket', 'kaffe'],
    },
    {
      type: 'dictation',
      audio: 'När är din födelsedag?',
      en: 'When is your birthday?',
      vocab: ['nar', 'fodelsedag', 'din'],
    },
    {
      type: 'speak',
      text: 'Var är festen, och när börjar den?',
      en: 'Where is the party, and when does it start?',
      vocab: ['var-where', 'fest', 'nar'],
    },
  ],
})
