import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u06-l03',
  learn: [
    {
      title: 'Verb first = a question',
      text: 'To turn a statement into a yes/no question, just move the **verb to the front**. There is no "do" in Swedish questions!\n\n[[Du talar svenska.]] → [[Talar du svenska?]] (Do you speak Swedish?)',
      table: {
        headers: ['Statement', 'Question', 'English'],
        rows: [
          ['Du talar svenska.', 'Talar du svenska?', 'Do you speak Swedish?'],
          ['Du dricker kaffe.', 'Dricker du kaffe?', 'Do you drink coffee?'],
          ['Du har en katt.', 'Har du en katt?', 'Do you have a cat?'],
          ['Hon är trött.', 'Är hon trött?', 'Is she tired?'],
          ['Du kan simma.', 'Kan du simma?', 'Can you swim?'],
        ],
        svColumns: [0, 1],
      },
      tip: 'Words like ofta and inte come after the subject in a question: [[Dricker du ofta kaffe?]] [[Talar du inte svenska?]]',
    },
    {
      title: 'Ja, nej… and jo!',
      text: 'Answer a question with [[ja]] or [[nej]]. But if the question has **inte** in it, "yes" is [[jo]].\n\n[[Talar du inte svenska?]] (Don’t you speak Swedish?)\n[[Jo, lite!]] (Yes, I do, a little!)\n\nJo contradicts the "not". Saying ja here would be confusing: it can sound like you agree that you don’t speak Swedish.',
      table: {
        headers: ['Question', 'Yes', 'No'],
        rows: [
          ['Gillar du kaffe?', 'Ja!', 'Nej.'],
          ['Gillar du inte kaffe?', 'Jo!', 'Nej.'],
        ],
        svColumns: [0, 1, 2],
      },
      tip: 'If you don’t understand a question, say [[Förlåt, jag förstår inte.]] (Sorry, I don’t understand.) and ask [[Förstår du?]] to check that someone follows you.',
    },
    {
      title: 'Or, right? and really',
      text: '[[eller]] means "or": [[Te eller kaffe?]]\n\nAdd [[väl]] after the verb to make a "…, right?" question. You expect the other person to agree: [[Du kommer väl?]] (You’re coming, right?)\n\nTo talk about what you like, use [[gillar]] (like), [[älskar]] (love) and [[hatar]] (hate), and make it stronger with [[verkligen]] (really).',
      examples: [
        { sv: 'Vill du ha te eller kaffe?', en: 'Would you like tea or coffee?' },
        { sv: 'Du gillar väl musik?', en: 'You like music, right?' },
        { sv: 'Jag älskar film!', en: 'I love films!' },
        { sv: 'Han hatar sport.', en: 'He hates sport.' },
        { sv: 'Jag gillar verkligen svenska.', en: 'I really like Swedish.' },
      ],
      tip: 'Swedes happily use älskar about things: [[Jag älskar glass!]] hatar is a strong word, so use it about things rather than people.',
    },
  ],
  vocab: [
    {
      id: 'jo',
      sv: 'jo',
      en: 'yes (to a negative question)',
      pos: 'interjection',
      pron: 'yoo',
      note: 'Talar du inte svenska? – Jo, lite!',
    },
    { id: 'eller', sv: 'eller', en: 'or', pos: 'conjunction' },
    {
      id: 'val-tag',
      sv: 'väl',
      en: '…, right? / surely',
      pos: 'adverb',
      note: 'Du kommer väl? = You’re coming, right?',
      enAlt: ['right', 'surely'],
    },
    { id: 'verkligen', sv: 'verkligen', en: 'really', pos: 'adverb', pron: 'VERK-li-gen' },
    {
      id: 'forsta',
      sv: 'förstå',
      en: 'to understand',
      pos: 'verb',
      forms: { present: 'förstår', past: 'förstod', supine: 'förstått', imperative: 'förstå' },
      enAlt: ['understand'],
    },
    {
      id: 'gilla',
      sv: 'gilla',
      en: 'to like',
      pos: 'verb',
      forms: { present: 'gillar', past: 'gillade', supine: 'gillat', imperative: 'gilla' },
      enAlt: ['like'],
    },
    {
      id: 'alska',
      sv: 'älska',
      en: 'to love',
      pos: 'verb',
      forms: { present: 'älskar', past: 'älskade', supine: 'älskat', imperative: 'älska' },
      enAlt: ['love'],
    },
    {
      id: 'hata',
      sv: 'hata',
      en: 'to hate',
      pos: 'verb',
      forms: { present: 'hatar', past: 'hatade', supine: 'hatat', imperative: 'hata' },
      enAlt: ['hate'],
    },
    {
      id: 'sport',
      sv: 'sport',
      en: 'sport / sports',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'sporten', plural: 'sporter', pluralDefinite: 'sporterna' },
      enAlt: ['sport', 'sports'],
    },
    {
      id: 'musik',
      sv: 'musik',
      en: 'music',
      pos: 'noun',
      gender: 'en',
      pron: 'mu-SEEK',
      forms: { definite: 'musiken' },
    },
    {
      id: 'film',
      sv: 'film',
      en: 'film / movie',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'filmen', plural: 'filmer', pluralDefinite: 'filmerna' },
      enAlt: ['film', 'movie'],
    },
  ],
  dialogue: {
    title: 'Don’t you speak Swedish?',
    setting: 'Mira is new at the language café. Jonas says hello.',
    lines: [
      { speaker: 'Jonas', sv: 'Hej! Är du Mira?', en: 'Hi! Are you Mira?' },
      {
        speaker: 'Mira',
        sv: 'Ja, hej! Förlåt, talar du engelska?',
        en: 'Yes, hi! Sorry, do you speak English?',
      },
      {
        speaker: 'Jonas',
        sv: 'Ja, men talar du inte svenska?',
        en: 'Yes, but don’t you speak Swedish?',
      },
      {
        speaker: 'Mira',
        sv: 'Jo, lite! Och jag förstår mycket.',
        en: 'I do, a little! And I understand a lot.',
      },
      { speaker: 'Jonas', sv: 'Bra! Gillar du musik?', en: 'Great! Do you like music?' },
      {
        speaker: 'Mira',
        sv: 'Ja, jag älskar musik! Och film.',
        en: 'Yes, I love music! And films.',
      },
      {
        speaker: 'Jonas',
        sv: 'Och sport? Du gillar väl fotboll?',
        en: 'And sport? You like football, right?',
      },
      {
        speaker: 'Mira',
        sv: 'Nej, jag hatar verkligen fotboll!',
        en: 'No, I really hate football!',
      },
    ],
  },
  exercises: [
    {
      type: 'build',
      prompt: 'Do you speak Swedish?',
      answer: 'Talar du svenska?',
      distractors: ['gör'],
      explanation: 'Just put the verb first: Talar du …? Swedish has no "do" in questions.',
      vocab: ['svenska'],
    },
    {
      type: 'build',
      prompt: 'Do you often watch films?',
      answer: 'Tittar du ofta på film?',
      accept: ['Tittar du på film ofta?'],
      distractors: ['gör'],
      explanation:
        'Verb first, then the subject, then ofta: Tittar du ofta …? "Watch films" is titta på film.',
      vocab: ['film', 'ofta'],
    },
    {
      type: 'build',
      prompt: 'Don’t you understand?',
      answer: 'Förstår du inte?',
      distractors: ['gör'],
      explanation: 'Verb first, then the subject, then inte: Förstår du inte?',
      vocab: ['forsta', 'inte'],
    },
    {
      type: 'build',
      prompt: 'You’re coming, right?',
      answer: 'Du kommer väl?',
      distractors: ['gör'],
      explanation:
        'This is a statement with väl after the verb. It asks the other person to agree: "You’re coming, right?"',
      vocab: ['val-tag'],
    },
    {
      type: 'mcq',
      prompt: 'Do you have a cat?',
      promptLang: 'en',
      question: 'Which sentence is correct?',
      choices: ['Har du en katt?', 'Gör du har en katt?', 'Har en katt du?'],
      answer: 'Har du en katt?',
      explanation:
        'Verb first, then the subject: Har du …? Swedish never adds gör as a helper, the way English adds "do".',
      vocab: ['katt'],
    },
    {
      type: 'dialogueReply',
      lines: [
        {
          speaker: 'Ella',
          sv: 'Talar du inte svenska?',
          en: 'Don’t you speak Swedish?',
        },
      ],
      question: 'You do speak a little Swedish. What do you answer?',
      choices: ['Jo, lite!', 'Ja, lite!', 'Nej, lite!'],
      answer: 'Jo, lite!',
      explanation:
        'The question has inte in it, so "yes" is jo. Ja would be confusing: it can sound like you agree that you don’t.',
      vocab: ['jo'],
    },
    {
      type: 'gap',
      text: 'Vill du ha te ___ kaffe?',
      en: 'Would you like tea or coffee?',
      choices: ['eller', 'och', 'väl'],
      answer: 'eller',
      explanation: 'eller = or. och = and.',
      vocab: ['eller', 'te', 'kaffe'],
    },
    {
      type: 'listen',
      audio: 'Gillar du inte sport?',
      choices: ['Don’t you like sport?', 'Do you like sport?', 'You like sport, right?'],
      answer: 'Don’t you like sport?',
      explanation: 'The verb comes first, so it is a question, and inte makes it negative.',
      vocab: ['gilla', 'sport'],
    },
    {
      type: 'type',
      prompt: 'I don’t understand.',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'Jag förstår inte.',
      explanation: 'förstår is the verb, and inte comes right after it.',
      vocab: ['forsta', 'inte'],
    },
    {
      type: 'speak',
      text: 'Jag älskar verkligen musik!',
      en: 'I really love music!',
      vocab: ['alska', 'verkligen', 'musik'],
    },
  ],
})
