import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u06-l01',
  learn: [
    {
      title: 'Who, verb, the rest',
      text: 'A basic Swedish sentence is built just like an English one: first **who** (the subject), then the **verb**, then the rest.\n\n[[Jag dricker kaffe.]] (I drink coffee.)\n[[Hon jobbar idag.]] (She’s working today.)\n\nAnd remember: the verb has the same form for everyone, so it is jag dricker, du dricker, hon dricker, vi dricker.',
      table: {
        headers: ['Subject', 'Verb', 'The rest', 'English'],
        rows: [
          ['Jag', 'dricker', 'kaffe', 'I drink coffee'],
          ['Hon', 'jobbar', 'idag', 'She’s working today'],
          ['Vi', 'talar', 'svenska', 'We speak Swedish'],
          ['De', 'äter', 'glass', 'They’re eating ice cream'],
        ],
      },
    },
    {
      title: 'How often? Right after the verb',
      text: 'Words that say **how often** go straight **after the verb**, in the same spot as [[inte]].\n\nThis is the opposite of English! In English we say "I **always** drink", but Swedish says "I drink **always**": [[Jag dricker alltid kaffe.]]',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['Jag dricker alltid kaffe.', 'I always drink coffee.'],
          ['Hon jobbar ofta på lördagar.', 'She often works on Saturdays.'],
          ['Han läser ibland på kvällen.', 'He sometimes reads in the evening.'],
          ['Vi äter sällan glass.', 'We rarely eat ice cream.'],
          ['Jag dricker aldrig mjölk.', 'I never drink milk.'],
        ],
        svColumns: [0],
      },
      tip: 'Think of inte: [[Jag dricker inte kaffe]] → [[Jag dricker aldrig kaffe]]. Same place, different word. (ibland is a bit freer: you will also hear it at the start or the end of a sentence.)',
    },
    {
      title: 'Every day, in the morning',
      text: '[[varje]] means "every" and never changes: [[varje dag]], [[varje vecka]], [[varje år]].\n\nFor "in the morning" or "in the evening" in general, use **på** + the the-form: [[på morgonen]], [[på kvällen]]. These time phrases usually go at the **end** of the sentence.',
      examples: [
        { sv: 'Jag dricker te varje kväll.', en: 'I drink tea every evening.' },
        {
          sv: 'Hon dricker alltid kaffe på morgonen.',
          en: 'She always drinks coffee in the morning.',
        },
        { sv: 'Vi talar svenska varje dag.', en: 'We speak Swedish every day.' },
      ],
      tip: 'In morgon the g is silent: "MOR-on". The plural drops the o: en morgon, två morgnar.',
    },
  ],
  vocab: [
    { id: 'alltid', sv: 'alltid', en: 'always', pos: 'adverb', pron: 'AL-tid' },
    { id: 'ofta', sv: 'ofta', en: 'often', pos: 'adverb' },
    { id: 'ibland', sv: 'ibland', en: 'sometimes', pos: 'adverb', pron: 'ee-BLAND' },
    {
      id: 'sallan',
      sv: 'sällan',
      en: 'rarely / seldom',
      pos: 'adverb',
      enAlt: ['rarely', 'seldom'],
    },
    { id: 'aldrig', sv: 'aldrig', en: 'never', pos: 'adverb' },
    {
      id: 'varje',
      sv: 'varje',
      en: 'every / each',
      pos: 'pronoun',
      note: 'Never changes: varje dag, varje år.',
      enAlt: ['every', 'each'],
    },
    {
      id: 'dag',
      sv: 'dag',
      en: 'day',
      pos: 'noun',
      gender: 'en',
      pron: 'dahg (often just "dah")',
      forms: { definite: 'dagen', plural: 'dagar', pluralDefinite: 'dagarna' },
    },
    {
      id: 'morgon',
      sv: 'morgon',
      en: 'morning',
      pos: 'noun',
      gender: 'en',
      pron: 'MOR-on (silent g)',
      note: 'på morgonen = in the morning',
      forms: { definite: 'morgonen', plural: 'morgnar', pluralDefinite: 'morgnarna' },
    },
    {
      id: 'kvall',
      sv: 'kväll',
      en: 'evening',
      pos: 'noun',
      gender: 'en',
      note: 'på kvällen = in the evening',
      forms: { definite: 'kvällen', plural: 'kvällar', pluralDefinite: 'kvällarna' },
      enAlt: ['night'],
    },
    {
      id: 'te',
      sv: 'te',
      en: 'tea',
      pos: 'noun',
      gender: 'ett',
      pron: 'tay',
      forms: { definite: 'teet' },
    },
    {
      id: 'mjolk',
      sv: 'mjölk',
      en: 'milk',
      pos: 'noun',
      gender: 'en',
      pron: 'myölk (the j sounds like y)',
      forms: { definite: 'mjölken' },
    },
  ],
  dialogue: {
    title: 'Coffee or tea?',
    setting: 'Ahmed and Sara are colleagues. Ahmed is making coffee in the office kitchen.',
    lines: [
      { speaker: 'Ahmed', sv: 'Vill du ha kaffe, Sara?', en: 'Would you like some coffee, Sara?' },
      {
        speaker: 'Sara',
        sv: 'Nej tack, jag dricker aldrig kaffe.',
        en: 'No thanks, I never drink coffee.',
      },
      {
        speaker: 'Ahmed',
        sv: 'Aldrig? Jag dricker kaffe varje morgon!',
        en: 'Never? I drink coffee every morning!',
      },
      {
        speaker: 'Sara',
        sv: 'Jag dricker alltid te på morgonen.',
        en: 'I always drink tea in the morning.',
      },
      { speaker: 'Ahmed', sv: 'Och på kvällen?', en: 'And in the evening?' },
      { speaker: 'Sara', sv: 'Ibland ett glas mjölk.', en: 'Sometimes a glass of milk.' },
      {
        speaker: 'Ahmed',
        sv: 'Mjölk! Jag dricker sällan mjölk.',
        en: 'Milk! I rarely drink milk.',
      },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: 'I always drink coffee.',
      promptLang: 'en',
      question: 'Which sentence is correct?',
      choices: [
        'Jag dricker alltid kaffe.',
        'Jag alltid dricker kaffe.',
        'Alltid jag dricker kaffe.',
      ],
      answer: 'Jag dricker alltid kaffe.',
      explanation:
        'alltid goes right after the verb, in the same place as inte. English puts "always" before the verb; Swedish does not.',
      vocab: ['alltid', 'kaffe'],
    },
    {
      type: 'build',
      prompt: 'She often works on Saturdays.',
      answer: 'Hon jobbar ofta på lördagar.',
      accept: ['På lördagar jobbar hon ofta.', 'Ofta jobbar hon på lördagar.'],
      distractors: ['lördag'],
      explanation:
        'ofta comes straight after the verb jobbar. på lördagar (plural) means on Saturdays in general; på lördag means this Saturday.',
      vocab: ['ofta', 'lordag'],
    },
    {
      type: 'build',
      prompt: 'I never drink milk.',
      answer: 'Jag dricker aldrig mjölk.',
      accept: ['Aldrig dricker jag mjölk.', 'Mjölk dricker jag aldrig.'],
      distractors: ['inte'],
      explanation: 'aldrig (never) sits right after the verb, exactly where inte would go.',
      vocab: ['aldrig', 'mjolk'],
    },
    {
      type: 'build',
      prompt: 'He always reads in the evening.',
      answer: 'Han läser alltid på kvällen.',
      accept: ['På kvällen läser han alltid.', 'Alltid läser han på kvällen.'],
      distractors: ['kvällar'],
      explanation:
        'Verb, then alltid, then the time phrase at the end. "In the evening" is på kvällen, with the the-ending.',
      vocab: ['alltid', 'kvall'],
    },
    {
      type: 'gap',
      text: 'Jag äter ___ glass.',
      en: 'I rarely eat ice cream.',
      choices: ['sällan', 'ofta', 'alltid', 'aldrig'],
      answer: 'sällan',
      explanation: 'sällan means rarely. ofta = often, alltid = always, aldrig = never.',
      vocab: ['sallan', 'glass'],
    },
    {
      type: 'gap',
      text: 'Jag dricker kaffe ___ morgon.',
      en: 'I drink coffee every morning.',
      choices: ['varje', 'alla', 'på'],
      answer: 'varje',
      explanation:
        'varje (every) is followed by the plain noun: varje morgon. "In the morning" would be på morgonen, with the ending.',
      vocab: ['varje', 'morgon'],
    },
    {
      type: 'listen',
      audio: 'Hon dricker te varje kväll.',
      choices: [
        'She drinks tea every evening.',
        'She drinks tea every morning.',
        'She never drinks tea in the evening.',
      ],
      answer: 'She drinks tea every evening.',
      explanation: 'varje kväll = every evening. Morning is morgon.',
      vocab: ['te', 'varje', 'kvall'],
    },
    {
      type: 'dialogueReply',
      lines: [
        {
          speaker: 'Ahmed',
          sv: 'Dricker du kaffe på morgonen?',
          en: 'Do you drink coffee in the morning?',
        },
      ],
      question: 'You drink coffee every single morning. What do you say?',
      choices: [
        'Ja, jag dricker alltid kaffe på morgonen.',
        'Ja, jag alltid dricker kaffe på morgonen.',
        'Nej, jag dricker aldrig kaffe.',
      ],
      answer: 'Ja, jag dricker alltid kaffe på morgonen.',
      explanation: 'alltid comes after the verb: jag dricker alltid, never "jag alltid dricker".',
      vocab: ['alltid', 'morgon', 'kaffe'],
    },
    {
      type: 'type',
      prompt: 'I drink tea every day.',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'Jag dricker te varje dag.',
      accept: ['Varje dag dricker jag te.', 'Te dricker jag varje dag.'],
      explanation: 'Subject, verb, the rest: Jag dricker te, then the time phrase varje dag.',
      vocab: ['te', 'varje', 'dag'],
    },
    {
      type: 'speak',
      text: 'Jag dricker alltid kaffe på morgonen.',
      en: 'I always drink coffee in the morning.',
      vocab: ['alltid', 'kaffe', 'morgon'],
    },
  ],
})
