import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u02-l05',
  learn: [
    {
      title: 'Excuse me or sorry?',
      text: 'Swedish has two little words where English often uses "sorry":\n\n[[Ursäkta!]] (excuse me) gets someone\'s attention, or asks to get past.\n[[Förlåt!]] (sorry) is a real apology: you bumped into someone or made a mistake.\n\nThe friendly reply to an apology is [[Ingen fara!]] (no worries, literally "no danger").',
      examples: [
        { sv: 'Ursäkta, pratar du engelska?', en: 'Excuse me, do you speak English?' },
        { sv: 'Förlåt!', en: 'Sorry!' },
        { sv: 'Ingen fara!', en: 'No worries!' },
      ],
      tip: 'The rs in ursäkta sounds like "sh": "OO-shek-ta".',
    },
    {
      title: 'Thanks, thanks a lot, thanks a million',
      text: 'Swedes say [[tack]] all the time. Make it bigger when you mean it:',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['tack', 'thanks'],
          ['tack så mycket', 'thank you very much'],
          ['tusen tack', 'thanks a lot (literally "a thousand thanks")'],
        ],
        svColumns: [0],
      },
      tip: 'When someone thanks you, say "Ingen orsak!" (don\'t mention it). When you hand something over, say "Varsågod!"',
    },
    {
      title: 'Where is "please"?',
      text: 'In everyday requests, Swedes put **tack** at the end instead of "please": [[En kaffe, tack.]] (a coffee, please).\n\n[[Snälla]] also means "please", but it sounds insistent, almost pleading. Save it for when you really want something: [[Snälla, prata engelska!]] (please, speak English!).\n\nTwo more handy words: [[kanske]] (maybe) and [[okej]] (okay).',
      examples: [
        { sv: 'Ja, tack!', en: 'Yes, please!' },
        { sv: 'Kanske.', en: 'Maybe.' },
        { sv: 'Okej, tack!', en: 'Okay, thanks!' },
      ],
    },
  ],
  vocab: [
    {
      id: 'ursakta',
      sv: 'ursäkta',
      en: 'excuse me',
      pos: 'interjection',
      pron: 'OO-shek-ta (rs sounds like "sh")',
      note: 'To get attention, to get past someone, or as "sorry?" when you didn’t hear.',
    },
    {
      id: 'forlat',
      sv: 'förlåt',
      en: 'sorry',
      pos: 'interjection',
      pron: 'fur-LOHT',
      note: 'A real apology.',
    },
    {
      id: 'ingen-fara',
      sv: 'ingen fara',
      en: 'no worries / no problem',
      pos: 'phrase',
      pron: 'ING-en FAH-ra',
      note: 'Literally "no danger". The reply to förlåt.',
      enAlt: ['no worries', 'no problem'],
    },
    {
      id: 'snalla',
      sv: 'snälla',
      en: 'please (when pleading)',
      pos: 'interjection',
      pron: 'SNEL-la',
      note: 'Sounds insistent or pleading. For ordinary requests, use tack: En kaffe, tack.',
      enAlt: ['please'],
    },
    {
      id: 'tack-sa-mycket',
      sv: 'tack så mycket',
      en: 'thank you very much',
      pos: 'phrase',
      pron: 'tack soh MICK-keh (round your lips on the i)',
      enAlt: ['thanks very much', 'thank you so much'],
    },
    {
      id: 'tusen-tack',
      sv: 'tusen tack',
      en: 'thanks a lot',
      pos: 'phrase',
      pron: 'TOO-sen tack',
      note: 'Literally "a thousand thanks".',
      enAlt: ['a thousand thanks', 'thanks a million'],
    },
    {
      id: 'ingen-orsak-u2',
      sv: 'ingen orsak',
      en: 'don’t mention it',
      pos: 'phrase',
      pron: 'ING-en OO-shahk',
      note: 'A reply to tack. Literally "no reason".',
      enAlt: ["don't mention it", "you're welcome", 'no problem'],
    },
    {
      id: 'kanske',
      sv: 'kanske',
      en: 'maybe',
      pos: 'adverb',
      pron: 'KAN-sheh',
      note: 'sk before e sounds like "sh", as you learned in Unit 1.',
      enAlt: ['perhaps'],
    },
    {
      id: 'okej',
      sv: 'okej',
      en: 'okay',
      pos: 'interjection',
      pron: 'oh-KAY',
      alt: ['ok'],
      enAlt: ['ok'],
    },
  ],
  dialogue: {
    title: 'A busy café',
    setting: 'Ali is meeting Lina for the first time, at a crowded café. He bumps into her chair.',
    lines: [
      { speaker: 'Ali', sv: 'Oj, förlåt!', en: 'Oops, sorry!' },
      { speaker: 'Lina', sv: 'Ingen fara!', en: 'No worries!' },
      { speaker: 'Ali', sv: 'Ursäkta, är du Lina?', en: 'Excuse me, are you Lina?' },
      {
        speaker: 'Lina',
        sv: 'Ja! Och du är Ali? Välkommen! Kaffe?',
        en: 'Yes! And you’re Ali? Welcome! Coffee?',
      },
      { speaker: 'Ali', sv: 'Ja, tack så mycket!', en: 'Yes, thank you very much!' },
      { speaker: 'Lina', sv: 'Varsågod!', en: 'Here you go!' },
      { speaker: 'Ali', sv: 'Tusen tack!', en: 'Thanks a lot!' },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: 'You bump into someone on the bus.',
      promptLang: 'en',
      question: 'What do you say?',
      choices: ['Förlåt!', 'Tusen tack!', 'Varsågod!'],
      answer: 'Förlåt!',
      explanation: 'Förlåt is a real apology: "sorry!"',
      vocab: ['forlat'],
    },
    {
      type: 'mcq',
      prompt: 'You want to ask a stranger a question.',
      promptLang: 'en',
      question: 'How do you start?',
      choices: [
        'Ursäkta, pratar du engelska?',
        'Ingen fara, pratar du engelska?',
        'Tusen tack, pratar du engelska?',
      ],
      answer: 'Ursäkta, pratar du engelska?',
      explanation: 'Ursäkta (excuse me) is how you get someone’s attention.',
      vocab: ['ursakta'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Erik', sv: 'Förlåt!', en: 'Sorry!' }],
      question: 'Erik stepped on your foot, but it doesn’t matter. What do you say?',
      choices: ['Ingen fara!', 'Tack så mycket!', 'Välkommen!'],
      answer: 'Ingen fara!',
      explanation: 'Ingen fara (no worries) is the friendly reply to förlåt.',
      vocab: ['ingen-fara'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Maja', sv: 'Tack så mycket!', en: 'Thank you very much!' }],
      question: 'You helped Maja. How do you reply?',
      choices: ['Ingen orsak!', 'Förlåt!', 'Kanske.'],
      answer: 'Ingen orsak!',
      explanation: 'Ingen orsak means "don’t mention it", a reply to tack.',
      vocab: ['ingen-orsak-u2', 'tack-sa-mycket'],
    },
    {
      type: 'gap',
      text: 'En kaffe, ___.',
      en: 'A coffee, please.',
      choices: ['tack', 'okej', 'förlåt'],
      answer: 'tack',
      explanation: 'In everyday requests, Swedes say tack where English says "please".',
    },
    {
      type: 'build',
      prompt: 'Thank you very much!',
      answer: 'Tack så mycket!',
      distractors: ['tusen', 'snälla'],
      explanation: 'Tack så mycket is literally "thanks so much".',
      vocab: ['tack-sa-mycket'],
    },
    {
      type: 'build',
      prompt: 'Excuse me, do you speak Swedish?',
      answer: 'Ursäkta, pratar du svenska?',
      distractors: ['tack', 'engelska'],
      explanation:
        'Ursäkta gets attention, and a yes/no question starts with the verb: pratar du …?',
      vocab: ['ursakta', 'prata', 'svenska'],
    },
    {
      type: 'listen',
      audio: 'Okej, tusen tack!',
      choices: ['Okay, thanks a lot!', 'Maybe, thank you!', 'No worries, thanks!'],
      answer: 'Okay, thanks a lot!',
      vocab: ['okej', 'tusen-tack'],
    },
    {
      type: 'dictation',
      audio: 'Ursäkta, är du Erik?',
      en: 'Excuse me, are you Erik?',
      vocab: ['ursakta'],
    },
    {
      type: 'speak',
      text: 'Snälla, prata engelska!',
      en: 'Please, speak English!',
      vocab: ['snalla', 'prata', 'engelska'],
    },
  ],
})
