import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u02-l04',
  learn: [
    {
      title: 'Where are you from?',
      text: 'Ask [[Var kommer du ifrån?]] (where are you from?). Answer with [[Jag kommer från …]] and a place.\n\nNotice the two forms of "from": **ifrån** usually sits at the very end of the question, and **från** goes right before the place. (In speech you will also hear *Var kommer du från?* Both are fine.)',
      examples: [
        { sv: 'Var kommer du ifrån?', en: 'Where are you from?' },
        { sv: 'Jag kommer från England.', en: "I'm from England." },
        { sv: 'Jag kommer från Sverige.', en: "I'm from Sweden." },
        { sv: 'Hon kommer från Syrien.', en: "She's from Syria." },
      ],
      tip: "Country names start with a capital letter (Sverige), but languages don't (svenska, engelska).",
    },
    {
      title: 'Where do you live?',
      text: 'Ask [[Var bor du?]] and answer with **bor i** + the place: [[Jag bor i Göteborg.]] (I live in Gothenburg).\n\nYou now know three question words. They always come first:',
      table: {
        headers: ['Swedish', 'English', 'Example'],
        rows: [
          ['vad', 'what', 'Vad heter du?'],
          ['hur', 'how', 'Hur mår du?'],
          ['var', 'where', 'Var bor du?'],
        ],
        svColumns: [0, 2],
      },
      tip: 'Var and vad sound alike. Listen for the r at the end of var (where).',
    },
    {
      title: 'Do you speak Swedish?',
      text: 'For a yes/no question, simply put the verb first: [[Du pratar svenska.]] (you speak Swedish) becomes [[Pratar du svenska?]] (do you speak Swedish?).\n\nThe honest answer for now: [[Ja, lite.]] (yes, a little).',
      examples: [
        { sv: 'Pratar du engelska?', en: 'Do you speak English?' },
        { sv: 'Ja, lite.', en: 'Yes, a little.' },
        {
          sv: 'Jag pratar engelska och lite svenska.',
          en: 'I speak English and a little Swedish.',
        },
      ],
    },
  ],
  vocab: [
    {
      id: 'var-where',
      sv: 'var',
      en: 'where',
      pos: 'adverb',
      pron: 'vahr',
      note: 'Don’t mix it up with vad (what).',
    },
    {
      id: 'komma',
      sv: 'komma',
      en: 'to come',
      pos: 'verb',
      pron: 'KOM-ma',
      forms: { present: 'kommer', past: 'kom', supine: 'kommit', imperative: 'kom' },
    },
    {
      id: 'ifran',
      sv: 'ifrån',
      en: 'from (at the end of a question)',
      pos: 'adverb',
      pron: 'ee-FROHN',
      note: 'Var kommer du ifrån? The answer uses från: Jag kommer från …',
    },
    {
      id: 'fran-u2',
      sv: 'från',
      en: 'from',
      pos: 'preposition',
      pron: 'frohn',
      note: 'Goes right before the place: Jag kommer från Kanada.',
    },
    {
      id: 'bo',
      sv: 'bo',
      en: 'to live (somewhere)',
      pos: 'verb',
      pron: 'boo',
      forms: { present: 'bor', past: 'bodde', supine: 'bott', imperative: 'bo' },
      note: 'For where you live: Jag bor i Malmö.',
      enAlt: ['to live', 'live'],
    },
    { id: 'i', sv: 'i', en: 'in', pos: 'preposition', pron: 'ee' },
    {
      id: 'sverige',
      sv: 'Sverige',
      en: 'Sweden',
      pos: 'other',
      pron: 'SVAIR-yeh',
      note: 'The g is soft, like a y. Country names have a capital letter.',
    },
    {
      id: 'svenska',
      sv: 'svenska',
      en: 'Swedish (the language)',
      pos: 'other',
      pron: 'SVEN-ska',
      note: 'Languages have a small letter and no en or ett: Jag pratar svenska.',
      enAlt: ['Swedish'],
    },
    {
      id: 'engelska',
      sv: 'engelska',
      en: 'English (the language)',
      pos: 'other',
      pron: 'ENG-el-ska',
      enAlt: ['English'],
    },
    {
      id: 'prata',
      sv: 'prata',
      en: 'to speak / talk',
      pos: 'verb',
      pron: 'PRAH-ta',
      forms: { present: 'pratar', past: 'pratade', supine: 'pratat', imperative: 'prata' },
      enAlt: ['to speak', 'to talk', 'speak', 'talk'],
    },
    {
      id: 'lite',
      sv: 'lite',
      en: 'a little',
      pos: 'adverb',
      pron: 'LEE-teh',
      enAlt: ['a bit', 'little'],
    },
  ],
  dialogue: {
    title: 'At the language café',
    setting: 'Johan and Amira meet at a language café in Gothenburg.',
    lines: [
      { speaker: 'Johan', sv: 'Hej! Var kommer du ifrån?', en: 'Hi! Where are you from?' },
      { speaker: 'Amira', sv: 'Jag kommer från Syrien. Och du?', en: "I'm from Syria. And you?" },
      {
        speaker: 'Johan',
        sv: 'Jag kommer från Umeå. Var bor du?',
        en: "I'm from Umeå. Where do you live?",
      },
      { speaker: 'Amira', sv: 'Jag bor i Göteborg.', en: 'I live in Gothenburg.' },
      { speaker: 'Johan', sv: 'Pratar du arabiska?', en: 'Do you speak Arabic?' },
      {
        speaker: 'Amira',
        sv: 'Ja, och engelska. Och lite svenska!',
        en: 'Yes, and English. And a little Swedish!',
      },
      { speaker: 'Johan', sv: 'Du pratar jättebra svenska!', en: 'You speak great Swedish!' },
      { speaker: 'Amira', sv: 'Tack!', en: 'Thanks!' },
    ],
  },
  exercises: [
    {
      type: 'build',
      prompt: 'Where are you from?',
      answer: 'Var kommer du ifrån?',
      distractors: ['i', 'vad'],
      explanation: 'Var (where) comes first, and ifrån goes at the very end of the question.',
      vocab: ['var-where', 'komma', 'ifran'],
    },
    {
      type: 'build',
      prompt: 'I live in Sweden.',
      answer: 'Jag bor i Sverige.',
      distractors: ['från', 'kommer'],
      explanation: 'Bor i + place: Jag bor i Sverige.',
      vocab: ['bo', 'i', 'sverige'],
    },
    {
      type: 'gap',
      text: 'Var kommer du ___?',
      en: 'Where are you from?',
      choices: ['ifrån', 'i', 'vad'],
      answer: 'ifrån',
      explanation: 'At the end of the question, "from" is ifrån.',
      vocab: ['ifran'],
    },
    {
      type: 'gap',
      text: 'Jag kommer ___ Kanada.',
      en: "I'm from Canada.",
      choices: ['från', 'i', 'var'],
      answer: 'från',
      explanation: 'Right before the place, "from" is från: Jag kommer från Kanada.',
      vocab: ['fran-u2', 'komma'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Maja', sv: 'Pratar du svenska?', en: 'Do you speak Swedish?' }],
      question: 'You speak a little Swedish. What do you answer?',
      choices: ['Ja, lite.', 'Jag bor i Sverige.', 'Var bor du?'],
      answer: 'Ja, lite.',
      explanation: 'Maja asks a yes/no question, so start with ja. Lite means "a little".',
      vocab: ['lite'],
    },
    {
      type: 'listen',
      audio: 'Var bor du?',
      choices: ['Where do you live?', 'Where are you from?', "What's your name?"],
      answer: 'Where do you live?',
      explanation: 'Bor means "live". "Where are you from?" would be Var kommer du ifrån?',
      vocab: ['var-where', 'bo'],
    },
    {
      type: 'listen',
      audio: 'Hon pratar engelska och lite svenska.',
      choices: [
        'She speaks English and a little Swedish.',
        'He speaks Swedish and a little English.',
        'She lives in England and speaks Swedish.',
      ],
      answer: 'She speaks English and a little Swedish.',
      vocab: ['prata', 'engelska', 'svenska', 'lite'],
    },
    {
      type: 'type',
      prompt: 'Do you speak English?',
      promptLang: 'en',
      answer: 'Pratar du engelska?',
      explanation: 'In a yes/no question the verb comes first: Pratar du …?',
      vocab: ['prata', 'engelska'],
    },
    {
      type: 'dictation',
      audio: 'Jag bor i Sverige och pratar svenska.',
      en: 'I live in Sweden and speak Swedish.',
      vocab: ['bo', 'sverige', 'prata', 'svenska'],
    },
    {
      type: 'speak',
      text: 'Jag pratar lite svenska.',
      en: 'I speak a little Swedish.',
      vocab: ['prata', 'lite', 'svenska'],
    },
  ],
})
