import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u02-l01',
  learn: [
    {
      title: 'One hello for everyone',
      text: 'You already know [[Hej!]] It is the Swedish hello for every situation: your best friend, a shop assistant, your boss, your neighbour. Swedes say it all day long.\n\nTwo friendly variations: [[Hejsan!]] is a warm "hi there", and [[Tjena!]] is a casual "hey" you only use with friends.',
      table: {
        headers: ['Swedish', 'Means', 'Use it with'],
        rows: [
          ['hej', 'hi / hello', 'anyone, any time'],
          ['hejsan', 'hi there', 'anyone, a little warmer'],
          ['tjena', 'hey', 'friends only'],
        ],
        svColumns: [0],
      },
    },
    {
      title: 'Morning, evening, night',
      text: 'For a slightly more polite greeting, use the time of day. Watch the spelling: [[god morgon]] is said "go morron", and the **d** in **god** is silent in all of these.',
      table: {
        headers: ['Swedish', 'English', 'When'],
        rows: [
          ['god morgon', 'good morning', 'until about 10 in the morning'],
          ['god kväll', 'good evening', 'in the evening (a bit formal)'],
          ['god natt', 'good night', 'when someone goes to bed, or you part late at night'],
        ],
        svColumns: [0],
      },
      tip: 'In the middle of the day, just say hej. "God dag" exists, but it sounds very old-fashioned.',
    },
    {
      title: 'Goodbye and welcome',
      text: 'The everyday goodbye is [[Hej då!]] Add [[Vi ses!]] (see you) or [[Ha det bra!]] (take care, literally "have it good").\n\nWhen someone arrives, say [[Välkommen!]] To a group, it becomes [[Välkomna!]]',
      examples: [
        { sv: 'Hej då! Vi ses!', en: 'Bye! See you!' },
        { sv: 'Ha det bra!', en: 'Take care!' },
        { sv: 'Välkommen, Anna!', en: 'Welcome, Anna!' },
        { sv: 'Välkomna!', en: 'Welcome! (to several people)' },
      ],
      tip: 'Swedes often say "hej hej!" as a quick, cheerful bye.',
    },
  ],
  vocab: [
    {
      id: 'hejsan',
      sv: 'hejsan',
      en: 'hi there',
      pos: 'interjection',
      pron: 'HAY-san',
      note: 'A friendly hello. Works with friends, in shops, almost everywhere.',
      enAlt: ['hi', 'hello'],
    },
    {
      id: 'hej-da',
      sv: 'hej då',
      en: 'bye / goodbye',
      pos: 'phrase',
      pron: 'hey DOH',
      note: 'The everyday goodbye, for anyone.',
      enAlt: ['bye', 'goodbye'],
    },
    {
      id: 'god-morgon',
      sv: 'god morgon',
      en: 'good morning',
      pos: 'phrase',
      pron: 'goo MORR-on',
      note: 'Spelled "god morgon" but said "go morron". The d in god is silent.',
    },
    {
      id: 'god-kvall',
      sv: 'god kväll',
      en: 'good evening',
      pos: 'phrase',
      pron: 'goo KVELL',
      note: 'A little formal. Among friends, hej is more common in the evening too.',
    },
    {
      id: 'god-natt',
      sv: 'god natt',
      en: 'good night',
      pos: 'phrase',
      pron: 'goo NATT',
      note: 'Only when someone goes to bed or you say goodbye late at night.',
    },
    {
      id: 'vi-ses',
      sv: 'vi ses',
      en: 'see you',
      pos: 'phrase',
      pron: 'vee SAYSS',
      note: 'Literally "we see each other".',
      enAlt: ['see you later'],
    },
    {
      id: 'ha-det-bra',
      sv: 'ha det bra',
      en: 'take care',
      pos: 'phrase',
      pron: 'ha deh BRAH',
      note: 'Literally "have it good". The t in det is silent.',
      enAlt: ['all the best', 'have a good one'],
    },
    {
      id: 'valkommen',
      sv: 'välkommen',
      en: 'welcome',
      pos: 'adjective',
      pron: 'VELL-kom-men',
      forms: { neuter: 'välkommet', plural: 'välkomna' },
      note: 'Say välkomna to two or more people.',
    },
    {
      id: 'tjena',
      sv: 'tjena',
      en: 'hey (casual)',
      pos: 'interjection',
      pron: 'SHAY-na (the soft tj-sound)',
      note: 'Very casual, for friends. Starts with the tj-sound from Unit 1.',
      enAlt: ['hey', 'hiya'],
    },
  ],
  dialogue: {
    title: 'Dinner at Erik’s',
    setting: 'Sara arrives at Erik’s place for dinner. Later that night, she goes home.',
    lines: [
      { speaker: 'Erik', sv: 'Hejsan, Sara! Välkommen!', en: 'Hi there, Sara! Welcome!' },
      { speaker: 'Sara', sv: 'Tack! Hej, Erik!', en: 'Thanks! Hi, Erik!' },
      { speaker: 'Erik', sv: 'Kaffe?', en: 'Coffee?' },
      { speaker: 'Sara', sv: 'Ja, gärna!', en: 'Yes, I’d love some!' },
      { speaker: 'Erik', sv: 'Varsågod!', en: 'Here you go!' },
      { speaker: 'Sara', sv: 'Hej då, Erik! Tack!', en: 'Bye, Erik! Thank you!' },
      { speaker: 'Erik', sv: 'Hej då! Ha det bra!', en: 'Bye! Take care!' },
      { speaker: 'Sara', sv: 'Vi ses! God natt!', en: 'See you! Good night!' },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: "It's 7:30 in the morning and you meet your neighbour.",
      promptLang: 'en',
      question: 'What do you say?',
      choices: ['God morgon!', 'God natt!', 'God kväll!'],
      answer: 'God morgon!',
      explanation:
        'God morgon is for the morning. God natt is only for bedtime, and god kväll for the evening.',
      vocab: ['god-morgon', 'god-natt', 'god-kvall'],
    },
    {
      type: 'mcq',
      prompt: 'You meet your best friend at a café.',
      promptLang: 'en',
      question: 'Which greeting is the most casual?',
      choices: ['Tjena!', 'God kväll!', 'God morgon!'],
      answer: 'Tjena!',
      explanation:
        'Tjena is a relaxed "hey" between friends. God morgon and god kväll are more polite.',
      vocab: ['tjena'],
    },
    {
      type: 'listen',
      audio: 'Hej då! Vi ses!',
      choices: ['Bye! See you!', 'Hi! Welcome!', 'Good night! Take care!'],
      answer: 'Bye! See you!',
      vocab: ['hej-da', 'vi-ses'],
    },
    {
      type: 'minimalPair',
      focus: 'One person or a group?',
      options: [
        { sv: 'välkommen', en: 'welcome (to one person)' },
        { sv: 'välkomna', en: 'welcome (to a group)' },
      ],
      answer: 'välkomna',
      explanation: 'Välkomna, ending in -a, is what you say to two or more people.',
      vocab: ['valkommen'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Johan', sv: 'Hej då! Ha det bra!', en: 'Bye! Take care!' }],
      question: 'Johan is leaving. Pick a natural reply.',
      choices: ['Hej då! Vi ses!', 'Välkommen!', 'God morgon!'],
      answer: 'Hej då! Vi ses!',
      explanation:
        'He is saying goodbye, so you say goodbye back. Välkommen is for someone arriving.',
      vocab: ['hej-da', 'vi-ses', 'ha-det-bra'],
    },
    {
      type: 'gap',
      text: 'Hej då! Vi ___!',
      en: 'Bye! See you!',
      choices: ['ses', 'bra', 'natt'],
      answer: 'ses',
      explanation: 'Vi ses means "see you" (literally "we see each other").',
      vocab: ['vi-ses'],
    },
    {
      type: 'build',
      prompt: 'Good morning, Anna!',
      answer: 'God morgon, Anna!',
      distractors: ['natt', 'då'],
      explanation: 'God morgon: god (good) + morgon (morning), said "go morron".',
      vocab: ['god-morgon'],
    },
    {
      type: 'build',
      prompt: 'Bye, take care!',
      answer: 'Hej då, ha det bra!',
      distractors: ['ses', 'god'],
      explanation: 'Ha det bra is literally "have it good", the Swedish way to say "take care".',
      vocab: ['hej-da', 'ha-det-bra'],
    },
    {
      type: 'dictation',
      audio: 'God kväll! Välkommen!',
      en: 'Good evening! Welcome!',
      vocab: ['god-kvall', 'valkommen'],
    },
    {
      type: 'speak',
      text: 'Hejsan! Välkommen!',
      en: 'Hi there! Welcome!',
      vocab: ['hejsan', 'valkommen'],
    },
  ],
})
