import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u02-l06',
  learn: [
    {
      title: 'All the people words',
      text: 'Here is the full set of Swedish personal pronouns. You know four already. The verb never changes: [[jag heter]], [[vi heter]], [[de heter]].',
      table: {
        headers: ['Swedish', 'English', 'Sounds like'],
        rows: [
          ['jag', 'I', 'yah'],
          ['du', 'you (one person)', 'doo'],
          ['han', 'he', 'hann'],
          ['hon', 'she', 'hoon'],
          ['hen', 'they (one person, no gender)', 'hen'],
          ['vi', 'we', 'vee'],
          ['ni', 'you (two or more)', 'nee'],
          ['de', 'they', 'dom'],
        ],
        svColumns: [0],
      },
    },
    {
      title: '"De" sounds like "dom"',
      text: 'One spelling trap: **de** (they) is written *de* but said "dom". [[De bor i Sverige.]] (they live in Sweden).\n\nAnd when you talk to two or more people, "you" is **ni**: [[Var bor ni?]] (where do you live?).',
      examples: [
        { sv: 'De pratar svenska.', en: 'They speak Swedish.' },
        { sv: 'Vi kommer från England.', en: 'We come from England.' },
        { sv: 'Var kommer ni ifrån?', en: 'Where are you (all) from?' },
        { sv: 'Hen heter Kim.', en: 'Their name is Kim.' },
      ],
    },
    {
      title: 'I am teacher?',
      text: 'When you say what job someone has, Swedish drops "a": [[Jag är lärare.]] means "I am a teacher" (literally "I am teacher").',
      examples: [
        { sv: 'Hon är lärare.', en: 'She is a teacher.' },
        { sv: 'Han är chef.', en: 'He is a manager.' },
        { sv: 'Vi är kollegor.', en: 'We are colleagues.' },
      ],
      tip: 'Chef is a false friend: it means "boss" or "manager". A chef in a kitchen is a kock.',
    },
  ],
  culture: {
    title: 'Everyone is "du"',
    text: 'Until the 1960s, Swedish politeness was complicated. You avoided the word "you" with people you didn\'t know well, and used titles instead: "Would the doctor like some coffee?" Even **ni** could feel rude.\n\nThen, in just a few years at the end of the 1960s, came the **du-reform** (*du-reformen*). A famous moment was in 1967, when Bror Rexed, the new head of the National Board of Health and Welfare (Socialstyrelsen), told his staff that he would say **du** to everyone, and that they should say **du** to him.\n\nToday almost everyone says [[du]]: to your boss, your teacher, your doctor, even to government ministers. People use first names too. Your teacher is just *Anna*, not *Mrs Andersson*. The main exception is the royal family, who are still addressed with titles.\n\n[[Ni]] is the normal word for "you" when you talk to two or more people. Using *ni* politely to one person is rare. Some shop staff use it with older customers, but many Swedes find it distant or old-fashioned.\n\n**Hen** is a gender-neutral pronoun, first suggested in the 1960s. It became widely used in the 2010s and was added to SAOL, the Swedish Academy\'s official word list, in 2015. Use it for someone whose gender you don\'t know or that doesn\'t matter, and for people who are neither *han* nor *hon*.',
    tip: 'When in doubt, say du. It is almost never rude in Sweden.',
  },
  vocab: [
    { id: 'vi', sv: 'vi', en: 'we', pos: 'pronoun', pron: 'vee' },
    {
      id: 'ni',
      sv: 'ni',
      en: 'you (two or more)',
      pos: 'pronoun',
      pron: 'nee',
      note: 'For talking to a group. As a polite "you" to one person, it is rare today.',
      enAlt: ['you', 'you all', 'you guys'],
    },
    {
      id: 'de',
      sv: 'de',
      en: 'they',
      pos: 'pronoun',
      pron: 'dom',
      note: 'Written de, said "dom".',
    },
    {
      id: 'hen',
      sv: 'hen',
      en: 'they (one person, gender-neutral)',
      pos: 'pronoun',
      pron: 'hen',
      note: 'For one person when gender is unknown or doesn’t matter. In SAOL since 2015.',
    },
    {
      id: 'alla',
      sv: 'alla',
      en: 'everyone / all',
      pos: 'pronoun',
      pron: 'AL-la',
      enAlt: ['everyone', 'everybody', 'all'],
    },
    {
      id: 'larare',
      sv: 'lärare',
      en: 'teacher',
      pos: 'noun',
      gender: 'en',
      pron: 'LAIR-a-reh',
      forms: { definite: 'läraren', plural: 'lärare', pluralDefinite: 'lärarna' },
    },
    {
      id: 'chef',
      sv: 'chef',
      en: 'boss / manager',
      pos: 'noun',
      gender: 'en',
      pron: 'shayf',
      forms: { definite: 'chefen', plural: 'chefer', pluralDefinite: 'cheferna' },
      note: 'Not a cook! A cook is en kock.',
      enAlt: ['boss', 'manager'],
    },
    {
      id: 'kollega',
      sv: 'kollega',
      en: 'colleague',
      pos: 'noun',
      gender: 'en',
      pron: 'kol-LAY-ga',
      forms: { definite: 'kollegan', plural: 'kollegor', pluralDefinite: 'kollegorna' },
      enAlt: ['co-worker', 'workmate'],
    },
  ],
  dialogue: {
    title: 'First day at work',
    setting: 'Sara starts a new job at an office. Her boss, Johan, welcomes her.',
    lines: [
      {
        speaker: 'Johan',
        sv: 'Hej, Sara! Välkommen! Jag heter Johan.',
        en: "Hi, Sara! Welcome! I'm Johan.",
      },
      { speaker: 'Sara', sv: 'Hej! Är du chefen?', en: 'Hi! Are you the boss?' },
      {
        speaker: 'Johan',
        sv: 'Ja. Och det här är Lina och Omar.',
        en: 'Yes. And this is Lina and Omar.',
      },
      { speaker: 'Lina', sv: 'Hej! Nu är vi kollegor!', en: "Hi! Now we're colleagues!" },
      { speaker: 'Sara', sv: 'Trevligt att träffas!', en: 'Nice to meet you!' },
      {
        speaker: 'Omar',
        sv: 'Detsamma! Här säger alla du.',
        en: 'Likewise! Everyone says "du" here.',
      },
      { speaker: 'Johan', sv: 'Ja, alla. Jag också!', en: 'Yes, everyone. Me too!' },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: 'You are talking to your new boss in Sweden.',
      promptLang: 'en',
      question: 'Which word for "you" is normal?',
      choices: ['du', 'ni', 'hen'],
      answer: 'du',
      explanation:
        'Since the du-reform, Swedes say du to almost everyone, bosses and doctors included. Ni to one person sounds distant.',
      vocab: ['du', 'ni'],
    },
    {
      type: 'mcq',
      prompt: 'Kim',
      promptLang: 'en',
      question: 'You don’t know if Kim is a man or a woman. Which word fits best?',
      choices: ['hen', 'han', 'hon'],
      answer: 'hen',
      explanation: 'Hen is the gender-neutral pronoun for one person.',
      vocab: ['hen'],
    },
    {
      type: 'listen',
      audio: 'De bor i Sverige.',
      question: 'Remember: de is said "dom".',
      choices: ['They live in Sweden.', 'We live in Sweden.', 'You live in Sweden.'],
      answer: 'They live in Sweden.',
      vocab: ['de'],
    },
    {
      type: 'gap',
      text: '___ är kollegor.',
      en: 'We are colleagues.',
      choices: ['Vi', 'Hen', 'Jag'],
      answer: 'Vi',
      explanation: 'Vi means "we". Kollegor is plural, so it needs more than one person.',
      vocab: ['vi', 'kollega'],
    },
    {
      type: 'gap',
      text: 'Hej ___!',
      en: 'Hi, everyone!',
      choices: ['alla', 'de', 'hen'],
      answer: 'alla',
      explanation: 'Alla means "everyone". Hej alla! is a common way to greet a group.',
      vocab: ['alla'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Lina', sv: 'Var kommer ni ifrån?', en: 'Where are you (both) from?' }],
      question: 'You and your friend are both from England. Answer for the two of you.',
      choices: ['Vi kommer från England.', 'De kommer från England.', 'Ni kommer från England.'],
      answer: 'Vi kommer från England.',
      explanation: 'Lina asks ni (you two), so you answer vi (we).',
      vocab: ['ni', 'vi'],
    },
    {
      type: 'build',
      prompt: 'She is a teacher.',
      answer: 'Hon är lärare.',
      distractors: ['en', 'han'],
      explanation: 'With jobs, Swedish drops the "a": Hon är lärare.',
      vocab: ['larare', 'hon'],
    },
    {
      type: 'build',
      prompt: 'They are colleagues.',
      answer: 'De är kollegor.',
      distractors: ['dom', 'kollega'],
      explanation: 'They = de (said "dom"). Colleagues = kollegor, the plural of kollega.',
      vocab: ['de', 'kollega'],
    },
    {
      type: 'dictation',
      audio: 'Vi är lärare och han är chef.',
      en: "We're teachers and he's a manager.",
      vocab: ['vi', 'larare', 'chef'],
    },
    {
      type: 'speak',
      text: 'De heter Erik och Maja.',
      en: 'Their names are Erik and Maja.',
      vocab: ['de'],
    },
  ],
})
