import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u02-l02',
  learn: [
    {
      title: '"I am called …"',
      text: 'Swedes rarely say "my name is" (*mitt namn är* sounds stiff). They say "I am called": [[Jag heter Anna.]]\n\nThe best part: **heter** stays the same for everyone. No "am / is / are" to juggle.',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['jag heter', 'I am called / my name is'],
          ['du heter', 'you are called / your name is'],
          ['han heter', 'he is called / his name is'],
          ['hon heter', 'she is called / her name is'],
        ],
        svColumns: [0],
      },
      examples: [{ sv: 'Maja är ett fint namn.', en: 'Maja is a nice name.' }],
      tip: 'Han = he, hon = she. One letter apart, so take a second look!',
    },
    {
      title: 'The question word goes first',
      text: 'To ask a question, put the question word first, then the verb, then the person: [[Vad heter du?]] (literally "What are-called you?").\n\nCompare the answer, where the person comes first: [[Jag heter Erik.]]',
      examples: [
        { sv: 'Vad heter du?', en: "What's your name?" },
        { sv: 'Vad heter hon?', en: "What's her name?" },
        { sv: 'Hon heter Maja.', en: 'Her name is Maja.' },
      ],
      tip: 'In everyday speech, vad is often just "va".',
    },
    {
      title: 'Nice to meet you!',
      text: 'When you meet someone new, say [[Trevligt att träffas!]] (nice to meet you). The easy reply is [[Detsamma!]] (likewise).',
      examples: [
        { sv: 'Trevligt att träffas!', en: 'Nice to meet you!' },
        { sv: 'Detsamma!', en: 'Likewise!' },
      ],
      tip: 'Swedes usually shake hands and say just their first name: "Hej, Johan!"',
    },
  ],
  vocab: [
    {
      id: 'jag',
      sv: 'jag',
      en: 'I',
      pos: 'pronoun',
      pron: 'yah (the g is usually silent)',
      note: 'Written with a small j, unless it starts a sentence.',
    },
    {
      id: 'du',
      sv: 'du',
      en: 'you (one person)',
      pos: 'pronoun',
      pron: 'doo, with the tongue forward and lips tightly rounded',
      enAlt: ['you'],
    },
    { id: 'han', sv: 'han', en: 'he', pos: 'pronoun', pron: 'hann (short a)' },
    {
      id: 'hon',
      sv: 'hon',
      en: 'she',
      pos: 'pronoun',
      pron: 'hoon (short)',
      note: 'han = he, hon = she.',
    },
    {
      id: 'heta',
      sv: 'heta',
      en: 'to be called',
      pos: 'verb',
      pron: 'HAY-ta',
      forms: { present: 'heter', past: 'hette', supine: 'hetat' },
      note: 'Jag heter … = My name is … (literally "I am called …").',
      enAlt: ['be called', 'to be named'],
    },
    {
      id: 'vad',
      sv: 'vad',
      en: 'what',
      pos: 'pronoun',
      pron: 'vah (the d is often silent)',
    },
    {
      id: 'namn',
      sv: 'namn',
      en: 'name',
      pos: 'noun',
      gender: 'ett',
      pron: 'nahmn (say both m and n)',
      forms: { definite: 'namnet', plural: 'namn', pluralDefinite: 'namnen' },
      note: 'You see Namn: on forms. To ask for a name, just say Vad heter du?',
    },
    {
      id: 'trevligt',
      sv: 'trevligt',
      en: 'nice / pleasant',
      pos: 'adjective',
      pron: 'TRAYV-lit (the g is silent)',
      note: 'The -t form of trevlig (nice), used in Trevligt att träffas!',
      enAlt: ['nice', 'pleasant'],
    },
    {
      id: 'trevligt-att-traffas-u2',
      sv: 'trevligt att träffas',
      en: 'nice to meet you',
      pos: 'phrase',
      pron: 'TRAYV-lit att TREFF-as',
    },
    {
      id: 'detsamma',
      sv: 'detsamma',
      en: 'likewise / same to you',
      pos: 'phrase',
      pron: 'deh-SAM-ma',
      note: 'The reply to Trevligt att träffas! or Ha det bra!',
      enAlt: ['likewise', 'same to you'],
    },
  ],
  dialogue: {
    title: 'First day at the Swedish course',
    setting: 'Ali sits down next to Maja in class.',
    lines: [
      {
        speaker: 'Ali',
        sv: 'Hej! Jag heter Ali. Vad heter du?',
        en: "Hi! I'm Ali. What's your name?",
      },
      { speaker: 'Maja', sv: 'Hej, Ali! Jag heter Maja.', en: "Hi, Ali! I'm Maja." },
      { speaker: 'Ali', sv: 'Trevligt att träffas, Maja!', en: 'Nice to meet you, Maja!' },
      { speaker: 'Maja', sv: 'Detsamma! Vad heter han?', en: "Likewise! What's his name?" },
      { speaker: 'Ali', sv: 'Han heter Johan.', en: 'His name is Johan.' },
      { speaker: 'Maja', sv: 'Och vad heter hon?', en: "And what's her name?" },
      { speaker: 'Ali', sv: 'Hon heter Sara.', en: 'Her name is Sara.' },
    ],
  },
  exercises: [
    {
      type: 'build',
      prompt: 'My name is Erik.',
      answer: 'Jag heter Erik.',
      distractors: ['är', 'namn'],
      explanation: 'Swedes say "I am called": Jag heter Erik. No är and no namn needed.',
      vocab: ['jag', 'heta'],
    },
    {
      type: 'build',
      prompt: "What's your name?",
      answer: 'Vad heter du?',
      distractors: ['jag', 'är'],
      explanation: 'The question word vad comes first, then the verb heter, then du.',
      vocab: ['vad', 'heta', 'du'],
    },
    {
      type: 'gap',
      text: '___ heter du?',
      en: "What's your name?",
      choices: ['Vad', 'Jag', 'Han'],
      answer: 'Vad',
      explanation: 'Vad means "what". Question words start the question.',
      vocab: ['vad'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Erik', sv: 'Vad heter hon?', en: "What's her name?" }],
      question: 'Erik asks about a woman in your class. Answer.',
      choices: ['Hon heter Lina.', 'Han heter Lina.', 'Jag heter Lina.'],
      answer: 'Hon heter Lina.',
      explanation: 'Erik asks about hon (she), so you answer with hon. Han means "he".',
      vocab: ['hon', 'heta'],
    },
    {
      type: 'dialogueReply',
      lines: [
        { speaker: 'Sara', sv: 'Hej! Jag heter Sara.', en: "Hi! I'm Sara." },
        { speaker: 'Omar', sv: 'Hej! Jag heter Omar.', en: "Hi! I'm Omar." },
        { speaker: 'Sara', sv: 'Trevligt att träffas!', en: 'Nice to meet you!' },
      ],
      question: 'What does Omar say?',
      choices: ['Detsamma!', 'Vad heter du?', 'Hej då!'],
      answer: 'Detsamma!',
      explanation: 'Detsamma (likewise) is the natural reply to Trevligt att träffas!',
      vocab: ['detsamma', 'trevligt-att-traffas-u2'],
    },
    {
      type: 'listen',
      audio: 'Vad heter han?',
      choices: ["What's his name?", "What's her name?", "What's your name?"],
      answer: "What's his name?",
      explanation: 'Han = he. Hon (she) has a darker, rounder vowel.',
      vocab: ['vad', 'heta', 'han'],
    },
    {
      type: 'listen',
      audio: 'Trevligt att träffas!',
      choices: ['Nice to meet you!', 'Good night!', 'See you!'],
      answer: 'Nice to meet you!',
      vocab: ['trevligt', 'trevligt-att-traffas-u2'],
    },
    {
      type: 'type',
      prompt: "He's called Johan.",
      promptLang: 'en',
      answer: 'Han heter Johan.',
      strict: true,
      explanation: 'Han = he, and heter is the same for everyone.',
      vocab: ['han', 'heta'],
    },
    {
      type: 'dictation',
      audio: 'Jag heter Maja. Vad heter du?',
      en: "My name is Maja. What's your name?",
      vocab: ['jag', 'heta', 'vad', 'du'],
    },
    {
      type: 'speak',
      text: 'Hej! Vad heter du?',
      en: "Hi! What's your name?",
      vocab: ['vad', 'heta', 'du'],
    },
  ],
})
