import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u02-l03',
  learn: [
    {
      title: 'How are you?',
      text: 'Ask [[Hur mår du?]] (how are you?). The verb **mår** is only used for how you feel. Answer with **Jag mår …** and a word from the scale below.',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['Jag mår jättebra!', "I'm great!"],
          ['Jag mår bra.', "I'm fine. / I'm good."],
          ['Så där.', 'So-so.'],
          ['Jag mår inte bra.', "I'm not well."],
        ],
        svColumns: [0],
      },
      tip: 'Swedes take "Hur mår du?" fairly literally. A lighter everyday version is "Hur är det?" (how\'s it going?).',
    },
    {
      title: '"Not" comes after the verb',
      text: 'To say "not", put [[inte]] straight after the verb. No "do" or "don\'t" needed: [[Jag mår inte bra.]] means "I don\'t feel well".',
      table: {
        headers: ['Statement', 'With inte'],
        rows: [
          ['Jag mår bra.', 'Jag mår inte bra.'],
          ['Jag är trött.', 'Jag är inte trött.'],
          ['Hon är glad.', 'Hon är inte glad.'],
        ],
        svColumns: [0, 1],
      },
      tip: 'Think: person, verb, inte. Jag är inte …',
    },
    {
      title: 'And you? Me too!',
      text: "Be polite and send the question back: [[Och du?]] (and you?). If you feel the same, say [[Jag också!]] (me too!).\n\nTo describe your mood, use **är** (am) with a feeling: [[Jag är trött.]] (I'm tired), [[Jag är glad.]] (I'm happy).",
      examples: [
        { sv: 'Jag mår bra, tack. Och du?', en: "I'm fine, thanks. And you?" },
        { sv: 'Jag är trött.', en: "I'm tired." },
        { sv: 'Jag också!', en: 'Me too!' },
        { sv: 'Han är ledsen.', en: 'He is sad.' },
      ],
    },
  ],
  vocab: [
    { id: 'hur', sv: 'hur', en: 'how', pos: 'adverb', pron: 'hoor (Swedish u, lips rounded)' },
    {
      id: 'ma',
      sv: 'må',
      en: 'to feel (be well or unwell)',
      pos: 'verb',
      pron: 'moh',
      forms: { present: 'mår', past: 'mådde', supine: 'mått' },
      note: 'For how you feel: Hur mår du? – Jag mår bra.',
      enAlt: ['to feel', 'feel'],
    },
    {
      id: 'inte',
      sv: 'inte',
      en: 'not',
      pos: 'adverb',
      pron: 'IN-teh',
      note: 'Goes right after the verb: Jag mår inte bra.',
    },
    {
      id: 'sa-dar',
      sv: 'så där',
      en: 'so-so',
      pos: 'phrase',
      pron: 'soh DAIR',
      note: 'As an answer to Hur mår du? it means "so-so" (literally "like that").',
      enAlt: ['so so', 'okay', 'not great'],
    },
    {
      id: 'trott',
      sv: 'trött',
      en: 'tired',
      pos: 'adjective',
      forms: { neuter: 'trött', plural: 'trötta' },
    },
    {
      id: 'glad',
      sv: 'glad',
      en: 'happy',
      pos: 'adjective',
      pron: 'glahd',
      forms: { neuter: 'glatt', plural: 'glada' },
      note: 'Swedish glad means happy or cheerful.',
      enAlt: ['glad', 'cheerful'],
    },
    {
      id: 'ledsen',
      sv: 'ledsen',
      en: 'sad / sorry',
      pos: 'adjective',
      pron: 'LESS-en (the d is silent)',
      forms: { neuter: 'ledset', plural: 'ledsna' },
      note: 'Jag är ledsen can mean "I\'m sad" or "I\'m sorry".',
      enAlt: ['sad', 'sorry'],
    },
    {
      id: 'jattebra',
      sv: 'jättebra',
      en: 'great / really good',
      pos: 'adjective',
      pron: 'YET-teh-brah',
      note: 'jätte- ("giant") makes a word stronger: jättebra, jättekul.',
      enAlt: ['great', 'really good', 'very good'],
    },
    {
      id: 'ocksa',
      sv: 'också',
      en: 'also / too',
      pos: 'adverb',
      pron: 'OCK-soh',
      note: 'Jag också! = Me too!',
      enAlt: ['also', 'too'],
    },
  ],
  dialogue: {
    title: 'Monday morning',
    setting: 'Lina meets her workmate Omar in the office kitchen.',
    lines: [
      {
        speaker: 'Lina',
        sv: 'God morgon, Omar! Hur mår du?',
        en: 'Good morning, Omar! How are you?',
      },
      { speaker: 'Omar', sv: 'Så där. Jag är trött. Och du?', en: "So-so. I'm tired. And you?" },
      { speaker: 'Lina', sv: 'Jag är också trött. Kaffe?', en: "I'm tired too. Coffee?" },
      { speaker: 'Omar', sv: 'Ja, tack! Jättebra!', en: 'Yes, please! Great!' },
      { speaker: 'Lina', sv: 'Varsågod!', en: 'Here you go!' },
      { speaker: 'Omar', sv: 'Tack! Nu mår jag bra!', en: 'Thanks! Now I feel good!' },
    ],
  },
  exercises: [
    {
      type: 'listen',
      audio: 'Hur mår du?',
      choices: ['How are you?', "What's your name?", 'Are you tired?'],
      answer: 'How are you?',
      vocab: ['hur', 'ma'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Erik', sv: 'Hej! Hur mår du?', en: 'Hi! How are you?' }],
      question: 'You feel great. What do you answer?',
      choices: ['Jag mår jättebra, tack! Och du?', 'Jag heter Erik. Och du?', 'Jag är ledsen.'],
      answer: 'Jag mår jättebra, tack! Och du?',
      explanation: 'Jättebra means "great". "Och du?" politely sends the question back.',
      vocab: ['ma', 'jattebra'],
    },
    {
      type: 'build',
      prompt: "I don't feel well.",
      answer: 'Jag mår inte bra.',
      distractors: ['är', 'hur'],
      explanation:
        'Inte goes straight after the verb mår. Swedish needs no extra word for "do" or "don\'t".',
      vocab: ['ma', 'inte'],
    },
    {
      type: 'build',
      prompt: "I'm not tired.",
      answer: 'Jag är inte trött.',
      distractors: ['mår', 'glad'],
      explanation: 'Person, verb, inte: Jag är inte trött.',
      vocab: ['inte', 'trott'],
    },
    {
      type: 'gap',
      text: 'Jag mår ___ bra.',
      en: "I'm not feeling well.",
      choices: ['inte', 'hur', 'glad'],
      answer: 'inte',
      explanation: 'Inte (not) comes right after the verb mår.',
      vocab: ['inte'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Sara', sv: 'Jag är trött.', en: "I'm tired." }],
      question: 'You are tired too. What do you say?',
      choices: ['Jag också!', 'Detsamma!', 'Trevligt att träffas!'],
      answer: 'Jag också!',
      explanation:
        'Jag också means "me too". Detsamma returns a wish or greeting, like Ha det bra!, not a feeling.',
      vocab: ['ocksa'],
    },
    {
      type: 'listen',
      audio: 'Hon är ledsen.',
      choices: ['She is sad.', 'He is sad.', 'She is tired.'],
      answer: 'She is sad.',
      explanation: 'Hon = she, ledsen = sad. The d in ledsen is silent: "lessen".',
      vocab: ['hon', 'ledsen'],
    },
    {
      type: 'type',
      prompt: 'Jag mår bra.',
      promptLang: 'sv',
      question: 'Make it negative: add "not".',
      answer: 'Jag mår inte bra.',
      strict: true,
      reject: ['Jag inte mår bra.'],
      explanation: 'Inte goes right after the verb: Jag mår inte bra.',
      vocab: ['inte', 'ma'],
    },
    {
      type: 'dictation',
      audio: 'Jag mår bra, tack. Och du?',
      en: "I'm fine, thanks. And you?",
      vocab: ['ma'],
    },
    {
      type: 'speak',
      text: 'Hur mår du? Jag mår jättebra!',
      en: "How are you? I'm great!",
      vocab: ['hur', 'ma', 'jattebra'],
    },
  ],
})
