import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u04-l03',
  learn: [
    {
      title: 'Here and there',
      text: '[[här]] means "here" and sounds a lot like English "hair". [[där]] means "there" and sounds like "dair".',
      examples: [
        { sv: 'Jag är här!', en: 'I’m here!' },
        { sv: 'Anna är där.', en: 'Anna is over there.' },
      ],
    },
    {
      title: 'This one and that one',
      text: 'To say "this" and "that", Swedish adds **här** (here) or **där** (there) to **den** or **det**:\n\nen-words use **den**: [[den här jackan]] (this jacket), [[den där jackan]] (that jacket).\nett-words use **det**: [[det här rummet]] (this room), [[det där rummet]] (that room).\n\nNotice that the noun also gets its "the" ending: literally "this here the-jacket".',
      table: {
        headers: ['', 'en-words', 'ett-words'],
        rows: [
          ['this', 'den här jackan', 'det här rummet'],
          ['that', 'den där jackan', 'det där rummet'],
          ['this one', 'den här', 'det här'],
        ],
        svColumns: [1, 2],
      },
      tip: 'To introduce something, always say "Det här är …", even for en-words: [[Det här är en tröja.]] (This is a sweater.) [[Det här är Anna.]] (This is Anna.)',
    },
    {
      title: 'Which one?',
      text: '"Which" also matches the noun: [[vilken]] for en-words and [[vilket]] for ett-words. After vilken/vilket the noun has **no** ending.',
      examples: [
        { sv: 'Vilken jacka?', en: 'Which jacket?' },
        { sv: 'Vilket rum?', en: 'Which room?' },
        { sv: 'Vilken sko? Den här?', en: 'Which shoe? This one?' },
      ],
    },
  ],
  vocab: [
    { id: 'har-here', sv: 'här', en: 'here', pos: 'adverb', pron: 'hair' },
    { id: 'dar-there', sv: 'där', en: 'there', pos: 'adverb', pron: 'dair' },
    {
      id: 'den',
      sv: 'den',
      en: 'it / that (en-words)',
      pos: 'pronoun',
      note: 'den här = this (en-words), den där = that (en-words).',
      enAlt: ['it', 'that'],
    },
    {
      id: 'det',
      sv: 'det',
      en: 'it / that (ett-words)',
      pos: 'pronoun',
      pron: 'deh (the t is usually silent)',
      note: 'det här = this (ett-words), det där = that (ett-words). "Det här är …" = "This is …".',
      enAlt: ['it', 'that'],
    },
    {
      id: 'vilken',
      sv: 'vilken',
      en: 'which',
      pos: 'pronoun',
      note: 'vilken for en-words, vilket for ett-words, vilka for plural.',
      forms: { neuter: 'vilket', plural: 'vilka' },
    },
    {
      id: 'troja',
      sv: 'tröja',
      en: 'sweater / top',
      pos: 'noun',
      gender: 'en',
      pron: 'TRUH-ya (ö as in "fur")',
      forms: { definite: 'tröjan', plural: 'tröjor', pluralDefinite: 'tröjorna' },
      enAlt: ['sweater', 'jumper', 'top'],
    },
    {
      id: 'jacka',
      sv: 'jacka',
      en: 'jacket',
      pos: 'noun',
      gender: 'en',
      pron: 'YACK-a',
      forms: { definite: 'jackan', plural: 'jackor', pluralDefinite: 'jackorna' },
      enAlt: ['coat'],
    },
    {
      id: 'mossa',
      sv: 'mössa',
      en: 'woolly hat / beanie',
      pos: 'noun',
      gender: 'en',
      pron: 'MUSS-a (ö as in "fur")',
      forms: { definite: 'mössan', plural: 'mössor', pluralDefinite: 'mössorna' },
      enAlt: ['hat', 'beanie', 'woolly hat', 'cap'],
    },
    {
      id: 'sko',
      sv: 'sko',
      en: 'shoe',
      pos: 'noun',
      gender: 'en',
      pron: 'skoo',
      forms: { definite: 'skon', plural: 'skor', pluralDefinite: 'skorna' },
    },
  ],
  dialogue: {
    title: 'At the flea market',
    setting: 'Maja is at a loppis (flea market). Olle is selling old clothes.',
    lines: [
      {
        speaker: 'Maja',
        sv: 'Hej! Vad kostar den här jackan?',
        en: 'Hi! How much is this jacket?',
      },
      {
        speaker: 'Olle',
        sv: 'Den där? Hundra kronor.',
        en: 'That one? A hundred kronor.',
      },
      { speaker: 'Maja', sv: 'Okej. Och den här mössan?', en: 'Okay. And this hat?' },
      { speaker: 'Olle', sv: 'Vilken mössa?', en: 'Which hat?' },
      { speaker: 'Maja', sv: 'Den här!', en: 'This one!' },
      { speaker: 'Olle', sv: 'Tjugo kronor.', en: 'Twenty kronor.' },
      {
        speaker: 'Maja',
        sv: 'Bra! Jag köper jackan och mössan.',
        en: 'Great! I’ll take the jacket and the hat.',
      },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Jag köper ___ här mössan.',
      en: 'I’ll buy this hat.',
      choices: ['den', 'det'],
      answer: 'den',
      explanation: 'mössa is an en-word, so "this hat" is den här mössan.',
      vocab: ['den', 'mossa'],
    },
    {
      type: 'gap',
      text: 'Den här ___ är bra.',
      en: 'This jacket is good.',
      choices: ['jackan', 'jacka'],
      answer: 'jackan',
      explanation: 'After den här / det här the noun takes its "the" ending: den här jackan.',
      vocab: ['jacka'],
    },
    {
      type: 'gap',
      text: '___ rum bor du i?',
      en: 'Which room do you live in?',
      choices: ['Vilken', 'Vilket'],
      answer: 'Vilket',
      explanation: 'rum is an ett-word, so "which" is vilket. Vilken is for en-words.',
      vocab: ['vilken', 'rum'],
    },
    {
      type: 'gap',
      text: '___ här är Anna.',
      en: 'This is Anna.',
      choices: ['Det', 'Den'],
      answer: 'Det',
      explanation: 'To introduce someone or something, always use "Det här är …".',
      vocab: ['det', 'har-here'],
    },
    {
      type: 'type',
      prompt: 'this room',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'det här rummet',
      reject: ['den här rummet', 'det här rum'],
      strict: true,
      hint: 'ett rum',
      explanation: 'rum is an ett-word: det här + rummet (the room).',
      vocab: ['det', 'har-here', 'rum'],
    },
    {
      type: 'build',
      prompt: 'This is a jacket.',
      answer: 'Det här är en jacka.',
      distractors: ['Den', 'ett'],
      explanation: '"Det här är …" introduces something, even an en-word like jacka.',
      vocab: ['det', 'jacka'],
    },
    {
      type: 'build',
      prompt: 'Where is that sweater?',
      answer: 'Var är den där tröjan?',
      distractors: ['det', 'tröja'],
      explanation: 'tröja is an en-word: den där tröjan.',
      vocab: ['den', 'dar-there', 'troja'],
    },
    {
      type: 'listen',
      audio: 'Vilken jacka? Den där?',
      choices: ['Which jacket? That one?', 'Which jacket? This one?', 'Which hat? That one?'],
      answer: 'Which jacket? That one?',
      explanation: 'där means "there", so den där is "that one". "This one" would be den här.',
      vocab: ['vilken', 'jacka', 'dar-there'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Olle', sv: 'Vilken mössa?', en: 'Which hat?' }],
      question: 'Point at the hat in front of you.',
      choices: ['Den här!', 'Det här!', 'Den här mössa!'],
      answer: 'Den här!',
      explanation:
        'mössa is an en-word, so "this one" is den här. With the noun it would be den här mössan.',
      vocab: ['den', 'har-here'],
    },
    {
      type: 'speak',
      text: 'Vilken sko? Den här?',
      en: 'Which shoe? This one?',
      vocab: ['vilken', 'sko'],
    },
  ],
})
