import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u04-l04',
  learn: [
    {
      title: 'My: min, mitt, mina',
      text: 'The Swedish word for "my" changes to match the noun:\n\n**min** for en-words: [[min cykel]] (my bike)\n**mitt** for ett-words: [[mitt rum]] (my room)\n**mina** for plurals: [[mina skor]] (my shoes)\n\n"Your", "our" and "your (to several people)" work the same way.',
      table: {
        headers: ['', 'en-words', 'ett-words', 'plural'],
        rows: [
          ['my / mine', 'min', 'mitt', 'mina'],
          ['your / yours (one person)', 'din', 'ditt', 'dina'],
          ['our / ours', 'vår', 'vårt', 'våra'],
          ['your / yours (several people)', 'er', 'ert', 'era'],
        ],
        svColumns: [1, 2, 3],
      },
    },
    {
      title: 'No ending after "my"',
      text: 'After min, din, vår and the rest, the noun stays in its basic form with **no** "the" ending. The word "my" already tells you which one you mean.\n\n[[min bil]] = my car (never "min bilen")',
      examples: [
        { sv: 'min cykel', en: 'my bike' },
        { sv: 'ditt glas', en: 'your glass' },
        { sv: 'vår hund', en: 'our dog' },
        { sv: 'mina nycklar', en: 'my keys' },
      ],
      tip: 'Plurals you need here: en sko → två skor (shoes), en nyckel → två nycklar (keys).',
    },
    {
      title: 'His, her, their never change',
      text: '[[hans]] (his), [[hennes]] (her) and [[deras]] (their) are the same for en-words, ett-words and plurals. Easy!',
      examples: [
        { sv: 'hans cykel', en: 'his bike' },
        { sv: 'hans rum', en: 'his room' },
        { sv: 'hennes katt', en: 'her cat' },
        { sv: 'deras skor', en: 'their shoes' },
      ],
      tip: 'For hen (the gender-neutral "they"), the word is hens: hens katt.',
    },
  ],
  vocab: [
    {
      id: 'min',
      sv: 'min',
      en: 'my / mine',
      pos: 'pronoun',
      note: 'min for en-words, mitt for ett-words, mina for plurals.',
      forms: { neuter: 'mitt', plural: 'mina' },
      enAlt: ['my', 'mine'],
    },
    {
      id: 'din',
      sv: 'din',
      en: 'your / yours (one person)',
      pos: 'pronoun',
      note: 'din for en-words, ditt for ett-words, dina for plurals.',
      forms: { neuter: 'ditt', plural: 'dina' },
      enAlt: ['your', 'yours'],
    },
    {
      id: 'hans',
      sv: 'hans',
      en: 'his',
      pos: 'pronoun',
      note: 'Never changes: hans cykel, hans rum, hans skor.',
    },
    {
      id: 'hennes',
      sv: 'hennes',
      en: 'her / hers',
      pos: 'pronoun',
      pron: 'HEN-es',
      note: 'Never changes: hennes cykel, hennes rum, hennes skor.',
      enAlt: ['her', 'hers'],
    },
    {
      id: 'var-our',
      sv: 'vår',
      en: 'our / ours',
      pos: 'pronoun',
      pron: 'vohr',
      note: 'vår for en-words, vårt for ett-words, våra for plurals.',
      forms: { neuter: 'vårt', plural: 'våra' },
      enAlt: ['our', 'ours'],
    },
    {
      id: 'er',
      sv: 'er',
      en: 'your / yours (several people)',
      pos: 'pronoun',
      pron: 'ehr',
      note: 'Use it when you talk to more than one person (ni). er for en-words, ert for ett-words, era for plurals.',
      forms: { neuter: 'ert', plural: 'era' },
    },
    {
      id: 'deras',
      sv: 'deras',
      en: 'their / theirs',
      pos: 'pronoun',
      pron: 'DEH-ras',
      note: 'Never changes: deras cykel, deras rum, deras skor.',
      enAlt: ['their', 'theirs'],
    },
    {
      id: 'cykel',
      sv: 'cykel',
      en: 'bike',
      pos: 'noun',
      gender: 'en',
      pron: 'SICK-el (c sounds like s, y with rounded lips)',
      forms: { definite: 'cykeln', plural: 'cyklar', pluralDefinite: 'cyklarna' },
      enAlt: ['bicycle'],
    },
    {
      id: 'hund',
      sv: 'hund',
      en: 'dog',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'hunden', plural: 'hundar', pluralDefinite: 'hundarna' },
    },
    {
      id: 'katt',
      sv: 'katt',
      en: 'cat',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'katten', plural: 'katter', pluralDefinite: 'katterna' },
    },
  ],
  dialogue: {
    title: 'Whose is this?',
    setting: 'A party is over. Elin and Johan are looking for their things in the hall.',
    lines: [
      {
        speaker: 'Elin',
        sv: 'Johan, är det här din jacka?',
        en: 'Johan, is this your jacket?',
      },
      {
        speaker: 'Johan',
        sv: 'Nej, det är hans jacka. Min jacka är där.',
        en: 'No, that’s his jacket. My jacket is over there.',
      },
      { speaker: 'Elin', sv: 'Okej. Och den här mössan?', en: 'Okay. And this hat?' },
      { speaker: 'Johan', sv: 'Mössan är min! Tack.', en: 'The hat is mine! Thanks.' },
      { speaker: 'Elin', sv: 'Var är mina skor?', en: 'Where are my shoes?' },
      { speaker: 'Johan', sv: 'Dina skor? De är här.', en: 'Your shoes? They’re here.' },
      { speaker: 'Elin', sv: 'Bra, tack! Nu går vi.', en: 'Great, thanks! Let’s go.' },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Det här är ___ rum.',
      en: 'This is my room.',
      choices: ['min', 'mitt', 'mina'],
      answer: 'mitt',
      explanation: 'rum is an ett-word, so "my" is mitt: mitt rum.',
      vocab: ['min', 'rum'],
    },
    {
      type: 'gap',
      text: 'Var är ___ nycklar?',
      en: 'Where are my keys?',
      choices: ['min', 'mitt', 'mina'],
      answer: 'mina',
      explanation: 'nycklar is plural (more than one key), so "my" is mina.',
      vocab: ['min', 'nyckel'],
    },
    {
      type: 'gap',
      text: 'Var är min ___?',
      en: 'Where is my bike?',
      choices: ['cykel', 'cykeln'],
      answer: 'cykel',
      explanation:
        'After min, din, vår and so on, the noun has no ending: min cykel, not min cykeln.',
      vocab: ['min', 'cykel'],
    },
    {
      type: 'mcq',
      prompt: 'her cat',
      promptLang: 'en',
      question: 'How do you say this in Swedish?',
      choices: ['hennes katt', 'hans katt', 'hennes katten'],
      answer: 'hennes katt',
      explanation: 'hennes means "her" (hans is "his"), and the noun has no ending after it.',
      vocab: ['hennes', 'katt'],
    },
    {
      type: 'type',
      prompt: 'our keys',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'våra nycklar',
      reject: ['vår nycklar', 'vårt nycklar', 'våra nycklarna'],
      strict: true,
      hint: 'en nyckel, two keys: nycklar',
      explanation: 'nycklar is plural, so "our" is våra: våra nycklar.',
      vocab: ['var-our', 'nyckel'],
    },
    {
      type: 'build',
      prompt: 'This is my dog.',
      answer: 'Det här är min hund.',
      distractors: ['mitt', 'hunden'],
      explanation: 'hund is an en-word, so "my" is min, and there is no ending after min.',
      vocab: ['min', 'hund'],
    },
    {
      type: 'build',
      prompt: 'Where are your shoes?',
      answer: 'Var är dina skor?',
      distractors: ['din', 'skorna'],
      explanation: 'skor is plural, so "your" is dina.',
      vocab: ['din', 'sko'],
    },
    {
      type: 'listen',
      audio: 'Är det hennes katt?',
      choices: ['Is it her cat?', 'Is it his cat?', 'Is it their cat?'],
      answer: 'Is it her cat?',
      explanation: 'hennes = her, hans = his, deras = their.',
      vocab: ['hennes', 'katt'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Elin', sv: 'Är det här din jacka?', en: 'Is this your jacket?' }],
      question: 'Yes, it’s yours. What do you say?',
      choices: ['Ja, det är min jacka.', 'Ja, det är mitt jacka.', 'Ja, det är min jackan.'],
      answer: 'Ja, det är min jacka.',
      explanation: 'jacka is an en-word, so it is min jacka, with no ending after min.',
      vocab: ['min', 'jacka'],
    },
    {
      type: 'speak',
      text: 'Det här är mitt rum och min säng.',
      en: 'This is my room and my bed.',
      vocab: ['min', 'rum', 'sang'],
    },
  ],
})
