import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u04-l01',
  learn: [
    {
      title: 'Two words for "a"',
      text: 'English has one word for "a". Swedish has two: **en** and **ett**. Every noun belongs to one of two groups: it is either an **en**-word or an **ett**-word.\n\n[[en stol]] (a chair) but [[ett rum]] (a room).\n\nYou already know these two words from Unit 3: they also mean "one". [[en stol]] is "a chair" or "one chair".',
      table: {
        headers: ['en-words', 'ett-words'],
        rows: [
          ['en stol', 'ett bord'],
          ['en dörr', 'ett fönster'],
          ['en lampa', 'ett rum'],
          ['en nyckel', 'ett hus'],
          ['en bil', 'ett äpple'],
        ],
        svColumns: [0, 1],
      },
    },
    {
      title: 'No rule, so learn it as a pair',
      text: 'There is no reliable way to tell from a word whether it takes en or ett. The good news: about **3 out of 4** nouns are en-words. So if you have to guess, guess **en**.\n\nWords for people and animals are usually en-words: [[en tjej]], [[en pojke]], [[en lärare]]. But watch out for [[ett barn]] (a child), a famous exception!',
      examples: [
        { sv: 'en telefon', en: 'a phone' },
        { sv: 'en dator', en: 'a computer' },
        { sv: 'en väska', en: 'a bag' },
        { sv: 'ett fönster', en: 'a window' },
      ],
      tip: 'Never learn just "stol". Learn "en stol", the way you would learn a name together with a surname.',
    },
    {
      title: 'Saying en and ett',
      text: '[[ett]] is short and crisp, like "et" in "set". The double t tells you the vowel is short.\n\n[[en]] is short too, like "en" in "pen". Listen to the difference: [[en dörr]], [[ett fönster]].',
    },
  ],
  vocab: [
    {
      id: 'stol',
      sv: 'stol',
      en: 'chair',
      pos: 'noun',
      gender: 'en',
      pron: 'stool',
      forms: { definite: 'stolen', plural: 'stolar', pluralDefinite: 'stolarna' },
    },
    {
      id: 'dorr',
      sv: 'dörr',
      en: 'door',
      pos: 'noun',
      gender: 'en',
      pron: 'durr',
      forms: { definite: 'dörren', plural: 'dörrar', pluralDefinite: 'dörrarna' },
    },
    {
      id: 'fonster',
      sv: 'fönster',
      en: 'window',
      pos: 'noun',
      gender: 'ett',
      pron: 'FUHN-ster',
      forms: { definite: 'fönstret', plural: 'fönster', pluralDefinite: 'fönstren' },
    },
    {
      id: 'lampa',
      sv: 'lampa',
      en: 'lamp',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'lampan', plural: 'lampor', pluralDefinite: 'lamporna' },
    },
    {
      id: 'sang',
      sv: 'säng',
      en: 'bed',
      pos: 'noun',
      gender: 'en',
      pron: 'seng',
      forms: { definite: 'sängen', plural: 'sängar', pluralDefinite: 'sängarna' },
    },
    {
      id: 'telefon',
      sv: 'telefon',
      en: 'phone',
      pos: 'noun',
      gender: 'en',
      pron: 'teh-leh-FOON',
      forms: { definite: 'telefonen', plural: 'telefoner', pluralDefinite: 'telefonerna' },
      enAlt: ['telephone'],
    },
    {
      id: 'dator',
      sv: 'dator',
      en: 'computer',
      pos: 'noun',
      gender: 'en',
      pron: 'DAH-tor',
      forms: { definite: 'datorn', plural: 'datorer', pluralDefinite: 'datorerna' },
    },
    {
      id: 'rum',
      sv: 'rum',
      en: 'room',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'rummet', plural: 'rum', pluralDefinite: 'rummen' },
    },
    {
      id: 'nyckel',
      sv: 'nyckel',
      en: 'key',
      pos: 'noun',
      gender: 'en',
      pron: 'NYCK-el (y with rounded lips)',
      forms: { definite: 'nyckeln', plural: 'nycklar', pluralDefinite: 'nycklarna' },
    },
    {
      id: 'vaska',
      sv: 'väska',
      en: 'bag',
      pos: 'noun',
      gender: 'en',
      pron: 'VES-ka',
      forms: { definite: 'väskan', plural: 'väskor', pluralDefinite: 'väskorna' },
      enAlt: ['handbag', 'suitcase'],
    },
  ],
  dialogue: {
    title: 'At IKEA',
    setting: 'Erik is moving into a new flat. He and Anna are shopping at IKEA.',
    lines: [
      { speaker: 'Anna', sv: 'Okej! Vad köper du, Erik?', en: 'Okay! What are you buying, Erik?' },
      { speaker: 'Erik', sv: 'En säng, en stol och en lampa.', en: 'A bed, a chair and a lamp.' },
      { speaker: 'Anna', sv: 'Och ett bord?', en: 'And a table?' },
      { speaker: 'Erik', sv: 'Ja, ett bord också.', en: 'Yes, a table too.' },
      { speaker: 'Anna', sv: 'En lampa eller två?', en: 'One lamp or two?' },
      { speaker: 'Erik', sv: 'En lampa räcker.', en: 'One lamp is enough.' },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Jag köper ___ dator.',
      en: 'I’m buying a computer.',
      choices: ['en', 'ett'],
      answer: 'en',
      explanation: 'dator is an en-word: en dator.',
      vocab: ['dator'],
    },
    {
      type: 'gap',
      text: 'Anna bor i ___ hus.',
      en: 'Anna lives in a house.',
      choices: ['en', 'ett'],
      answer: 'ett',
      explanation: 'hus is an ett-word: ett hus.',
    },
    {
      type: 'gap',
      text: 'En stol och ___ bord.',
      en: 'A chair and a table.',
      choices: ['en', 'ett'],
      answer: 'ett',
      explanation: 'stol is an en-word, but bord is an ett-word: en stol, ett bord.',
      vocab: ['stol'],
    },
    {
      type: 'gap',
      text: 'Ett fönster och ___ dörr.',
      en: 'A window and a door.',
      choices: ['en', 'ett'],
      answer: 'en',
      explanation: 'fönster is an ett-word, but dörr is an en-word: ett fönster, en dörr.',
      vocab: ['fonster', 'dorr'],
    },
    {
      type: 'mcq',
      prompt: 'Which of these is an ett-word?',
      promptLang: 'en',
      choices: ['stol', 'fönster', 'lampa', 'nyckel'],
      answer: 'fönster',
      explanation:
        'ett fönster. The others are en-words: en stol, en lampa, en nyckel. Most nouns are en-words.',
      vocab: ['fonster', 'stol', 'lampa', 'nyckel'],
    },
    {
      type: 'minimalPair',
      focus: 'en or ett?',
      options: [
        { sv: 'en', en: 'a (en-word)' },
        { sv: 'ett', en: 'a (ett-word)' },
      ],
      answer: 'ett',
      explanation: 'ett ends in a crisp t sound, like "et" in "set". en ends in an n.',
    },
    {
      type: 'listen',
      audio: 'En säng och ett rum.',
      choices: ['A bed and a room.', 'A chair and a room.', 'A bed and a window.'],
      answer: 'A bed and a room.',
      vocab: ['sang', 'rum'],
    },
    {
      type: 'build',
      prompt: 'I’m buying a bed and a lamp.',
      answer: 'Jag köper en säng och en lampa.',
      distractors: ['ett'],
      explanation: 'Both säng and lampa are en-words.',
      vocab: ['sang', 'lampa'],
    },
    {
      type: 'type',
      prompt: 'a room',
      promptLang: 'en',
      question: 'Write this in Swedish, with en or ett',
      answer: 'ett rum',
      reject: ['en rum'],
      strict: true,
      explanation: 'rum is an ett-word: ett rum.',
      vocab: ['rum'],
    },
    {
      type: 'speak',
      text: 'En telefon och en väska.',
      en: 'A phone and a bag.',
      vocab: ['telefon', 'vaska'],
    },
  ],
})
