import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u04-l02',
  learn: [
    {
      title: '"The" is an ending',
      text: 'In English, "the" is a separate word in front of the noun. In Swedish, "the" is an **ending** glued onto the noun.\n\nen-words add **-en**: [[en kopp]] → [[koppen]] (the cup).\nett-words add **-et**: [[ett bord]] → [[bordet]] (the table).',
      table: {
        headers: ['a …', 'the …', 'English'],
        rows: [
          ['en kopp', 'koppen', 'the cup'],
          ['en kniv', 'kniven', 'the knife'],
          ['en mobil', 'mobilen', 'the mobile phone'],
          ['ett hus', 'huset', 'the house'],
          ['ett glas', 'glaset', 'the glass'],
        ],
        svColumns: [0, 1],
      },
      tip: 'Use en/ett the first time you mention something, and the ending when you both know which one you mean: "Här är en kopp. Koppen är full." (Here is a cup. The cup is full.)',
    },
    {
      title: 'Words that end in a vowel',
      text: 'If the noun already ends in a vowel, just add **-n** (en-words) or **-t** (ett-words).',
      table: {
        headers: ['a …', 'the …', 'English'],
        rows: [
          ['en flaska', 'flaskan', 'the bottle'],
          ['en penna', 'pennan', 'the pen'],
          ['en soffa', 'soffan', 'the sofa'],
          ['ett äpple', 'äpplet', 'the apple'],
          ['ett kaffe', 'kaffet', 'the coffee'],
        ],
        svColumns: [0, 1],
      },
      tip: 'tv works the same way: en tv → tv:n. The colon is just how Swedes write it.',
    },
    {
      title: 'Words ending in -el, -er and -or',
      text: 'Nouns that end in an unstressed **-el**, **-er** or **-or** follow their own pattern.\n\nen-words just add **-n**: [[nyckel]] → [[nyckeln]], [[vinter]] → [[vintern]], [[dator]] → [[datorn]].\nett-words drop the e and add **-et**: [[fönster]] → [[fönstret]], [[papper]] → [[pappret]].',
      table: {
        headers: ['a …', 'the …', 'English'],
        rows: [
          ['en nyckel', 'nyckeln', 'the key'],
          ['en gaffel', 'gaffeln', 'the fork'],
          ['ett papper', 'pappret', 'the paper'],
          ['ett fönster', 'fönstret', 'the window'],
          ['en dator', 'datorn', 'the computer'],
        ],
        svColumns: [0, 1],
      },
      tip: 'One more spelling detail: rum has a short vowel but only one m. Before an ending the m doubles: ett rum → rummet.',
    },
  ],
  vocab: [
    {
      id: 'kopp',
      sv: 'kopp',
      en: 'cup',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'koppen', plural: 'koppar', pluralDefinite: 'kopparna' },
      enAlt: ['mug'],
    },
    {
      id: 'tallrik',
      sv: 'tallrik',
      en: 'plate',
      pos: 'noun',
      gender: 'en',
      pron: 'TAL-rick',
      forms: { definite: 'tallriken', plural: 'tallrikar', pluralDefinite: 'tallrikarna' },
    },
    {
      id: 'gaffel',
      sv: 'gaffel',
      en: 'fork',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'gaffeln', plural: 'gafflar', pluralDefinite: 'gafflarna' },
    },
    {
      id: 'kniv',
      sv: 'kniv',
      en: 'knife',
      pos: 'noun',
      gender: 'en',
      pron: 'k-neev (say the k!)',
      forms: { definite: 'kniven', plural: 'knivar', pluralDefinite: 'knivarna' },
    },
    {
      id: 'flaska',
      sv: 'flaska',
      en: 'bottle',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'flaskan', plural: 'flaskor', pluralDefinite: 'flaskorna' },
    },
    {
      id: 'penna',
      sv: 'penna',
      en: 'pen',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'pennan', plural: 'pennor', pluralDefinite: 'pennorna' },
      enAlt: ['pencil'],
    },
    {
      id: 'papper',
      sv: 'papper',
      en: 'paper / sheet of paper',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'pappret', plural: 'papper', pluralDefinite: 'pappren' },
      enAlt: ['paper', 'sheet of paper'],
    },
    {
      id: 'mobil',
      sv: 'mobil',
      en: 'mobile phone',
      pos: 'noun',
      gender: 'en',
      pron: 'moh-BEEL',
      forms: { definite: 'mobilen', plural: 'mobiler', pluralDefinite: 'mobilerna' },
      enAlt: ['mobile', 'cell phone', 'cellphone'],
    },
    {
      id: 'soffa',
      sv: 'soffa',
      en: 'sofa',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'soffan', plural: 'soffor', pluralDefinite: 'sofforna' },
      enAlt: ['couch'],
    },
    {
      id: 'tv',
      sv: 'tv',
      en: 'TV',
      pos: 'noun',
      gender: 'en',
      pron: 'tay-vay',
      note: '"The TV" is written tv:n.',
      forms: { definite: 'tv:n' },
      enAlt: ['television'],
    },
  ],
  dialogue: {
    title: 'Fika',
    setting: 'Jonas is visiting Emma. She makes coffee.',
    lines: [
      { speaker: 'Emma', sv: 'Kaffe?', en: 'Coffee?' },
      { speaker: 'Jonas', sv: 'Ja, gärna!', en: 'Yes, please!' },
      {
        speaker: 'Emma',
        sv: 'Varsågod, en kopp kaffe. Koppen är varm!',
        en: 'Here you go, a cup of coffee. The cup is hot!',
      },
      { speaker: 'Jonas', sv: 'Tack! Har du en sked?', en: 'Thanks! Do you have a spoon?' },
      { speaker: 'Emma', sv: 'Skeden ligger på tallriken.', en: 'The spoon is on the plate.' },
      { speaker: 'Jonas', sv: 'Jaha! Tack!', en: 'Oh, I see! Thanks!' },
    ],
  },
  exercises: [
    {
      type: 'match',
      pairs: [
        { sv: 'en kopp', en: 'a cup' },
        { sv: 'koppen', en: 'the cup' },
        { sv: 'en penna', en: 'a pen' },
        { sv: 'pennan', en: 'the pen' },
        { sv: 'soffan', en: 'the sofa' },
      ],
      explanation: 'No en or ett in front means "the": the ending does the job.',
      vocab: ['kopp', 'penna', 'soffa'],
    },
    {
      type: 'gap',
      text: '___ är full.',
      en: 'The cup is full.',
      choices: ['Koppen', 'Koppet', 'En koppen'],
      answer: 'Koppen',
      explanation:
        'kopp is an en-word, so "the cup" is koppen. Never put en in front of the ending: there is only one "the".',
      vocab: ['kopp'],
    },
    {
      type: 'gap',
      text: 'Var är ___?',
      en: 'Where’s the paper?',
      choices: ['pappret', 'pappern', 'papperen'],
      answer: 'pappret',
      explanation:
        'papper is an ett-word, so it takes -et, and the e in -er drops: papper → pappret.',
      vocab: ['papper'],
    },
    {
      type: 'gap',
      text: 'Var är ___?',
      en: 'Where’s the fork?',
      choices: ['gaffeln', 'gaffelen', 'gaffelet'],
      answer: 'gaffeln',
      explanation: 'gaffel is an en-word ending in -el, so it just adds -n: gaffel → gaffeln.',
      vocab: ['gaffel'],
    },
    {
      type: 'type',
      prompt: 'the bottle',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'flaskan',
      reject: ['flaska', 'en flaska', 'flaskaen'],
      strict: true,
      hint: 'en flaska ends in a vowel',
      explanation: 'en flaska ends in a vowel, so just add -n: flaskan.',
      vocab: ['flaska'],
    },
    {
      type: 'type',
      prompt: 'the window',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'fönstret',
      reject: ['fönsteret', 'fönster'],
      strict: true,
      hint: 'ett fönster',
      explanation: 'ett fönster takes -et, and the e in -er drops: fönster → fönstret.',
      vocab: ['fonster'],
    },
    {
      type: 'build',
      prompt: 'Where is the key?',
      answer: 'Var är nyckeln?',
      distractors: ['nyckelen', 'en'],
      explanation: 'nyckel is an en-word ending in -el, so it just adds -n: nyckeln.',
      vocab: ['nyckel'],
    },
    {
      type: 'listen',
      audio: 'Var är mobilen?',
      choices: ['Where is the phone?', 'Where is a phone?', 'Where is the TV?'],
      answer: 'Where is the phone?',
      explanation: 'mobilen ends in -en, so it means "the phone".',
      vocab: ['mobil'],
    },
    {
      type: 'dictation',
      audio: 'Var är kniven och gaffeln?',
      en: 'Where are the knife and fork?',
      vocab: ['kniv', 'gaffel'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Jonas', sv: 'Har du en sked?', en: 'Do you have a spoon?' }],
      question: 'The spoon is in the cup. What do you say?',
      choices: ['Ja, skeden är i koppen.', 'Ja, en skeden är i koppen.', 'Ja, sked är i koppen.'],
      answer: 'Ja, skeden är i koppen.',
      explanation:
        '"The spoon" is skeden and "the cup" is koppen: just the ending, no en in front.',
      vocab: ['kopp'],
    },
    {
      type: 'speak',
      text: 'Var är tallriken?',
      en: 'Where is the plate?',
      vocab: ['tallrik'],
    },
  ],
})
