import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u04-l05',
  learn: [
    {
      title: 'Where is it?',
      text: 'These little words tell you where something is. The thing after them usually has its "the" ending: [[på bordet]] (on the table), [[i väskan]] (in the bag).',
      table: {
        headers: ['Swedish', 'English', 'Example', 'Meaning'],
        rows: [
          ['på', 'on', 'på bordet', 'on the table'],
          ['under', 'under', 'under sängen', 'under the bed'],
          ['i', 'in', 'i väskan', 'in the bag'],
          ['bredvid', 'next to', 'bredvid datorn', 'next to the computer'],
          ['framför', 'in front of', 'framför dörren', 'in front of the door'],
          ['bakom', 'behind', 'bakom soffan', 'behind the sofa'],
          ['mellan', 'between', 'mellan stolen och sängen', 'between the chair and the bed'],
        ],
        svColumns: [0, 2],
      },
    },
    {
      title: 'Lying or standing?',
      text: 'Swedes often don’t say "is" about where things are. They say whether the thing is **lying** or **standing**.\n\nThings lying flat [[ligger]]: [[Nyckeln ligger på bordet.]] (The key is on the table.)\nThings standing upright [[står]]: [[Lampan står på bordet.]] (The lamp is on the table.)',
      examples: [
        { sv: 'Telefonen ligger bredvid datorn.', en: 'The phone is next to the computer.' },
        { sv: 'Väskan står framför dörren.', en: 'The bag is in front of the door.' },
        { sv: 'Boken ligger under soffan.', en: 'The book is under the sofa.' },
      ],
      tip: 'Not sure? With "är" everyone will still understand you (Nyckeln är på bordet), but ligger and står sound much more Swedish.',
    },
    {
      title: '"It" matches the noun',
      text: 'When you answer, "it" is **den** for en-words and **det** for ett-words. "They" is **de** (said "dom").',
      examples: [
        { sv: 'Var är nyckeln? Den ligger på bordet.', en: 'Where’s the key? It’s on the table.' },
        {
          sv: 'Var är pappret? Det ligger på stolen.',
          en: 'Where’s the paper? It’s on the chair.',
        },
        {
          sv: 'Var är mina nycklar? De ligger i väskan.',
          en: 'Where are my keys? They’re in the bag.',
        },
        { sv: 'Jag hittar inte min mobil!', en: 'I can’t find my phone!' },
        { sv: 'Min nyckel är borta.', en: 'My key is gone.' },
      ],
    },
  ],
  vocab: [
    {
      id: 'pa',
      sv: 'på',
      en: 'on',
      pos: 'preposition',
      pron: 'poh',
      note: 'Also "at" in many phrases.',
    },
    { id: 'under', sv: 'under', en: 'under', pos: 'preposition', enAlt: ['below', 'underneath'] },
    {
      id: 'bredvid',
      sv: 'bredvid',
      en: 'next to',
      pos: 'preposition',
      pron: 'breh-VEED',
      enAlt: ['beside'],
    },
    {
      id: 'framfor',
      sv: 'framför',
      en: 'in front of',
      pos: 'preposition',
      pron: 'FRAM-fur',
    },
    { id: 'bakom', sv: 'bakom', en: 'behind', pos: 'preposition', pron: 'BAH-kom' },
    { id: 'mellan', sv: 'mellan', en: 'between', pos: 'preposition' },
    {
      id: 'hitta',
      sv: 'hitta',
      en: 'to find',
      pos: 'verb',
      forms: { present: 'hittar', past: 'hittade', supine: 'hittat', imperative: 'hitta' },
      enAlt: ['find'],
    },
    {
      id: 'borta',
      sv: 'borta',
      en: 'gone / missing',
      pos: 'adverb',
      enAlt: ['gone', 'missing', 'away'],
    },
    {
      id: 'ligga',
      sv: 'ligga',
      en: 'to lie (be lying)',
      pos: 'verb',
      note: 'For things lying flat: Nyckeln ligger på bordet.',
      forms: { present: 'ligger', past: 'låg', supine: 'legat', imperative: 'ligg' },
      enAlt: ['lie', 'to lie', 'be lying'],
    },
    {
      id: 'sta',
      sv: 'stå',
      en: 'to stand',
      pos: 'verb',
      pron: 'stoh',
      note: 'For things standing upright: Lampan står på bordet.',
      forms: { present: 'står', past: 'stod', supine: 'stått', imperative: 'stå' },
      enAlt: ['stand'],
    },
  ],
  dialogue: {
    title: 'Where are my keys?',
    setting: 'Oskar is late for work. Lina is having breakfast.',
    lines: [
      { speaker: 'Oskar', sv: 'Var är mina nycklar?', en: 'Where are my keys?' },
      { speaker: 'Lina', sv: 'De ligger på bordet.', en: 'They’re on the table.' },
      {
        speaker: 'Oskar',
        sv: 'Nej, de ligger inte där. Och jag hittar inte min mobil!',
        en: 'No, they’re not there. And I can’t find my phone!',
      },
      {
        speaker: 'Lina',
        sv: 'Mobilen ligger bredvid datorn.',
        en: 'The phone is next to the computer.',
      },
      {
        speaker: 'Oskar',
        sv: 'Tack! Men nycklarna är borta.',
        en: 'Thanks! But the keys are gone.',
      },
      { speaker: 'Lina', sv: 'Vänta … de ligger i väskan!', en: 'Wait … they’re in your bag!' },
      { speaker: 'Oskar', sv: 'Tack! Hej då!', en: 'Thanks! Bye!' },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Nyckeln ___ på bordet.',
      en: 'The key is on the table.',
      choices: ['ligger', 'står'],
      answer: 'ligger',
      explanation: 'A key lies flat, so it ligger.',
      vocab: ['ligga', 'pa', 'nyckel'],
    },
    {
      type: 'gap',
      text: 'Lampan ___ på bordet.',
      en: 'The lamp is on the table.',
      choices: ['ligger', 'står'],
      answer: 'står',
      explanation: 'A lamp stands upright, so it står.',
      vocab: ['sta', 'pa', 'lampa'],
    },
    {
      type: 'gap',
      text: 'Var är pappret? ___ ligger under boken.',
      en: 'Where’s the paper? It’s under the book.',
      choices: ['Den', 'Det', 'De'],
      answer: 'Det',
      explanation: 'papper is an ett-word, so "it" is det.',
      vocab: ['det', 'under', 'papper'],
    },
    {
      type: 'gap',
      text: 'Var är mina nycklar? ___ ligger i väskan.',
      en: 'Where are my keys? They’re in the bag.',
      choices: ['Den', 'Det', 'De'],
      answer: 'De',
      explanation: 'nycklar is plural, so "they" is de (said "dom").',
      vocab: ['ligga', 'nyckel'],
    },
    {
      type: 'build',
      prompt: 'The phone is next to the computer.',
      answer: 'Telefonen ligger bredvid datorn.',
      distractors: ['bakom', 'datoren'],
      explanation: 'A phone lies flat, so it ligger. dator → datorn.',
      vocab: ['bredvid', 'ligga', 'telefon', 'dator'],
    },
    {
      type: 'build',
      prompt: 'I can’t find my key!',
      answer: 'Jag hittar inte min nyckel!',
      distractors: ['mitt', 'nyckeln'],
      explanation: 'inte comes right after the verb: Jag hittar inte …',
      vocab: ['hitta', 'min', 'nyckel'],
    },
    {
      type: 'listen',
      audio: 'Stolen står mellan sängen och dörren.',
      choices: [
        'The chair is between the bed and the door.',
        'The chair is next to the bed.',
        'The chair is behind the door.',
      ],
      answer: 'The chair is between the bed and the door.',
      explanation: 'mellan means "between".',
      vocab: ['mellan', 'sta', 'stol'],
    },
    {
      type: 'dictation',
      audio: 'Min nyckel är borta.',
      en: 'My key is gone.',
      vocab: ['borta', 'nyckel'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Oskar', sv: 'Var är min mobil?', en: 'Where’s my phone?' }],
      question: 'It’s next to the computer. What do you say?',
      choices: [
        'Den ligger bredvid datorn.',
        'Det ligger bredvid datorn.',
        'De ligger bredvid datorn.',
      ],
      answer: 'Den ligger bredvid datorn.',
      explanation: 'mobil is an en-word, so "it" is den.',
      vocab: ['den', 'bredvid', 'mobil'],
    },
    {
      type: 'speak',
      text: 'Var är mobilen? Den ligger på bordet.',
      en: 'Where’s the phone? It’s on the table.',
      vocab: ['pa', 'ligga', 'mobil'],
    },
  ],
})
