import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u05-l05',
  learn: [
    {
      title: 'Lagom: just right',
      text: '[[lagom]] means "just the right amount": not too much, not too little. There is no single English word for it, and many Swedes see it as the most Swedish word of all.\n\nCoffee can be lagom strong, a room lagom warm, and a working week lagom long. A famous saying is [[Lagom är bäst.]] (Just right is best.)',
      examples: [
        {
          sv: 'Hur mycket kaffe? Lagom, tack.',
          en: 'How much coffee? Just the right amount, thanks.',
        },
        { sv: 'Det är lagom.', en: "That's just right." },
        { sv: 'Lagom är bäst.', en: 'Just right is best.' },
      ],
      tip: 'lagom never changes its form: en lagom kopp, ett lagom glas.',
    },
    {
      title: 'Too much: för mycket',
      text: '[[mycket]] means "much, a lot" and also "very". Put [[för]] in front and you get "too": [[för mycket]] (too much).\n\nThe opposite of stressed is calm: [[stressad]] and [[lugn]]. And when someone is stressed, Swedes say [[Ta det lugnt!]] (Take it easy!)',
      examples: [
        { sv: 'Jag jobbar för mycket.', en: 'I work too much.' },
        { sv: 'Hon är för stressad.', en: "She's too stressed." },
        { sv: 'Jag är mycket trött.', en: "I'm very tired." },
        { sv: 'Vi läser mycket.', en: 'We read a lot.' },
      ],
    },
    {
      title: 'Time off',
      text: '[[ledig]] means "off, free (from work)": [[Jag är ledig imorgon.]] (I\'m off tomorrow.)\n\n[[semester]] is your holiday from work, and [[fritid]] is your free time.\n\n[[trivas]] is a special verb: its present form ends in **-s**, not -r: [[Jag trivs i Sverige.]] It means you like it somewhere and feel at home.',
      examples: [
        { sv: 'Jag har semester i juli.', en: "I'm on holiday in July." },
        { sv: 'Vad gör du på fritiden?', en: 'What do you do in your free time?' },
        { sv: 'Trivs du i Sverige?', en: 'Do you like living in Sweden?' },
      ],
      tip: 'semester is not a school term! It means a holiday from work.',
    },
  ],
  culture: {
    title: 'Lagom and the long Swedish summer',
    text: "**Lagom** sums up an ideal many Swedes share: balance. Don't show off, don't take more than your share, don't work yourself to exhaustion, and don't be lazy either. Life should be [[lagom]].\n\nYou may hear a story that the word comes from the Vikings, who passed a drinking horn *laget om* (\"around the team\") so that everyone got just the right amount. It's a nice tale, but language historians don't believe it. The word really comes from an old form of [[lag]] (law): \"according to the rule\".\n\nBalance shows in working life too. By law, employees in Sweden have the right to **25 days** (five weeks) of holiday a year, paid once you have worked for a full year, and many workplaces give even more. You normally have the right to take four of those weeks in a row between June and August. Many Swedes take three or four weeks off in **July**, so offices go quiet and the whole country seems to be on [[semester]]. In June, colleagues ask each other: [[Har du semester snart?]]",
    tip: "Don't expect quick answers to emails in July. Everyone is ledig!",
  },
  vocab: [
    {
      id: 'lagom',
      sv: 'lagom',
      en: 'just right / just enough',
      pos: 'adverb',
      pron: 'LAH-gom',
      note: 'Not too much, not too little. It never changes form.',
      enAlt: ['just right', 'just enough', 'the right amount'],
    },
    {
      id: 'lugn',
      sv: 'lugn',
      en: 'calm',
      pos: 'adjective',
      pron: 'lungn',
      forms: { neuter: 'lugnt', plural: 'lugna' },
      note: 'Ta det lugnt! = Take it easy!',
      enAlt: ['relaxed', 'quiet'],
    },
    {
      id: 'stressad',
      sv: 'stressad',
      en: 'stressed',
      pos: 'adjective',
      forms: { neuter: 'stressat', plural: 'stressade' },
    },
    {
      id: 'ledig',
      sv: 'ledig',
      en: 'off (work) / free',
      pos: 'adjective',
      pron: 'LEH-dig',
      forms: { neuter: 'ledigt', plural: 'lediga' },
      note: 'Jag är ledig imorgon. = I\'m off tomorrow. Also "free, available": Är den här stolen ledig?',
      enAlt: ['off', 'free', 'available'],
    },
    {
      id: 'semester',
      sv: 'semester',
      en: 'holiday / vacation (from work)',
      pos: 'noun',
      gender: 'en',
      pron: 'seh-MES-ter',
      forms: { definite: 'semestern', plural: 'semestrar', pluralDefinite: 'semestrarna' },
      note: "Not a school term! Jag har semester. = I'm on holiday.",
      enAlt: ['holiday', 'vacation'],
    },
    {
      id: 'fritid',
      sv: 'fritid',
      en: 'free time / spare time',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'fritiden' },
      note: 'på fritiden = in your free time.',
      enAlt: ['free time', 'spare time', 'leisure'],
    },
    {
      id: 'trivas',
      sv: 'trivas',
      en: 'to like it / feel at home',
      pos: 'verb',
      forms: { present: 'trivs', past: 'trivdes', supine: 'trivts' },
      note: 'The present ends in -s: Jag trivs i Sverige. = I like it in Sweden.',
      enAlt: ['to like it', 'to feel at home', 'to be happy', 'to thrive'],
    },
    {
      id: 'mycket',
      sv: 'mycket',
      en: 'much / a lot / very',
      pos: 'adverb',
      pron: 'MYCK-eh (the t is silent)',
      note: 'Jag läser mycket. (a lot) Jag är mycket trött. (very)',
      enAlt: ['much', 'a lot', 'very', 'lots'],
    },
    {
      id: 'for-too',
      sv: 'för',
      en: 'too (too much)',
      pos: 'adverb',
      pron: 'fur',
      note: 'för mycket = too much, för stressad = too stressed. (för also means "for".)',
      enAlt: ['too'],
    },
  ],
  dialogue: {
    title: 'Too much work',
    setting: 'Sanna meets her neighbour Viktor outside their building.',
    lines: [
      { speaker: 'Sanna', sv: 'Hej Viktor! Hur mår du?', en: 'Hi Viktor! How are you?' },
      {
        speaker: 'Viktor',
        sv: 'Så där. Jag är stressad. Jag jobbar för mycket.',
        en: "So-so. I'm stressed. I work too much.",
      },
      {
        speaker: 'Sanna',
        sv: 'Åh nej! Har du semester snart?',
        en: 'Oh no! Is your holiday coming up soon?',
      },
      { speaker: 'Viktor', sv: 'Ja, i juli. Fyra veckor!', en: 'Yes, in July. Four weeks!' },
      {
        speaker: 'Sanna',
        sv: 'Vad skönt! Vad gör du på fritiden?',
        en: 'How nice! What do you do in your free time?',
      },
      {
        speaker: 'Viktor',
        sv: 'Jag läser och cyklar. Och jag sover mycket!',
        en: 'I read and cycle. And I sleep a lot!',
      },
      {
        speaker: 'Sanna',
        sv: 'Bra! Ta det lugnt. Lagom är bäst!',
        en: 'Good! Take it easy. Just right is best!',
      },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Jag jobbar ___ mycket.',
      en: 'I work too much.',
      choices: ['för', 'ledig', 'lugn'],
      answer: 'för',
      explanation: 'för + mycket = too much.',
      vocab: ['for-too', 'mycket'],
    },
    {
      type: 'gap',
      text: 'Jag är ___ imorgon.',
      en: "I'm off tomorrow.",
      choices: ['ledig', 'fritid', 'semester'],
      answer: 'ledig',
      explanation:
        'ledig (off, free) describes you, like trött or glad. fritid and semester are nouns: Jag har semester.',
      vocab: ['ledig'],
    },
    {
      type: 'build',
      prompt: 'I like it in Sweden.',
      answer: 'Jag trivs i Sverige.',
      distractors: ['trivas', 'trivar'],
      explanation: 'trivas is special: its present form ends in -s, so it is trivs for everyone.',
      vocab: ['trivas'],
    },
    {
      type: 'listen',
      audio: 'Jag har semester i juli.',
      choices: ["I'm on holiday in July.", "I'm working in July.", "I'm off in June."],
      answer: "I'm on holiday in July.",
      explanation: 'Har semester means "to be on holiday", and juli is July.',
      vocab: ['semester'],
    },
    {
      type: 'type',
      prompt: "I'm off today.",
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'Jag är ledig idag.',
      accept: ['Idag är jag ledig.', 'Jag är ledig i dag.', 'I dag är jag ledig.'],
      explanation:
        'ledig means off work. If you start with Idag, the verb comes next: Idag är jag ledig.',
      vocab: ['ledig'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Petra', sv: 'Trivs du i Sverige?', en: 'Do you like it in Sweden?' }],
      question: 'You like it a lot. What do you answer?',
      choices: ['Ja, jag trivs jättebra!', 'Ja, jag trivas jättebra!', 'Ja, jag trivar jättebra!'],
      answer: 'Ja, jag trivs jättebra!',
      explanation: 'The present form of trivas is trivs, with an -s and no -r.',
      vocab: ['trivas'],
    },
    {
      type: 'mcq',
      prompt: 'Ta det lugnt!',
      promptLang: 'sv',
      question: 'What does this mean?',
      choices: ['Take it easy!', 'Take it now!', 'Take a lot!'],
      answer: 'Take it easy!',
      explanation: 'lugn means calm, so Ta det lugnt! is "Take it easy!"',
      vocab: ['lugn'],
    },
    {
      type: 'mcq',
      prompt: 'Paid holiday in Sweden',
      promptLang: 'en',
      question: 'How much holiday a year does Swedish law give employees?',
      choices: ['At least five weeks', 'Two weeks', 'Ten days'],
      answer: 'At least five weeks',
      explanation:
        'The law gives employees 25 days of holiday a year (five working weeks), and some agreements give more. Many Swedes take three or four of those weeks in July.',
      vocab: ['semester'],
    },
    {
      type: 'dictation',
      audio: 'Hon är stressad och jobbar för mycket.',
      en: "She's stressed and works too much.",
      vocab: ['stressad', 'for-too', 'mycket'],
    },
    {
      type: 'speak',
      text: 'Lagom är bäst.',
      en: 'Just right is best.',
      vocab: ['lagom'],
    },
  ],
})
