import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u05-l02',
  learn: [
    {
      title: '-a becomes -er',
      text: 'The second big group of verbs swaps the final **-a** for **-er**: [[läsa]] → [[läser]] (read). Again, one form for everyone: [[jag läser]], [[hon läser]], [[de läser]].\n\nYou already know a few: [[heter]], [[kommer]], [[ligger]], [[köper]].',
      table: {
        headers: ['Dictionary form', 'Present', 'English'],
        rows: [
          ['läsa', 'läser', 'read'],
          ['skriva', 'skriver', 'write'],
          ['ringa', 'ringer', 'call, phone'],
          ['hjälpa', 'hjälper', 'help'],
          ['behöva', 'behöver', 'need'],
          ['använda', 'använder', 'use'],
        ],
        svColumns: [0, 1],
      },
      tip: "The dictionary form doesn't tell you whether a verb takes -ar or -er, so learn the present form with every new verb: läsa, läser.",
    },
    {
      title: 'Stems ending in r',
      text: 'Take away the **-a** and look at what is left. If it already ends in **r**, add nothing: [[höra]] → [[hör]] (hear). You know this from [[göra]] → [[gör]] (do).\n\nCommands are short too: just drop the **-er** from the present form.',
      table: {
        headers: ['Present', 'Command', 'English'],
        rows: [
          ['läser', 'läs!', 'read!'],
          ['skriver', 'skriv!', 'write!'],
          ['hjälper', 'hjälp!', 'help!'],
          ['ringer', 'ring!', 'call!'],
          ['stänger', 'stäng!', 'close!'],
        ],
        svColumns: [0, 1],
      },
      examples: [
        { sv: 'Hör du?', en: 'Can you hear (me)?' },
        { sv: 'Förlåt, jag hör inte.', en: "Sorry, I can't hear." },
        { sv: 'Stäng dörren, snälla!', en: 'Close the door, please!' },
      ],
    },
    {
      title: 'tycka and känna',
      text: '[[tycka]] is for opinions: [[Vad tycker du?]] (What do you think?).\n\nWith **om** it means "like": [[Jag tycker om kaffe.]] (I like coffee.)\n\n[[känna]] means to **know a person**: [[Jag känner Erik.]] It can also mean "to feel".',
      examples: [
        { sv: 'Vad tycker du om jackan?', en: 'What do you think of the jacket?' },
        { sv: 'Jag tycker om den!', en: 'I like it!' },
        { sv: 'Känner du Sara?', en: 'Do you know Sara?' },
        { sv: 'Barnen leker.', en: 'The children are playing.' },
      ],
      tip: '"Play" has two words: leka is what children do, spela is for games, sports and music (spela fotboll).',
    },
  ],
  vocab: [
    {
      id: 'lasa',
      sv: 'läsa',
      en: 'to read',
      pos: 'verb',
      forms: { present: 'läser', past: 'läste', supine: 'läst', imperative: 'läs' },
      note: 'Also "to study": Jag läser svenska.',
      enAlt: ['read', 'to study'],
    },
    {
      id: 'skriva',
      sv: 'skriva',
      en: 'to write',
      pos: 'verb',
      forms: { present: 'skriver', past: 'skrev', supine: 'skrivit', imperative: 'skriv' },
      enAlt: ['write'],
    },
    {
      id: 'tycka',
      sv: 'tycka',
      en: 'to think (have an opinion)',
      pos: 'verb',
      forms: { present: 'tycker', past: 'tyckte', supine: 'tyckt' },
      note: 'Vad tycker du? = What do you think? tycka om = to like: Jag tycker om kaffe.',
      enAlt: ['to think', 'think'],
    },
    {
      id: 'hora',
      sv: 'höra',
      en: 'to hear',
      pos: 'verb',
      forms: { present: 'hör', past: 'hörde', supine: 'hört', imperative: 'hör' },
      note: 'The stem ends in r, so the present is just hör.',
      enAlt: ['hear'],
    },
    {
      id: 'ringa',
      sv: 'ringa',
      en: 'to call / phone',
      pos: 'verb',
      forms: { present: 'ringer', past: 'ringde', supine: 'ringt', imperative: 'ring' },
      enAlt: ['to call', 'to phone', 'to ring', 'call', 'phone'],
    },
    {
      id: 'stanga',
      sv: 'stänga',
      en: 'to close / shut',
      pos: 'verb',
      forms: { present: 'stänger', past: 'stängde', supine: 'stängt', imperative: 'stäng' },
      enAlt: ['to close', 'to shut', 'close', 'shut'],
    },
    {
      id: 'resa',
      sv: 'resa',
      en: 'to travel',
      pos: 'verb',
      forms: { present: 'reser', past: 'reste', supine: 'rest', imperative: 'res' },
      enAlt: ['travel'],
    },
    {
      id: 'leka',
      sv: 'leka',
      en: 'to play (like children do)',
      pos: 'verb',
      forms: { present: 'leker', past: 'lekte', supine: 'lekt', imperative: 'lek' },
      note: 'For games and sports, use spela: spela fotboll.',
      enAlt: ['to play', 'play'],
    },
    {
      id: 'anvanda',
      sv: 'använda',
      en: 'to use',
      pos: 'verb',
      pron: 'an-VEN-da',
      forms: { present: 'använder', past: 'använde', supine: 'använt', imperative: 'använd' },
      enAlt: ['use'],
    },
    {
      id: 'behova',
      sv: 'behöva',
      en: 'to need',
      pos: 'verb',
      forms: { present: 'behöver', past: 'behövde', supine: 'behövt' },
      enAlt: ['need'],
    },
    {
      id: 'hjalpa',
      sv: 'hjälpa',
      en: 'to help',
      pos: 'verb',
      pron: 'YEL-pa (silent h)',
      forms: { present: 'hjälper', past: 'hjälpte', supine: 'hjälpt', imperative: 'hjälp' },
      enAlt: ['help'],
    },
    {
      id: 'kanna',
      sv: 'känna',
      en: 'to know (a person) / feel',
      pos: 'verb',
      pron: 'SHEN-na',
      forms: { present: 'känner', past: 'kände', supine: 'känt', imperative: 'känn' },
      note: 'For people: Jag känner Erik. For facts you use veta (next lesson).',
      enAlt: ['to know', 'to feel', 'know', 'feel'],
    },
  ],
  dialogue: {
    title: 'A book in Swedish',
    setting: 'Sofia meets Jamal in the library.',
    lines: [
      { speaker: 'Sofia', sv: 'Hej Jamal! Vad läser du?', en: 'Hi Jamal! What are you reading?' },
      {
        speaker: 'Jamal',
        sv: 'En bok på svenska. Jag läser lite varje dag.',
        en: 'A book in Swedish. I read a little every day.',
      },
      {
        speaker: 'Sofia',
        sv: 'Vad bra! Vad tycker du om boken?',
        en: 'Great! What do you think of the book?',
      },
      {
        speaker: 'Jamal',
        sv: 'Jag tycker om den. Men jag behöver hjälp med några ord.',
        en: 'I like it. But I need help with a few words.',
      },
      {
        speaker: 'Sofia',
        sv: 'Jag hjälper dig gärna. Ring mig imorgon!',
        en: "I'm happy to help you. Call me tomorrow!",
      },
      {
        speaker: 'Jamal',
        sv: 'Tack, Sofia! Jag ringer imorgon.',
        en: "Thanks, Sofia! I'll call tomorrow.",
      },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Jag ___ en bok.',
      en: "I'm reading a book.",
      choices: ['läser', 'läsar', 'läsa'],
      answer: 'läser',
      explanation: 'läsa is an -er verb: läsa → läser. There is no form läsar.',
      vocab: ['lasa'],
    },
    {
      type: 'gap',
      text: 'Förlåt, jag ___ inte!',
      en: "Sorry, I can't hear!",
      choices: ['hör', 'hörer', 'höra'],
      answer: 'hör',
      explanation:
        'Take away the -a from höra and you get hör. It already ends in r, so nothing is added.',
      vocab: ['hora'],
    },
    {
      type: 'gap',
      text: 'Jag ___ om kaffe.',
      en: 'I like coffee.',
      choices: ['tycker', 'känner', 'behöver'],
      answer: 'tycker',
      explanation: 'tycka om means "to like": Jag tycker om kaffe.',
      vocab: ['tycka'],
    },
    {
      type: 'build',
      prompt: 'Do you use the computer?',
      answer: 'Använder du datorn?',
      distractors: ['använda', 'användar'],
      explanation:
        'In a yes/no question the verb comes first. använda is an -er verb, so the present is använder.',
      vocab: ['anvanda'],
    },
    {
      type: 'type',
      prompt: 'Close the door!',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'Stäng dörren!',
      reject: ['Stänga dörren', 'Stänger dörren'],
      strict: true,
      hint: 'A command is the present form without -er',
      explanation: 'stänger without -er gives the command: stäng! And "the door" is dörren.',
      vocab: ['stanga', 'dorr'],
    },
    {
      type: 'listen',
      audio: 'Vi reser på fredag.',
      choices: [
        "We're travelling on Friday.",
        "We're reading on Friday.",
        "We're resting on Friday.",
      ],
      answer: "We're travelling on Friday.",
      explanation: 'reser comes from resa (travel). "Reading" would be läser, "resting" vilar.',
      vocab: ['resa'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Leo', sv: 'Jag hittar inte min mobil!', en: "I can't find my phone!" }],
      question: 'Offer to call his phone.',
      choices: ['Jag ringer din mobil.', 'Jag ringar din mobil.', 'Jag ringa din mobil.'],
      answer: 'Jag ringer din mobil.',
      explanation: 'ringa is an -er verb: ringa → ringer.',
      vocab: ['ringa'],
    },
    {
      type: 'mcq',
      prompt: 'Känner du Erik?',
      promptLang: 'sv',
      question: 'What does this mean?',
      choices: ['Do you know Erik?', 'Do you like Erik?', 'Are you calling Erik?'],
      answer: 'Do you know Erik?',
      explanation:
        'känna means to know a person. "Do you like Erik?" would be Tycker du om Erik? and "Are you calling Erik?" Ringer du Erik?',
      vocab: ['kanna'],
    },
    {
      type: 'dictation',
      audio: 'Barnen leker och jag skriver.',
      en: "The children are playing and I'm writing.",
      vocab: ['leka', 'skriva'],
    },
    {
      type: 'speak',
      text: 'Jag behöver en penna.',
      en: 'I need a pen.',
      vocab: ['behova', 'penna'],
    },
  ],
})
