import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u05-l01',
  learn: [
    {
      title: 'One form for everyone',
      text: 'Good news: Swedish verbs **never change for the person**. English says "I speak" but "she speak**s**". Swedish says [[talar]] for everyone.\n\nYou have already seen this with [[pratar]] and [[heter]]: [[jag heter]], [[hon heter]], [[vi heter]].',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['jag talar', 'I speak'],
          ['du talar', 'you speak'],
          ['han talar', 'he speaks'],
          ['hon talar', 'she speaks'],
          ['vi talar', 'we speak'],
          ['ni talar', 'you (all) speak'],
          ['de talar', 'they speak'],
        ],
        svColumns: [0],
      },
      tip: 'The same form also covers "I am speaking" and "I do speak". Jag talar can mean all three.',
    },
    {
      title: '-a becomes -ar',
      text: 'In a word list, verbs appear in the **dictionary form** (the infinitive), which usually ends in **-a**: [[tala]] (to speak).\n\nThe biggest group of verbs simply adds **-r** to make the present tense: [[tala]] → [[talar]]. You already know [[prata]] → [[pratar]] and [[hitta]] → [[hittar]].',
      table: {
        headers: ['Dictionary form', 'Present', 'English'],
        rows: [
          ['jobba', 'jobbar', 'work'],
          ['titta', 'tittar', 'look, watch'],
          ['lyssna', 'lyssnar', 'listen'],
          ['städa', 'städar', 'clean'],
          ['vänta', 'väntar', 'wait'],
          ['svara', 'svarar', 'answer'],
        ],
        svColumns: [0, 1],
      },
      tip: 'To tell someone to do something, use the dictionary form: [[Lyssna!]] (Listen!), [[Titta!]] (Look!), [[Vänta!]] (Wait!).',
    },
    {
      title: 'Useful everyday phrases',
      text: 'Some verbs like company. Many take **på**: [[titta på tv]] (watch TV), [[lyssna på]] (listen to), [[vänta på]] (wait for).\n\n[[laga mat]] means "to cook" (literally "make food"). [[jobba]] is the everyday word for "work", and [[arbeta]] is a bit more formal. In the same way, [[prata]] is everyday "talk", and [[tala]] is a little more formal. Both work in [[Jag talar svenska]].',
      examples: [
        { sv: 'Han lagar mat och hon städar.', en: "He's cooking and she's cleaning." },
        { sv: 'Vi tittar på tv.', en: "We're watching TV." },
        { sv: 'Jag väntar på Lisa.', en: "I'm waiting for Lisa." },
        { sv: 'Hon arbetar på lördag.', en: "She's working on Saturday." },
        { sv: 'På söndag spelar de fotboll.', en: 'On Sunday they play football.' },
      ],
      tip: 'Remember: the verb comes second. If you start with På söndag, the person comes after the verb: På söndag spelar de …',
    },
  ],
  vocab: [
    {
      id: 'tala',
      sv: 'tala',
      en: 'to speak (a bit formal)',
      pos: 'verb',
      forms: { present: 'talar', past: 'talade', supine: 'talat', imperative: 'tala' },
      note: 'prata is the everyday word. tala is common for languages: Jag talar svenska.',
      enAlt: ['to speak', 'speak'],
    },
    {
      id: 'arbeta',
      sv: 'arbeta',
      en: 'to work (a bit formal)',
      pos: 'verb',
      forms: { present: 'arbetar', past: 'arbetade', supine: 'arbetat', imperative: 'arbeta' },
      note: 'jobba means the same and is more common when you talk.',
      enAlt: ['to work', 'work'],
    },
    {
      id: 'jobba',
      sv: 'jobba',
      en: 'to work',
      pos: 'verb',
      pron: 'YOB-ba',
      forms: { present: 'jobbar', past: 'jobbade', supine: 'jobbat', imperative: 'jobba' },
      enAlt: ['work'],
    },
    {
      id: 'titta',
      sv: 'titta',
      en: 'to look / watch',
      pos: 'verb',
      forms: { present: 'tittar', past: 'tittade', supine: 'tittat', imperative: 'titta' },
      note: 'titta på = look at, watch: Vi tittar på tv.',
      enAlt: ['to look', 'to watch', 'look', 'watch'],
    },
    {
      id: 'lyssna',
      sv: 'lyssna',
      en: 'to listen',
      pos: 'verb',
      pron: 'LISS-na',
      forms: { present: 'lyssnar', past: 'lyssnade', supine: 'lyssnat', imperative: 'lyssna' },
      note: 'lyssna på = listen to.',
      enAlt: ['listen'],
    },
    {
      id: 'laga',
      sv: 'laga',
      en: 'to cook / to fix',
      pos: 'verb',
      forms: { present: 'lagar', past: 'lagade', supine: 'lagat', imperative: 'laga' },
      note: 'laga mat = to cook. laga also means "to repair": laga cykeln.',
      enAlt: ['to cook', 'to fix', 'to repair', 'cook', 'fix'],
    },
    {
      id: 'stada',
      sv: 'städa',
      en: 'to clean / tidy',
      pos: 'verb',
      forms: { present: 'städar', past: 'städade', supine: 'städat', imperative: 'städa' },
      enAlt: ['to clean', 'to tidy', 'clean', 'tidy'],
    },
    {
      id: 'spela',
      sv: 'spela',
      en: 'to play (a game, sport or instrument)',
      pos: 'verb',
      forms: { present: 'spelar', past: 'spelade', supine: 'spelat', imperative: 'spela' },
      note: 'For games and music: spela fotboll, spela gitarr.',
      enAlt: ['to play', 'play'],
    },
    {
      id: 'dansa',
      sv: 'dansa',
      en: 'to dance',
      pos: 'verb',
      forms: { present: 'dansar', past: 'dansade', supine: 'dansat', imperative: 'dansa' },
      enAlt: ['dance'],
    },
    {
      id: 'vanta',
      sv: 'vänta',
      en: 'to wait',
      pos: 'verb',
      forms: { present: 'väntar', past: 'väntade', supine: 'väntat', imperative: 'vänta' },
      note: 'vänta på = wait for: Jag väntar på Lisa.',
      enAlt: ['wait'],
    },
    {
      id: 'fraga',
      sv: 'fråga',
      en: 'to ask',
      pos: 'verb',
      forms: { present: 'frågar', past: 'frågade', supine: 'frågat', imperative: 'fråga' },
      enAlt: ['ask'],
    },
    {
      id: 'svara',
      sv: 'svara',
      en: 'to answer',
      pos: 'verb',
      forms: { present: 'svarar', past: 'svarade', supine: 'svarat', imperative: 'svara' },
      enAlt: ['answer', 'to reply', 'reply'],
    },
  ],
  dialogue: {
    title: 'The weekend',
    setting: 'Linnea and Ahmed are colleagues. It is Friday afternoon.',
    lines: [
      {
        speaker: 'Linnea',
        sv: 'Vad gör du på lördag, Ahmed?',
        en: 'What are you doing on Saturday, Ahmed?',
      },
      { speaker: 'Ahmed', sv: 'Jag jobbar. Och du?', en: "I'm working. And you?" },
      {
        speaker: 'Linnea',
        sv: 'Jag spelar fotboll. Och på söndag städar jag.',
        en: "I'm playing football. And on Sunday I'm cleaning.",
      },
      {
        speaker: 'Ahmed',
        sv: 'Jag städar inte på söndag. Jag lagar mat och tittar på tv!',
        en: "I'm not cleaning on Sunday. I'm cooking and watching TV!",
      },
      {
        speaker: 'Linnea',
        sv: 'Lagar du mat? Vad lagar du?',
        en: 'You cook? What are you making?',
      },
      {
        speaker: 'Ahmed',
        sv: 'Pasta! Kom och ät hos mig på söndag!',
        en: 'Pasta! Come and eat at my place on Sunday!',
      },
      { speaker: 'Linnea', sv: 'Gärna! Tack!', en: "I'd love to! Thanks!" },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Hon ___ svenska.',
      en: 'She speaks Swedish.',
      choices: ['talar', 'tala', 'talat'],
      answer: 'talar',
      explanation:
        'The present tense of tala is talar, and it is the same for everyone: jag talar, hon talar, de talar. tala is the dictionary form.',
      vocab: ['tala'],
    },
    {
      type: 'gap',
      text: 'Jag ___ på Lisa.',
      en: "I'm waiting for Lisa.",
      choices: ['väntar', 'svarar', 'städar'],
      answer: 'väntar',
      explanation: 'vänta på means "wait for": Jag väntar på Lisa.',
      vocab: ['vanta'],
    },
    {
      type: 'gap',
      text: 'Ni ___ jättebra!',
      en: 'You dance really well!',
      choices: ['dansar', 'dansa', 'dansat'],
      answer: 'dansar',
      explanation:
        'ni (you, plural) takes the same form as everyone else: ni dansar. Swedish never adds a different ending for a different person.',
      vocab: ['dansa'],
    },
    {
      type: 'build',
      prompt: 'On Saturday I clean the kitchen.',
      answer: 'På lördag städar jag köket.',
      distractors: ['städa', 'städat'],
      explanation:
        'The sentence starts with På lördag, so the verb comes next (second place) and jag follows it: På lördag städar jag …',
      vocab: ['stada', 'lordag'],
    },
    {
      type: 'listen',
      audio: 'Hon tittar på tv och han lagar mat.',
      choices: [
        "She's watching TV and he's cooking.",
        "He's watching TV and she's cooking.",
        "She's watching TV and he's cleaning.",
      ],
      answer: "She's watching TV and he's cooking.",
      explanation: 'tittar på tv = is watching TV, lagar mat = is cooking.',
      vocab: ['titta', 'laga'],
    },
    {
      type: 'type',
      prompt: "They're listening.",
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'De lyssnar.',
      accept: ['Dom lyssnar.'],
      reject: ['De lyssna', 'De lyssnat', 'Dom lyssna'],
      strict: true,
      hint: 'lyssna is an -ar verb',
      explanation: 'lyssna → lyssnar. The -r ending is the present tense, for every person.',
      vocab: ['lyssna'],
    },
    {
      type: 'dictation',
      audio: 'Vi arbetar idag och spelar fotboll på söndag.',
      en: "We're working today and playing football on Sunday.",
      accept: ['Vi arbetar i dag och spelar fotboll på söndag.'],
      vocab: ['arbeta', 'spela'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Eva', sv: 'Talar du svenska?', en: 'Do you speak Swedish?' }],
      question: 'You speak a little. What do you answer?',
      choices: [
        'Ja, jag talar lite svenska.',
        'Ja, jag tala lite svenska.',
        'Ja, talar jag lite svenska.',
      ],
      answer: 'Ja, jag talar lite svenska.',
      explanation:
        'Use the present form talar, and keep the normal order: jag + verb. "Ja" doesn\'t count as the first part of the sentence.',
      vocab: ['tala'],
    },
    {
      type: 'mcq',
      prompt: 'Hon frågar och jag svarar.',
      promptLang: 'sv',
      question: 'What does this mean?',
      choices: ['She asks and I answer.', 'She answers and I ask.', 'She listens and I answer.'],
      answer: 'She asks and I answer.',
      explanation: 'frågar = asks, svarar = answers.',
      vocab: ['fraga', 'svara'],
    },
    {
      type: 'speak',
      text: 'Jag jobbar på lördag och söndag.',
      en: "I'm working on Saturday and Sunday.",
      vocab: ['jobba'],
    },
  ],
})
