import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u05-l03',
  learn: [
    {
      title: 'vara and ha',
      text: 'The two most important verbs are **vara** (to be) and **ha** (to have). You already know [[är]]: it is the present form of [[vara]].\n\n[[ha]] becomes [[har]]. As always, one form for everyone.',
      examples: [
        { sv: 'Jag är trött.', en: "I'm tired." },
        { sv: 'Vi är lärare.', en: "We're teachers." },
        { sv: 'Hon har en hund och en katt.', en: 'She has a dog and a cat.' },
        { sv: 'Har du en penna?', en: 'Do you have a pen?' },
      ],
      tip: 'English "am, is, are" are all just är in Swedish: jag är, du är, de är.',
    },
    {
      title: 'Short verbs add -r',
      text: 'Very short verbs (just one syllable, ending in a vowel) simply add **-r**. You already know one: [[bo]] → [[bor]].',
      table: {
        headers: ['Dictionary form', 'Present', 'English'],
        rows: [
          ['ha', 'har', 'have'],
          ['gå', 'går', 'go, walk'],
          ['se', 'ser', 'see'],
          ['tro', 'tror', 'think, believe'],
          ['få', 'får', 'get, may'],
          ['ta', 'tar', 'take'],
        ],
        svColumns: [0, 1],
      },
      tip: 'gå means going on foot (or leaving): [[Vi går nu.]] (We\'re leaving now.) Får jag …? means "May I …?": [[Får jag ett glas vatten?]]',
    },
    {
      title: 'More everyday verbs',
      text: '[[äta]] → [[äter]], [[dricka]] → [[dricker]] and [[sova]] → [[sover]] are normal in the present. (Their past forms are irregular, but that comes later.)\n\n[[veta]] is the odd one: the present is just [[vet]].\n\nEnglish "know" has two Swedish words. **veta** is for facts, **känna** for people. And [[tro]] is "think" in the sense of "believe, guess".',
      examples: [
        { sv: 'Jag vet inte.', en: "I don't know." },
        { sv: 'Vet du var Lisa är?', en: 'Do you know where Lisa is?' },
        { sv: 'Jag känner Lisa.', en: 'I know Lisa.' },
        { sv: 'Hon sover, tror jag.', en: "She's sleeping, I think." },
      ],
      tip: 'tro = you think it is true but you are not sure. tycka = your opinion: Vad tycker du?',
    },
  ],
  vocab: [
    {
      id: 'vara',
      sv: 'vara',
      en: 'to be',
      pos: 'verb',
      forms: { present: 'är', past: 'var', supine: 'varit', imperative: 'var' },
      note: 'Present: är. Var snäll! = Be kind!',
      enAlt: ['be'],
    },
    {
      id: 'ha',
      sv: 'ha',
      en: 'to have',
      pos: 'verb',
      pron: 'hah',
      forms: { present: 'har', past: 'hade', supine: 'haft', imperative: 'ha' },
      enAlt: ['have'],
    },
    {
      id: 'ga-go',
      sv: 'gå',
      en: 'to go / walk',
      pos: 'verb',
      pron: 'goh',
      forms: { present: 'går', past: 'gick', supine: 'gått', imperative: 'gå' },
      note: 'Usually on foot. Also "to leave": Vi går nu.',
      enAlt: ['to go', 'to walk', 'go', 'walk', 'to leave'],
    },
    {
      id: 'tro',
      sv: 'tro',
      en: 'to think / believe',
      pos: 'verb',
      pron: 'troo',
      forms: { present: 'tror', past: 'trodde', supine: 'trott', imperative: 'tro' },
      note: 'Jag tror det. = I think so.',
      enAlt: ['to think', 'to believe', 'think', 'believe'],
    },
    {
      id: 'se',
      sv: 'se',
      en: 'to see',
      pos: 'verb',
      pron: 'seh',
      forms: { present: 'ser', past: 'såg', supine: 'sett', imperative: 'se' },
      enAlt: ['see'],
    },
    {
      id: 'ata',
      sv: 'äta',
      en: 'to eat',
      pos: 'verb',
      forms: { present: 'äter', past: 'åt', supine: 'ätit', imperative: 'ät' },
      enAlt: ['eat'],
    },
    {
      id: 'dricka',
      sv: 'dricka',
      en: 'to drink',
      pos: 'verb',
      forms: { present: 'dricker', past: 'drack', supine: 'druckit', imperative: 'drick' },
      enAlt: ['drink'],
    },
    {
      id: 'sova',
      sv: 'sova',
      en: 'to sleep',
      pos: 'verb',
      forms: { present: 'sover', past: 'sov', supine: 'sovit', imperative: 'sov' },
      enAlt: ['sleep'],
    },
    {
      id: 'veta',
      sv: 'veta',
      en: 'to know (a fact)',
      pos: 'verb',
      forms: { present: 'vet', past: 'visste', supine: 'vetat' },
      note: "Present: vet (no -er). Jag vet inte. = I don't know. For people, use känna.",
      enAlt: ['to know', 'know'],
    },
    {
      id: 'fa',
      sv: 'få',
      en: 'to get / may',
      pos: 'verb',
      pron: 'foh',
      forms: { present: 'får', past: 'fick', supine: 'fått', imperative: 'få' },
      note: 'Får jag …? = May I …? / Can I have …?',
      enAlt: ['to get', 'to receive', 'may', 'get', 'to be allowed to'],
    },
    {
      id: 'ta',
      sv: 'ta',
      en: 'to take',
      pos: 'verb',
      pron: 'tah',
      forms: { present: 'tar', past: 'tog', supine: 'tagit', imperative: 'ta' },
      enAlt: ['take'],
    },
  ],
  dialogue: {
    title: 'Morning coffee',
    setting: 'Elsa and Noah share a flat with Lisa. It is early in the morning.',
    lines: [
      {
        speaker: 'Elsa',
        sv: 'God morgon, Noah! Har du kaffe?',
        en: 'Good morning, Noah! Do you have coffee?',
      },
      { speaker: 'Noah', sv: 'Ja, i köket. Ta en kopp!', en: 'Yes, in the kitchen. Have a cup!' },
      { speaker: 'Elsa', sv: 'Tack! Jag är så trött idag.', en: "Thanks! I'm so tired today." },
      { speaker: 'Noah', sv: 'Sover du inte bra?', en: "Aren't you sleeping well?" },
      {
        speaker: 'Elsa',
        sv: 'Nej, inte så bra. Var är Lisa?',
        en: 'No, not very well. Where is Lisa?',
      },
      {
        speaker: 'Noah',
        sv: 'Jag vet inte. Hon sover, tror jag.',
        en: "I don't know. She's asleep, I think.",
      },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Jag ___ inte.',
      en: "I don't know.",
      choices: ['vet', 'veter', 'känner'],
      answer: 'vet',
      explanation:
        'veta is irregular: the present is just vet. känna is for knowing people, and it needs a person after it.',
      vocab: ['veta'],
    },
    {
      type: 'gap',
      text: 'Barnen ___ nu.',
      en: 'The children are sleeping now.',
      choices: ['sover', 'sovar', 'sova'],
      answer: 'sover',
      explanation: 'sova takes -er in the present: sova → sover.',
      vocab: ['sova'],
    },
    {
      type: 'gap',
      text: 'Hon ___ en hund och en katt.',
      en: 'She has a dog and a cat.',
      choices: ['har', 'ha', 'är'],
      answer: 'har',
      explanation: 'ha (to have) is short, so it just adds -r: har.',
      vocab: ['ha'],
    },
    {
      type: 'build',
      prompt: "Today I'm drinking water.",
      answer: 'Idag dricker jag vatten.',
      distractors: ['dricka', 'drickar'],
      explanation:
        'The sentence starts with Idag, so the verb comes second and jag follows it. dricka → dricker.',
      vocab: ['dricka', 'idag'],
    },
    {
      type: 'listen',
      audio: 'Ser du katten?',
      choices: ['Do you see the cat?', 'Do you have a cat?', 'Is the cat sleeping?'],
      answer: 'Do you see the cat?',
      explanation: 'ser comes from se (see). "Do you have a cat?" would be Har du en katt?',
      vocab: ['se'],
    },
    {
      type: 'mcq',
      prompt: 'I know Anna.',
      promptLang: 'en',
      question: 'Which is right?',
      choices: ['Jag känner Anna.', 'Jag vet Anna.', 'Jag tycker Anna.'],
      answer: 'Jag känner Anna.',
      explanation: 'For people, "know" is känna. veta is only for facts: Jag vet var hon bor.',
      vocab: ['kanna', 'veta'],
    },
    {
      type: 'type',
      prompt: "I don't think so.",
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'Jag tror inte det.',
      accept: ['Det tror jag inte.', 'Jag tror det inte.'],
      explanation:
        'tror is "think" in the sense of "believe". inte comes right after the verb: Jag tror inte det.',
      vocab: ['tro'],
    },
    {
      type: 'dialogueReply',
      lines: [
        { speaker: 'Kalle', sv: 'Får jag ett glas vatten?', en: 'May I have a glass of water?' },
      ],
      question: 'Give him the water.',
      choices: ['Ja, varsågod!', 'Nej, jag sover.', 'Ja, jag får.'],
      answer: 'Ja, varsågod!',
      explanation:
        'Får jag …? asks for something politely. Answer with varsågod as you hand it over. "Ja, jag får" makes no sense here: he is the one asking.',
      vocab: ['fa'],
    },
    {
      type: 'dictation',
      audio: 'Hon äter och dricker kaffe.',
      en: "She's eating and drinking coffee.",
      vocab: ['ata', 'dricka'],
    },
    {
      type: 'speak',
      text: 'Vi går nu. Hej då!',
      en: "We're leaving now. Bye!",
      vocab: ['ga-go'],
    },
  ],
})
