import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u05-l04',
  learn: [
    {
      title: 'Helper verb + dictionary form',
      text: 'Words like **kan** (can), **vill** (want to), **ska** (will, going to) and **måste** (must, have to) are helper verbs. After them comes a second verb in the **dictionary form**, with no "att" (to) in between.\n\n[[Jag kan simma.]] (I can swim.) [[Hon vill dricka kaffe.]] (She wants to drink coffee.)',
      table: {
        headers: ['Helper', 'Meaning', 'Example', 'English'],
        rows: [
          ['kan', 'can', 'Jag kan simma.', 'I can swim.'],
          ['vill', 'want to', 'Hon vill dricka kaffe.', 'She wants to drink coffee.'],
          ['ska', 'will, be going to', 'Vi ska äta.', "We're going to eat."],
          ['måste', 'must, have to', 'Jag måste jobba.', 'I have to work.'],
        ],
        svColumns: [0, 2],
      },
      tip: 'English says "want **to** eat", but Swedish just says vill äta. Never put att after kan, vill, ska or måste.',
    },
    {
      title: 'inte goes after the helper',
      text: "The helper is the verb that sits in second place, so **inte** comes right after it: [[Jag kan inte simma.]] (I can't swim.)\n\nFor a question, put the helper first: [[Kan du simma?]] (Can you swim?)",
      examples: [
        { sv: 'Hon vill inte sjunga.', en: "She doesn't want to sing." },
        { sv: 'Vill du cykla imorgon?', en: 'Do you want to cycle tomorrow?' },
        { sv: 'Ska vi äta nu?', en: 'Shall we eat now?' },
      ],
      tip: 'Ska vi …? is the easiest way to suggest something: [[Ska vi fika?]] (Shall we have a coffee?)',
    },
    {
      title: 'Starting and stopping',
      text: '[[börja]] (start) and [[sluta]] (stop, finish) are normal -ar verbs. In everyday Swedish they are often followed directly by a dictionary form, too.',
      examples: [
        { sv: 'Jag börjar jobba klockan åtta.', en: 'I start work at eight.' },
        { sv: 'Jag slutar klockan fem.', en: 'I finish at five.' },
        { sv: 'Skolan börjar på måndag.', en: 'School starts on Monday.' },
      ],
    },
  ],
  vocab: [
    {
      id: 'kunna',
      sv: 'kunna',
      en: 'can / to be able to',
      pos: 'verb',
      forms: { present: 'kan', past: 'kunde', supine: 'kunnat' },
      note: 'Present: kan. Jag kan simma. Also "know" a skill or language: Jag kan svenska.',
      enAlt: ['can', 'to be able to', 'be able to'],
    },
    {
      id: 'vilja',
      sv: 'vilja',
      en: 'to want (to)',
      pos: 'verb',
      forms: { present: 'vill', past: 'ville', supine: 'velat' },
      note: 'Present: vill. Jag vill dricka kaffe. (no att!)',
      enAlt: ['to want', 'want', 'want to'],
    },
    {
      id: 'ska',
      sv: 'ska',
      en: 'will / be going to / shall',
      pos: 'verb',
      forms: { present: 'ska', past: 'skulle' },
      note: 'For plans and suggestions: Vi ska äta. Ska vi fika? The old dictionary form is skola, and in formal writing you may see skall.',
      enAlt: ['will', 'shall', 'be going to', 'going to'],
    },
    {
      id: 'maste',
      sv: 'måste',
      en: 'must / have to',
      pos: 'verb',
      forms: { present: 'måste' },
      note: 'The same form is also used for the past: Igår måste jag jobba. (Yesterday I had to work.)',
      enAlt: ['must', 'have to', 'to have to'],
    },
    {
      id: 'borja',
      sv: 'börja',
      en: 'to start / begin',
      pos: 'verb',
      pron: 'BUR-ya',
      forms: { present: 'börjar', past: 'började', supine: 'börjat', imperative: 'börja' },
      enAlt: ['to start', 'to begin', 'start', 'begin'],
    },
    {
      id: 'sluta',
      sv: 'sluta',
      en: 'to stop / finish',
      pos: 'verb',
      forms: { present: 'slutar', past: 'slutade', supine: 'slutat', imperative: 'sluta' },
      note: 'Also "to quit": Sluta! = Stop it!',
      enAlt: ['to stop', 'to finish', 'to end', 'stop', 'finish', 'quit'],
    },
    {
      id: 'simma',
      sv: 'simma',
      en: 'to swim',
      pos: 'verb',
      forms: { present: 'simmar', past: 'simmade', supine: 'simmat', imperative: 'simma' },
      enAlt: ['swim'],
    },
    {
      id: 'cykla',
      sv: 'cykla',
      en: 'to cycle / ride a bike',
      pos: 'verb',
      forms: { present: 'cyklar', past: 'cyklade', supine: 'cyklat', imperative: 'cykla' },
      enAlt: ['to cycle', 'to bike', 'to ride a bike', 'cycle', 'bike'],
    },
    {
      id: 'sjunga',
      sv: 'sjunga',
      en: 'to sing',
      pos: 'verb',
      pron: 'SHUNG-a',
      forms: { present: 'sjunger', past: 'sjöng', supine: 'sjungit', imperative: 'sjung' },
      enAlt: ['sing'],
    },
  ],
  dialogue: {
    title: 'Saturday plans',
    setting: 'Maja calls her friend Omar on a hot day in June.',
    lines: [
      {
        speaker: 'Maja',
        sv: 'Hej Omar! Vad ska du göra på lördag?',
        en: 'Hi Omar! What are you doing on Saturday?',
      },
      {
        speaker: 'Omar',
        sv: 'Jag ska cykla till sjön. Vill du följa med?',
        en: "I'm going to cycle to the lake. Do you want to come along?",
      },
      { speaker: 'Maja', sv: 'Gärna! Kan vi simma där?', en: "I'd love to! Can we swim there?" },
      { speaker: 'Omar', sv: 'Ja, men vattnet är kallt!', en: 'Yes, but the water is cold!' },
      {
        speaker: 'Maja',
        sv: 'Ingen fara. Men jag måste jobba på morgonen. Jag slutar klockan tolv.',
        en: 'No problem. But I have to work in the morning. I finish at twelve.',
      },
      {
        speaker: 'Omar',
        sv: 'Bra! Då cyklar vi klockan ett.',
        en: "Great! Then we'll cycle at one.",
      },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Jag kan ___.',
      en: 'I can swim.',
      choices: ['simma', 'simmar', 'att simma'],
      answer: 'simma',
      explanation: 'After kan comes the dictionary form, with no att: Jag kan simma.',
      vocab: ['kunna', 'simma'],
    },
    {
      type: 'gap',
      text: 'Hon ___ inte sjunga.',
      en: "She doesn't want to sing.",
      choices: ['vill', 'vilja', 'viller'],
      answer: 'vill',
      explanation: 'The present of vilja is vill, the same for everyone. inte comes after it.',
      vocab: ['vilja', 'sjunga'],
    },
    {
      type: 'build',
      prompt: "I can't swim.",
      answer: 'Jag kan inte simma.',
      distractors: ['att', 'simmar'],
      explanation:
        'inte goes straight after the helper kan, and simma stays in the dictionary form without att.',
      vocab: ['kunna', 'simma'],
    },
    {
      type: 'listen',
      audio: 'Vill du cykla imorgon?',
      choices: [
        'Do you want to cycle tomorrow?',
        'Can you cycle tomorrow?',
        'Are you cycling today?',
      ],
      answer: 'Do you want to cycle tomorrow?',
      explanation: 'vill = want to. "Can you" would be kan du.',
      vocab: ['vilja', 'cykla'],
    },
    {
      type: 'type',
      prompt: 'I have to work.',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'Jag måste jobba.',
      accept: ['Jag måste arbeta.'],
      reject: [
        'Jag måste att jobba',
        'Jag måste jobbar',
        'Jag måste att arbeta',
        'Jag måste arbetar',
      ],
      strict: true,
      hint: 'No att after måste',
      explanation: 'måste + dictionary form: Jag måste jobba. No att, and no -r on jobba.',
      vocab: ['maste', 'jobba'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Elin', sv: 'Kan du sjunga?', en: 'Can you sing?' }],
      question: "You can't sing. What do you answer?",
      choices: [
        'Nej, jag kan inte sjunga.',
        'Nej, jag kan sjunga inte.',
        'Nej, jag inte kan sjunga.',
      ],
      answer: 'Nej, jag kan inte sjunga.',
      explanation: 'inte comes right after the first verb, kan: jag kan inte sjunga.',
      vocab: ['kunna', 'sjunga'],
    },
    {
      type: 'gap',
      text: 'Vi ___ äta klockan sex.',
      en: "We're going to eat at six.",
      choices: ['ska', 'äter', 'måste att'],
      answer: 'ska',
      explanation:
        'ska is for plans: Vi ska äta (we are going to eat). äter cannot be followed by a second verb like this, and måste never takes att.',
      vocab: ['ska'],
    },
    {
      type: 'mcq',
      prompt: 'Jag slutar klockan fem.',
      promptLang: 'sv',
      question: 'What does this mean?',
      choices: ['I finish at five.', 'I start at five.', 'I sleep at five.'],
      answer: 'I finish at five.',
      explanation: 'sluta = stop, finish. "Start" is börja: Jag börjar klockan fem.',
      vocab: ['sluta'],
    },
    {
      type: 'dictation',
      audio: 'Jag börjar jobba klockan åtta.',
      en: 'I start work at eight.',
      vocab: ['borja'],
    },
    {
      type: 'speak',
      text: 'Vi ska cykla och simma på lördag.',
      en: "We're going to cycle and swim on Saturday.",
      vocab: ['ska', 'cykla', 'simma'],
    },
  ],
})
