import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u07-l02',
  learn: [
    {
      title: 'Kan jag få …?',
      text: 'The most useful phrase in any café is [[Kan jag få …?]] Can I have …? (literally "Can I get …?"). Another easy way is to just say what you’ll take: [[Jag tar …]] I’ll have …\n\nYou don’t need a word for "please" when you order ([[snälla]] sounds like pleading). Just put [[tack]] at the end and you are polite enough anywhere.',
      examples: [
        { sv: 'Kan jag få en kopp kaffe?', en: 'Can I have a cup of coffee?' },
        { sv: 'Kan jag få ett glas vatten, tack?', en: 'Could I have a glass of water, please?' },
        { sv: 'Jag tar en kanelbulle, tack.', en: 'I’ll have a cinnamon bun, please.' },
        { sv: 'Kan vi beställa?', en: 'Can we order?' },
      ],
      tip: 'When ordering a cup, Swedes often say [[en kaffe]] instead of ett kaffe: "En kaffe, tack!"',
    },
    {
      title: 'At the counter',
      text: 'These are the questions you will hear at the counter, and easy answers. [[Det var allt]] literally means "that was all": Swedes use the past tense here.',
      table: {
        headers: ['You hear', 'English', 'You answer', 'English'],
        rows: [
          ['Något mer?', 'Anything else?', 'Nej tack, det var allt.', 'No thanks, that’s all.'],
          [
            'Ska du äta här eller ta med?',
            'For here or to go?',
            'Äta här, tack.',
            'For here, please.',
          ],
          ['Ska du äta här eller ta med?', 'For here or to go?', 'Ta med, tack.', 'To go, please.'],
          [
            'Vad vill du dricka?',
            'What would you like to drink?',
            'Ett glas vatten, tack.',
            'A glass of water, please.',
          ],
        ],
        svColumns: [0, 2],
      },
      tip: '[[ta med]] literally means "take with (you)".',
    },
    {
      title: 'Paying and eating',
      text: 'When you are finished at a restaurant, ask the waiter for the bill: [[Kan jag få notan?]] Paying by card is normal almost everywhere: [[Kan jag betala med kort?]] ([[med]] means "with" or "by".)\n\nWhen the food arrives, the waiter or your host may say [[Smaklig måltid!]] Enjoy your meal!',
      examples: [
        { sv: 'Kan jag få notan, tack?', en: 'Could I have the bill, please?' },
        { sv: 'Kan jag betala med kort?', en: 'Can I pay by card?' },
        { sv: 'kaffe med mjölk', en: 'coffee with milk' },
        { sv: 'Jag är hungrig och törstig.', en: 'I’m hungry and thirsty.' },
        { sv: 'Smaklig måltid!', en: 'Enjoy your meal!' },
      ],
      tip: 'After a meal at someone’s home, Swedes thank the cook with [[Tack för maten!]] (Thanks for the food!).',
    },
  ],
  vocab: [
    {
      id: 'bestalla',
      sv: 'beställa',
      en: 'to order',
      pos: 'verb',
      pron: 'beh-STELL-a',
      forms: { present: 'beställer', past: 'beställde', supine: 'beställt', imperative: 'beställ' },
    },
    {
      id: 'meny',
      sv: 'meny',
      en: 'menu',
      pos: 'noun',
      gender: 'en',
      pron: 'meh-NEE',
      forms: { definite: 'menyn', plural: 'menyer', pluralDefinite: 'menyerna' },
    },
    {
      id: 'ta-med',
      sv: 'ta med',
      en: 'to go / takeaway',
      pos: 'phrase',
      note: 'Literally "take with". Ta med, tack = To go, please.',
      enAlt: ['to go', 'takeaway', 'take away', 'to take away', 'to take with'],
    },
    {
      id: 'ata-har',
      sv: 'äta här',
      en: 'for here / eat in',
      pos: 'phrase',
      note: 'Äta här, tack = For here, please.',
      enAlt: ['for here', 'eat in', 'eat here', 'to eat here', 'to eat in'],
    },
    {
      id: 'nota',
      sv: 'nota',
      en: 'bill (in a restaurant)',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'notan', plural: 'notor', pluralDefinite: 'notorna' },
      enAlt: ['bill', 'check'],
    },
    {
      id: 'betala',
      sv: 'betala',
      en: 'to pay',
      pos: 'verb',
      pron: 'beh-TAH-la',
      forms: { present: 'betalar', past: 'betalade', supine: 'betalat', imperative: 'betala' },
    },
    {
      id: 'servitor',
      sv: 'servitör',
      en: 'waiter / server',
      pos: 'noun',
      gender: 'en',
      pron: 'ser-vi-TUR',
      note: 'A woman is sometimes called servitris, but servitör works for everyone.',
      forms: { definite: 'servitören', plural: 'servitörer', pluralDefinite: 'servitörerna' },
      enAlt: ['waiter', 'server', 'waitress'],
    },
    {
      id: 'hungrig',
      sv: 'hungrig',
      en: 'hungry',
      pos: 'adjective',
      forms: { neuter: 'hungrigt', plural: 'hungriga' },
    },
    {
      id: 'torstig',
      sv: 'törstig',
      en: 'thirsty',
      pos: 'adjective',
      pron: 'TURSH-tig',
      forms: { neuter: 'törstigt', plural: 'törstiga' },
    },
    {
      id: 'smaklig-maltid',
      sv: 'smaklig måltid',
      en: 'enjoy your meal',
      pos: 'phrase',
      pron: 'SMAHK-li MOHL-teed',
      note: 'Said when the food is served, like "bon appétit".',
      enAlt: ['bon appetit', 'enjoy your food'],
    },
    {
      id: 'med-u7',
      sv: 'med',
      en: 'with / by',
      pos: 'preposition',
      note: 'betala med kort = pay by card; kaffe med mjölk = coffee with milk.',
      enAlt: ['with', 'by'],
    },
  ],
  dialogue: {
    title: 'At the café counter',
    setting: 'Sara is at a café. Johan works behind the counter.',
    lines: [
      { speaker: 'Johan', sv: 'Hej! Vad vill du ha?', en: 'Hi! What would you like?' },
      {
        speaker: 'Sara',
        sv: 'Hej! Kan jag få en kopp kaffe och en kanelbulle?',
        en: 'Hi! Can I have a cup of coffee and a cinnamon bun?',
      },
      { speaker: 'Johan', sv: 'Absolut. Något mer?', en: 'Sure. Anything else?' },
      { speaker: 'Sara', sv: 'Nej tack, det var allt.', en: 'No thanks, that’s all.' },
      { speaker: 'Johan', sv: 'Ska du äta här eller ta med?', en: 'For here or to go?' },
      {
        speaker: 'Sara',
        sv: 'Äta här, tack. Kan jag betala med kort?',
        en: 'For here, please. Can I pay by card?',
      },
      { speaker: 'Johan', sv: 'Ja, visst. Varsågod!', en: 'Yes, of course. Here you go!' },
    ],
  },
  exercises: [
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Johan', sv: 'Något mer?', en: 'Anything else?' }],
      question: 'You don’t want anything else. What do you say?',
      choices: ['Nej tack, det var allt.', 'Ta med, tack.', 'Smaklig måltid!'],
      answer: 'Nej tack, det var allt.',
      explanation: '"Det var allt" (that’s all) is the standard way to finish your order.',
      vocab: ['nej', 'tack'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Johan', sv: 'Ska du äta här eller ta med?', en: 'For here or to go?' }],
      question: 'You want to take your coffee with you. What do you say?',
      choices: ['Ta med, tack.', 'Äta här, tack.', 'Kan jag få notan?'],
      answer: 'Ta med, tack.',
      explanation: 'ta med means "to go" (literally "take with"). äta här means "eat here".',
      vocab: ['ta-med', 'ata-har'],
    },
    {
      type: 'gap',
      text: 'Kan jag ___ en kopp kaffe?',
      en: 'Can I have a cup of coffee?',
      choices: ['få', 'får', 'tar'],
      answer: 'få',
      explanation:
        'After kan, the next verb is in its basic form (the infinitive): kan jag få. "Kan jag få …?" is the polite way to order.',
      vocab: ['kopp', 'kaffe'],
    },
    {
      type: 'gap',
      text: 'Kan vi ___ nu?',
      en: 'Can we order now?',
      choices: ['beställa', 'beställer', 'beställde'],
      answer: 'beställa',
      explanation:
        'After kan, use the infinitive: kan vi beställa. beställer is the present tense.',
      vocab: ['bestalla', 'nu'],
    },
    {
      type: 'build',
      prompt: 'Can I have the bill, please?',
      answer: 'Kan jag få notan, tack?',
      distractors: ['nota', 'får'],
      explanation:
        'You ask for "the bill", so it is notan (nota + n). After kan, the verb stays in the infinitive: få.',
      vocab: ['nota'],
    },
    {
      type: 'build',
      prompt: 'I’ll have a cinnamon bun, please.',
      answer: 'Jag tar en kanelbulle, tack.',
      distractors: ['ett', 'kanelbullen'],
      explanation:
        '"Jag tar …" (I’ll take …) is a simple way to order. kanelbulle is an en-word: en kanelbulle.',
      vocab: ['kanelbulle'],
    },
    {
      type: 'mcq',
      prompt: 'Smaklig måltid!',
      promptLang: 'sv',
      question: 'The waiter brings your food and says this. What does it mean?',
      choices: ['Enjoy your meal!', 'Here is the bill.', 'Anything else?'],
      answer: 'Enjoy your meal!',
      explanation:
        'smaklig måltid literally means "tasty meal". It’s said when the food is served.',
      vocab: ['smaklig-maltid'],
    },
    {
      type: 'listen',
      audio: 'Jag är hungrig och törstig.',
      choices: ['I’m hungry and thirsty.', 'I’m tired and thirsty.', 'I’m hungry and happy.'],
      answer: 'I’m hungry and thirsty.',
      explanation: 'hungrig = hungry, törstig = thirsty. (Tired is trött, happy is glad.)',
      vocab: ['hungrig', 'torstig'],
    },
    {
      type: 'dictation',
      audio: 'Kan jag betala med kort?',
      en: 'Can I pay by card?',
      vocab: ['betala', 'med-u7', 'kort'],
    },
    {
      type: 'speak',
      text: 'Kan jag få en kopp kaffe och en kanelbulle, tack?',
      en: 'Can I have a cup of coffee and a cinnamon bun, please?',
      vocab: ['kopp', 'kaffe', 'kanelbulle'],
    },
  ],
})
