import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u07-l04',
  learn: [
    {
      title: 'In the shop',
      text: 'A food shop is [[en mataffär]], but most people just say [[affären]] (the shop). Here is what goes in the basket.\n\nSome foods are "stuff" rather than "things": you say [[smör]], [[kött]] and [[mjölk]] with no en or ett, just like "butter" and "meat" in English.',
      table: {
        headers: ['a …', 'the …', 'English'],
        rows: [
          ['ett bröd', 'brödet', 'a loaf of bread'],
          ['smör', 'smöret', 'butter'],
          ['en ost', 'osten', 'a cheese'],
          ['ett ägg', 'ägget', 'an egg'],
          ['en frukt', 'frukten', 'a piece of fruit'],
          ['en grönsak', 'grönsaken', 'a vegetable'],
          ['kött', 'köttet', 'meat'],
          ['en fisk', 'fisken', 'a fish'],
          ['en potatis', 'potatisen', 'a potato'],
          ['en påse', 'påsen', 'a bag'],
        ],
        svColumns: [0, 1],
      },
      tip: 'ägg is the same in the plural: [[ett ägg]], [[tolv ägg]]. The same goes for bröd: [[två bröd]].',
    },
    {
      title: 'Det finns: there is, there are',
      text: 'To say that something exists or is available, Swedes say [[det finns]]: [[Det finns ost.]] There’s cheese.\n\nTurn it around to ask: [[Finns det …?]] Is there …? / Do you have …? And in a shop, ask where something is with [[Var finns …?]]',
      examples: [
        { sv: 'Det finns bröd och smör.', en: 'There’s bread and butter.' },
        { sv: 'Finns det ägg?', en: 'Are there any eggs?' },
        { sv: 'Det finns ingen mjölk.', en: 'There’s no milk.' },
        { sv: 'Ursäkta, var finns osten?', en: 'Excuse me, where’s the cheese?' },
      ],
      tip: 'Finns det …? is also how you ask staff if they have something: [[Finns det kanelbullar?]]',
    },
    {
      title: 'The shopping list',
      text: 'Write your list with [[Vi behöver …]] We need … At the checkout you will usually hear [[Vill du ha en påse?]] Bags usually cost a few kronor, so many Swedes bring their own.',
      examples: [
        { sv: 'Vi behöver mjölk och bröd.', en: 'We need milk and bread.' },
        { sv: 'Vi behöver tolv ägg och lite ost.', en: 'We need twelve eggs and some cheese.' },
        { sv: 'Vill du ha en påse?', en: 'Do you want a bag?' },
        { sv: 'Nej tack, jag har en påse.', en: 'No thanks, I have a bag.' },
      ],
    },
  ],
  vocab: [
    {
      id: 'affar',
      sv: 'affär',
      en: 'shop / store',
      pos: 'noun',
      gender: 'en',
      pron: 'a-FAIR',
      note: 'A food shop is en mataffär.',
      forms: { definite: 'affären', plural: 'affärer', pluralDefinite: 'affärerna' },
      enAlt: ['shop', 'store'],
    },
    {
      id: 'brod',
      sv: 'bröd',
      en: 'bread',
      pos: 'noun',
      gender: 'ett',
      pron: 'brurd (long ö)',
      note: 'ett bröd = a loaf of bread.',
      forms: { definite: 'brödet', plural: 'bröd', pluralDefinite: 'bröden' },
      enAlt: ['loaf', 'loaf of bread'],
    },
    {
      id: 'smor',
      sv: 'smör',
      en: 'butter',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'smöret' },
    },
    {
      id: 'ost',
      sv: 'ost',
      en: 'cheese',
      pos: 'noun',
      gender: 'en',
      pron: 'oost (long o, like "oo")',
      forms: { definite: 'osten', plural: 'ostar', pluralDefinite: 'ostarna' },
    },
    {
      id: 'agg',
      sv: 'ägg',
      en: 'egg',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'ägget', plural: 'ägg', pluralDefinite: 'äggen' },
    },
    {
      id: 'frukt',
      sv: 'frukt',
      en: 'fruit',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'frukten', plural: 'frukter', pluralDefinite: 'frukterna' },
    },
    {
      id: 'gronsak',
      sv: 'grönsak',
      en: 'vegetable',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'grönsaken', plural: 'grönsaker', pluralDefinite: 'grönsakerna' },
      enAlt: ['veggie'],
    },
    {
      id: 'kott',
      sv: 'kött',
      en: 'meat',
      pos: 'noun',
      gender: 'ett',
      pron: 'soft k (the tj-sound), short ö',
      forms: { definite: 'köttet' },
    },
    {
      id: 'fisk',
      sv: 'fisk',
      en: 'fish',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'fisken', plural: 'fiskar', pluralDefinite: 'fiskarna' },
    },
    {
      id: 'potatis',
      sv: 'potatis',
      en: 'potato',
      pos: 'noun',
      gender: 'en',
      pron: 'poo-TAH-tis',
      note: 'Often used like "stuff" too: Vi köper potatis.',
      forms: { definite: 'potatisen', plural: 'potatisar', pluralDefinite: 'potatisarna' },
      enAlt: ['potatoes'],
    },
    {
      id: 'pase',
      sv: 'påse',
      en: 'bag',
      pos: 'noun',
      gender: 'en',
      pron: 'POH-seh',
      note: 'A plastic or paper bag. A handbag is en väska.',
      forms: { definite: 'påsen', plural: 'påsar', pluralDefinite: 'påsarna' },
      enAlt: ['plastic bag', 'paper bag', 'carrier bag'],
    },
    {
      id: 'det-finns-u7',
      sv: 'det finns',
      en: 'there is / there are',
      pos: 'phrase',
      note: 'Question: Finns det …? (Is there …?). Var finns …? = Where is …? (in a shop)',
      enAlt: ['there is', 'there are'],
    },
  ],
  dialogue: {
    title: 'The weekly shop',
    setting: 'Lina and Oskar are at the supermarket. Ali works at the checkout.',
    lines: [
      { speaker: 'Lina', sv: 'Vad behöver vi?', en: 'What do we need?' },
      {
        speaker: 'Oskar',
        sv: 'Vi behöver mjölk, bröd och ägg.',
        en: 'We need milk, bread and eggs.',
      },
      { speaker: 'Lina', sv: 'Och ost! Var finns osten?', en: 'And cheese! Where’s the cheese?' },
      { speaker: 'Oskar', sv: 'Där borta, bredvid smöret.', en: 'Over there, next to the butter.' },
      {
        speaker: 'Lina',
        sv: 'Ska vi köpa fisk eller kött idag?',
        en: 'Shall we buy fish or meat today?',
      },
      {
        speaker: 'Oskar',
        sv: 'Fisk! Och potatis och lite grönsaker.',
        en: 'Fish! And potatoes and some vegetables.',
      },
      { speaker: 'Ali', sv: 'Hej! Vill du ha en påse?', en: 'Hi! Do you want a bag?' },
      { speaker: 'Lina', sv: 'Nej tack, vi har en påse.', en: 'No thanks, we have a bag.' },
    ],
  },
  exercises: [
    {
      type: 'listen',
      audio: 'Vi behöver mjölk och bröd.',
      choices: ['We need milk and bread.', 'We need milk and butter.', 'We have milk and bread.'],
      answer: 'We need milk and bread.',
      explanation: 'behöver = need, bröd = bread. (Butter is smör, and "we have" is vi har.)',
      vocab: ['brod'],
    },
    {
      type: 'gap',
      text: '___ det ägg?',
      en: 'Are there any eggs?',
      choices: ['Finns', 'Har', 'Köper'],
      answer: 'Finns',
      explanation:
        'Is there / Are there … ? is Finns det …? The verb comes first in a yes/no question.',
      vocab: ['det-finns-u7', 'agg'],
    },
    {
      type: 'gap',
      text: 'Jag köper tolv ___.',
      en: 'I’m buying twelve eggs.',
      choices: ['ägg', 'äggar', 'äggen'],
      answer: 'ägg',
      explanation:
        'Most ett-words that end in a consonant have no plural ending: ett ägg, tolv ägg. äggen means "the eggs".',
      vocab: ['agg', 'tolv', 'kopa'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Ali', sv: 'Vill du ha en påse?', en: 'Do you want a bag?' }],
      question: 'You brought your own bag. What do you say?',
      choices: ['Nej tack, jag har en påse.', 'Ja tack, två påsar.', 'Det finns ingen påse.'],
      answer: 'Nej tack, jag har en påse.',
      explanation:
        'Bags usually cost a few kronor in Swedish shops, so it is normal to say no if you have your own.',
      vocab: ['pase'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Ali', sv: 'Hej! Kan jag hjälpa till?', en: 'Hi! Can I help?' }],
      question: 'You can’t find the fish. What do you ask?',
      choices: [
        'Ja tack, var finns fisken?',
        'Ja tack, finns det en påse?',
        'Nej tack, jag har fisk.',
      ],
      answer: 'Ja tack, var finns fisken?',
      explanation: 'Var finns …? is the way to ask where something is in a shop: Var finns fisken?',
      vocab: ['fisk', 'det-finns-u7'],
    },
    {
      type: 'build',
      prompt: 'We need bread and butter.',
      answer: 'Vi behöver bröd och smör.',
      accept: ['Vi behöver smör och bröd.'],
      distractors: ['brödet', 'har'],
      explanation:
        'behöver = need. Bread and butter are general "stuff" here, so no en/ett and no -et ending.',
      vocab: ['brod', 'smor'],
    },
    {
      type: 'build',
      prompt: 'Is there any cheese?',
      answer: 'Finns det ost?',
      distractors: ['är', 'osten'],
      explanation: 'Finns det …? asks if something is there. Cheese in general is just ost.',
      vocab: ['ost', 'det-finns-u7'],
    },
    {
      type: 'mcq',
      prompt: 'Vill du ha en påse?',
      promptLang: 'sv',
      question: 'The cashier asks you this. What does she want to know?',
      choices: ['If you want a bag', 'If you want the receipt', 'If you have a card'],
      answer: 'If you want a bag',
      explanation: 'en påse is a (shopping) bag. The receipt is kvittot.',
      vocab: ['pase'],
    },
    {
      type: 'dictation',
      audio: 'Vi köper fisk, potatis och grönsaker.',
      en: 'We’re buying fish, potatoes and vegetables.',
      vocab: ['fisk', 'potatis', 'gronsak', 'kopa'],
    },
    {
      type: 'speak',
      text: 'Ursäkta, var finns brödet?',
      en: 'Excuse me, where’s the bread?',
      vocab: ['ursakta', 'brod', 'det-finns-u7'],
    },
  ],
})
