import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u07-l03',
  learn: [
    {
      title: 'What does it cost?',
      text: 'Swedish money is the **krona** (crown). One is [[en krona]], more than one is [[kronor]]. Prices are written **kr**, but you say the whole word: 45 kr = [[fyrtiofem kronor]].\n\nTo ask the price, say [[Vad kostar …?]] or [[Hur mycket kostar …?]] At the till you will hear [[Det blir …]] That’ll be …',
      examples: [
        { sv: 'Vad kostar en kanelbulle?', en: 'How much is a cinnamon bun?' },
        { sv: 'Den kostar fyrtiotvå kronor.', en: 'It costs 42 kronor.' },
        { sv: 'Hur mycket kostar kaffet?', en: 'How much is the coffee?' },
        { sv: 'Det blir åttiofem kronor.', en: 'That’ll be 85 kronor.' },
      ],
      table: {
        caption: 'A café price list (example prices)',
        headers: ['On the menu', 'Price', 'Say it'],
        rows: [
          ['en kopp kaffe', '35 kr', 'trettiofem kronor'],
          ['en kanelbulle', '42 kr', 'fyrtiotvå kronor'],
          ['en varm choklad', '45 kr', 'fyrtiofem kronor'],
          ['en smörgås', '89 kr', 'åttionio kronor'],
        ],
        svColumns: [0, 2],
      },
    },
    {
      title: 'Cheap or expensive?',
      text: '[[billig]] means cheap and [[dyr]] means expensive. When you talk about a price in general, say [[Det är dyrt]] or [[Det är billigt]], with a **-t** (you will learn why in Unit 9).\n\nLooking for a bargain? [[Det är rea!]] means "There’s a sale on!"',
      examples: [
        { sv: 'Oj, det är dyrt!', en: 'Oh, that’s expensive!' },
        { sv: 'Det är billigt här.', en: 'It’s cheap here.' },
        { sv: 'Priset är bra.', en: 'The price is good.' },
        { sv: 'Det är rea på fredag.', en: 'There’s a sale on Friday.' },
      ],
    },
    {
      title: 'Card, Swish or cash?',
      text: 'Cash is rarely used in Sweden. Most people pay by card, or they [[swisha]]: **Swish** is a mobile app connected to your bank account, and almost everyone uses it, even to pay a friend back.\n\nMany cafés and some shops don’t take cash at all, so check before you ask [[Kan jag betala kontant?]] (Can I pay cash?). After you pay, you may hear [[Vill du ha kvittot?]] Do you want the receipt?',
      examples: [
        { sv: 'Kan jag swisha?', en: 'Can I pay with Swish?' },
        { sv: 'Kan jag betala kontant?', en: 'Can I pay (in) cash?' },
        { sv: 'Vill du ha kvittot?', en: 'Do you want the receipt?' },
        { sv: 'Jag swishar dig femtio kronor.', en: 'I’ll Swish you fifty kronor.' },
      ],
      tip: 'A common sign: [[Vi tar inte kontanter]] (We don’t take cash).',
    },
  ],
  vocab: [
    {
      id: 'krona',
      sv: 'krona',
      en: 'krona (Swedish crown)',
      pos: 'noun',
      gender: 'en',
      note: 'Written kr: 45 kr = fyrtiofem kronor. Also means "crown".',
      forms: { definite: 'kronan', plural: 'kronor', pluralDefinite: 'kronorna' },
      enAlt: ['krona', 'kronor', 'crown', 'Swedish crown'],
    },
    {
      id: 'kosta',
      sv: 'kosta',
      en: 'to cost',
      pos: 'verb',
      forms: { present: 'kostar', past: 'kostade', supine: 'kostat' },
    },
    {
      id: 'billig',
      sv: 'billig',
      en: 'cheap',
      pos: 'adjective',
      forms: { neuter: 'billigt', plural: 'billiga' },
      enAlt: ['inexpensive'],
    },
    {
      id: 'dyr',
      sv: 'dyr',
      en: 'expensive',
      pos: 'adjective',
      pron: 'deer (Swedish y)',
      forms: { neuter: 'dyrt', plural: 'dyra' },
      enAlt: ['dear', 'pricey'],
    },
    {
      id: 'pris',
      sv: 'pris',
      en: 'price',
      pos: 'noun',
      gender: 'ett',
      note: 'Also means "prize".',
      forms: { definite: 'priset', plural: 'priser', pluralDefinite: 'priserna' },
    },
    {
      id: 'swisha',
      sv: 'swisha',
      en: 'to pay with Swish',
      pos: 'verb',
      pron: 'SWISH-a',
      note: 'Swish is the mobile payment app almost everyone in Sweden uses.',
      forms: { present: 'swishar', past: 'swishade', supine: 'swishat', imperative: 'swisha' },
      enAlt: ['to swish', 'swish', 'pay with Swish'],
    },
    {
      id: 'kvitto',
      sv: 'kvitto',
      en: 'receipt',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'kvittot', plural: 'kvitton', pluralDefinite: 'kvittona' },
    },
    {
      id: 'rea',
      sv: 'rea',
      en: 'sale',
      pos: 'noun',
      gender: 'en',
      pron: 'REH-a',
      note: 'Det är rea = There’s a sale on.',
      forms: { definite: 'rean', plural: 'reor', pluralDefinite: 'reorna' },
    },
    {
      id: 'kontant',
      sv: 'kontant',
      en: 'in cash',
      pos: 'adverb',
      note: 'betala kontant = pay (in) cash. Cash itself is kontanter.',
      enAlt: ['cash'],
    },
  ],
  dialogue: {
    title: 'At the bakery',
    setting: 'Ella is buying something at a bakery. Mikael works at the till.',
    lines: [
      {
        speaker: 'Ella',
        sv: 'Hej! Vad kostar kanelbullarna?',
        en: 'Hi! How much are the cinnamon buns?',
      },
      {
        speaker: 'Mikael',
        sv: 'De kostar trettiofem kronor styck.',
        en: 'They’re 35 kronor each.',
      },
      {
        speaker: 'Ella',
        sv: 'Okej. Och tårtan? Hur mycket kostar den?',
        en: 'OK. And the cake? How much is it?',
      },
      { speaker: 'Mikael', sv: 'Den kostar trehundrafemtio kronor.', en: 'It costs 350 kronor.' },
      {
        speaker: 'Ella',
        sv: 'Oj, det är dyrt! Jag tar två kanelbullar.',
        en: 'Oh, that’s expensive! I’ll take two cinnamon buns.',
      },
      {
        speaker: 'Mikael',
        sv: 'Det blir sjuttio kronor. Kort eller Swish?',
        en: 'That’ll be 70 kronor. Card or Swish?',
      },
      { speaker: 'Ella', sv: 'Kan jag betala kontant?', en: 'Can I pay cash?' },
      {
        speaker: 'Mikael',
        sv: 'Tyvärr, vi tar inte kontanter.',
        en: 'Sorry, we don’t take cash.',
      },
    ],
  },
  exercises: [
    {
      type: 'listen',
      audio: 'Det kostar fyrtiofem kronor.',
      choices: ['It costs 45 kronor.', 'It costs 55 kronor.', 'It costs 40 kronor.'],
      answer: 'It costs 45 kronor.',
      explanation: 'fyrtiofem = 45. In numbers, the tens come first, as in English: fyrtio + fem.',
      vocab: ['kosta', 'krona', 'fyrtio', 'fem'],
    },
    {
      type: 'mcq',
      prompt: '76 kr',
      promptLang: 'en',
      question: 'How do you say this price?',
      choices: ['sjuttiosex kronor', 'sextiosju kronor', 'sjuttiosex krona'],
      answer: 'sjuttiosex kronor',
      explanation:
        '76 is sjuttio + sex, written as one word. kr is always said kronor when there is more than one.',
      vocab: ['krona', 'sjuttio', 'sex'],
    },
    {
      type: 'gap',
      text: '___ kostar en kopp kaffe?',
      en: 'How much is a cup of coffee?',
      choices: ['Vad', 'Var', 'Vem'],
      answer: 'Vad',
      explanation: 'Swedes ask "What does it cost?": Vad kostar …? (Or: Hur mycket kostar …?)',
      vocab: ['kosta', 'vad'],
    },
    {
      type: 'gap',
      text: 'Två kanelbullar kostar sjuttio ___.',
      en: 'Two cinnamon buns cost 70 kronor.',
      choices: ['kronor', 'krona', 'kronan'],
      answer: 'kronor',
      explanation:
        'More than one krona is kronor. Only "one krona" is en krona, and kronan means "the krona".',
      vocab: ['krona', 'kanelbulle'],
    },
    {
      type: 'dialogueReply',
      lines: [
        {
          speaker: 'Mikael',
          sv: 'Det blir åttiofem kronor. Kort eller Swish?',
          en: 'That’ll be 85 kronor. Card or Swish?',
        },
      ],
      question: 'You want to pay with the app on your phone. What do you say?',
      choices: ['Jag swishar.', 'Kontant, tack.', 'Det är dyrt.'],
      answer: 'Jag swishar.',
      explanation: 'swisha means to pay with Swish, the mobile payment app: jag swishar.',
      vocab: ['swisha'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Mikael', sv: 'Vill du ha kvittot?', en: 'Do you want the receipt?' }],
      question: 'You don’t need it. What do you say?',
      choices: ['Nej tack, det är bra.', 'Ja, det är dyrt.', 'Nej, det kostar tio kronor.'],
      answer: 'Nej tack, det är bra.',
      explanation: '"Nej tack, det är bra" is a friendly "No thanks, I’m fine".',
      vocab: ['kvitto', 'nej', 'tack'],
    },
    {
      type: 'build',
      prompt: 'How much does the cake cost?',
      answer: 'Hur mycket kostar tårtan?',
      distractors: ['tårta', 'många'],
      explanation:
        'Hur mycket = how much, then the verb kostar, then the thing: tårtan (the cake). Hur många is for things you count: how many.',
      vocab: ['kosta', 'tarta', 'hur-mycket'],
    },
    {
      type: 'build',
      prompt: 'There’s a sale today!',
      answer: 'Det är rea idag!',
      accept: ['Idag är det rea!'],
      distractors: ['en', 'reor'],
      explanation:
        '"Det är rea" means there’s a sale on. If you start with idag, the verb comes next: Idag är det rea!',
      vocab: ['rea', 'idag'],
    },
    {
      type: 'dictation',
      audio: 'Kan jag betala kontant?',
      en: 'Can I pay cash?',
      vocab: ['kontant', 'betala'],
    },
    {
      type: 'speak',
      text: 'Hur mycket kostar kanelbullarna?',
      en: 'How much are the cinnamon buns?',
      vocab: ['kosta', 'kanelbulle'],
    },
  ],
})
