import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u07-l05',
  learn: [
    {
      title: 'Three meals a day',
      text: 'The meals are [[frukost]] (breakfast), [[lunch]] and [[middag]] (dinner). Just like in English, you don’t put en or ett in front when you eat them: [[äta frukost]], [[äta lunch]], [[äta middag]].\n\nThe big question at home: [[Vad blir det till middag?]] What’s for dinner?',
      table: {
        headers: ['Meal', 'English', 'Typical time'],
        rows: [
          ['frukost', 'breakfast', '7–8'],
          ['lunch', 'lunch', '11.30–13'],
          ['middag', 'dinner', '17–18'],
        ],
        svColumns: [0],
      },
      examples: [
        { sv: 'Jag äter frukost klockan sju.', en: 'I have breakfast at seven.' },
        { sv: 'Vi äter middag klockan sex.', en: 'We have dinner at six.' },
        { sv: 'Vad blir det till middag?', en: 'What’s for dinner?' },
        { sv: 'Det blir kyckling och ris.', en: 'We’re having chicken and rice.' },
      ],
      tip: 'Swedes eat dinner early, often around five or six in the evening.',
    },
    {
      title: 'Jag tycker om …',
      text: '[[Jag tycker om …]] means "I like …". To say you don’t like something, put **inte** right after tycker: [[Jag tycker inte om …]]\n\nDon’t eat meat? Say [[Jag är vegetarian.]] Just like with jobs (Jag är lärare), there is no en in front.',
      examples: [
        { sv: 'Jag tycker om soppa.', en: 'I like soup.' },
        { sv: 'Jag tycker inte om fisk.', en: 'I don’t like fish.' },
        { sv: 'Tycker du om kyckling?', en: 'Do you like chicken?' },
        { sv: 'Jag är vegetarian.', en: 'I’m a vegetarian.' },
      ],
      tip: '[[gillar]] means the same and is a bit more casual: [[Jag gillar pasta.]]',
    },
    {
      title: 'Allergies',
      text: 'To talk about an allergy, say [[Jag är allergisk mot …]] I’m allergic to … ([[mot]] usually means "against".)',
      examples: [
        { sv: 'Jag är allergisk mot nötter.', en: 'I’m allergic to nuts.' },
        { sv: 'Jag är allergisk mot fisk.', en: 'I’m allergic to fish.' },
        { sv: 'Är du allergisk mot något?', en: 'Are you allergic to anything?' },
        { sv: 'Jag äter inte kött.', en: 'I don’t eat meat.' },
      ],
      tip: 'Restaurants in Sweden are used to allergies. Just say it when you order.',
    },
  ],
  culture: {
    title: 'Dagens lunch',
    text: 'On weekdays, lots of restaurants serve [[dagens lunch]] ("today’s lunch"): a daily special at a set price, often somewhere around 120–160 kronor. Salad, bread, a drink and coffee are often included, so it is a popular deal.\n\nLunch is early, from about half past eleven, and many people eat it with colleagues. Others bring a [[matlåda]] (lunch box) from home and heat it in the office microwave.\n\nThe evening meal comes early too: many families eat [[middag]] at around five or six.',
    examples: [
      { sv: 'Vad är dagens lunch?', en: 'What’s today’s lunch special?' },
      { sv: 'Dagens lunch: kyckling med ris', en: 'Today’s lunch: chicken with rice' },
      { sv: 'Ska vi äta lunch?', en: 'Shall we have lunch?' },
    ],
  },
  vocab: [
    {
      id: 'frukost',
      sv: 'frukost',
      en: 'breakfast',
      pos: 'noun',
      gender: 'en',
      pron: 'FROO-kost',
      forms: { definite: 'frukosten', plural: 'frukostar', pluralDefinite: 'frukostarna' },
    },
    {
      id: 'lunch',
      sv: 'lunch',
      en: 'lunch',
      pos: 'noun',
      gender: 'en',
      pron: 'lunsh (Swedish u)',
      forms: { definite: 'lunchen', plural: 'luncher', pluralDefinite: 'luncherna' },
    },
    {
      id: 'middag',
      sv: 'middag',
      en: 'dinner',
      pos: 'noun',
      gender: 'en',
      pron: 'MID-dahg',
      note: 'äta middag = have dinner.',
      forms: { definite: 'middagen', plural: 'middagar', pluralDefinite: 'middagarna' },
    },
    {
      id: 'recept',
      sv: 'recept',
      en: 'recipe',
      pos: 'noun',
      gender: 'ett',
      pron: 'reh-SEPT',
      note: 'Also a (doctor’s) prescription.',
      forms: { definite: 'receptet', plural: 'recept', pluralDefinite: 'recepten' },
    },
    {
      id: 'sallad',
      sv: 'sallad',
      en: 'salad / lettuce',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'salladen', plural: 'sallader', pluralDefinite: 'salladerna' },
      enAlt: ['salad', 'lettuce'],
    },
    {
      id: 'soppa',
      sv: 'soppa',
      en: 'soup',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'soppan', plural: 'soppor', pluralDefinite: 'sopporna' },
    },
    {
      id: 'kyckling',
      sv: 'kyckling',
      en: 'chicken',
      pos: 'noun',
      gender: 'en',
      pron: 'CHICK-ling (soft k)',
      forms: { definite: 'kycklingen', plural: 'kycklingar', pluralDefinite: 'kycklingarna' },
    },
    {
      id: 'ris',
      sv: 'ris',
      en: 'rice',
      pos: 'noun',
      gender: 'ett',
      pron: 'rees',
      forms: { definite: 'riset' },
    },
    {
      id: 'pasta',
      sv: 'pasta',
      en: 'pasta',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'pastan' },
    },
    {
      id: 'vegetarian',
      sv: 'vegetarian',
      en: 'vegetarian',
      pos: 'noun',
      gender: 'en',
      pron: 'veh-geh-ta-ri-AHN',
      note: 'Jag är vegetarian (no en in front).',
      forms: { definite: 'vegetarianen', plural: 'vegetarianer', pluralDefinite: 'vegetarianerna' },
    },
    {
      id: 'allergisk',
      sv: 'allergisk',
      en: 'allergic',
      pos: 'adjective',
      pron: 'al-LER-gisk (hard g)',
      note: 'allergisk mot = allergic to.',
      forms: { neuter: 'allergiskt', plural: 'allergiska' },
    },
    {
      id: 'mot-u7',
      sv: 'mot',
      en: 'against / to',
      pos: 'preposition',
      pron: 'moot',
      note: 'allergisk mot nötter = allergic to nuts.',
      enAlt: ['against', 'to', 'towards'],
    },
  ],
  dialogue: {
    title: 'Dinner on Friday',
    setting: 'Karin invites her colleague Amir to dinner at her home.',
    lines: [
      {
        speaker: 'Karin',
        sv: 'Vill du äta middag hos oss på fredag?',
        en: 'Would you like to have dinner at our place on Friday?',
      },
      {
        speaker: 'Amir',
        sv: 'Ja, gärna! Jag äter inte kött.',
        en: 'Yes, I’d love to! I don’t eat meat.',
      },
      {
        speaker: 'Karin',
        sv: 'Inga problem. Tycker du om pasta?',
        en: 'No problem. Do you like pasta?',
      },
      { speaker: 'Amir', sv: 'Ja, jag älskar pasta!', en: 'Yes, I love pasta!' },
      {
        speaker: 'Karin',
        sv: 'Bra! Jag har ett jättegott recept. Är du allergisk mot något?',
        en: 'Great! I have a really good recipe. Are you allergic to anything?',
      },
      { speaker: 'Amir', sv: 'Ja, mot nötter.', en: 'Yes, to nuts.' },
      {
        speaker: 'Karin',
        sv: 'Okej, inga nötter då. Vi äter klockan sex.',
        en: 'OK, no nuts then. We eat at six.',
      },
      { speaker: 'Amir', sv: 'Perfekt! Tack!', en: 'Perfect! Thanks!' },
    ],
  },
  exercises: [
    {
      type: 'listen',
      audio: 'Jag äter frukost klockan sju.',
      choices: ['I have breakfast at seven.', 'I have lunch at seven.', 'I have dinner at seven.'],
      answer: 'I have breakfast at seven.',
      explanation: 'frukost = breakfast, lunch = lunch, middag = dinner.',
      vocab: ['frukost', 'klocka', 'sju'],
    },
    {
      type: 'gap',
      text: 'Jag tycker ___ om fisk.',
      en: 'I don’t like fish.',
      choices: ['inte', 'ingen', 'nej'],
      answer: 'inte',
      explanation: 'inte goes right after the verb tycker, before om: Jag tycker inte om fisk.',
      vocab: ['inte', 'fisk'],
    },
    {
      type: 'gap',
      text: 'Jag är allergisk ___ ägg.',
      en: 'I’m allergic to eggs.',
      choices: ['mot', 'till', 'i'],
      answer: 'mot',
      explanation: 'In Swedish you are allergic "against" something: allergisk mot ägg.',
      vocab: ['allergisk', 'mot-u7', 'agg'],
    },
    {
      type: 'gap',
      text: 'Vi äter ___ klockan tolv.',
      en: 'We have lunch at twelve.',
      choices: ['lunch', 'en lunch', 'lunchen'],
      answer: 'lunch',
      explanation: 'Meals have no en or ett after äta: äta frukost, äta lunch, äta middag.',
      vocab: ['lunch', 'tolv'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Servitören', sv: 'Vad vill du äta?', en: 'What would you like to eat?' }],
      question: 'You are a vegetarian. What do you order?',
      choices: [
        'Jag tar pasta med grönsaker, tack.',
        'Jag tar kyckling med ris, tack.',
        'Jag tar fisk och potatis, tack.',
      ],
      answer: 'Jag tar pasta med grönsaker, tack.',
      explanation: 'Pasta with vegetables has no meat or fish. kyckling is chicken, fisk is fish.',
      vocab: ['pasta', 'gronsak', 'vegetarian'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Karin', sv: 'Tycker du om kyckling?', en: 'Do you like chicken?' }],
      question: 'You do. What do you say?',
      choices: [
        'Ja, jag tycker om kyckling.',
        'Ja, jag tycker kyckling om.',
        'Ja, jag om tycker kyckling.',
      ],
      answer: 'Ja, jag tycker om kyckling.',
      explanation: 'tycker om belongs together, and the food comes after: Jag tycker om kyckling.',
      vocab: ['kyckling'],
    },
    {
      type: 'build',
      prompt: 'I don’t like soup.',
      answer: 'Jag tycker inte om soppa.',
      distractors: ['tar', 'ingen'],
      explanation: 'inte comes right after the verb tycker and before om.',
      vocab: ['soppa', 'inte'],
    },
    {
      type: 'mcq',
      prompt: 'dagens lunch',
      promptLang: 'sv',
      question: 'You see this sign outside a restaurant. What is it?',
      choices: [
        'A daily lunch special, often with salad, bread and coffee',
        'A lunch that is only for children',
        'A shop that sells lunch boxes',
      ],
      answer: 'A daily lunch special, often with salad, bread and coffee',
      explanation:
        'Dagens lunch means "today’s lunch": a set dish at a set price, often with salad, bread and coffee included.',
      vocab: ['lunch', 'sallad'],
    },
    {
      type: 'type',
      prompt: 'We have dinner at six.',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'Vi äter middag klockan sex.',
      accept: [
        'Klockan sex äter vi middag.',
        'Vi äter middag klockan 6.',
        'Klockan 6 äter vi middag.',
      ],
      hint: 'to eat = äta',
      explanation:
        'äta middag (no en) = have dinner. If you start with klockan sex, the verb comes next: Klockan sex äter vi middag.',
      vocab: ['middag', 'klocka', 'sex'],
    },
    {
      type: 'speak',
      text: 'Jag är allergisk mot nötter.',
      en: 'I’m allergic to nuts.',
      vocab: ['allergisk', 'mot-u7'],
    },
  ],
})
