import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u07-l01',
  learn: [
    {
      title: 'Fika: something you do and something you have',
      text: '[[fika]] is a verb: you **fika** with friends or colleagues. In the present tense it is [[fikar]], just like [[pratar]].\n\nIt is also a noun: [[en fika]] is a coffee break. The classic invitation is [[Ska vi fika?]] Shall we have a fika?',
      examples: [
        { sv: 'Ska vi fika?', en: 'Shall we have a fika? / Want to grab a coffee?' },
        { sv: 'Ska vi ta en fika?', en: 'Shall we take a coffee break?' },
        { sv: 'Vi fikar klockan tre.', en: 'We have fika at three o’clock.' },
        {
          sv: 'Min kollega och jag fikar varje dag.',
          en: 'My colleague and I have fika every day.',
        },
      ],
      tip: 'English has no real word for it, so many English speakers in Sweden just say "Let’s fika!"',
    },
    {
      title: 'What’s on the table',
      text: 'A fika is coffee or tea with something to eat. Here are the classics. [[socker]] and [[choklad]] are "stuff" words, so they usually have no en or ett in front.',
      table: {
        headers: ['a …', 'the …', 'English'],
        rows: [
          ['en kanelbulle', 'kanelbullen', 'a cinnamon bun'],
          ['en kaka', 'kakan', 'a cookie / a simple cake'],
          ['en tårta', 'tårtan', 'a layer cake (with cream)'],
          ['en smörgås', 'smörgåsen', 'an open sandwich'],
          ['socker', 'sockret', 'sugar'],
          ['choklad', 'chokladen', 'chocolate'],
        ],
        svColumns: [0, 1],
      },
      tip: 'More than one: [[kanelbullar]], [[kakor]], [[tårtor]], [[smörgåsar]]. A birthday cake is normally en tårta, not en kaka.',
    },
    {
      title: 'Hot and cold',
      text: '[[varm]] means warm or hot, and [[kall]] means cold. You will see them with a **-t** or an **-a** at the end sometimes, depending on the noun. Don’t worry about that yet: you will learn the pattern in Unit 9. For now, just recognise them.',
      examples: [
        { sv: 'Kaffet är varmt.', en: 'The coffee is hot.' },
        { sv: 'Mjölken är kall.', en: 'The milk is cold.' },
        { sv: 'en varm choklad', en: 'a hot chocolate' },
        { sv: 'ett glas kallt vatten', en: 'a glass of cold water' },
      ],
    },
  ],
  culture: {
    title: 'Fika is about the pause',
    text: 'Swedes drink a lot of coffee, among the most in the world. But **fika** is not really about the coffee. It is about stopping for a moment and spending time with people. You can fika with tea, juice or just a glass of water, as long as you sit down together.\n\nAt many workplaces there is a fixed [[fikarast]] or [[fikapaus]] (fika break), often in the middle of the morning and again in the afternoon. Everyone joins in, the boss too, and it is where a lot of the real talking happens. Saying no every time can seem a bit unfriendly.\n\n[[Ska vi fika?]] is also a relaxed way to suggest meeting someone new, or even a first date: no pressure, just a coffee.\n\nAnd on **4 October** it is [[kanelbullens dag]], Cinnamon Bun Day. Bakeries and supermarkets sell huge numbers of buns, and many offices make sure there are kanelbullar on the table.',
    examples: [
      { sv: 'Nu är det fika!', en: 'It’s fika time!' },
      { sv: 'Ska vi fika på fredag?', en: 'Shall we have a fika on Friday?' },
      { sv: 'Grattis på kanelbullens dag!', en: 'Happy Cinnamon Bun Day!' },
    ],
    tip: 'Don’t drink coffee? No problem. Join the fika anyway with tea or water. The company is the point.',
  },
  vocab: [
    {
      id: 'fika',
      sv: 'fika',
      en: 'to have a coffee break / fika',
      pos: 'verb',
      pron: 'FEE-ka',
      note: 'Also a noun: en fika (a coffee break). Ska vi fika? = Shall we have a fika?',
      forms: { present: 'fikar', past: 'fikade', supine: 'fikat', imperative: 'fika' },
      enAlt: ['to have a coffee break', 'to have fika', 'to fika', 'coffee break', 'fika'],
    },
    {
      id: 'kanelbulle',
      sv: 'kanelbulle',
      en: 'cinnamon bun',
      pos: 'noun',
      gender: 'en',
      pron: 'ka-NEHL-bull-eh',
      forms: { definite: 'kanelbullen', plural: 'kanelbullar', pluralDefinite: 'kanelbullarna' },
      enAlt: ['cinnamon roll', 'cinnamon bun'],
    },
    {
      id: 'kaka',
      sv: 'kaka',
      en: 'cookie / cake',
      pos: 'noun',
      gender: 'en',
      note: 'Cookies, biscuits and simple cakes. A cream cake is en tårta.',
      forms: { definite: 'kakan', plural: 'kakor', pluralDefinite: 'kakorna' },
      enAlt: ['cookie', 'biscuit', 'cake'],
    },
    {
      id: 'tarta',
      sv: 'tårta',
      en: 'cake (layer cake)',
      pos: 'noun',
      gender: 'en',
      pron: 'TOHR-ta',
      note: 'A cake with layers and cream, e.g. for a birthday.',
      forms: { definite: 'tårtan', plural: 'tårtor', pluralDefinite: 'tårtorna' },
      enAlt: ['cake', 'layer cake', 'gateau'],
    },
    {
      id: 'smorgas',
      sv: 'smörgås',
      en: 'sandwich',
      pos: 'noun',
      gender: 'en',
      pron: 'SMUR-gohs',
      note: 'Usually one slice of bread with toppings (an open sandwich). Casual word: macka.',
      forms: { definite: 'smörgåsen', plural: 'smörgåsar', pluralDefinite: 'smörgåsarna' },
      enAlt: ['open sandwich'],
    },
    {
      id: 'socker',
      sv: 'socker',
      en: 'sugar',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'sockret' },
    },
    {
      id: 'choklad',
      sv: 'choklad',
      en: 'chocolate',
      pos: 'noun',
      gender: 'en',
      pron: 'sho-KLAHD',
      note: 'en varm choklad = a hot chocolate.',
      forms: { definite: 'chokladen' },
    },
    {
      id: 'varm',
      sv: 'varm',
      en: 'warm / hot',
      pos: 'adjective',
      forms: { neuter: 'varmt', plural: 'varma' },
      enAlt: ['warm', 'hot'],
    },
    {
      id: 'kall',
      sv: 'kall',
      en: 'cold',
      pos: 'adjective',
      forms: { neuter: 'kallt', plural: 'kalla' },
    },
  ],
  dialogue: {
    title: 'Fika at work',
    setting: 'It’s three o’clock at the office. Lisa finds her colleague Ahmed.',
    lines: [
      {
        speaker: 'Lisa',
        sv: 'Klockan är tre. Ska vi fika?',
        en: 'It’s three o’clock. Shall we have a fika?',
      },
      {
        speaker: 'Ahmed',
        sv: 'Ja, gärna! Vad har vi idag?',
        en: 'Yes, I’d love to! What have we got today?',
      },
      {
        speaker: 'Lisa',
        sv: 'Idag har vi kanelbullar och kakor.',
        en: 'Today we have cinnamon buns and cookies.',
      },
      { speaker: 'Ahmed', sv: 'Mmm, vad gott!', en: 'Mmm, yummy!' },
      {
        speaker: 'Lisa',
        sv: 'Vill du ha socker i kaffet?',
        en: 'Do you want sugar in your coffee?',
      },
      {
        speaker: 'Ahmed',
        sv: 'Nej tack. Lite mjölk, tack.',
        en: 'No thanks. A little milk, please.',
      },
      { speaker: 'Lisa', sv: 'Varsågod! Kaffet är varmt.', en: 'Here you go! The coffee is hot.' },
      { speaker: 'Ahmed', sv: 'Tack! Jag älskar fika!', en: 'Thanks! I love fika!' },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: 'Ska vi fika?',
      promptLang: 'sv',
      question: 'Your colleague says this. What is she suggesting?',
      choices: [
        'Taking a break together, with coffee and something to eat',
        'Going out for dinner tonight',
        'Buying a new coffee machine',
      ],
      answer: 'Taking a break together, with coffee and something to eat',
      explanation:
        'Fika is a break with coffee (or tea) and usually something sweet. The pause and the company matter more than the coffee.',
      vocab: ['fika'],
    },
    {
      type: 'mcq',
      prompt: 'kanelbullens dag',
      promptLang: 'sv',
      question: 'When is Cinnamon Bun Day?',
      choices: ['4 October', '24 December', '6 June'],
      answer: '4 October',
      explanation:
        'Kanelbullens dag is on 4 October. (24 December is Christmas Eve and 6 June is Sweden’s National Day.)',
      vocab: ['kanelbulle'],
    },
    {
      type: 'gap',
      text: 'Ska vi ___?',
      en: 'Shall we have a fika?',
      choices: ['fika', 'fikar', 'en fika'],
      answer: 'fika',
      explanation:
        'After ska, use the basic form of the verb (the infinitive): ska vi fika. With the noun you need another verb: Ska vi ta en fika?',
      vocab: ['fika'],
    },
    {
      type: 'gap',
      text: 'Vi ___ klockan tre varje dag.',
      en: 'We have fika at three o’clock every day.',
      choices: ['fikar', 'fika', 'fikat'],
      answer: 'fikar',
      explanation: 'fika is an -ar verb, so the present tense is fikar, like pratar.',
      vocab: ['fika', 'klocka', 'tre'],
    },
    {
      type: 'dialogueReply',
      lines: [
        {
          speaker: 'Lisa',
          sv: 'Klockan är tre. Ska vi fika?',
          en: 'It’s three o’clock. Shall we have a fika?',
        },
      ],
      question: 'You’d love to. What do you say?',
      choices: ['Ja, gärna!', 'Varsågod!', 'Hej då!'],
      answer: 'Ja, gärna!',
      explanation:
        '"Ja, gärna!" means "Yes, I’d love to!". Varsågod is what you say when you hand something over.',
      vocab: ['garna', 'fika'],
    },
    {
      type: 'dialogueReply',
      lines: [
        {
          speaker: 'Lisa',
          sv: 'Vill du ha socker i kaffet?',
          en: 'Do you want sugar in your coffee?',
        },
      ],
      question: 'You don’t take sugar. What do you say?',
      choices: ['Nej tack, inget socker.', 'Ja tack, mycket socker.', 'Varsågod, socker.'],
      answer: 'Nej tack, inget socker.',
      explanation:
        '"Nej tack" is a polite "no thanks". socker is an ett-word, so "no sugar" is inget socker.',
      vocab: ['socker', 'nej', 'tack'],
    },
    {
      type: 'listen',
      audio: 'Kaffet är varmt och mjölken är kall.',
      choices: [
        'The coffee is hot and the milk is cold.',
        'The coffee is cold and the milk is hot.',
        'The tea is hot and the water is cold.',
      ],
      answer: 'The coffee is hot and the milk is cold.',
      explanation: 'varm(t) means hot or warm, kall means cold.',
      vocab: ['varm', 'kall', 'kaffe'],
    },
    {
      type: 'build',
      prompt: 'Today we have cake and coffee.',
      answer: 'Idag har vi tårta och kaffe.',
      accept: [
        'Idag har vi kaffe och tårta.',
        'Vi har tårta och kaffe idag.',
        'Vi har kaffe och tårta idag.',
      ],
      distractors: ['jag', 'tårtan'],
      explanation:
        'When a sentence starts with idag, the verb comes second and the subject after it: Idag har vi …',
      vocab: ['tarta', 'kaffe', 'idag'],
    },
    {
      type: 'dictation',
      audio: 'Ska vi fika klockan tre?',
      en: 'Shall we have a fika at three?',
      vocab: ['fika', 'klocka', 'tre'],
    },
    {
      type: 'speak',
      text: 'Ska vi fika? Jag vill ha en kanelbulle.',
      en: 'Shall we have a fika? I want a cinnamon bun.',
      vocab: ['fika', 'kanelbulle'],
    },
  ],
})
