import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u08-l05',
  learn: [
    {
      title: 'Hur ser hon ut?',
      text: 'To ask what someone looks like, say [[Hur ser hon ut?]] The little word **ut** goes at the very end.\n\nAnswer with **är** + a describing word, or **har** + a feature:',
      examples: [
        { sv: 'Hur ser din bror ut?', en: 'What does your brother look like?' },
        { sv: 'Han är lång och har skägg.', en: 'He’s tall and has a beard.' },
        { sv: 'Hon är kort och har glasögon.', en: 'She’s short and wears glasses.' },
        { sv: 'Du ser trött ut.', en: 'You look tired.' },
      ],
      tip: 'Swedes "have" glasses: [[Hon har glasögon.]] And se ut also works like English "look": [[Du ser glad ut!]] (You look happy!)',
    },
    {
      title: 'Hair and eyes',
      text: '[[hår]] (hair) is an **ett**-word, so a describing word in front of it gets a **-t**: [[långt hår]]. kort already ends in t, so it stays [[kort hår]]. You will learn the full rule in Unit 9. For now, learn these as phrases.\n\n[[öga]] (eye) has an irregular plural: [[ett öga]], [[två ögon]].',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['Hon har långt hår.', 'She has long hair.'],
          ['Han har kort hår.', 'He has short hair.'],
          ['Han har skägg.', 'He has a beard.'],
          ['Hon har glasögon.', 'She wears glasses.'],
          ['Han har snälla ögon.', 'He has kind eyes.'],
        ],
        svColumns: [0],
      },
      tip: 'glasögon is literally "glass eyes", and it is always plural, like English "glasses": [[ett par glasögon]] (a pair of glasses).',
    },
    {
      title: 'What are they like?',
      text: 'For personality, ask [[Hur är han?]] (What is he like?) and answer with är.',
      examples: [
        { sv: 'Hur är han?', en: 'What’s he like?' },
        { sv: 'Han är snäll och rolig.', en: 'He’s kind and funny.' },
        { sv: 'Min syster är lite blyg.', en: 'My sister is a bit shy.' },
        { sv: 'Hon är ung och smart.', en: 'She’s young and smart.' },
        {
          sv: 'Mina föräldrar är snälla.',
          en: 'My parents are kind.',
          note: 'With plurals, describing words add -a. More in Unit 9.',
        },
      ],
      tip: 'rolig means "fun" as well as "funny": [[Det är roligt!]] (It’s fun!) kul from Unit 1 is its casual twin.',
    },
  ],
  vocab: [
    {
      id: 'lang-tall',
      sv: 'lång',
      en: 'tall / long',
      pos: 'adjective',
      forms: { neuter: 'långt', plural: 'långa' },
      enAlt: ['tall', 'long'],
    },
    {
      id: 'kort-short',
      sv: 'kort',
      en: 'short',
      pos: 'adjective',
      note: 'Not to be confused with ett kort (a card).',
      forms: { neuter: 'kort', plural: 'korta' },
    },
    {
      id: 'ung',
      sv: 'ung',
      en: 'young',
      pos: 'adjective',
      forms: { neuter: 'ungt', plural: 'unga' },
    },
    {
      id: 'snall',
      sv: 'snäll',
      en: 'kind / nice',
      pos: 'adjective',
      note: 'snälla (please) from Unit 2 is a form of the same word.',
      forms: { neuter: 'snällt', plural: 'snälla' },
      enAlt: ['kind', 'nice'],
    },
    {
      id: 'rolig',
      sv: 'rolig',
      en: 'funny / fun',
      pos: 'adjective',
      forms: { neuter: 'roligt', plural: 'roliga' },
      enAlt: ['funny', 'fun'],
    },
    {
      id: 'blyg',
      sv: 'blyg',
      en: 'shy',
      pos: 'adjective',
      forms: { neuter: 'blygt', plural: 'blyga' },
    },
    {
      id: 'smart',
      sv: 'smart',
      en: 'smart / clever',
      pos: 'adjective',
      forms: { neuter: 'smart', plural: 'smarta' },
      enAlt: ['smart', 'clever'],
    },
    {
      id: 'har-hair',
      sv: 'hår',
      en: 'hair',
      pos: 'noun',
      gender: 'ett',
      note: 'Usually singular, like in English: Hon har långt hår.',
      forms: { definite: 'håret', plural: 'hår', pluralDefinite: 'håren' },
    },
    {
      id: 'oga',
      sv: 'öga',
      en: 'eye',
      pos: 'noun',
      gender: 'ett',
      note: 'Irregular plural: två ögon.',
      forms: { definite: 'ögat', plural: 'ögon', pluralDefinite: 'ögonen' },
    },
    {
      id: 'glasogon',
      sv: 'par glasögon',
      en: 'glasses',
      pos: 'noun',
      gender: 'ett',
      note: 'Always plural: glasögon (glasses), glasögonen (the glasses). Count them in pairs: ett par glasögon, två par glasögon. Never "ett glasögon".',
      forms: { definite: 'glasögonen', plural: 'glasögon' },
      alt: ['glasögon'],
      enAlt: ['a pair of glasses', 'pair of glasses', 'spectacles'],
    },
    {
      id: 'skagg',
      sv: 'skägg',
      en: 'beard',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'skägget', plural: 'skägg', pluralDefinite: 'skäggen' },
    },
    {
      id: 'se-ut',
      sv: 'se ut',
      en: 'to look (like)',
      pos: 'verb',
      note: '"Hur ser hon ut?" = What does she look like? "Du ser trött ut" = You look tired.',
      forms: { present: 'ser ut', past: 'såg ut', supine: 'sett ut' },
      enAlt: ['to look', 'to look like'],
    },
  ],
  dialogue: {
    title: 'At the station',
    setting: 'Ella is picking up Sofia’s brother from the train, but she has never met him.',
    lines: [
      {
        speaker: 'Ella',
        sv: 'Jag ska hämta din bror på stationen. Hur ser han ut?',
        en: 'I’m picking up your brother at the station. What does he look like?',
      },
      {
        speaker: 'Sofia',
        sv: 'Han är lång och har kort hår.',
        en: 'He’s tall and has short hair.',
      },
      { speaker: 'Ella', sv: 'Har han skägg?', en: 'Does he have a beard?' },
      { speaker: 'Sofia', sv: 'Ja, och glasögon.', en: 'Yes, and glasses.' },
      { speaker: 'Ella', sv: 'Okej. Och hur är han?', en: 'Okay. And what’s he like?' },
      {
        speaker: 'Sofia',
        sv: 'Han är jättesnäll och rolig, men lite blyg.',
        en: 'He’s really kind and funny, but a bit shy.',
      },
      { speaker: 'Ella', sv: 'Bra! Hur gammal är han?', en: 'Good! How old is he?' },
      { speaker: 'Sofia', sv: 'Han är ung, bara nitton.', en: 'He’s young, only nineteen.' },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: 'Hur ser hon ut?',
      promptLang: 'sv',
      question: 'What does this mean?',
      choices: ['What does she look like?', 'What is she like?', 'How is she doing?'],
      answer: 'What does she look like?',
      explanation:
        'se ut = look (like). "What is she like?" would be Hur är hon? and "How is she doing?" Hur mår hon?',
      vocab: ['se-ut'],
    },
    {
      type: 'dialogueReply',
      lines: [
        { speaker: 'Sofia', sv: 'Hur ser din pappa ut?', en: 'What does your dad look like?' },
      ],
      question: 'Describe him.',
      choices: ['Han är lång och har skägg.', 'Han mår bra, tack.', 'Han ser ut lång.'],
      answer: 'Han är lång och har skägg.',
      explanation:
        'Describe looks with är and har. Han mår bra answers "how is he?", and ut never comes before the describing word.',
      vocab: ['se-ut', 'lang-tall', 'skagg'],
    },
    {
      type: 'gap',
      text: 'Hur ser din syster ___?',
      en: 'What does your sister look like?',
      choices: ['ut', 'upp', 'på'],
      answer: 'ut',
      explanation: 'se ut means "look like", and ut goes at the end of the question.',
      vocab: ['se-ut', 'syster'],
    },
    {
      type: 'gap',
      text: 'Hon har snälla ___.',
      en: 'She has kind eyes.',
      choices: ['ögon', 'ögor', 'ögar'],
      answer: 'ögon',
      explanation: 'öga has an irregular plural: ett öga, två ögon.',
      vocab: ['oga', 'snall'],
    },
    {
      type: 'build',
      prompt: 'He is tall and has a beard.',
      answer: 'Han är lång och har skägg.',
      distractors: ['kort', 'hon'],
      explanation: 'lång means tall (and long). Swedes just say har skägg, without "a".',
      vocab: ['lang-tall', 'skagg'],
    },
    {
      type: 'build',
      prompt: 'What does your brother look like?',
      answer: 'Hur ser din bror ut?',
      distractors: ['är', 'vad'],
      explanation: 'Hur (how) + ser + the person + ut at the end.',
      vocab: ['se-ut', 'bror', 'din'],
    },
    {
      type: 'listen',
      audio: 'Hon är kort och har långt hår.',
      choices: [
        'She is short and has long hair.',
        'She is tall and has short hair.',
        'She is short and has short hair.',
      ],
      answer: 'She is short and has long hair.',
      explanation: 'kort = short, långt hår = long hair.',
      vocab: ['kort-short', 'lang-tall', 'har-hair'],
    },
    {
      type: 'type',
      prompt: 'She is young and smart.',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'Hon är ung och smart.',
      explanation: 'ung = young, smart = smart.',
      vocab: ['ung', 'smart'],
    },
    {
      type: 'dictation',
      audio: 'Min farfar har glasögon och skägg.',
      en: 'My grandpa has glasses and a beard.',
      vocab: ['glasogon', 'skagg', 'farfar'],
    },
    {
      type: 'speak',
      text: 'Hon är snäll, rolig och lite blyg.',
      en: 'She’s kind, funny and a bit shy.',
      vocab: ['snall', 'rolig', 'blyg'],
    },
  ],
})
