import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u08-l02',
  learn: [
    {
      title: 'Partners',
      text: '[[man]] means both "man" and "husband", so [[min man]] is "my husband". The plural is irregular: [[en man]] → [[två män]].\n\n[[fru]] means "wife". For "a woman" in general, the word is [[kvinna]].\n\nBoyfriend and girlfriend are built from [[vän]] (friend): [[pojkvän]] and [[flickvän]].',
      table: {
        headers: ['Swedish', 'English'],
        rows: [
          ['en man', 'a man / a husband'],
          ['en kvinna', 'a woman'],
          ['en fru', 'a wife'],
          ['en pojkvän', 'a boyfriend'],
          ['en flickvän', 'a girlfriend'],
          ['en vän', 'a friend'],
        ],
        svColumns: [0],
      },
      tip: 'In everyday speech, many people just say [[min kille]] (my guy) or [[min tjej]] (my girl) about a boyfriend or girlfriend.',
    },
    {
      title: 'Sambo: very Swedish',
      text: 'A [[sambo]] is a partner you live with without being married. The word comes from **sam**manboende, "living together".\n\nIn Sweden this is completely normal: many couples live together for years, have children and never marry. Sambos even have their own law. So when a Swede says "min sambo", think "my partner".',
      examples: [
        { sv: 'Är du gift?', en: 'Are you married?' },
        { sv: 'Nej, men jag har en sambo.', en: 'No, but I live with my partner.' },
        { sv: 'Vi är sambor.', en: 'We live together.' },
        { sv: 'Han är gift.', en: 'He’s married.' },
        { sv: 'Mina föräldrar är skilda.', en: 'My parents are divorced.' },
      ],
      tip: 'Learn gift and skild as phrases for now: one person [[är gift]], two people [[är gifta]]. You will see why in Unit 9.',
    },
    {
      title: 'Släkt: the relatives',
      text: '[[släkten]] means your relatives, the whole extended family: aunts, uncles, cousins and all. [[Vi är släkt]] means "we are related".\n\n[[kusin]] (cousin) is the same word for a man and a woman. And [[barnbarn]] (grandchild) is literally "child-child": barn + barn.',
      examples: [
        { sv: 'Min kusin bor i Malmö.', en: 'My cousin lives in Malmö.' },
        { sv: 'Farmor har sju barnbarn.', en: 'Grandma has seven grandchildren.' },
        { sv: 'Är ni släkt?', en: 'Are you related?' },
      ],
      tip: 'barnbarn is an ett-word with the same form in the plural: ett barnbarn, två barnbarn.',
    },
  ],
  vocab: [
    {
      id: 'man',
      sv: 'man',
      en: 'man / husband',
      pos: 'noun',
      gender: 'en',
      note: 'Irregular plural: två män. "Min man" = my husband.',
      forms: { definite: 'mannen', plural: 'män', pluralDefinite: 'männen' },
      enAlt: ['man', 'husband'],
    },
    {
      id: 'fru',
      sv: 'fru',
      en: 'wife',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'frun', plural: 'fruar', pluralDefinite: 'fruarna' },
    },
    {
      id: 'sambo',
      sv: 'sambo',
      en: 'live-in partner',
      pos: 'noun',
      gender: 'en',
      note: 'A partner you live with without being married. Very common in Sweden.',
      forms: { definite: 'sambon', plural: 'sambor', pluralDefinite: 'samborna' },
      enAlt: ['partner', 'cohabiting partner'],
    },
    {
      id: 'gift',
      sv: 'gift',
      en: 'married',
      pos: 'adjective',
      note: 'Han är gift. De är gifta.',
      forms: { neuter: 'gift', plural: 'gifta' },
    },
    {
      id: 'skild',
      sv: 'skild',
      en: 'divorced',
      pos: 'adjective',
      note: 'Hon är skild. De är skilda. You will also hear frånskild.',
      forms: { neuter: 'skilt', plural: 'skilda' },
      alt: ['frånskild'],
    },
    {
      id: 'pojkvan',
      sv: 'pojkvän',
      en: 'boyfriend',
      pos: 'noun',
      gender: 'en',
      note: 'pojke (boy) + vän (friend).',
      forms: { definite: 'pojkvännen', plural: 'pojkvänner', pluralDefinite: 'pojkvännerna' },
    },
    {
      id: 'flickvan',
      sv: 'flickvän',
      en: 'girlfriend',
      pos: 'noun',
      gender: 'en',
      note: 'flicka (girl) + vän (friend).',
      forms: { definite: 'flickvännen', plural: 'flickvänner', pluralDefinite: 'flickvännerna' },
    },
    {
      id: 'kusin',
      sv: 'kusin',
      en: 'cousin',
      pos: 'noun',
      gender: 'en',
      pron: 'koo-SEEN',
      forms: { definite: 'kusinen', plural: 'kusiner', pluralDefinite: 'kusinerna' },
    },
    {
      id: 'slakt',
      sv: 'släkt',
      en: 'relatives / extended family',
      pos: 'noun',
      gender: 'en',
      note: '"Släkten" = the relatives. "Vi är släkt" = we are related.',
      forms: { definite: 'släkten', plural: 'släkter', pluralDefinite: 'släkterna' },
      enAlt: ['relatives', 'family', 'extended family', 'relations'],
    },
    {
      id: 'barnbarn',
      sv: 'barnbarn',
      en: 'grandchild',
      pos: 'noun',
      gender: 'ett',
      note: 'barn + barn: a child’s child.',
      forms: { definite: 'barnbarnet', plural: 'barnbarn', pluralDefinite: 'barnbarnen' },
      enAlt: ['grandchildren', 'grandson', 'granddaughter'],
    },
    {
      id: 'kvinna',
      sv: 'kvinna',
      en: 'woman',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'kvinnan', plural: 'kvinnor', pluralDefinite: 'kvinnorna' },
    },
    {
      id: 'van-u8',
      sv: 'vän',
      en: 'friend',
      pos: 'noun',
      gender: 'en',
      note: 'Hidden in pojkvän and flickvän. In everyday speech, kompis is just as common.',
      forms: { definite: 'vännen', plural: 'vänner', pluralDefinite: 'vännerna' },
    },
  ],
  dialogue: {
    title: 'Who’s who?',
    setting: 'Ahmed and Sara are at a birthday party.',
    lines: [
      { speaker: 'Ahmed', sv: 'Vem är mannen där borta?', en: 'Who’s the man over there?' },
      { speaker: 'Sara', sv: 'Det är Johan, min kusin.', en: 'That’s Johan, my cousin.' },
      { speaker: 'Ahmed', sv: 'Och kvinnan bredvid honom?', en: 'And the woman next to him?' },
      { speaker: 'Sara', sv: 'Det är hans fru, Maria.', en: 'That’s his wife, Maria.' },
      { speaker: 'Ahmed', sv: 'Är du också gift?', en: 'Are you married too?' },
      {
        speaker: 'Sara',
        sv: 'Nej, men jag har en sambo. Vi bor ihop i Uppsala.',
        en: 'No, but I have a partner. We live together in Uppsala.',
      },
      { speaker: 'Ahmed', sv: 'Är han här?', en: 'Is he here?' },
      { speaker: 'Sara', sv: 'Nej, han jobbar idag.', en: 'No, he’s working today.' },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: 'sambo',
      promptLang: 'sv',
      question: 'What is a sambo?',
      choices: ['a partner you live with', 'a cousin', 'a husband', 'a neighbour'],
      answer: 'a partner you live with',
      explanation:
        'A sambo is a partner you live with without being married. A husband is a man: min man = my husband.',
      vocab: ['sambo'],
    },
    {
      type: 'gap',
      text: 'Min ___ heter Anna. Vi är gifta.',
      en: 'My wife is called Anna. We’re married.',
      choices: ['fru', 'kvinna', 'flickvän'],
      answer: 'fru',
      explanation:
        'fru means "wife". kvinna is any woman, and a flickvän is a girlfriend, so not married.',
      vocab: ['fru', 'gift'],
    },
    {
      type: 'gap',
      text: 'Mormor har fyra ___.',
      en: 'Grandma has four grandchildren.',
      choices: ['barnbarn', 'barnbarnen', 'barnbarner'],
      answer: 'barnbarn',
      explanation:
        'barnbarn is an ett-word, and like barn it looks the same in the plural: ett barnbarn, fyra barnbarn.',
      vocab: ['barnbarn', 'mormor'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Ahmed', sv: 'Är du gift?', en: 'Are you married?' }],
      question: 'You aren’t married, but you live with your partner. What do you say?',
      choices: ['Nej, men jag har en sambo.', 'Ja, jag har en sambo.', 'Nej, jag har en kusin.'],
      answer: 'Nej, men jag har en sambo.',
      explanation: 'You are not married, so start with nej. A partner you live with is a sambo.',
      vocab: ['gift', 'sambo'],
    },
    {
      type: 'build',
      prompt: 'My parents are divorced.',
      answer: 'Mina föräldrar är skilda.',
      distractors: ['min', 'gifta'],
      explanation: 'föräldrar is plural, so "my" is mina.',
      vocab: ['skild', 'foralder', 'min'],
    },
    {
      type: 'build',
      prompt: 'Is the woman his wife?',
      answer: 'Är kvinnan hans fru?',
      distractors: ['frun', 'han'],
      explanation:
        'A yes/no question starts with the verb. After hans (his) there is no "the" ending, so it is hans fru, not hans frun.',
      vocab: ['kvinna', 'fru', 'hans'],
    },
    {
      type: 'listen',
      audio: 'Vi är inte gifta, vi är sambor.',
      choices: [
        'We aren’t married, we live together.',
        'We are married and live together.',
        'We aren’t married, we are cousins.',
      ],
      answer: 'We aren’t married, we live together.',
      explanation: 'inte gifta = not married. Sambor are partners who live together.',
      vocab: ['gift', 'sambo'],
    },
    {
      type: 'type',
      prompt: 'my husband',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'min man',
      accept: ['min make'],
      explanation:
        'man means both "man" and "husband". min man is the everyday way to say "my husband".',
      vocab: ['man', 'min'],
    },
    {
      type: 'dictation',
      audio: 'Min kusin har en flickvän.',
      en: 'My cousin has a girlfriend.',
      vocab: ['kusin', 'flickvan'],
    },
    {
      type: 'speak',
      text: 'Nej, jag är inte gift, men jag har en pojkvän.',
      en: 'No, I’m not married, but I have a boyfriend.',
      vocab: ['gift', 'pojkvan'],
    },
  ],
})
