import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u08-l01',
  learn: [
    {
      title: 'Family words',
      text: 'Most family words are **en**-words: [[en mamma]], [[en pappa]], [[en bror]], [[en syster]]. One exception you already know: [[ett barn]] (a child).\n\nWatch the plurals. Some of them change their vowel, just like English man → men: [[en bror]] → [[två bröder]], [[en son]] → [[två söner]], [[en dotter]] → [[två döttrar]].',
      table: {
        headers: ['a …', 'the …', 'two …', 'English'],
        rows: [
          ['en mamma', 'mamman', 'mammor', 'mum'],
          ['en pappa', 'pappan', 'pappor', 'dad'],
          ['en förälder', 'föräldern', 'föräldrar', 'parent'],
          ['en bror', 'brodern', 'bröder', 'brother'],
          ['en syster', 'systern', 'systrar', 'sister'],
          ['en son', 'sonen', 'söner', 'son'],
          ['en dotter', 'dottern', 'döttrar', 'daughter'],
        ],
        svColumns: [0, 1, 2],
      },
      tip: 'Swedes call their parents mamma and pappa at any age. The words mor (mother) and far (father) exist too, but they sound more formal. You need them for the next card, though!',
    },
    {
      title: 'Mormor or farmor?',
      text: 'English has one word for "grandma". Swedish tells you **which side** of the family she is on. Just put mor (mother) and far (father) together:\n\n[[mormor]] = mother’s mother\n[[farmor]] = father’s mother\n\nThe first part is your parent, the second part is their parent.',
      table: {
        headers: ['Swedish', 'Literally', 'English'],
        rows: [
          ['mormor', 'mother’s mother', 'grandma (mum’s side)'],
          ['morfar', 'mother’s father', 'grandpa (mum’s side)'],
          ['farmor', 'father’s mother', 'grandma (dad’s side)'],
          ['farfar', 'father’s father', 'grandpa (dad’s side)'],
        ],
        svColumns: [0],
      },
      tip: 'Within the family, these words are often used like names, without "the" or "my": [[Mormor kommer på söndag.]] (Grandma is coming on Sunday.) Talking to others, you also hear [[min mormor]].',
    },
    {
      title: 'Talking about your family',
      text: 'Use min, mitt and mina from Unit 4: [[min bror]], [[mina föräldrar]]. Remember: no "the" ending after "my".\n\nSwedish also has a handy word for brothers and sisters together: [[syskon]] (siblings). It is an ett-word, and the plural looks the same: ett syskon, två syskon. Swedes use it all the time, much more than English "siblings".',
      examples: [
        { sv: 'Jag har en bror och en syster.', en: 'I have a brother and a sister.' },
        { sv: 'Hur många syskon har du?', en: 'How many brothers and sisters do you have?' },
        { sv: 'Jag har två syskon.', en: 'I have two siblings.' },
        { sv: 'Mina föräldrar bor i Malmö.', en: 'My parents live in Malmö.' },
        { sv: 'Min dotter heter Ella.', en: 'My daughter is called Ella.' },
      ],
    },
  ],
  culture: {
    title: 'Latte dads',
    text: 'Swedish parents share 480 days of paid parental leave for each child, and 90 of those days are reserved for each parent. So on a weekday you will see plenty of dads pushing prams with a coffee in hand. Swedes jokingly call them [[lattepappor]]: latte dads.',
  },
  vocab: [
    {
      id: 'familj',
      sv: 'familj',
      en: 'family',
      pos: 'noun',
      gender: 'en',
      pron: 'fa-MILJ (j like y)',
      forms: { definite: 'familjen', plural: 'familjer', pluralDefinite: 'familjerna' },
    },
    {
      id: 'mamma',
      sv: 'mamma',
      en: 'mum / mom',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'mamman', plural: 'mammor', pluralDefinite: 'mammorna' },
      enAlt: ['mum', 'mom', 'mother', 'mummy'],
    },
    {
      id: 'pappa',
      sv: 'pappa',
      en: 'dad',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'pappan', plural: 'pappor', pluralDefinite: 'papporna' },
      enAlt: ['father', 'daddy'],
    },
    {
      id: 'foralder',
      sv: 'förälder',
      en: 'parent',
      pos: 'noun',
      gender: 'en',
      note: 'Mostly used in the plural: mina föräldrar (my parents).',
      forms: { definite: 'föräldern', plural: 'föräldrar', pluralDefinite: 'föräldrarna' },
    },
    {
      id: 'bror',
      sv: 'bror',
      en: 'brother',
      pos: 'noun',
      gender: 'en',
      note: 'Plural with a vowel change: två bröder. "The brother" is brodern (in speech often brorn), but you will mostly say min bror.',
      forms: { definite: 'brodern', plural: 'bröder', pluralDefinite: 'bröderna' },
    },
    {
      id: 'syster',
      sv: 'syster',
      en: 'sister',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'systern', plural: 'systrar', pluralDefinite: 'systrarna' },
    },
    {
      id: 'son',
      sv: 'son',
      en: 'son',
      pos: 'noun',
      gender: 'en',
      pron: 'sohn (o like å)',
      forms: { definite: 'sonen', plural: 'söner', pluralDefinite: 'sönerna' },
    },
    {
      id: 'dotter',
      sv: 'dotter',
      en: 'daughter',
      pos: 'noun',
      gender: 'en',
      note: 'Plural with a vowel change: två döttrar.',
      forms: { definite: 'dottern', plural: 'döttrar', pluralDefinite: 'döttrarna' },
    },
    {
      id: 'mormor',
      sv: 'mormor',
      en: 'grandma (mum’s mum)',
      pos: 'noun',
      gender: 'en',
      note: 'mor (mother) + mor: your mother’s mother. Used like a name: "Mormor kommer."',
      enAlt: ['grandma', 'grandmother', 'maternal grandmother', 'mother’s mother'],
    },
    {
      id: 'farmor',
      sv: 'farmor',
      en: 'grandma (dad’s mum)',
      pos: 'noun',
      gender: 'en',
      note: 'far (father) + mor: your father’s mother.',
      enAlt: ['grandma', 'grandmother', 'paternal grandmother', 'father’s mother'],
    },
    {
      id: 'morfar',
      sv: 'morfar',
      en: 'grandpa (mum’s dad)',
      pos: 'noun',
      gender: 'en',
      note: 'mor (mother) + far: your mother’s father.',
      enAlt: ['grandpa', 'grandfather', 'maternal grandfather', 'mother’s father'],
    },
    {
      id: 'farfar',
      sv: 'farfar',
      en: 'grandpa (dad’s dad)',
      pos: 'noun',
      gender: 'en',
      note: 'far (father) + far: your father’s father.',
      enAlt: ['grandpa', 'grandfather', 'paternal grandfather', 'father’s father'],
    },
  ],
  dialogue: {
    title: 'Family photos',
    setting: 'Lisa is showing Omar some photos on her phone.',
    lines: [
      { speaker: 'Omar', sv: 'Är det din familj?', en: 'Is that your family?' },
      {
        speaker: 'Lisa',
        sv: 'Ja! Det är mina föräldrar, och det är min bror Erik.',
        en: 'Yes! Those are my parents, and that’s my brother Erik.',
      },
      {
        speaker: 'Omar',
        sv: 'Har du fler syskon?',
        en: 'Do you have any other brothers or sisters?',
      },
      {
        speaker: 'Lisa',
        sv: 'Ja, en syster. Hon bor i Umeå.',
        en: 'Yes, a sister. She lives in Umeå.',
      },
      { speaker: 'Omar', sv: 'Och vem är det här?', en: 'And who’s this?' },
      {
        speaker: 'Lisa',
        sv: 'Det är mormor. Hon är åttio år!',
        en: 'That’s my grandma, my mum’s mum. She’s eighty!',
      },
      {
        speaker: 'Omar',
        sv: 'Vad kul! Min farfar är nittio.',
        en: 'How nice! My grandpa is ninety.',
      },
    ],
  },
  exercises: [
    {
      type: 'mcq',
      prompt: 'your mum’s father',
      promptLang: 'en',
      question: 'What do you call him in Swedish?',
      choices: ['morfar', 'farfar', 'mormor', 'farmor'],
      answer: 'morfar',
      explanation:
        'First your parent, then their parent: mor (your mother) + far (her father) = morfar.',
      vocab: ['morfar', 'farfar'],
    },
    {
      type: 'gap',
      text: 'Jag har två ___.',
      en: 'I have two brothers.',
      choices: ['bröder', 'brorar', 'brodrar'],
      answer: 'bröder',
      explanation: 'bror has an irregular plural with a vowel change: en bror, två bröder.',
      vocab: ['bror'],
    },
    {
      type: 'gap',
      text: 'Mina ___ bor i Stockholm.',
      en: 'My parents live in Stockholm.',
      choices: ['föräldrar', 'förälder', 'föräldern'],
      answer: 'föräldrar',
      explanation:
        'mina means "my" for plurals, so the noun must be plural too: föräldrar. After mina there is no "the" ending.',
      vocab: ['foralder', 'min'],
    },
    {
      type: 'build',
      prompt: 'I have a brother and a sister.',
      answer: 'Jag har en bror och en syster.',
      distractors: ['ett', 'bröder'],
      explanation: 'bror and syster are both en-words, so "a" is en each time.',
      vocab: ['bror', 'syster'],
    },
    {
      type: 'build',
      prompt: 'On Sunday my grandpa (my dad’s dad) is coming.',
      answer: 'På söndag kommer min farfar.',
      accept: ['Min farfar kommer på söndag.'],
      distractors: ['morfar', 'farmor'],
      explanation:
        'Your dad’s dad is far + far = farfar. The sentence starts with a time, so the verb kommer comes second and min farfar follows it (V2).',
      vocab: ['farfar', 'sondag'],
    },
    {
      type: 'listen',
      audio: 'Min mamma har tre systrar.',
      choices: [
        'My mum has three sisters.',
        'My mum has three brothers.',
        'My sister has three children.',
      ],
      answer: 'My mum has three sisters.',
      explanation: 'systrar is the plural of syster (sister). Brothers would be bröder.',
      vocab: ['mamma', 'syster'],
    },
    {
      type: 'dialogueReply',
      lines: [
        {
          speaker: 'Omar',
          sv: 'Hur många syskon har du?',
          en: 'How many brothers and sisters do you have?',
        },
      ],
      question: 'You have one brother and one sister. What do you say?',
      choices: ['Jag har två syskon.', 'Jag har två bröder.', 'Jag har två systrar.'],
      answer: 'Jag har två syskon.',
      explanation:
        'syskon covers brothers and sisters together. Two bröder would be two brothers, and two systrar two sisters.',
      vocab: ['bror', 'syster'],
    },
    {
      type: 'type',
      prompt: 'two daughters',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'två döttrar',
      reject: ['två dottrar', 'två döttrer', 'två dotter', 'två dottrer'],
      strict: true,
      hint: 'en dotter: the o changes in the plural',
      explanation: 'dotter has an irregular plural: the o becomes ö and the e drops, so döttrar.',
      vocab: ['dotter', 'tva'],
    },
    {
      type: 'dictation',
      audio: 'Min farmor och min farfar bor i Sverige.',
      en: 'My grandma and grandpa on my dad’s side live in Sweden.',
      vocab: ['farmor', 'farfar'],
    },
    {
      type: 'speak',
      text: 'Jag har en dotter och en son.',
      en: 'I have a daughter and a son.',
      vocab: ['dotter', 'son'],
    },
  ],
})
