import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u08-l04',
  learn: [
    {
      title: 'Verbs with a "self" word',
      text: 'Some Swedish verbs need a little word that points back to the person doing the action, like English "myself". [[Jag tvättar mig]] is literally "I wash myself".\n\nEnglish often drops it ("I wash"), but with these verbs Swedish always keeps it. The self word changes with the person:',
      table: {
        headers: ['Person', 'Self word', 'Example', 'English'],
        rows: [
          ['jag', 'mig', 'jag tvättar mig', 'I wash'],
          ['du', 'dig', 'du tvättar dig', 'you wash'],
          ['han / hon / hen', 'sig', 'hon tvättar sig', 'she washes'],
          ['vi', 'oss', 'vi tvättar oss', 'we wash'],
          ['ni', 'er', 'ni tvättar er', 'you (all) wash'],
          ['de', 'sig', 'de tvättar sig', 'they wash'],
        ],
        svColumns: [0, 1, 2],
      },
      tip: 'mig, dig and sig are pronounced "may", "day" and "say". And sig is used for han, hon, hen and de alike.',
    },
    {
      title: 'Your morning',
      text: '[[vakna]] means "wake up" (open your eyes), and [[gå upp]] means "get up" (out of bed).\n\nSwedes brush "the teeth", not "my teeth": [[Jag borstar tänderna.]] And at night you [[lägger dig]] (go to bed) and [[somnar]] (fall asleep).',
      examples: [
        { sv: 'Jag vaknar klockan sju.', en: 'I wake up at seven.' },
        { sv: 'Jag går upp och duschar.', en: 'I get up and have a shower.' },
        { sv: 'Jag klär på mig.', en: 'I get dressed.' },
        { sv: 'Jag skyndar mig till jobbet.', en: 'I hurry to work.' },
        { sv: 'Jag lägger mig och somnar.', en: 'I go to bed and fall asleep.' },
      ],
      tip: 'Tell someone to hurry or to sit down with dig: [[Skynda dig!]] (Hurry up!) [[Sätt dig!]] (Sit down!)',
    },
    {
      title: 'Time first, verb second',
      text: 'Routines often start with a time. Remember V2 from Unit 6: the verb stays in **second** place, and the subject moves after it. The self word comes right after the subject.',
      examples: [
        { sv: 'Jag lägger mig klockan elva.', en: 'I go to bed at eleven.' },
        { sv: 'Klockan elva lägger jag mig.', en: 'At eleven I go to bed.' },
        { sv: 'På morgonen tvättar hon sig.', en: 'In the morning she washes.' },
        { sv: 'Sedan sätter vi oss och äter frukost.', en: 'Then we sit down and have breakfast.' },
      ],
      tip: 'The past forms (vaknade, gick upp, klädde på sig) are on each word card. You will practise them in Unit 10.',
    },
  ],
  vocab: [
    {
      id: 'vakna',
      sv: 'vakna',
      en: 'to wake up',
      pos: 'verb',
      forms: { present: 'vaknar', past: 'vaknade', supine: 'vaknat', imperative: 'vakna' },
      enAlt: ['wake up', 'to wake'],
    },
    {
      id: 'ga-upp',
      sv: 'gå upp',
      en: 'to get up',
      pos: 'verb',
      note: 'Get out of bed. Waking up is vakna.',
      forms: { present: 'går upp', past: 'gick upp', supine: 'gått upp', imperative: 'gå upp' },
    },
    {
      id: 'duscha',
      sv: 'duscha',
      en: 'to shower / have a shower',
      pos: 'verb',
      forms: { present: 'duschar', past: 'duschade', supine: 'duschat', imperative: 'duscha' },
      enAlt: ['to shower', 'to have a shower', 'to take a shower'],
    },
    {
      id: 'tvatta-sig',
      sv: 'tvätta sig',
      en: 'to wash (yourself)',
      pos: 'verb',
      note: 'sig changes with the person: jag tvättar mig, du tvättar dig, vi tvättar oss.',
      forms: {
        present: 'tvättar sig',
        past: 'tvättade sig',
        supine: 'tvättat sig',
        imperative: 'tvätta dig',
      },
      enAlt: ['to wash', 'to wash yourself', 'to have a wash'],
    },
    {
      id: 'kla-pa-sig',
      sv: 'klä på sig',
      en: 'to get dressed',
      pos: 'verb',
      note: 'The opposite is klä av sig (get undressed).',
      forms: {
        present: 'klär på sig',
        past: 'klädde på sig',
        supine: 'klätt på sig',
        imperative: 'klä på dig',
      },
    },
    {
      id: 'borsta-tanderna',
      sv: 'borsta tänderna',
      en: 'to brush your teeth',
      pos: 'verb',
      note: 'Literally "brush the teeth": en tand, två tänder, tänderna.',
      forms: {
        present: 'borstar tänderna',
        past: 'borstade tänderna',
        supine: 'borstat tänderna',
        imperative: 'borsta tänderna',
      },
      enAlt: ['to brush my teeth', 'to brush the teeth', 'brush your teeth'],
    },
    {
      id: 'satta-sig',
      sv: 'sätta sig',
      en: 'to sit down',
      pos: 'verb',
      note: '"Sätt dig!" = Sit down!',
      forms: {
        present: 'sätter sig',
        past: 'satte sig',
        supine: 'satt sig',
        imperative: 'sätt dig',
      },
    },
    {
      id: 'lagga-sig',
      sv: 'lägga sig',
      en: 'to go to bed / lie down',
      pos: 'verb',
      note: 'Past: la sig (also written lade sig).',
      forms: { present: 'lägger sig', past: 'la sig', supine: 'lagt sig', imperative: 'lägg dig' },
      enAlt: ['to go to bed', 'to lie down'],
    },
    {
      id: 'skynda-sig',
      sv: 'skynda sig',
      en: 'to hurry',
      pos: 'verb',
      note: '"Skynda dig!" = Hurry up!',
      forms: {
        present: 'skyndar sig',
        past: 'skyndade sig',
        supine: 'skyndat sig',
        imperative: 'skynda dig',
      },
      enAlt: ['to hurry up', 'to be quick'],
    },
    {
      id: 'somna',
      sv: 'somna',
      en: 'to fall asleep',
      pos: 'verb',
      note: 'somna = fall asleep; sova = be asleep.',
      forms: { present: 'somnar', past: 'somnade', supine: 'somnat', imperative: 'somna' },
      enAlt: ['to go to sleep', 'to drop off'],
    },
    {
      id: 'jobb',
      sv: 'jobb',
      en: 'job / work',
      pos: 'noun',
      gender: 'ett',
      note: '"på jobbet" = at work. "till jobbet" = to work.',
      forms: { definite: 'jobbet', plural: 'jobb', pluralDefinite: 'jobben' },
      enAlt: ['job', 'work'],
    },
  ],
  dialogue: {
    title: 'Five more minutes',
    setting: 'It’s a weekday morning. Maja is trying to get Leo out of bed.',
    lines: [
      {
        speaker: 'Maja',
        sv: 'Leo! Vakna! Klockan är halv åtta.',
        en: 'Leo! Wake up! It’s half past seven.',
      },
      { speaker: 'Leo', sv: 'Mm … fem minuter till.', en: 'Mm … five more minutes.' },
      {
        speaker: 'Maja',
        sv: 'Nej, skynda dig! Du ska vara på jobbet klockan åtta.',
        en: 'No, hurry up! You have to be at work at eight.',
      },
      { speaker: 'Leo', sv: 'Okej, okej. Jag går upp nu.', en: 'Okay, okay. I’m getting up now.' },
      {
        speaker: 'Maja',
        sv: 'Duscha nu och borsta tänderna!',
        en: 'Have a shower now, and brush your teeth!',
      },
      { speaker: 'Leo', sv: 'Ja, mamma!', en: 'Yes, Mum!' },
      {
        speaker: 'Maja',
        sv: 'Haha. Kaffet står på bordet.',
        en: 'Haha. The coffee’s on the table.',
      },
      { speaker: 'Leo', sv: 'Tack! Jag klär på mig först.', en: 'Thanks! I’ll get dressed first.' },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'Först duschar jag, sedan klär jag på ___.',
      en: 'First I have a shower, then I get dressed.',
      choices: ['mig', 'sig', 'oss'],
      answer: 'mig',
      explanation: 'The subject is jag, so the self word is mig.',
      vocab: ['kla-pa-sig', 'duscha'],
    },
    {
      type: 'gap',
      text: 'Barnen lägger ___ klockan åtta.',
      en: 'The children go to bed at eight.',
      choices: ['sig', 'oss', 'mig'],
      answer: 'sig',
      explanation:
        'Barnen (the children) are de (they), and for de the self word is sig, just like for han and hon.',
      vocab: ['lagga-sig', 'barn'],
    },
    {
      type: 'gap',
      text: 'Vi sätter ___ och äter frukost.',
      en: 'We sit down and have breakfast.',
      choices: ['oss', 'sig', 'er'],
      answer: 'oss',
      explanation: 'The subject is vi (we), so the self word is oss.',
      vocab: ['satta-sig', 'vi'],
    },
    {
      type: 'build',
      prompt: 'At seven I wake up.',
      answer: 'Klockan sju vaknar jag.',
      accept: ['Jag vaknar klockan sju.'],
      distractors: ['mig', 'vakna'],
      explanation:
        'The sentence starts with the time, so the verb vaknar comes second and jag moves after it (V2). vakna has no self word.',
      vocab: ['vakna', 'klocka', 'sju'],
    },
    {
      type: 'build',
      prompt: 'Then I get dressed.',
      answer: 'Sedan klär jag på mig.',
      accept: ['Jag klär på mig sedan.'],
      distractors: ['sig', 'klä'],
      explanation:
        'After sedan (then) the verb comes second: Sedan klär jag … The self word for jag is mig.',
      vocab: ['kla-pa-sig'],
    },
    {
      type: 'build',
      prompt: 'At eleven she goes to bed.',
      answer: 'Klockan elva lägger hon sig.',
      accept: ['Hon lägger sig klockan elva.'],
      distractors: ['henne', 'mig'],
      explanation:
        'V2: time first, then the verb lägger, then hon. The self word for hon is sig. henne would mean she puts someone else to bed!',
      vocab: ['lagga-sig', 'elva', 'hon'],
    },
    {
      type: 'listen',
      audio: 'Jag vaknar klockan sex, men jag går upp klockan sju.',
      choices: [
        'I wake up at six, but I get up at seven.',
        'I get up at six, but I wake up at seven.',
        'I wake up at seven, but I get up at six.',
      ],
      answer: 'I wake up at six, but I get up at seven.',
      explanation: 'vakna = wake up, gå upp = get up (out of bed).',
      vocab: ['vakna', 'ga-upp'],
    },
    {
      type: 'dialogueReply',
      lines: [
        {
          speaker: 'Maja',
          sv: 'Skynda dig! Klockan är åtta!',
          en: 'Hurry up! It’s eight o’clock!',
        },
      ],
      question: 'Tell her you’re getting dressed.',
      choices: ['Jag klär på mig!', 'Jag klär på dig!', 'Jag klär på sig!'],
      answer: 'Jag klär på mig!',
      explanation:
        'With jag the self word is mig. Jag klär på dig would mean you are dressing Maja!',
      vocab: ['kla-pa-sig', 'skynda-sig'],
    },
    {
      type: 'dictation',
      audio: 'Jag duschar och borstar tänderna.',
      en: 'I have a shower and brush my teeth.',
      vocab: ['duscha', 'borsta-tanderna'],
    },
    {
      type: 'speak',
      text: 'Klockan sju vaknar jag och duschar.',
      en: 'At seven I wake up and have a shower.',
      vocab: ['vakna', 'duscha'],
    },
  ],
})
