import { defineLesson } from '../../define'

export default defineLesson({
  id: 'u08-l03',
  learn: [
    {
      title: 'Room by room',
      text: '[[rum]] (room) is an **ett**-word, and so is every room that ends in -rum. Many of them are easy to take apart: [[vardagsrum]] is "everyday room", [[sovrum]] is "sleep room".\n\nRemember the double m before an ending: [[sovrum]] → [[sovrummet]].',
      table: {
        headers: ['a …', 'the …', 'English'],
        rows: [
          ['ett vardagsrum', 'vardagsrummet', 'the living room'],
          ['ett sovrum', 'sovrummet', 'the bedroom'],
          ['ett badrum', 'badrummet', 'the bathroom'],
          ['ett kök', 'köket', 'the kitchen'],
          ['en hall', 'hallen', 'the hall'],
          ['en balkong', 'balkongen', 'the balcony'],
        ],
        svColumns: [0, 1],
      },
      tip: 'Swedes count rooms without the kitchen. [[en tvåa]] (“a two”) is a flat with two rooms and a kitchen, [[en trea]] has three rooms and a kitchen. Ads write it as 2 rok: två rum och kök.',
    },
    {
      title: 'Det finns: there is, there are',
      text: 'You met [[det finns]] in Unit 7. It is perfect for describing a home, and it is the same for one thing or many.\n\nIf you start the sentence with the place, V2 kicks in: **finns** stays in second place and **det** moves after it.',
      examples: [
        { sv: 'Det finns en balkong.', en: 'There’s a balcony.' },
        { sv: 'Det finns två sovrum i lägenheten.', en: 'There are two bedrooms in the flat.' },
        { sv: 'I lägenheten finns det två sovrum.', en: 'In the flat, there are two bedrooms.' },
        { sv: 'Finns det en dusch?', en: 'Is there a shower?' },
        { sv: 'Finns det mjölk i kylskåpet?', en: 'Is there any milk in the fridge?' },
      ],
    },
    {
      title: 'Where things are',
      text: 'Use the prepositions and the verbs ligger and står from Unit 4. Things lying flat **ligger**, things standing up **står**.\n\n[[på golvet]] (on the floor), [[på väggen]] (on the wall), [[i kylskåpet]] (in the fridge).',
      examples: [
        { sv: 'Mobilen ligger på golvet.', en: 'The phone is on the floor.' },
        { sv: 'Mjölken står i kylskåpet.', en: 'The milk is in the fridge.' },
        { sv: 'Det finns en klocka på väggen.', en: 'There’s a clock on the wall.' },
        { sv: 'Väskan står i hallen.', en: 'The bag is in the hall.' },
      ],
      tip: 'Swedes often give the floor they live on in flights of stairs: [[Jag bor två trappor upp.]] means "I live two flights up".',
    },
  ],
  culture: {
    title: 'Renting or “buying”?',
    text: 'Most Swedes in towns and cities live in flats. A [[hyresrätt]] is a rental flat. In Stockholm the queue for a first-hand contract can be ten years or more, so many people rent second-hand ([[i andra hand]]).\n\nA [[bostadsrätt]] is the closest thing to owning a flat: you buy the right to live in it, and the building belongs to a housing association.\n\nWhen you visit someone’s home, take your shoes off in the hall. Almost everybody does!',
  },
  vocab: [
    {
      id: 'lagenhet',
      sv: 'lägenhet',
      en: 'flat / apartment',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'lägenheten', plural: 'lägenheter', pluralDefinite: 'lägenheterna' },
      enAlt: ['flat', 'apartment'],
    },
    {
      id: 'vardagsrum',
      sv: 'vardagsrum',
      en: 'living room',
      pos: 'noun',
      gender: 'ett',
      note: 'vardag (everyday) + rum (room).',
      forms: { definite: 'vardagsrummet', plural: 'vardagsrum', pluralDefinite: 'vardagsrummen' },
      enAlt: ['lounge', 'sitting room'],
    },
    {
      id: 'sovrum',
      sv: 'sovrum',
      en: 'bedroom',
      pos: 'noun',
      gender: 'ett',
      note: 'sova (sleep) + rum (room).',
      forms: { definite: 'sovrummet', plural: 'sovrum', pluralDefinite: 'sovrummen' },
    },
    {
      id: 'badrum',
      sv: 'badrum',
      en: 'bathroom',
      pos: 'noun',
      gender: 'ett',
      forms: { definite: 'badrummet', plural: 'badrum', pluralDefinite: 'badrummen' },
    },
    {
      id: 'hall',
      sv: 'hall',
      en: 'hall / hallway',
      pos: 'noun',
      gender: 'en',
      note: 'Where you take your shoes off.',
      forms: { definite: 'hallen', plural: 'hallar', pluralDefinite: 'hallarna' },
      enAlt: ['hall', 'hallway'],
    },
    {
      id: 'balkong',
      sv: 'balkong',
      en: 'balcony',
      pos: 'noun',
      gender: 'en',
      pron: 'bal-KONG',
      forms: { definite: 'balkongen', plural: 'balkonger', pluralDefinite: 'balkongerna' },
    },
    {
      id: 'trappa',
      sv: 'trappa',
      en: 'stairs / staircase',
      pos: 'noun',
      gender: 'en',
      note: '"Jag bor två trappor upp" = I live two flights up.',
      forms: { definite: 'trappan', plural: 'trappor', pluralDefinite: 'trapporna' },
      enAlt: ['stairs', 'staircase', 'flight of stairs'],
    },
    {
      id: 'golv',
      sv: 'golv',
      en: 'floor',
      pos: 'noun',
      gender: 'ett',
      note: 'The floor you stand on. A floor (storey) in a building is en våning.',
      forms: { definite: 'golvet', plural: 'golv', pluralDefinite: 'golven' },
    },
    {
      id: 'vagg',
      sv: 'vägg',
      en: 'wall',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'väggen', plural: 'väggar', pluralDefinite: 'väggarna' },
    },
    {
      id: 'kylskap',
      sv: 'kylskåp',
      en: 'fridge',
      pos: 'noun',
      gender: 'ett',
      note: 'kyl (cool) + skåp (cupboard). Often just kylen.',
      forms: { definite: 'kylskåpet', plural: 'kylskåp', pluralDefinite: 'kylskåpen' },
      enAlt: ['refrigerator'],
    },
    {
      id: 'dusch',
      sv: 'dusch',
      en: 'shower',
      pos: 'noun',
      gender: 'en',
      forms: { definite: 'duschen', plural: 'duschar', pluralDefinite: 'duscharna' },
    },
    {
      id: 'hemma-u8',
      sv: 'hemma',
      en: 'at home',
      pos: 'adverb',
      note: '"Jag är hemma" = I’m at home. Going home is hem: "Jag går hem."',
      enAlt: ['home'],
    },
  ],
  dialogue: {
    title: 'The new flat',
    setting: 'Noah is visiting Elin in her new flat.',
    lines: [
      {
        speaker: 'Elin',
        sv: 'Välkommen! Skorna kan stå i hallen.',
        en: 'Welcome! Your shoes can go in the hall.',
      },
      {
        speaker: 'Noah',
        sv: 'Tack! Vad fint! Hur många rum har du?',
        en: 'Thanks! How nice! How many rooms do you have?',
      },
      {
        speaker: 'Elin',
        sv: 'Det är en tvåa: ett vardagsrum, ett sovrum och ett kök.',
        en: 'It’s a two-room flat: a living room, a bedroom and a kitchen.',
      },
      { speaker: 'Noah', sv: 'Finns det en balkong?', en: 'Is there a balcony?' },
      {
        speaker: 'Elin',
        sv: 'Ja, den ligger bredvid vardagsrummet.',
        en: 'Yes, it’s next to the living room.',
      },
      { speaker: 'Noah', sv: 'Kul! Och var är badrummet?', en: 'Great! And where’s the bathroom?' },
      {
        speaker: 'Elin',
        sv: 'Där borta, bredvid sovrummet.',
        en: 'Over there, next to the bedroom.',
      },
    ],
  },
  exercises: [
    {
      type: 'gap',
      text: 'I lägenheten ___ det två sovrum.',
      en: 'In the flat, there are two bedrooms.',
      choices: ['finns', 'har', 'det finns'],
      answer: 'finns',
      explanation:
        'The sentence starts with a place, so the verb finns comes second and det moves after it: I lägenheten finns det …',
      vocab: ['lagenhet', 'sovrum'],
    },
    {
      type: 'gap',
      text: 'Mjölken står i ___.',
      en: 'The milk is in the fridge.',
      choices: ['kylskåpet', 'kylskåp', 'kylskåpan'],
      answer: 'kylskåpet',
      explanation: 'kylskåp is an ett-word, so "the fridge" is kylskåpet.',
      vocab: ['kylskap'],
    },
    {
      type: 'build',
      prompt: 'In the apartment, there are two bedrooms.',
      answer: 'I lägenheten finns det två sovrum.',
      accept: ['Det finns två sovrum i lägenheten.'],
      distractors: ['har', 'sovrummet'],
      explanation:
        'Starting with the place (I lägenheten), the verb finns must come second, so det goes after it.',
      vocab: ['lagenhet', 'sovrum'],
    },
    {
      type: 'build',
      prompt: 'There is a clock on the wall.',
      answer: 'Det finns en klocka på väggen.',
      accept: ['På väggen finns det en klocka.'],
      distractors: ['vägg', 'ett'],
      explanation: 'vägg is an en-word, so "the wall" is väggen. klocka is an en-word too.',
      vocab: ['vagg', 'klocka'],
    },
    {
      type: 'dialogueReply',
      lines: [{ speaker: 'Noah', sv: 'Finns det en balkong?', en: 'Is there a balcony?' }],
      question: 'There is one, next to the living room. What do you say?',
      choices: [
        'Ja, den ligger bredvid vardagsrummet.',
        'Ja, det ligger bredvid vardagsrummet.',
        'Ja, den ligger bredvid vardagsrum.',
      ],
      answer: 'Ja, den ligger bredvid vardagsrummet.',
      explanation:
        'balkong is an en-word, so "it" is den. "The living room" needs the ending: vardagsrummet.',
      vocab: ['balkong', 'vardagsrum'],
    },
    {
      type: 'mcq',
      prompt: 'en trea',
      promptLang: 'sv',
      question: 'A flat in an ad is “en trea”. What does it have?',
      choices: [
        'three rooms and a kitchen',
        'three rooms, including the kitchen',
        'three bathrooms',
      ],
      answer: 'three rooms and a kitchen',
      explanation:
        'Swedes count rooms without the kitchen: en tvåa has two rooms and a kitchen, en trea three.',
      vocab: ['lagenhet'],
    },
    {
      type: 'listen',
      audio: 'Mobilen ligger på golvet i hallen.',
      choices: [
        'The phone is on the floor in the hall.',
        'The phone is on the wall in the hall.',
        'The phone is on the floor in the bathroom.',
      ],
      answer: 'The phone is on the floor in the hall.',
      explanation: 'golvet = the floor, hallen = the hall. The wall would be väggen.',
      vocab: ['golv', 'hall', 'mobil'],
    },
    {
      type: 'type',
      prompt: 'the bathroom',
      promptLang: 'en',
      question: 'Write this in Swedish',
      answer: 'badrummet',
      reject: ['badrumet', 'badrum', 'badrummen', 'badrumen'],
      strict: true,
      hint: 'ett badrum: remember the double m',
      explanation:
        'badrum is an ett-word like rum, so it takes -et. The m doubles before the ending: badrummet.',
      vocab: ['badrum'],
    },
    {
      type: 'dictation',
      audio: 'Kylskåpet står i köket.',
      en: 'The fridge is in the kitchen.',
      vocab: ['kylskap', 'kok', 'sta'],
    },
    {
      type: 'speak',
      text: 'Jag är hemma. Jag bor i en lägenhet med balkong.',
      en: 'I’m at home. I live in a flat with a balcony.',
      vocab: ['hemma-u8', 'lagenhet', 'balkong'],
    },
  ],
})
